### ISSUE TITLE
iOS 14 date-picker is not displayed correctly

### ISSUE THREAD

**Issue by rotem-hen** [apache/cordova-ios#1001]
## Problem
1. Add this to index.html:
```
<input type="datetime-local" />
```

2. When clicking on the input box, it displays the picker wrong.

### What is expected to happen?
Expected to see the new picker Safari uses in iOS 14:

<img width="350" alt="ipad, 14, safari" src="https://user-images.githubusercontent.com/17706553/94824945-3890d080-040e-11eb-9772-6f995d666e26.png">

### What does actually happen?
The new picker is displayed like this:

<img width="350" alt="ipad, 14, cordova" src="https://user-images.githubusercontent.com/17706553/94825153-7ee62f80-040e-11eb-8fa6-0941f38d2596.png">

## Information
1. The images are from iPad but it's the same on iPhone.
2. The images are with date picker but it's the same with time picker.
3. When looking at iOS 13.5 device, there is the old picker which works ok.

Safari (left) and Cordova (right):

<img width="250" alt="ipad, 13 5, safari" src="https://user-images.githubusercontent.com/17706553/94825282-a76e2980-040e-11eb-9cd6-a39d38a7a9b2.png"><img width="250" alt="ipad, 13 5, cordova" src="https://user-images.githubusercontent.com/17706553/94825301-accb7400-040e-11eb-9799-a01947939d27.png">

### Environment, Platform, Device
iOS 14 devices
cordova 9.0.0
cordova-ios 5.1.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Is this reproducible on cordova-ios@6?

**Comment by rotem-hen** [comment]
Sorry, it's not happening OOTB. Closing.
