### ISSUE TITLE
Failed to start debugserver: e8000022 The service is invalid.

### ISSUE THREAD

**Issue by vahost** [apache/cordova-ios#1003]
# Bug Report

ARCHIVE SUCCEEDED
EXPORT SUCCEEDED

------ Debug phase ------
Starting debug of c18d3c6652223a4ab9ba0ce745440fc3f131c227 (N71mAP, iPhone 6s, iphoneos, arm64) a.k.a. 'Walt's iPhone' connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
Failed to start debugserver: e8000022 The service is invalid.
Waiting for the device to scan mounted image
2020-10-03 05:55:22.877 ios-deploy[50835:1686031] [ !! ] Error 0xe8000022: The service is invalid. AMDeviceSecureStartService(device, CFSTR("com.apple.debugserver"), NULL, &con)
ios-deploy: Command failed with exit code 253

## Problem

I get the above message when I run this Quasar command: quasar dev -m cordova -T ios

### What is expected to happen?

I expect to get a successful dev build for testing to my iPhone.

### What does actually happen?

The build fails with the above errors and the app fails to load on the iPhone.

### Command or Code

quasar dev -m cordova -T ios

### Environment, Platform, Device

MacOS Catalina 10.15.6
iPhone 6s running iOS 14.0.1
Xcode 12.0.1
Visual Studio Code Version: 1.49.2
  Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
  Date: 2020-09-24T16:23:52.277Z (1 wk ago)
Chrome: 83.0.4103.122
Node.js: 12.14.1
OS: Darwin x64 19.6.0
Quasar 2.1.1

### Version information

Cordova CLI  10.0.0

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by timbru31** [comment]
This sounds a lot like an issue on either quasar, ios-deploy or Xcode in general. Can you please use the Cordova CLI to ensure the issue is not caused by a third party?

Besides that, your issue is missing the used cordova-ios version.

**Comment by timbru31** [comment]
Yes, this is caused by an outdated version of ios-deploy and not by Cordova.
