### ISSUE TITLE
AppStore Rejection due to UIWEBVIEW?

### ISSUE THREAD

**Issue by chwahab** [apache/cordova-ios#1008]
Hi, 
Is this issue resolved in 6.11 ?
https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

In your blog, your team mentioned that in feature everything will be replaced with WKWebView. 
Is 6.1.1 is candidate release for that ? Or should I still follow these instructions mentioned in your blog https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

**Comment by breautek** [comment]
The `WKWebViewOnly` flag is only configurable in `cordova-ios@5.1.1`.

In `cordova-ios@6` the `UIWebView` has been completely removed and thus default webview is the WKWebView, effectively hard-coding `WKWebViewOnly` flag to true.

As far as the Apache codebase goes, you'll need to have the following:

## cordova-ios@6

- Use the latest version of `cordova-ios`
- If [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine) is installed, uninstall it.
- If you use inappbrowser plugin, update to `4.0.0`

If for some reason you cannot yet upgrade to `cordova-ios@6`, then read further.

## cordova-ios@5

- Be on `cordova-ios@5.1.1`
- Have `WKWebViewOnly` preference enabled
- Have a WKWebView plugin installed such as [this](https://github.com/apache/cordova-plugin-wkwebview-engine) one.
- If you use the inappbrowser plugin, version `3.2.0` or later will respect the `WKWebViewOnly` flag.

## Note on other plugins

It is possible that other third-party plugins may also include references of the `UIWebView` leading to app store rejection. This isn't an exhaustive list but some known plugins are:
- social media plugins
- google maps plugin
- firebase plugins

These plugins if your app uses them will also need to be updated.

I invite you to our [slack](http://slack.cordova.io/) for further assistance.
