### ISSUE TITLE
Issue when compiling app for ios on mac made on Ubuntu 

### ISSUE THREAD

**Issue by gpistotnik** [apache/cordova-ios#1013]
### Issue Type

- [ X] Bug Report
- [ ] Feature Request
- [ X] Support Question

## Description
I am developing an app for ios and Android. For Android I use Ubuntu 20.04, and for ios mac. I get error on mac when compiling files from ubuntu.

### Command or Code
cordova build ios

### Environment, Platform, Device
App made on Ubuntu 20.04, compiled for android, moved to OSX, compilation error for ios

### Version information
All versions are updated to the latest

**Comment by breautek** [comment]
> I get error on mac when compiling files from ubuntu.

You can't just simply transfer files from one machine to another, especially cross OS. Doing so would bring over NPM dependencies and native binaries that are not for your target platform.

You can still share your repo cross OS, but the following directories should be ignored from your version control:
- node_modules
- platforms
- plugins

On every machine that you clone your project, you should run `npm install` to install all the dependencies (including any potential native dependencies). Then you should run `cordova platform add ios`. This will configure the iOS project properly on your mac. The platform and all plugins will be restored based on what is inside your `package.json` file (or `config.xml`)

If this doesn't solve your problem, then you will need to give us more details including cordova version and the actual error message. Please let us know.

**Comment by gpistotnik** [comment]
I get message:
The following build commands failed:
CompileAssetCatalog 
platforms/ios/build/emulator/APKNAME.app
platforms/ios/APKNAME/Images.xcasset
(1 failure)
xcodebuild: Command failed with exit code 65

cordova info:

Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.0
            serve: 4.0.0

Project Installed Platforms:

    ios: 6.1.1

Project Installed Plugins:

    cordova-plugin-whitelist: 1.3.4

Environment:

    OS: macOS Catalina 10.15.7 (19H2) (darwin 19.6.0) x64
    Node: v12.18.0
    npm: 6.14.8

ios Environment:

    xcodebuild:
Xcode 12.1
Build version 12A7403


Project Setting Files:

    config.xml:
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Name</name>
    <description>
        Description
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Gasper
    </author>
    <content src="index.html" />
    <access origin="*" />
    <icon src="res/logo.png"/>
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>

    package.json:
--- Start of Cordova JSON Snippet ---
{
  "plugins": {
    "cordova-plugin-whitelist": {}
  },
  "platforms": [
    "android",
    "ios"
  ]
}
--- End of Cordova JSON Snippet ---

**Comment by breautek** [comment]
> I get message:

Does this occur when you freshly add the ios platform to your project on your mac?

**Comment by gpistotnik** [comment]
Made android studio and xcode app. Thanks anyway
