### ISSUE TITLE
Xcode Fail to build cordova project

### ISSUE THREAD

**Issue by karimlahbach** [apache/cordova-ios#1021]
# Bug Report
xcode fail to build cordova project
### What is expected to happen?
i expect that when i open Cordova project in XCode everything work fine

### What does actually happen?
Xcode fail to build the project

## Information

this the link of the project so you can try yourself
https://www.dropbox.com/s/y1ly2c3yi45rop6/TestBuild.ios.project.zip?dl=0

### Command or Code

Just add admob to simple project and exported as xcode project

### Environment, Platform, Device

IOS

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
the sample project is no longer available

I can't reproduce on a regular project, so the problem might be related to the way you are adding admob.

**Comment by karimlahbach** [comment]
here is new link
https://mega.nz/file/1VBXRAZI#ZHxrfsArKVsavybSw5ZEZxg4R5lEaBzzKAk6w7O7DYc

**Comment by jcesarmobile** [comment]
you need to update CocoaPods to 1.10.0 or newer
