### ISSUE TITLE
Apple Review of iOS Cordova App - No User Agent received

### ISSUE THREAD

**Issue by Lindsay-Needs-Sleep** [apache/cordova-ios#1022]
Honestly not sure if this is a cordova issue or something else.  So this is more of a question to start.

This has happened 3 times over the last ~1.5 years.  (Out of about 10 reviews.)

On these 3 random occasions Apple reviewers have somehow sent requests which have:
1) Lost their session
2) AND somehow have **absolutely NO User Agent at all** (this is the one that really confuses us)

*(This results in our app being rejected because they have see unintended behavior because there is no session or useragent.)*

---
INFO: We have a Cordova app and point it to our website running on a Django server.  
```xml
<!--- config.xml --->
<preference name="AppendUserAgent" value="APP_NAME_cordova" />
```
This has happened for us:
* `cordova-ios@5.0.1` 2/8 times
* `cordova-ios@5.1.1` 0/1 times (Lucky?)
* `cordova-ios@6.1.1` 1/1 times
* Never when we are testing ourselves
* No reports from our ~8,000 iOS users that match this behavior
* Never on Android (Google reviews/~20,000 users/us)
* (Though we are just adding some logging when this situation is detected now)

How could this be happening?  
Could this be django dropping the user agent? (and session? :S)  
Could Cordova be failing to send the userAgent?  
Is Apple doing something special/weird?  
Any suggestions?  
(Right now we are just assuming requests that match the above 2 criteria to be Apple, and forcing the behavior. Not Ideal.)

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been over a year with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
