### ISSUE TITLE
ipa can't be installed in ios 14.1

### ISSUE THREAD

**Issue by brunoPert** [apache/cordova-ios#1025]
# Bug Report

## Problem

My app runs successfully at xcode emulator, but when making and ipa and deploying it to an iphone (I don't have access to it, as the QA team have them), the ipa isn't installed, showing the known alert "App_name can't be installed"

### What is expected to happen?

Ipa should be installed

### What does actually happen?

Ipa isn't installed

### Environment, Platform, Device
iOS 14.1
Xcode 12.1
iPhone 11 Pro

### Version information
Cordova CLI: 10.0.0 
Cordova Platform iOS: 5.1.1
Xcode: 12.1
OS: MacOS: 10.15.5 (19F101)

## Checklist

- [X ] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above
- [X ] I Looked for iphone device id and found it in info.plist
- [X ] I Tried to update to the latest cordova-ios version.

**Comment by timbru31** [comment]
With such little information we are unable to help. We need an actual error message/stack trace. This also sounds like a general issue with Xcode or iOS, not Cordova specific.

**Comment by brunoPert** [comment]
As I said before, I don't have access to the device, neither to any log/stack trace that it may print. I saw someone posted the same issue: https://github.com/apache/cordova-ios/issues/935, but I can't figure out the solution.

**Comment by breautek** [comment]
I think you need an enterprise license if you want to ad-hoc install IPAs without XCode. For QA/testing the more appropriate path is through the [Testflight](https://developer.apple.com/testflight/) system.

Your testers will install the Testflight app provided by Apple on the app store, and log into their apple accounts (which should be added as a tester to your developer team).

You can then deploy your app to [ITunes Connect](https://itunesconnect.apple.com/) and configure for a testflight release. There's a testflight tab when you enter your app.

**Comment by brunoPert** [comment]
thanks @breautek , I'll propose it

**Comment by breautek** [comment]
I'm wrong, you don't need an enterprise license for ad-hoc installs, at least for a limited set of registered devices. But your testers will either need to have XCode or Apple Configurator 2 installed to put the IPA app on the device.

https://help.apple.com/xcode/mac/current/#/dev7ccaf4d3c gives more information on the process.

Testflight is still a better system for testing in my opinion.

This isn't really a Cordova issue however so I'll be closing this ticket. If you need further assistance though, people on our [Slack](http://slack.cordova.io/) can probably help out.
