### ISSUE TITLE
cordova-ios 6.1.1: When keyboard comes up, view gets shrinked

### ISSUE THREAD

**Issue by brunoPert** [apache/cordova-ios#1027]
# Bug Report

## Problem

When focusing over an input, the whole screen gets shrinked an never comes back to original state.

### What is expected to happen?

The screen should remain the same

### What does actually happen?

Screeen gets shrinked

## Information

Bug came into when I updated cordova-ios to the 6.1.1 version.

Screen  changes as follows, instead of showing all, it shrinks the view and makes me scroll to the not seen sides of the screen:

![Captura de Pantalla 2020-11-16 a la(s) 11 29 15](https://user-images.githubusercontent.com/49445815/99264294-08a35e00-27ff-11eb-8b67-8f188eaaad2a.png)

### Version information

ios: 14.1
cordova-ios: 6.1.1
cordova: 10.0.0
xcode: 12.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above
- [x] I Tryed to fix the issue ussing "KeyboardShrinkView" parameter from cordova-plugin-keyboard.

**Comment by mmxcrono** [comment]
This plugin worked for me to fix it on iOS 12. Hope it does for yours.
https://www.npmjs.com/package/cordova-plugin-wkkeyboardfix

Although your iOS version is 14.1, it was supposed to have been fixed in 13.4

**Comment by brunoPert** [comment]
It was an issue related to the text input fosusing event. Found this solution:

`input, select:focus, textarea {
    font-size: 16px !important; // Thw new webview for ios requires this to work properly on input focus
}`

And all set! Hope it helps someone.
