### ISSUE TITLE
Document latest supported Xcode and SDK versions

### ISSUE THREAD

**Issue by jacobweber** [apache/cordova-ios#1028]
# Feature Request

## Motivation Behind Feature
It's often hard to tell whether cordova-ios works with the latest version of Xcode and the latest iOS SDK version. The [readme](https://github.com/apache/cordova-ios) says that 11.x or greater is required, but doesn't say whether 12.x is supported, or which SDK versions are supported. Apple is [requiring](https://developer.apple.com/news/?id=itpt8dkc) Xcode 12 and the iOS 14 SDK to be used starting April 2021, so this is important.

## Feature Description
Can you document this info in the readme, when a release is known to work with new Xcode/SDK versions?

## Alternatives or Workarounds
N/A

**Comment by jcesarmobile** [comment]
"or greater" means it's supported, and if it doesn't it's because of bugs and would be fixed if somebody report them.

The SDK versions are set by the Xcode version, Xcode 11 uses SDK 13, Xcode 12 SDK 14.
