### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/Users/src-cordova/platforms/ios/build/emulator'

### ISSUE THREAD

**Issue by SamnnyWong** [apache/cordova-ios#1039]
Environment: mac OS 10.15 and Xcode 12.2, Quasar build using cordova mode

when i run `quasar build -m cordova -T ios` it gives me this error.

complete log looks like this:

```
** ARCHIVE SUCCEEDED **

Running command: xcodebuild -exportArchive -archivePath TacticsApp.xcarchive -exportOptionsPlist /Users/xxx/src-cordova/platforms/ios/exportOptions.plist -exportPath /Users/xxx/src-cordova/platforms/ios/build/device
2020-12-09 02:36:59.575 xcodebuild[64442:4626987] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/62/74cgqn1d3q9b2x59g3gwm9hh0000gn/T/TacticsApp_2020-12-09_02-36-59.574.xcdistributionlogs'.
Exported TacticsApp to: /Users/sam/xxx/src-cordova/platforms/ios/build/device
** EXPORT SUCCEEDED **
(node:64230) UnhandledPromiseRejectionWarning:   Error: ENOENT: no such file or directory, stat '/Users/xxxsrc-cordova/platforms/ios/build/emulator'
  
  - polyfills.js:307 Object.statSync
    [AppTactics]/[graceful-fs]/polyfills.js:307:34
  
  - stat.js:10 statSync
    [AppTactics]/[fs-extra]/lib/util/stat.js:10:52
  
  - stat.js:24 getStatsSync
    [AppTactics]/[fs-extra]/lib/util/stat.js:24:19
  
  - stat.js:49 Object.checkPathsSync
    [AppTactics]/[fs-extra]/lib/util/stat.js:49:33
  
  - copy-sync.js:24 Object.copySync
    [AppTactics]/[fs-extra]/lib/copy-sync/copy-sync.js:24:38
  
  - index.js:94 CordovaRunner.build
    [AppTactics]/[@quasar]/app/lib/cordova/index.js:94:9
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```
I tried adding and removing ../platform/ios by running `cordova platform rm ios` and `cordova platform add ios` with no luck.
I also remove node_modules and npm install, doesn't work.
It saids its missing /src-cordova/platforms/ios/build/emulator, but when i run `quasar dev -m cordova -T ios` without the test device plug in to the mac, emulator boots up, app launch with no problem, and the emulator directory appears under /src-cordova/platforms/ios/build.
Even though it prompted an error but when I run `cordova run ios` under dir `src-cordova` the app launches and run with no problem.

been stuck to this issue for days and seems like no other similar post.
Also it is using the new build system because it shows once when executing the build command. 
thanks in advance.

**Comment by breautek** [comment]
Unfortunately we cannot provide support for third-party frameworks and like you said, if you run `cordova run ios` manually under what appears to be the cordova project folder in quaser, it works. This suggests that Cordova's side is working as intended.

Quasar's support channels will your best place for this I think.

If you can reproduce the issue in a test project that contains no frameworks, please do create a new issue.
