### ISSUE TITLE
Splash screen loader not showing in cordova-ios 6 

### ISSUE THREAD

**Issue by sufian1985** [apache/cordova-ios#1045]
# Bug Report

## Problem
Loader is not showing on the splash screen in cordova-ios 6 with plugin version 6
### What is expected to happen?
The loader should appear on the splash screen

### What does actually happen?
The splash screen works fine but the loader is not showing as if i have disabled it which i have not

## Information

cordova 10, cordova-ios 6 and splash screen plugin verison 6

Here is list of all other plugins
card.io.cordova.mobilesdk 2.1.0 "CardIO"
com-sarriaroman-photoviewer 1.2.4 "PhotoViewer"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-clipboard 1.3.0 "Clipboard"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-camera 5.0.1 "Camera"
cordova-plugin-chooser 1.3.1 "Chooser"
cordova-plugin-decimal-key 1.2.2 "Decimal Keyboard"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-document-viewer 0.9.13 "SitewaertsDocumentViewer"
cordova-plugin-file-transfer 1.8.0 "File Transfer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-preview-any-file 0.1.6 "PreviewAnyFile"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-telerik-imagepicker 2.3.3 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"

### Environment, Platform, Device

Ionic:

   Ionic CLI                     : 6.12.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.4
   @angular-devkit/build-angular : 0.1002.0
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 20 other plugins)

Utility:

   cordova-res (update available: 0.15.2) : 0.9.0
   native-run (update available: 1.2.2)   : 0.2.4

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.14.8
   OS         : macOS Big Sur
   Xcode      : Xcode 12.2 Build version 12B45b

## Checklist

- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by dpogue** [comment]
The spinner on the splashscreen is no longer supported as of Cordova iOS 6.0.0 with the move to Storyboard-based splashscreens.
