### ISSUE TITLE
request support xcode 12.x

### ISSUE THREAD

**Issue by haohetao** [apache/cordova-ios#1046]
# Feature Request

## Motivation Behind Feature
request support xcode 12.x

**Comment by haohetao** [comment]
Xcode11 cannot be installed on MacOS 14

**Comment by breautek** [comment]
I know there are people using Cordova with XCode 12 just fine. If there is a specific problem with XCode 12 please do open an issue for it.

**Comment by brodybits** [comment]
@haohetao I just reopened your request with the **info-needed** label for now. I am very sorry to say that from the description and your recent comment there is no way for us to understand what is not working and what you are looking for.

We generally focus on supporting the latest versions of the platforms, platform SDKs, and development tools, as generally needed by the app stores. That said, it is my understanding that there may be some people still using previous versions of Xcode for in-house enterprise applications. Unfortunately I do not recall whether or not the recent cordova-ios release still supports use with Xcode 11.

We would appreciate it if you can give us some more details about what is not working and what you are looking for, especially if you can answer the questions in the issue template. Please feel free to discuss further either here or in another new issue. Thanks.

**Comment by haohetao** [comment]
I plan to upgrade to MacOs14, but cordova-ios has no compatibility specification with xcode12, so I hesitate to upgrade

**Comment by breautek** [comment]
> I plan to upgrade to MacOs14, but cordova-ios does not have the compatibility specification with xcode12, so I have been hesitant to upgrade for fear that something might go wrong

What makes you say this? I'm able to build a sample app with XCode 12.3 Build Version 12C33

**Comment by haohetao** [comment]
xcode 12 on macos 10.15 is work.

**Comment by sandeep25061** [comment]
I am facing issue with xCode 12 , it never shows local network usage description pop up. Working fine with xCode 11.7.
Coredova-ios@6.2.0

**Comment by breautek** [comment]
Closing as stale, as XCode 12 is pretty obsolete.

I know Cordova also works with modern XCode versions including XCode 14.
