### ISSUE TITLE
properties declared in config.xml --> (config-file property) are not being added correctly in the .plist file

### ISSUE THREAD

**Issue by phyr0s** [apache/cordova-ios#1048]
# Bug Report

## Problem
properties declared in config.xml --> (config-file property) are not being added correctly in the .plist file

### What is expected to happen?
Add custom string/array of string to .plist file

### What does actually happen?
Nothing, just skip and add the default system string

## Information
Try to add for example NSCalendarsUsageDescription string to plist and will add the default string not the custom one.
   

### Command or Code
`$cordova build ios --device
`
In the config.xml file  just add --> 
```
<platform name="ios">
        <config-file parent="NSCalendarsUsageDescription" target="*-Info.plist">
            <string>Using calendar for.........</string>
        </config-file>
</platform>
```

### Environment, Platform, Device
iOS last version of xcode 12.3 and previous 12.2 (maybe happen with all)

### Version information
 cordova-ios 6.1.1
cordova 10.0.0

## Checklist

- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been over a year with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
