### ISSUE TITLE
Date Picker Dismissal Leaves Viewport Shifted in iOS 14 / XCode 12

### ISSUE THREAD

**Issue by JeffBerman** [apache/cordova-ios#1052]
# Bug Report

## Problem
If the keyboard is already visible when the iOS date picker is activated, the viewport is left in a shifted-up position.

### What is expected to happen?
The content would appear in the same position as before the date picker was invoked.

### What does actually happen?
When a date picker is invoked on a field that is physically low on the screen, the content is shifted up in the background when the date picker blurs out the background. It is left in this shifted state when the date picker is dismissed.

## Information
I am guessing that Apple's fix to #417 doesn't take into account the scenario where the keyboard is already visible when a date field is tapped. If the date field exists near the top of the screen then the problem doesn't manifest, and if the keyboard is first dismissed before a date field is tapped then it also doesn't manifest.

### Command or Code
Place a text input field near the top of the screen, and a date input field near the bottom of the screen. Tap on the text field to bring up the keyboard, then tap the date field to bring up the iOS date picker. You will see the screen scroll up at this time, where it will stick in that position after the date picker is dismissed.

### Environment, Platform, Device
Xcode 12.3
iPhone 6s at iOS 14.3
iPhone 12 (simulated) and iPhone 8 (simulated) at iOS 14.3

### Version information
Cordova CLI 10.0.0, Cordova-iOS 6.1.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

## Screenshots
Before tapping anything: 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/5559959/103813488-04343e00-5015-11eb-96e3-2830f70881a1.png">

After bringing up keyboard:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/5559959/103813526-157d4a80-5015-11eb-9b61-ae9bd5b53e63.png">

After bringing up date picker:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/5559959/103813554-23cb6680-5015-11eb-8ec8-d7d5b4dcc70e.png">

After dismissing date picker:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/5559959/103813591-304fbf00-5015-11eb-98d0-0ed29307175d.png">

Thank you!

**Comment by dpogue** [comment]
Please report this to Apple in their Feedback Assistant, and also on the WebKit bugzilla, with a test case HTML file.

There's likely nothing Cordova can do about this.

**Comment by JeffBerman** [comment]
Will do. Thanks!

**Comment by timbru31** [comment]
Closing as this seems a WebKit bug. Feel free to crossref your WebKit bug report link and the Radar copy on https://openradar.appspot.com (if you made a copy).
