### ISSUE TITLE
IOS Swipe back stopped working after upgrading from 5.1.1 to 6.1.1

### ISSUE THREAD

**Issue by parvageshahariar** [apache/cordova-ios#1061]
After upgrading from old  version of cordova 5.1.1 to 6.1.1  ios  swipe back stopped working which is an important part of my project. Can anyone has this issue. 

Ionic version: v1
Cordova version: 10.0.0

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
