### ISSUE TITLE
iOS scheme not work with "https" value

### ISSUE THREAD

**Issue by lucaele** [apache/cordova-ios#1062]
Hi all,
cordova-ios 6.1.1  with cordova 10.0.0,
when i set "scheme" with value "https", on device, window.location.protocol return always "app:".

<preference name="scheme" value="https" />

When i try to set other value it works, why?
Are there some limitation?

Thanks

**Comment by breautek** [comment]
> Are there some limitation?

Yes, you can't use well known schemes. Apple doesn't explicitly give a list of what is considered well known, but all existing protocol standards you can probably be assumed to be restricted, such as, but not limited to:

- http / https
- ftp
- ws / wss

If the scheme isn't usable, cordova will default to app.

**Comment by Olfredos6** [comment]
@lucaele Hi there,
I have been trying to achieve the same(using HTTP or HTTPS on iOS as a scheme), as the app I'm building uses a payment gateway that requires a return URL. Unfortunately, the service does not consider URLs starting with `app://` valid. Any suggestion?
