### ISSUE TITLE
Update jasmine and ios-sim for major release

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-ios#1068]
# Feature Request

## Motivation Behind Feature

While working on version 6.2.0 I found outdated dependencies like jasmine and ios-sim.

Upgrading jasmin broke tests.

## Feature Description

We should update them for the next major version.

**Comment by breautek** [comment]
Related: https://github.com/apache/cordova-ios/issues/978

**Comment by erisu** [comment]
https://github.com/apache/cordova-ios/pull/862
