### ISSUE TITLE
[Camera] Failed to read exposureBiasesByMode dictionary

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-ios#1072]
# Bug Report

### What is expected to happen?

click on input type=file and then choosing "do Photo or Video" should ask Permissions on first install and then open a camera.

### What does actually happen?

on iPad no permissions for first install for `back camera`, if I switch to the front camera then I see permission dialog and can take image from front camera. Switching back to the "back camera" help me not. I see black screen.

On first click on input field I have 1-2s downtime and then in xcode logs this exceptions:
```
Running cordova-ios@6.1.1
[Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
[Camera] Failed to get device from -[AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera mediaType:AVMediaTypeVideo position:1]
[Camera] Failed to get device from -[AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera mediaType:AVMediaTypeVideo position:1]
[Camera] Failed to find device BackWide for mode Photo. Falling back to BackWide
[Camera] Failed to get device from -[AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera mediaType:AVMediaTypeVideo position:1]
[Camera] Failed to get device from -[AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera mediaType:AVMediaTypeVideo position:1]
[Camera] Failed to find device BackWide for mode Photo. Falling back to BackWide
[Camera] Attempting to configure a mode with out a preset or device format! Results may be unexpected.
[Camera] Failed to get device from -[AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera mediaType:AVMediaTypeVideo position:1]
[Camera] Failed to get device from -[AVCaptureDevice defaultDeviceWithDeviceType:AVCaptureDeviceTypeBuiltInWideAngleCamera mediaType:AVMediaTypeVideo position:1]
[Camera] Failed to find device BackWide for mode Photo. Falling back to BackWide
[Camera] Attempting to use an unsupported session preset AVCaptureSessionPresetInputPriority on device (null)
[Camera] Failed to find video output connection for <AVCapturePhotoOutput: 0x282cbb5a0>
[Camera] CAMModeAndDeviceCommand configuration failed! (Error Domain=CAMModeAndDeviceCommandCannotCaptureErrorDomain Code=-32200 "(null)")
```

## Information

how to reproduce

1. create new project `cordova create test con.example.test test`
2. install cordova-ios@6.1.1
3. add in template `<input type="file">`
4. run app
5. check logs

### Environment, Platform, Device

- cordova v10.0.0
- cordova-ios v6.1.1
- node v14.15.4
- npm v6.14.10
- macOS Catalina v10.15.7 (19H512)
- Xcode v12.4 (12D4e)

**Update**:

after upgrading Xcode to `v12.4` on iPhone 6s (IOS 13.2) the file-input started work as expected. I see permisison dialog on first start. Before Xcode to `v12.4` was just black screen without any buttons and without permission. After restart App camera ask permissions and work. But this steps work not always.

currently on iPad Air 2 (IOS 14.3) 

1. click on file-input ![image](https://user-images.githubusercontent.com/2271337/106864584-617de680-66ca-11eb-9434-f94fd7fafeb2.png)
2. cordova open camera app 
![image](https://user-images.githubusercontent.com/2271337/106864627-6f336c00-66ca-11eb-9b16-a8ccbc33ce88.png)
Nothing happens
3. click on fron camera button 
![image](https://user-images.githubusercontent.com/2271337/106864699-87a38680-66ca-11eb-8349-ea24e6f779fd.png)
cordova ask permission
front camera work. Switching back to the back camera - black screen

Same for video settings. work only front camera.

 

click on "take image" button give me exception:
```
[Camera] No signpostID found for persistenceUUID C40227CA-9D4C-4F79-88AF-9ABFDA244EA8
[Camera] Failed to capture still image with request <CAMMutableStillImageCaptureRequest burstIdentifier:(null) irisIdentifier(null)> (Capture request failed because session configuration did not succeed)
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by WuglyakBolgoink** [comment]
Related
- https://github.com/ivpusic/react-native-image-crop-picker/issues/1424
- https://stackoverflow.com/questions/64061582/xcode-camera-failed-to-read-exposurebiasesbymode-dictionary

**Comment by jcesarmobile** [comment]
Input file is handled by the WKWebView itself, not by cordova, there is nothing we can do.
For WKWebView issues, report them to apple directly on https://bugs.webkit.org/
