### ISSUE TITLE
Tel link is not working as expected. 

### ISSUE THREAD

**Issue by manivacube** [apache/cordova-ios#1073]
Using <a href="tel:xxxx" /> in ios, we are getting below error. "
Failed to load resource: unsupported URL. it was properly working with cordova-ios@5.1.1 version. Please help us to overcome this issue.

## Information

cordova-ios : 6.1.1

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
