### ISSUE TITLE
handleOpenURL can't work after upgrade to Cordova IOS 6

### ISSUE THREAD

**Issue by xinhuadian** [apache/cordova-ios#1077]
# Bug Report

## Problem
This issue happen after our app upgrade from Cordova IOS 5.1 to 6.

### What is expected to happen?
When Our app open another app(such like Microsoft Authenticator), and Microsoft Authenticator call back to our app.
expected behavior is handleOpenURL will be called when back to our app. 

### What does actually happen?
HandleOpenURL not be triggered .  And this issue NOT happen when use Microsoft Authenticator directly open our app 
instead of our app -> Microsoft Authenticator --> our app.
And this issue also NOT happen in our app--> Microsoft Authenticator(wait for 5 seconds)--> our app.

## Information
I debug the issue ,found that  processOpenUrl in CDVHandleOpenURL.m have been  executed .
but the handleOpenURL javascript not be executed .

      NSString* jsString = [NSString stringWithFormat:@"document.addEventListener('deviceready',function(){if (typeof handleOpenURL === 'function') { handleOpenURL(\"%@\");}});", url.absoluteString];

        [weakSelf.webViewEngine evaluateJavaScript:jsString completionHandler:nil];

### Environment, Platform, Device

I test in IOS 13,14 . All same behavior. 

### Version information

Cordova 9.  
Cordova IOS 6.1 

## Checklist

- [x] I searched for existing GitHub issues
- [] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been over a year with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
