### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by piyushysoft** [apache/cordova-ios#1079]
# Bug Report

Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

## Information
I am using ios 5.1.1 version and still getting this issue.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above****

**Comment by timbru31** [comment]
See https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html
