### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by memphis23** [apache/cordova-ios#1083]
When I add ios platform 6.2.0 to my ionic project, it cannot be opened by XCode 12.4. I get the following error: "The project ‘MyApp’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts."

If I type command plutil -lint project.pbxproj I get more information "CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 59. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug."

If I remove cordova-ios 6.2.0 platform and I add cordova-ios 5.1.1 the project can be opened by XCode successfully.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
