### ISSUE TITLE
 Failed to acquire RBS MediaPlayback assertion 'WebKit Media Playback' 

### ISSUE THREAD

**Issue by palnatisriram** [apache/cordova-ios#1090]
<h3>**Problem**</h3>
This issue happen after my app upgraded from Cordova IOS 5.1 to 6.0.2.

What is expected to happen?
Here i'm integrating the Twilio voice functionality. Whenever click the call button it showing below error. 

<h3>**Error**</h3>
[ProcessSuspension] 0x1081d3ab0 - ProcessAssertion: Failed to acquire RBS MediaPlayback assertion 'WebKit Media Playback' for process with PID 2226, error: Error Domain=RBSAssertionErrorDomain Code=3 "Required client entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"MediaPlayback" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Required client entitlement is missing} <br/>

 User denied access to microphone, or the web browser did not allow microphone access at this address.

<h3>**Version information** </h3>
Ionic 5.6.0 <br/>
Cordova 10<br/>
Cordova iOS 6.2.0<br/>
Xcode 12

**Comment by Pasoul** [comment]
same issue

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by promit13** [comment]
same issue

**Comment by nik13** [comment]
same issue!!

**Comment by leas251** [comment]
same issue!!

**Comment by zhihongzhang123** [comment]
同样的问题！！

**Comment by hxf31891** [comment]
Any movement on this?
