### ISSUE TITLE
what schema and hostname should be set in config.xml

### ISSUE THREAD

**Issue by shanlin2dltk** [apache/cordova-ios#1092]
From version 6.0.0 instruction, it says to set the following in config.xml
`<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />`

I cannot find any post to explain under what circumstances "app" and "localhost" should be changed, and to what values.  Can someone shed some lights?  Thanks!

**Comment by breautek** [comment]
It's up to you. It just simply controls the origin point of the app, e.g: ``<scheme>://<hostname>`

The only limitation is iOS won't allow you to use well known schemes, so you can't set `scheme` preference to existing protocols, like `http` or `https`, etc.
