### ISSUE TITLE
Cordova not available on iPad using cordova-ios@6 or greater

### ISSUE THREAD

**Issue by Shane98c** [apache/cordova-ios#1097]
# Bug Report

### What is expected to happen?
cordova object should be available on iPad devices

### What does actually happen?
Cordova is not available

## Information
After upgrading our app from cordova-ios@5 to 6, we are not longer able to gain access to the cordova object on iPad devices, leading to plugin failure.

### Command or Code
In JS console type `cordova`

### Environment, Platform, Device
This seems to be exclusive to iPads. Cordova is available on all iPhone and Android devices we've tested. May potentially be related to https://github.com/apache/cordova-ios/issues/987

### Version information

Testing on iPad sim iOS@14.4 with cordova-ios@5 by typing `cordova` in the console window prints expected cordova object. When testing with cordova-ios@6 it returns a reference error.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by brodybits** [comment]
I would highly recommend you try this with a brand new Cordova project (do `cordova create`). I have already added the help wanted label.

I can try this on BrowserStack sometime early next week.

**Comment by Shane98c** [comment]
thanks @brodybits I should have done that earlier. This is working on on a blank project and appears to be an issue related to the interface between Ionic (3) and cordova. Would love to hear any ideas on where that issue could be coming from, but I'm going to close this in the meantime.

**Comment by brodybits** [comment]
I would recommend reporting this and #987 to Ionic then. It could help us avoid similar reports in the future. Thanks for the update.
