### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView

### ISSUE THREAD

**Issue by DuaneQ** [apache/cordova-ios#1099]
I've posted help requests on Stack and tagged Cordova, I've used your slack channel and Ionic and even apple but can't get any help.

I have no idea how to resolve this issue that's causing me to get rejected by Apple.  I've upgraded all of the Cordova plugins.  I've upgraded to cordova ios@5.1.x
I upgraded inAppBrowser to the latest version but I'm still seeing this in xCode:

`#ifdef __CORDOVA_4_0_0
    #import <Cordova/CDVUIWebViewDelegate.h>
#else
    #import <Cordova/CDVWebViewDelegate.h>
#endif

@class CDVUIInAppBrowserViewController;`

And I can't even find out which plugin is using 
`#if !WK_WEB_VIEW_ONLY

#import "CDVUIWebViewEngine.h"
#import "CDVUIWebViewDelegate.h"
#import "CDVUIWebViewNavigationDelegate.h"
#import "NSDictionary+CordovaPreferences.h"

#import <objc/message.h>

@interface CDVUIWebViewEngine `

and lastly:

`@interface CDVLocalStorage ()

@property (nonatomic, readwrite, strong) NSMutableArray* backupInfo;  // array of CDVBackupInfo objects
#if !WK_WEB_VIEW_ONLY
@property (nonatomic, readwrite, weak) id <UIWebViewDelegate> webviewDelegate;
#endif`

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).

**Comment by NiklasMerz** [comment]
You should use the latest version of cordova-ios and follow all steps to make you app ready for WKWebView. Most information should be here: https://cordova.apache.org/howto/2020/07/18/uiwebview-warning.html

As Tim said this is a support request and you should find help through different channels.
