### ISSUE TITLE
App view is scaled or cutting after keyboard open and close in file browse

### ISSUE THREAD

**Issue by sylvestrevgen** [apache/cordova-ios#1104]
# Bug Report

## Problem
App view is scaled or cutting after keyboard open and close in file browse
### What is expected to happen?
After file browse (choose file or just cancel) view is still the same.

### What does actually happen?
After file browse (choose file or just cancel) view is scaled/cutting.

### Environment, Platform, Device

iOS

### Version information
Cordova 10, cordova-ios 6.2.0, cordova-plugin-keyboard 1.2.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above
<img width="374" alt="Screenshot 2021-04-30 at 14 34 27" src="https://user-images.githubusercontent.com/32303723/116690162-ac558480-a9c1-11eb-8f9d-7e82b90abfd3.png">
<img width="376" alt="Screenshot 2021-04-30 at 14 34 44" src="https://user-images.githubusercontent.com/32303723/116690172-b081a200-a9c1-11eb-9883-af9dd2b3eda5.png">
<img width="375" alt="Screenshot 2021-04-30 at 14 34 56" src="https://user-images.githubusercontent.com/32303723/116690179-b1b2cf00-a9c1-11eb-9b7c-fcee3ecea8db.png">

**Comment by KuanYu0729** [comment]
I have the same issue. I'm using iOS 13.3

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been over a year with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

This sounds like an issue with the `viewport` meta tag values.

**Comment by dpogue** [comment]
Closing as stale.
