### ISSUE TITLE
Icon tag missing path errors logged as verbose

### ISSUE THREAD

**Issue by teranpeterson** [apache/cordova-ios#1106]
# Bug Report

### What is expected to happen?

When an icon tag references a missing source path, a warning or error should be displayed so that the user knows to fix it.

### What does actually happen?

All of the icons up to the missing icon are copied, and then the operation fails silently. The only way to detect this is to check the directory under `platforms/ios/<app name>/Images.xcassets/AppIcon.appiconset` or to install the app and see warnings/missing icons. 

### Command or Code

In `config.xml`:
``` html
<icon src="res/ios/icon-20.png" width="20" height="20" />
<icon src="res/ios/icon-24@2x.png" width="48" height="48" />
<icon src="res/ios/icon-27.5@2x.png" width="55" height="55" />
<icon src="res/ios/icon-40.png" width="40" height="40" />
...
```

### Environment, Platform, Device

This is happening consistently across all ios instances when `cordova prepare` or `cordova platform add ios` is run. 

### Version information

cordova-ios@6.2.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
I'm not able to reproduce this with cordova-ios 7.1.1:

```
$ npx cordova platform add ios

Using cordova-fetch for cordova-ios
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@7.1.1
Source path does not exist: nonexistent.png
```

with the following in config.xml:
```xml
    <platform name="ios">
        <icon src="nonexistent.png" width="1024" height="1024" />
    </platform>
```
