### ISSUE TITLE
App:// Scheme blocks all dynamic url loading patterns for cdn modules that use src="//whatever"

### ISSUE THREAD

**Issue by northkode** [apache/cordova-ios#1114]
# Bug Report

### What is expected to happen?
dynamic urls should still be able to load with https, but because of the cordova ios scheme of app://
JS and css scripts cant load when they are using the dynamic src of src="//somedomain.com/jstoload.js"

### What does actually happen?
the js tries to load from "app://somedomain.com/jstoload.js"

## Information
Can we remove this some how or have the wkwebview detect these calls and change there host protocal?

### Command or Code
Anything cordova ios 6.0.0+ because of the new app:// scheme

### Environment, Platform, Device
IOS

### Version information
All Versions

## Checklist

- [X ] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
this isn't a cordova issue, they shouldn't be using `src="//whatever"`, it's a bad practise, pretty sure it doesn't work when loading from file:// neither.
Also, there is nothing we can do, it's the webview itself what adds the scheme used to load the app when none is provided.
