### ISSUE TITLE
Please help to resolve issue about Cordova Platform iOS 6.x.x with Xcode 12.4

### ISSUE THREAD

**Issue by asgarde61** [apache/cordova-ios#1115]
# Bug Report

## Problem
I can't read and edit two files such as Cordova.h and Info.plist of the CordovaLib.xcodeproj through Xcode 12.4. These two files are red color. Please refer to the attached screenshot.

### What is expected to happen?
I expected that I can read and edit two files like a Cordova.h and an Info.plist.

### Command or Code

Please refer to the attached screenshots.

### Version information

Xcode 12.4
mac OS Catalina 10.15.7
Cordova 10.0.0
Cordova Platform iOS 6.1.1

## Checklist

- [V] I searched for existing GitHub issues
- [V] I updated all Cordova tooling to most recent version
- [V] I included all the necessary information above
![스크린샷 2021-05-29 오후 3 03 27](https://user-images.githubusercontent.com/84964029/120060391-8db2de00-c092-11eb-9bf6-1af20449c8c2.png)
![스크린샷 2021-05-29 오후 3 03 39](https://user-images.githubusercontent.com/84964029/120060396-96a3af80-c092-11eb-90ed-88ddb7db1113.png)

**Comment by dpogue** [comment]
This can happen if you open the .xcodeproj file instead of the .xcworkspace file.
