### ISSUE TITLE
Localstorage data cleared after app update from appstore

### ISSUE THREAD

**Issue by sargissaradyan** [apache/cordova-ios#1117]
# Bug Report

## Problem
After moving to wkwebview each time after app update localstorage data cleared  
### What is expected to happen?
Persist localstorage data after app update

### What does actually happen?
After updating app from AppStore localstorage data cleared  

### Command or Code

window.localStorage.setItem

### Environment, Platform, Device

All iOS devices

### Version information

Cordova iOS 6.2.0
Cordova CLI 10.0.0
Xcode 12.4

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by NiklasMerz** [comment]
Unfortunately this is not an issue that can be solved by Cordova. The iOS WebView tends to clear it's storage under certain conditions. I suggest you to investigate this and look for alternatives. 

From my experience native storage solutions (plugins) like SQLite are way more reliable.

**Comment by sargissaradyan** [comment]
> Unfortunately this is not an issue that can be solved by Cordova. The iOS WebView tends to clear it's storage under certain conditions. I suggest you to investigate this and look for alternatives.
> 
> From my experience native storage solutions (plugins) like SQLite are way more reliable.

Ok. Thank You.
