### ISSUE TITLE
How to set Bundle id via xcconfig in plist file? Is it broken ?

### ISSUE THREAD

**Issue by skurgansky-sugarcrm** [apache/cordova-ios#1118]
I have an issue with 6.2.0 version. prepare.js checks if PRODUCT_BUNDLE_IDENTIFIER and widget id in config.xml are different. If they are prepare.js will set PRODUCT_BUNDLE_IDENTIFIER from config.xml in project file.
I have PRODUCT_BUNDLE_IDENTIFIER=${APPLICATION_BUNDLE_ID} in project file for purpose and i can't delete it. **APPLICATION_BUNDLE_ID** is set via some xcconfig files for prod and dev builds. I also have `<key>CFBundleIdentifier</key<string>${APPLICATION_BUNDLE_ID}</string>` in plist but it is overridden via project file after prepare.js replaces `PRODUCT_BUNDLE_IDENTIFIER=${APPLICATION_BUNDLE_ID}` with `PRODUCT_BUNDLE_IDENTIFIER=com.acme.crm` .... Can i bypass it with some configuration settings?

**Comment by dpogue** [comment]
If you want to make different builds of the same Cordova project with different identifiers (such as for QA, Staging, and Production environments), I suggest looking at [seymour](https://www.npmjs.com/package/seymour) which will fill in config.xml values based on environment variables for use with CI systems.

Cordova itself only support building with the bundle identifier declared in config.xml.

**Comment by erisu** [comment]
Closing ticket as the above comment is sufficient.
