### ISSUE TITLE
No profiles were found

### ISSUE THREAD

**Issue by FireLizard** [apache/cordova-ios#1122]
# Bug Report

## Problem
When exporting the built app it should use the automatic created provisioning profile, but it was not found.
```shell
# part of `cordova build ios` (see below)
$ xcodebuild -exportArchive ...
...
Details:  Unable to close provisioning ledger entry because not all of its subentries are closed
Object:   <IDEProvisioningLedgerEntry: 0x7fe785999cb0>
Method:   -closeWithError:
Thread:   <NSThread: 0x7fe7853e1d70>{number = 8, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
error: exportArchive: Create certificate

Error Domain=IDEProvisioningErrorDomain Code=19 "Create certificate" UserInfo={IDEDistributionIssueSeverity=3, IDEProvisioningError_UserInfoKey_IDEProvisioningUserAction=<IDEProvisioningCreateTeamOwnedCertificateUserAction: 0x7fe7859aa8c0>, NSLocalizedRecoverySuggestion=Create a new Apple Distribution certificate for your team., NSLocalizedDescription=Create certificate}

error: exportArchive: No profiles for 'org.example.my-app' were found

Error Domain=IDEProfileLocatorErrorDomain Code=1 "No profiles for 'org.example.my-app' were found" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=No profiles for 'org.example.my-app' were found, NSLocalizedRecoverySuggestion=Xcode couldn't find any iOS App Store provisioning profiles matching 'org.example.my-app'.}

** EXPORT FAILED **
```

## Information
- Apple ID is registered in Xcode (_Xcode -> Preferences -> Account_)
- Automatic signing is enabled (verified through _Xcode -> Target Settings -> Signing & Capabilities_)
- Development Team is choosen (as before)
- Provisioning Profile was created by Xcode called "iOS Team Provisioing Profile: <app ID>"
- Signing certificate is in both keychains "System" and "Login"

It has worked so far until the provisioning profile was expired (`error: Provisioning profile "<name>" expired on 5. Jun 2021.`). 

### Command or Code
```shell
# clean or add the iOS build
$ cordova clean ios || cordova platform add ios --nosave

# build the iOS app (create archive and export)
$ cordova build ios --release --device --packageType=app-store --automaticProvisioning=true --codeSignIdentity="iPhone Developer" --developmentTeam="<team UID>"
```

### Environment, Platform, Device
- macOS Big Sur
- Xcode 12.5.1

### Version information
- cordova 10.0.0
- cordova-ios 6.2

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
The issue in this case is not the provisioning profile, but the certificate.

The next version of Cordova-iOS will include support for the Cloud Distribution certificate signing that was introduced in Xcode 13.
