### ISSUE TITLE
Upgrade cordova ios 5.1.0 -> 6.2.0. Caused Build input file cannot be found CDVWebViewProcessPoolFactory.m

### ISSUE THREAD

**Issue by alex-jesper** [apache/cordova-ios#1124]
# Bug Report
In an existing, working project I updated cordova ios from 5.1.0 to 6.2.0.
After that I get:
`error: Build input file cannot be found: '/Users/alex5828/bamboo-agent-home/xml-data/build-dir/DIA-DIAM16-BI/platforms/ios/CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewProcessPoolFactory.m' (in target 'CordovaLib' from project 'CordovaLib')`

### Command or Code
Installing as:
`ionic cordova build ios --device --prod  --release --buildConfig=build.json`

### Version information
Requirements check results for ios:
Apple macOS: installed darwin
Xcode: installed 12.4
ios-deploy: installed 1.10.0
CocoaPods: installed 1.9.3

npm list -g --depth 0
@ionic/cli@6.10.1
cordova@9.0.0
cordova-res@0.15.1
ios-deploy@1.10.0

## Checklist
- [x] I searched for existing GitHub issues
- [x] I included all the necessary information above

**Comment by NiklasMerz** [comment]
Did you remove the iOS platform first and checked the platforms folder to be empty? Possibly you need to upgrade other plugins like InAppBrowser.

Removing and addid the platform again should work.

**Comment by alex-jesper** [comment]
Well, its build from a CI system where the code is checked cleanly every time, so the platform is added and removed on each build i suppose. 
I basically just updated the ios-cordova package, and then let the build server do the work.

However, I found out that removing cordova-plugin-ionic-webview did the trick. I figure it is because the webview is now build-in, and having cordova-plugin-ionic-webview installed causes the error.

I am surprised no one else has this problem.
