### ISSUE TITLE
IOS, Calling js.focus() . the keyboard dose not show up

### ISSUE THREAD

**Issue by avrim-tr** [apache/cordova-ios#1130]
# Bug Report
IOS, Calling js.focus() . the keyboard dose not show up
## Problem
IOS, Calling js.focus() . the keyboard dose not show up
### What is expected to happen?
IOS, Calling js.focus() . the keyboard should show up

### What does actually happen?
IOS, Calling js.focus() . the keyboard dose not show up
By the way, in Android, it works well

### Environment, Platform, Device

IOS
### Version information

Cordova version: 10.0.0
part of our config.xml:
plugin name="cordova-plugin-ionic-keyboard" spec="2.2.0"
engine name="ios" spec="6.2.0"

## Checklist

- [V ] I searched for existing GitHub issues
- [V ] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by dpogue** [comment]
On iOS, the keyboard will only be shown in response to a user-initiated event. Calling `focus()` from JS code will not show the keyboard.
This is how Apple has designed the WKWebView on iOS to work.
