### ISSUE TITLE
Debugging WebKit

### ISSUE THREAD

**Issue by afioletov** [apache/cordova-ios#1136]
Did anybody try to debug WebKit? I'm trying to do it and see why I get "outside of sandbox" error described in #1134.

I followed instructions from [this article](https://engineering.salesforce.com/debugging-webkit-in-hybrid-mobile-apps-2eee63a4c922)
Xcode attaches to all required processes, but before initial page from bundle is rendered, com.apple.WebKit.WebContnet process fails with EXC_BAD_ACCESS (Code=2).

Was anybody able to successfully debug WebKit with Cordova app?
I use Cordova 10 and Cordova-ios 6.2.

![image](https://user-images.githubusercontent.com/40389323/128209568-b79deeb7-6c46-4dd4-90f5-c387c5ee27cd.png)

**Comment by sgoldberg-sfdc** [comment]
@afioletov are you able to debug Webkit in a non-Cordova simple WKWebview app? Recently I have seen crashes, even attaching safari debugger to iOS Simulator Debug builds. I believe it works if the app is a release build with symbols.

**Comment by sgoldberg-sfdc** [comment]
FWIW, when I wrote that article, we were using Cordova.

**Comment by afioletov** [comment]
Hi Stephen, thank you for response.
 
I tried to use release build, but got the same error. And I tried to use both debug builds (webkit app) - same result.
Do you have link to some non-Cordova simple WKWebview app? I'll try to run it and see if it works in my environment.

**Comment by afioletov** [comment]
I've just took the first I found in google: https://github.com/mmafrar/swift-ios-wkwebview-demo

Selected app from 
/Users/admin/Library/Developer/Xcode/DerivedData/wkwebview-fkbzjlguoomnlmhlhglpctmvqkol/Build/Products/**Release-iphonesimulator** and got the same issue. So I assume Cordova does not affect it.

**Comment by afioletov** [comment]
Looks like I missed something. The update-webkit fails with error, I'll start from scratch with webkit.

**Comment by sgoldberg-sfdc** [comment]
Thanks; feel free to ping me directly. Also, if you have updated Xcode since the last time you ran it, you may need to re-run

`sudo Tools/Scripts/configure-xcode-for-embedded-development`

**Comment by afioletov** [comment]
Good morning, Stephen.

No luck :( I tried it couple more times, but looks like I still missing something.

- MacBook Air (M1, 2020)
- macOS Big Sur 11.5
- Xcode 12.5.1 
- Simulators with iOS 14.5
- WebKit's master branch 

I run following commands:
```
git clone git://git.webkit.org/WebKit.git WebKit 
cd WebKit
sudo Tools/Scripts/configure-xcode-for-embedded-development
./Tools/Scripts/update-webkit
Tools/Scripts/build-webkit --ios-simulator

```
Set the relative paths and select WebKit scheme. It starts but crash exactly the same way. 
What hardware do you use? Might M1 creates the issue?

**Comment by sgoldberg-sfdc** [comment]
I am on an Intel-based iMac, I do not have an M1 machine to test.

Since this issue is occurring on non-Cordova projects as well I recommend closing this issue and we can take this discussion to another forum. Webkit has a Dec Slack you can join as well. webkit.slack.com.

**Comment by afioletov** [comment]
I created [new bug](https://bugs.webkit.org/show_bug.cgi?id=228990) in webkit bugzilla.
