### ISSUE TITLE
Positioning  cursor inside input doesn't work very well

### ISSUE THREAD

**Issue by angjelkom** [apache/cordova-ios#1142]
# Bug Report

## Problem
Moving cursor inside input field by tapping barely works

### What is expected to happen?
Like on android tapping inside input should move the cursor to the exact position

### What does actually happen?
The cursor doesn't move to the exact position instead it either:
- doesn't move at all
- moves to the very end
- very rarely it succeeds to move to the correct position
- it moves to the correct position but before that for a moment it moves to the very end

## Information

- I've tested this with a hello world app on iOS, just for comparison the Slack application on iOS and other similar apps don't have this issue

### Command or Code

Just a sample Hello World app with input field

### Environment, Platform, Device

Device: Iphone 8 plus
Platform: iOS 14.6

### Version information

Cordova iOS 6.2.0
Cordova 10.0.0
Xcode 12.5.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Text cursor control is handled by the webview and/or the OS, in this case WKWebVIew. So I don't think this is a Cordova issue. Can you create a sample XCode iOS app (Not using Cordova) to reproduce this issue? If so, I'd suggest taking that sample app and raising a bug report against WebKit.

Otherwise, someone smarter than me might be able to give better insight.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been over a year with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
