### ISSUE TITLE
evaluateJavaScript  do not work. without UIWebView component

### ISSUE THREAD

**Issue by dadigua2333** [apache/cordova-ios#1143]
When I communicate with the web. IOS actively notifies the web. I use it
 `[self.commandDelegate evalJs:@""];`
It doesn't work. But I use the old version. When UIWebview component is included, it can. Does WKWebview need to make some other settings?

**Comment by breautek** [comment]
If you wanted to send a message to the webview, you should be going through the plugin interface for the callback system, e.g. the webview registers a callback which the cordova plugin can keep the callback alive and reuse as necessary for continuous events.

But as for as evaluating javascript with WKWebview, I think you'll find [this](https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript?language=objc) interesting, but not recommended in the context of cordova plugins.
