### ISSUE TITLE
Pod error on app with scandinavian chacters in the name

### ISSUE THREAD

**Issue by cbjerg** [apache/cordova-ios#1150]
# Bug Report

## Problem
Using @havesource/cordova-plugin-push 2.0.0 in an app with a special character in the name (like æ ø å)results in a linker error. Pods install fine, but Xcode shows a build error: ld: framework not found Pods_Special_L_ringsportal (Project name is Special Læringsportal). All pods are in the correct places, and named correctly in the filesystem

### What is expected to happen?
App would build, as it does without adding the @havesource plugin

### What does actually happen?
Xcode shows a build error: ld: framework not found Pods_Special_L_ringsportal

### Environment, Platform, Device
MacOS: Catalina 10.15.4
Xcode: 12.4
Cordova-ios: 6.2.0 (tried 6.1.0 and 6.0.0 withg same result)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by meidlinga** [comment]
Probably same as: https://github.com/havesource/cordova-plugin-push/issues/95

**Comment by TripShade** [comment]
We are also experiencing this.

**Comment by meidlinga** [comment]
@TripShade , we worked around this issue the following way:
* Set the name itself to an alias without special characters (e.g. part of the package name). This wont be visible in the end.
* Set the short name to the prefered app name containing special characters
Example: `<name short="{{= name}}">{{= alias}}</name>`

* Set the Android App label explicitly in the Manifest
`
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
[...]
    <application android:label="{{= name}}" />
</edit-config>
`

**Comment by TripShade** [comment]
> @TripShade , we worked around this issue the following way:
> 
> * Set the name itself to an alias without special characters (e.g. part of the package name). This wont be visible in the end.
> 
> * Set the short name to the prefered app name containing special characters
> 
> Example: `<name short="{{= name}}">{{= alias}}</name>`
> 
> 
> 
> * Set the Android App label explicitly in the Manifest
> 
> ```
> 
> <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
> 
> [...]
> 
>     <application android:label="{{= name}}" />
> 
> </edit-config>
> 
> ```

Thx I'll give this a go 😃

**Comment by meidlinga** [comment]
@TripShade : I added a step i forgot to mention initially

**Comment by TripShade** [comment]
@meidlinga Works great thx again!

**Comment by acgodoi** [comment]
@meidlinga Worked for me as well! Great job! Thanks!
