### ISSUE TITLE
Cordova iOS 6.2.0 has not been published on Cocoapod

### ISSUE THREAD

**Issue by wmathurin** [apache/cordova-ios#1152]
# Bug Report

## Problem
Cordova iOS 6.2.0 has been published to npm back in February 2021. https://cordova.apache.org/announcements/2021/02/04/cordova-ios-release-6.2.0.html

But it was not published on Cocoapod. Instead the version there is still 6.1.1 published in September 2020.

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by timbru31** [comment]
Hi @NiklasMerz you took care of the latest release - can you take a look? I bet @erisu can support if assistance is required 👍

**Comment by erisu** [comment]
@wmathurin I just pushed 6.2.0 to CocoaPods: https://cocoapods.org/pods/Cordova

**Comment by wmathurin** [comment]
@FanningHau, our workaround is to point to github in our cordova plugin:

`<pod name="Cordova" git="https://github.com/apache/cordova-ios" tag="6.3.0" />`

See: https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/blob/dev/plugin.xml#L106

**Comment by FanningHau** [comment]
@wmathurin 
OK, thanks for your reply

**Comment by NiklasMerz** [comment]
6.3.0 is now published thanks to @erisu
