### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET is hardcoded to 8.0 and override does not work

### ISSUE THREAD

**Issue by laurentperez** [apache/cordova-ios#1164]
# Bug Report
- cordova add platform ios 6.2.0
- the Pods project.pbxproj has an harcoded version of ios8.0
- setting in config.xml a newer <preference deployment-target> has zero effect, per https://cordova.apache.org/docs/en/10.x/config_ref/

## Problem
- unable to override ios8.0, can't build for > 8 versions
- latest xcode on ARM64 M1 macs wants at least ios9
- can't use cordova ios on latest xcode since ios8.0 can't be overriden

### What is expected to happen?
- setting the config.xml preference deployment-target should erase the hardcoded project.pbxproj ios 8

### What does actually happen?
- ios8 is hardcoded hence xcodes fails to build since 9.0 - 15.0 is required

### Version information

- cordova 10.0.0
- ionic 6.12.4

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by pgib** [comment]
Running into this as well. 😕

**Comment by phablulo** [comment]
is there any workaround for this?

**Comment by peitschie** [comment]
If I'm understanding this correctly... this appears to be simply how CocoaPods works:
* https://github.com/CocoaPods/CocoaPods/issues/4859
* https://github.com/CocoaPods/CocoaPods/issues/7314

Changing this value only changes the Pod project's own default deployment target, which does nothing for the deployment settings of any individual pods.
