### ISSUE TITLE
App getting crash on IOS 15.1.1 , but working fine on IOS 15.0

### ISSUE THREAD

**Issue by 21pg** [apache/cordova-ios#1205]
# Bug Report
My app getting crash on IOS 15.1.1 while it works fine on IOS 15.0..

## Problem
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
*** First throw call stack:
(0x184ec1c9c 0x19c075758 0x19c32dedc 0x19c330a58 0x1873511a4 0x18753016c 0x1875f3bcc 0x187334464 0x18767c60c 0x18747ee64 0x1873f0798 0x1873d1b8c 0x19c330004 0x1873ccf4c 0x187637a40 0x187333354 0x187307b04 0x1874b4aac 0x187460968 0x19ea5aa80 0x19ea5a960 0x19ea5a940 0x1045ff99c 0x1045fb134 0x104df0718 0x104df1f94 0x104df4798 0x104e03d90 0x104e046fc 0x1dee95e48 0x1dee959f0)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
terminating with uncaught exception of type NSException

## Information
Installed platforms:
  ios 6.1.1

### Version information
---------------------Requirements check results for ios:----------------------------------
Apple macOS: installed darwin
Xcode: installed 13.1
ios-deploy: installed 1.11.4
CocoaPods: installed 1.11.2
---------------------Plugin installed -------------------------
cordova plugin add @ahovakimyan/cordova-plugin-wkwebviewxhrfix

@havesource/cordova-plugin-push 3.0.0 "Cordova Push Plugin"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-camera 5.0.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-theme-detection 1.2.1 "ThemeDetection"
cordova-plugin-whitelist 1.3.5 "Whitelist"
cordova-plugin-wkwebviewxhrfix 1.0.0 "Cordova WKWebView File XHR Fix"
cordova-plugin-x-socialsharing 5.3.2 "SocialSharing"
cordova-sqlite-evcore-extbuild-free 0.9.2 "Cordova sqlite storage - free enterprise version with Android performance/memory improvements and extra features for PhoneGap Build"
es6-promise-plugin 4.2.2 "Promise"

[https://i.diawi.com/jKHWGo]

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by 21pg** [comment]
Issue was due to plugin @ahovakimyan/cordova-plugin-wkwebviewxhrfix
I replaced it.. and it working now..

**Comment by kw-pr** [comment]
@21pg Can you tell me what you used instead?

**Comment by 21pg** [comment]
> @21pg Can you tell me what you used instead?
I replaced @ahovakimyan/cordova-plugin-wkwebviewxhrfix with 
 @globules-io/cordova-plugin-ios-xhr
 and added preference -
  <preference name="AllowUntrustedCerts"  value="true" />
  <preference name="InterceptRemoteRequests" value="all" />
  <preference name="allowFileAccessFromFileURLs" value="true" />
  <preference name="allowUniversalAccessFromFileURLs" value="true" />
