### ISSUE TITLE
Missing module "cordova-common" for ios platform add. (Cordova 6.5.0) 

### ISSUE THREAD

**Issue by smcnary** [apache/cordova-ios#1207]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
I'm having an issue running a build using a mac os X 11 build in azure devops.  I'm using cordova 6.5.0 and cordova ios 6.0.0.  It's keeps giving me the error that I'm missing "cordova-common".  I've tried doing an npm i -g cordova-common, but I'm still getting the error nonetheless.  I've tried using the latest version of cordova and tooling but get the same error.  
## Information
![image](https://user-images.githubusercontent.com/7374394/144243013-4ebbc1ae-b666-429d-b577-969ff313ee12.png)

### Command or Code
Console Commands: 
    npm i -g cordova@6.5.0
    npm i -g cordova-common
    cordova platform add ios@6.0.0

### Environment, Platform, Device
OS: macOS 11

### Version information
Cordova 6.5
Operating System : Mac OSX 11
Cordova IOS 6.0.0

## Checklist

- [x ] I searched for already existing GitHub issues about this
- [x ] I updated all Cordova tooling to their most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment]
>  cordova 6.5.0

This is an ancient version that is no longer supported. The latest cordova cli version is `10.0.0`.

> cordova platform add ios@6.0.0

Any particular reason you're using `6.0.0` exactly? Version 6.0.0 has some known issues which have been patched. I can't recall if cordova-common issues is one of them or not. The latest version currently is 6.2.0

No need to install `cordova-common` manually. They are dependencies of both `cordova-cli` and `cordova-ios` and will likely have their own versions installed in their own `node_modules` folder.

> I've tried using the latest version of cordova and tooling but get the same error.

To be clear, you've tried with `cordova-ios@6.2.0 and `cordova@10.0.0` ?

**Comment by breautek** [comment]
> In the meantime, is there a fix for the issue I'm having with the cordova-sqlite-storage storage plugin?

I use `cordova-sqlite-storage@6.0.0` successfully in my apps.

Older versions of Cordova allowed used to expose cordova's dependencies via `requireCordovaModule` method which was never intentional. But plugins used to consume cordova's dependencies rather than declaring/importing their own dependency. This obviously created brittle code and made it very hard for Cordova to update without breaking plugins that did this practice.  `cordova-sqlite-storage@6.0.0` appears to have these bad practices corrected.

**Comment by smcnary** [comment]
@breautek Correcting issues in package.json (we had older versions listed) as well as removing all specific installs in our build pipeline corrected the issue.  Thanks for your help.
