### ISSUE TITLE
How to support the front-end page to ignore the service verification of self signed certificates？

### ISSUE THREAD

**Issue by jingtiaopi** [apache/cordova-ios#1213]
I want your help. The network request is HTTPS, but it is a self signed certificate. How to set how certificate authentication can be ignored on IOS. I found that the network is initiated by JS and WebView cannot intercept it. Thank you!

**Comment by jcesarmobile** [comment]
It's not officially supported to ignore certificate exceptions as it's a security vulnerability.

You can probably create a plugin to do it or search as it might even exist already.
