### ISSUE TITLE
IOS 15.1: TypeError: undefined is not an object (evaluating 'window.webkit.messageHandlers')

### ISSUE THREAD

**Issue by vladislavgolubev** [apache/cordova-ios#1214]
# Bug Report

## Problem
Some users of my application complain that the application does not work.
I see an error in Sentry "TypeError iOSExec(cordova)" - undefined is not an object (evaluating 'window.webkit.messageHandlers')
https://sentry.io/share/issue/0f44ff97202e45e6932eb5b84cf80c70/

the error appears when any plugin tries to interact with the application via iOSExec  (window.webkit.messageHandlers.cordova.postMessage).

## Information
BROWSER
Name	: Mobile Safari
Version	: 15.1
DEVICE
Brand	: Apple
Family	: iPhone
Model	: iPhone 
OPERATING SYSTEM
Name	: iOS
Version	: 15.1

Any ideas?

**Comment by timbru31** [comment]
What version of cordova-ios are you using?

**Comment by bryan-hunter** [comment]
@vladislavgolubev @timbru31 I ran into this issue as well.  I can't reliably reproduce it, but it seems to happen after navigating away from the app (window.open or openUrl natively).

I don't know of a workaround atm.  Any thoughts?

**Comment by bryan-hunter** [comment]
I was able to reproduce it consistently by performing a window.open to a non-whitelisted URL (any URL that wasn't in my `allow-navigation`) that would open the url in the system browser (ie: `window.open(url, '_system')` ...  '_blank' may cause the same thing, but _system definitely does).

I modified all `window.open`s and `href`s to instead use `cordova.InAppBrowser.open(url, '_blank')` and that seemed to solve it.

Hope this information helps someone searching for the same issue as me.  Or someone corrects me and has a better solution :)

**Comment by bryan-hunter** [comment]
another problem that I just ran into:

I render a Spotify provided iFrame in my app (RYSE - check it out!).

this iFrame has a button to open https://open.spotify.com/

I have this url whitelisted in my Allow Navigation list, but because it is inside an iFrame, it hits an AppBoundDomains error.

**Comment by gazben** [comment]
I've managed to solve the issue, by setting the app bound domains. The whole problem comes from the fact that cordova cannot access some API-s on the given domain.

**Comment by bryan-hunter** [comment]
> I've managed to solve the issue, by setting the app bound domains. The whole problem comes from the fact that cordova cannot access some API-s on the given domain.

ahh, that's good to know, thanks!

**Comment by dpogue** [comment]
Having looked into this a bit, it appears to be the intended behaviour when App-Bound Domains are involved.

From https://webkit.org/blog/10882/app-bound-domains/ (emphasis mine):
> Due to the asynchronous nature of the web, a SocialApp developer could see different errors if trying to use restricted APIs and navigate to non app-bound domains in the same `WKWebView`. If a `WKWebView` in SocialApp uses a restricted API before any navigations occur, and then tries to navigate to a domain outside of the set of “app-bound” domains, the navigation will fail with the error “App-bound domain failure.” **Conversely, if SocialApp first navigates to a non-app-bound domain then tries to use a restricted API, the API call will fail.**

I don't think there's anything Cordova can do here.
