### ISSUE TITLE
The <content /> config setting for the entrypoint of the app is not working

### ISSUE THREAD

**Issue by CodeWithOz** [apache/cordova-ios#1217]
# Bug Report
Specifying a custom entry point for the app using `<content src="someothername.html" />` is not working.

## Problem
My app's entry point is named `main.html` rather than `index.html`. On Android it works as expected, the file is loaded when the app boots up. But on iOS the document never loads. Instead I get this message in the network tab of dev tools: `The resource was requested insecurely`. Changing the name to `index.html` makes it work properly.

### What is expected to happen?
The document should load the entrypoint file that's specified by the `<content>` tag in `config.xml`.

### What does actually happen?
The app builds but the document doesn't load. The html of the app just shows
```
<html>
  <head></head>
  <body></body>
</html>
```

### Command or Code

Create a new cordova project, rename the `index.html` file to `main.html`, then build the app.

### Environment, Platform, Device

Using iPhone simulator (xcode 13) to run an iPhone 13 simulator running iOS 15.2

### Version information

cordova ios v6.2.0, cordova cli 11

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
On Slack you commented that you were using ionic webview plugin, have you tried without it?

**Comment by CodeWithOz** [comment]
Yes I tried without the plugin and it worked but on the `file://` protocol.

**Comment by jcesarmobile** [comment]
cordova-ios 6.x also supports using schemes, I thought it was the default already, but looks like it was changed to default to file, so can you configure a scheme to use? i.e `<preference name="scheme" value="ionic" />` (so it uses the same as ionic webview plugin and you don't lose any data)

**Comment by msmtamburro** [comment]
Schemes look like they're currently broken due to: https://github.com/apache/cordova-ios/issues/1223#issuecomment-1608211672

**Comment by jcesarmobile** [comment]
I've retested on cordova-ios 6.3.0 and it's working fine.
