### ISSUE TITLE
npm security audit reports shelljs vulnerability

### ISSUE THREAD

**Issue by almercier** [apache/cordova-ios#1219]
# Bug Report

### What is expected to happen?
Running `npm audit` should report no vulnerable dependencies used by the latest version of cordova-ios

### What does actually happen?
I get an `Improper Privilege Management in shelljs ` warning from cordova-ios dependencies

## Information

```
shelljs  <0.8.5
Severity: moderate
Improper Privilege Management in shelljs - https://github.com/advisories/GHSA-64g7-mvw6-v9qj
fix available via `npm audit fix --force`
Will install cordova-ios@4.0.1, which is a breaking change
node_modules/shelljs
  simctl  >=0.0.2
  Depends on vulnerable versions of shelljs
  node_modules/simctl
    ios-sim  >=4.1.0
    Depends on vulnerable versions of simctl
    node_modules/ios-sim
      cordova-ios  >=4.1.0
      Depends on vulnerable versions of ios-sim
      node_modules/cordova-ios
```
Interestingly, the audit fix seems to think installing v4.1.0 will fix this issue, which is two major version behind where I am at currently on 6.2.0

### Command or Code

`npm i cordova-ios@latest`
`npm audit`

### Environment, Platform, Device

Macbook Pro, 15-inch, 2016

### Version information

MacOS 12.1
npm 8.1.2
cordova-ios 6.2.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by almercier** [comment]
Did some digging and shellJS is being installed from cordova-ios 6.0.0 as a nested dependency.
shellJS has since fixed the patch, but simctl which is depended by ios-sim which is depended by cordova-ios hasn't updated to it yet.

It's frustrating that a clean install of cordova-ios generates npm audit warnings, and it's frustrating that the bug report was dismissed as a invalid when it is immediately replicable albeit not exactly immediately solvable.

https://github.com/ios-control/simctl/issues/27

**Comment by almercier** [comment]
@breautek 
![image](https://user-images.githubusercontent.com/30079507/151579715-09d1d81a-6870-4af8-ad7b-bb772e70ac07.png)

**Comment by NiklasMerz** [comment]
[simctl has been updated](https://github.com/ios-control/simctl/releases/tag/v2.0.1) and the issues should be gone.

**Comment by almercier** [comment]
Just waiting on ios-sim to update to that simctl version. I submitted an issue there as well.
https://github.com/ios-control/ios-sim/issues/276

Once ios-sim gets that patch, then cordova-ios will need to bump their ios-sim dependency
