### ISSUE TITLE
iOS Native Camera View Occluding getUserMedia Camera stream and UI

### ISSUE THREAD

**Issue by ImranGholizadeh** [apache/cordova-ios#1226]
# Bug Report

## Problem

I have a webcam and QR reader feature that uses getUserMedia implemented in my Vue.js app, all is working perfectly on the browser. Now I am building the app for iOS using which needed an extra layer of explicit permission in info.plist. Now the app has the correct permissions to access the device camera on iOS (even though it asks for permissions twice, one for native camera access and one for getUserMedia stream). Below is the issue:

My app is calling the device's native camera which is overlaying the getUserMedia stream that we currently have in the app...and the native camera and its UI are occluding the UI overlaying the getUserMedia stream.

Are there any suggestions to quickly find a solution for this?

### What is expected to happen?

the user permits the app to use their camera and it opens the getUserMedia stream and UI that is implemented and working on the browser. 

### What does actually happen?

the native iOS camera completely covers and occludes the getUserMedia stream and UI and the getUserMedia steam is frozen. 

## Information

I am new to iOS builds using cordova, bear with me! 

### Command or Code

I can give access to the app on testflight. 

### Environment, Platform, Device

iOS 12 pro max using https://github.com/m0dch3n/vue-cli-plugin-cordova plugin in my Vue.js app

### Version information

Cordova plugin for vue: 
https://github.com/m0dch3n/vue-cli-plugin-cordova

Vue 2.6.1

xcode 12 

iOS target 14.4 

device iphone 12 Pro Max

## Checklist

- [x ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by logical99** [comment]
Hi Imran,

We are also facing similar issue. I saw that you managed to get it partially working through some xcode tweaks. Any suggestions?

Regards,
Vish

**Comment by ImranGholizadeh** [comment]
Hello logical99,

Yes, this issue has been solved by adding the following code to your config file.

<preference name="AllowInlineMediaPlayback" value="true" />    

Ensure the value for AllowInlineMediaPlayback is true which disables the native full screen controller and allows html5 to play inline on iOS.

Steps
1. Find your config.xml file in your xcode projects staging folder
2. Edit the preference value for AllowInlineMediaPlayback to true

<preference name="AllowInlineMediaPlayback" value="true" />  

3. Rebuild and test getUserMedia on the simulator.

**Comment by jcesarmobile** [comment]
closing since the issue was resolved
