### ISSUE TITLE
Custom URL Scheme that has Dynamic URL Params

### ISSUE THREAD

**Issue by ImranGholizadeh** [apache/cordova-ios#1227]
I want to change the scheme and hostname in my app to a custom URL scheme that has dynamic url params. Because the URL params are dynamic (using vue.js router) the app needs to account for rendering specific UI and data based on the param. 

For instance, I have a QR reader that redirects the user to a view that renders UI based on the URL param id.. 
So the QR reader redirects the user to a view such as https://xxxxxxxx.com/12345 where the param id is 12345.

In that case, how should I alter the code from my config.xml file below?

    <preference name="scheme" value="app" />
    <preference name="hostname" value="localhost" />

Building the app in Vue.js and using https://github.com/m0dch3n/vue-cli-plugin-cordova as a codova plugin.

**Comment by NiklasMerz** [comment]
I once implemented a plugin to switch the scheme at runtime. It's very experimental and you have to be a bit careful to make it work properly but it can be useful in some cases. https://github.com/GEDYSIntraWare/cordova-plugin-webview-switch
