### ISSUE TITLE
Change language app from device settings

### ISSUE THREAD

**Issue by adriansaenz** [apache/cordova-ios#1234]
Hi!
I'm doing an application using ionic framework and i'm looking for a way to change the app language from device app settings but i don't see any plugin to do it. I'm using the ngx-translate library to manage all translations inside the app but i don't see any connection with device setting.
Is there any plugin to get if user change the app language from device setting?

**Comment by breautek** [comment]
The webview way of doing this is via [languagechange](https://developer.mozilla.org/en-US/docs/Web/API/Window/languagechange_event#browser_compatibility) event on the `Window` object.

But I have no idea if system webviews invokes this correctly. Probably worth testing though.

**Comment by adriansaenz** [comment]
I was able to test it adding that language change event and it seems that is working. I did not test it deeply but for the moment seems to work.

**Comment by jcesarmobile** [comment]
Closing since languagechange event seems to work
