### ISSUE TITLE
cordova ios 6.1.0 all xhr POST requests failing and are converting as blob request

### ISSUE THREAD

**Issue by gangishettisahiti** [apache/cordova-ios#1236]
### Issue Type

- [ ] Bug Report

## Description
 I have migrated the Cordova app from UIWebview to WKWebview. All the ajax post calls are getting failed and they are converted as blob requests.  I am using the "cordova-plugin-wkwebview-file-xhr " plugin.

### Environment, Platform, Device

Cordova ios 6
iphone 11

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by NiklasMerz** [comment]
This is not a Cordova issues and more an issue of your implementation. You most likely need to make your CORS setup work.

You can probably learn from [my journey](https://blog.merzlabs.com/posts/webview-history/).
