### ISSUE TITLE
Apple App Store rejection due to non-public selectors

### ISSUE THREAD

**Issue by srkleiman** [apache/cordova-ios#1239]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Information

Today when I tried to build and submit an app that had been submitting fine I get:

> App Store Connect Operation Error
> The app references non-public selectors in Payload/Baron Performance.app/Baron Performance: applicationNameForUserAgent, initWithFrame:configuration:, isMainFrame, navigationDelegate, navigationType, setNavigationDelegate:, setProcessPool:, targetFrame, userContentController
> 

I upgraded to the latest Cordova CLI, Platforms, Xcode, no joy. Same error submitting via Xcode and or xcrun.

Other people are having this problem as well: https://developer.apple.com/forums/thread/127678

I believe Apple changed something that is causing Cordova apps to be rejected.

### Environment, Platform, Device

MacOS 12.3.1
Xcode 3.4.1

### Version information

Cordova 11.0.0
android 10.1.2
ios 6.2.0
cordova-plugin-splashscreen 6.0.1
cordova-plugin-statusbar 3.0.0

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
It sounds like this is affecting Cordova, Capacitor, Flutter, and ReactNative, and probably others as well.

Cordova iOS does not use any private APIs by default, and none of the Apache plugins do either, specifically to avoid running into this problem. (3rd party plugins might use private APIs, but we have no control over that)

This sounds like the issue is 100% on Apple's side, but I'll leave this open until we have some sort of resolution.

**Comment by shankari** [comment]
I got a similar error for an app built on a platform that has been used for multiple apps before (https://github.com/e-mission/e-mission-phone/)

I went through and searched for each supposedly private API listed, and all of them bar `transform` are related to the cordova libraries. 

- `applicationNameForUserAgent`: `CDVWebViewEngine`, `CDVWKInAppBrowser`, `CDVWKWebViewEngine`
- `dataTypes`: lots of javascript, `CDVWKInAppBrowser`
- `initWithFrame:configuration`: `CDVWebViewEngine`, `CDVWebViewUIDelegate`, `CDVWKInAppBrowser`, `CDVWKWebViewEngine`. There are other calls to `initWithFrame` but without the `configuration` parameter, 
- `isMainFrame`: `CDVWebViewUIDelegate`
- `navigationType`: `CDVWebViewEngine`, `CDVIntentAndNavigationFilter`, `CDVWKWebViewEngine`
- `setProcessPool`: not found
- `targetFrame`: `CDVWebViewUIDelegate`, `CDVWKInAppBrowser`
- `transform`: lots of javascript matches, `OIDExternalUserAgentIOSCustomBrowser` (from JWT), `GDTCORTransformer` (from GoogleDataTransport)
- `userContentController`: `CDVWebViewEngine`, `CDVWKInAppBrowser`, `CDVWKWebViewEngine`

**Comment by shankari** [comment]
I then checked the first three methods above against the apple documentation and they seem to be documented, public APIs in the webkit framework.

- `applicationNameForUserAgent`: https://developer.apple.com/documentation/webkit/webview/1408381-applicationnameforuseragent (public, deprecated)
- `dataTypes`: called on `WKWebsiteDataRecord`, https://developer.apple.com/documentation/webkit/wkwebsitedatarecord/1538007-datatypes?language=objc (public)
- `initWithFrame:configuration`: called on WKWebView, https://developer.apple.com/documentation/webkit/wkwebview/1414998-initwithframe?language=objc (public)

It looks like Apple's "non-public API usage" is not accounting for the public API for the WKWebView code, so it is breaking consistently for CordovaLib.

@dpogue are the cordova maintainers already in contact with Apple? Or should I file a tech support ticket?

**Comment by dpogue** [comment]
> @dpogue are the cordova maintainers already in contact with Apple? Or should I file a tech support ticket?

We have no direct contact with Apple, but I imagine they are getting lots of reports since this seems to affect almost every iOS app.

**Comment by shankari** [comment]
FYI: Developer Technical Support will be supporting [WWDC](https://developer.apple.com/wwdc22/) and won't be reviewing requests from June 4 to 12, 2022.

🙄 🤦

**Comment by paulocoutinhox** [comment]
Hi,

Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."

Thanks.

**Comment by shankari** [comment]
I can confirm that it worked on resubmission.

**Comment by dpogue** [comment]
Glad to hear. I'm going to mark this issue as closed :)
