### ISSUE TITLE
Unable to load the thewebview , cordova pliugin might cause this to kill it with error code （NSURLErrorDomainError-999）

### ISSUE THREAD

**Issue by guwitpro1** [apache/cordova-ios#1247]
# Bug Report

## Problem

When the native app runs on the IOS, and click on the ok button, and supposed to launch the page where the html load

This failed at the loadrequest
NSURL* URL = [[NSBundle mainBundle] URLForResource:@"camera.html" withExtension:nil subdirectory:@"www" ];
                
                [theWebView loadRequest:[NSURLRequest requestWithURL:URL]];
                
                return [ super webView:theWebView shouldStartLoadWithRequest:[NSURLRequest requestWithURL:URL] navigationType:5 ];
            }

I can see the error code below
2022-08-04 14:41:07.272673+0900 Alohajay[68157:2046295] Finished load of: https://www-412.alohajay.co.jp:447/Alohajay/content/OSE/page/index.html? clientId=287412&seqNo=561&agentCode=9000000010&navigate=N010&time=20220804144106
2022-08-04 14:41:31.987026+0900 Alohajay[68157:2046295] MainViewController url = https://www-412.alohajay.co.jp:447/Alohajay/N330Camera?&A=22J0102264&A=%E5%90% 8C%E6%84%8F%E6%9B%B8(%E7%81%BD%E5%AE%B3%E8%A3%9C%E5%84%9F%E8%A6%8F%E5%AE%9A %E7%AD%89%E6%B7%BB%E4%BB%98%E8%A3%9C%E8%B6%B3%E7%A2%BA%E8%AA%8D%E7%94%A8)&A =SBA49482&A=287412&A=561&A=5&A=9000000010
2022-08-04 14:41:31.989501+0900 Alohajay[68157:2046295] Resetting plugins due to page load.
2022-08-04 14:41:31.994464+0900 Alohajay[68157:2046295] Failed to load webpage with error: Could not complete the operation. (NSURLErrorDomain error -999)

and added the debug statement 
- (void)webView:(UIWebView *)webView didFailLoadWithError:(NSError *)error

{

NSLog(@"Error %i", error.code);

if (error.code == NSURLErrorCancelled) return; // this is Error -999

// error handling for "real" errors here

}

Shows below error
11:18:56.445482+0900 SMSC[91920:2570965] void SendDelegateMessage(RetainPtr<NSInvocation> &&): delegate (webView:didFailProvisionalLoadWithError:forFrame:) failed to return after waiting 10.000000 seconds. main run loop mode:

### What is expected to happen?
the loadRequest should load the camera.html but it does not load, and the native app has eyeglass.

### What does actually happen?
the camera.html loaded, and the user can take photos, and upload the picture to the server

## Information

Ipad 13 was working as claim but once we loaded the Xcode tool, and tested on simulator 13 using IOS15

### Command or Code

Run the native app , jsp pages, and get the point the html file opened

### Environment, Platform, Device

IOS 15, 14, 13 tested

### Version information

Ios15 
xcode 13.2.1
cordova-plugin-camera-version 6
inappbrowser 15.4
plugin file transfer 1.7.1
cordova-plugin-file 7.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
It looks like you're hosting your cordova app assets remotely (e.g. your cordova web assets aren't bundled within the app itself). If this is the case, using cordova plugins that exposes the native device APIs isn't supported. When code is not embedded in the binary, the app may only use standard WebKit features/APIs and must not attempt to extend or expose native platform APIs, according to Section 4.7 & 4.7.1 of the [Apple App Store](https://developer.apple.com/app-store/review/guidelines/#third-party-software) policies.

Can you confirm that is your case?

**Comment by breautek** [comment]
Closing as stale
