### ISSUE TITLE
https requests cannot be intercepted by NSURLProtocol

### ISSUE THREAD

**Issue by stupidchou** [apache/cordova-ios#1252]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
When I call the https request, I want to use the local js file and find that the local js cannot be intercepted

## Information
When using cordova to access remote html, I use <script src="ebeiapp://cordova.js"> to call my local js in html, and [NSURLProtocol wk_registerScheme:@"ebeiapp"] has been executed in iOS, Intercepted but https request NSURLProtocol interception did not take effect.

### Command or Code
 [NSURLProtocol wk_registerScheme:@"ebeiapp"];
 [NSURLProtocol registerClass:[EBURLProtocol class]];

https remote html, the following method does not execute
+ (BOOL)canInitWithRequest:(NSURLRequest*)theRequest
{
    NSURL* theUrl = [theRequest URL];
    
    if ([[theUrl absoluteString] hasPrefix:@"ebeiapp"]) {
        return YES;
    }
    else {
        if ([[theUrl absoluteString] hasPrefix:@"assets-library://"]) {
            return YES;
        }
        return NO;
    }
}

### Environment, Platform, Device
iOS

### Version information
Cordova:  Cordova Plugins 
Other Frameworks: Xcode

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

Looking forward to your reply

**Comment by jcesarmobile** [comment]
Yeah, WKWebView doesn't allow to intercept http/https requests, it's a know limitation.

**Comment by stupidchou** [comment]
> 是的，WKWebView 不允许拦截 http/https 请求，这是一个已知的限制。

I now need to intercept remote html and inject cordova.js, what should I do?
