### ISSUE TITLE
How to disable 3 fingers undo gesture on iPad OS 15.x and 16?

### ISSUE THREAD

**Issue by QQV5** [apache/cordova-ios#1253]
We have an hybrid app (based on Cordova) and 3 fingers undo gesture is conflicting with app's gesture. How can we disable 3 fingers gesture, via config, CSS or Objective-C or in Settings or other approaches?
![image](https://user-images.githubusercontent.com/113076128/189014764-264f21ef-7cdc-4c0e-9c97-c7d63a7afae0.png)

Thanks in advance!

**Comment by jcesarmobile** [comment]
It's not possible to disable it.
