### ISSUE TITLE
cordova ios sub html page XMLHttpRequest cannot load (json file) due to access control checks

### ISSUE THREAD

**Issue by Jung-Hey** [apache/cordova-ios#1259]
![스크린샷 2022-09-20 오전 9 02 16](https://user-images.githubusercontent.com/74144209/191390123-ada0c177-0444-4bc8-92af-018ae111c09c.png)

I am getting the above error. The same error occurred in the main index.html file, but it was easily solved by downloading the cordova-plugin-wkwebviewxhrfix plugin. The problem was that through the wkwebviewxhrfix plugin, the XMLHttpRequest cannot load error in the main index.html file was solved, but the sub page index.html file did not solve the same error. I need a solution.

![스크린샷 2022-09-19 오후 5 47 14](https://user-images.githubusercontent.com/74144209/191390183-e89cba1a-1374-4b42-b499-f61c116432ec.png)
![스크린샷 2022-09-19 오후 5 47 39](https://user-images.githubusercontent.com/74144209/191390196-13ac5d1e-22c3-4cc6-acdd-ada6e2b60891.png)

(main) index.html path : www/index.html
(sub) index.html path : www/world/wikitude_AR/inedex.html

**Comment by erisu** [comment]
Duplicate #1260
