### ISSUE TITLE
window.webkit.messageHandlers undefined after iframe triggers navigation action

### ISSUE THREAD

**Issue by elisemn** [apache/cordova-ios#1261]
# Bug Report

## Problem

An iframe in our app triggers a navigation action via `window.open` or `window.top.location.href` to a url that is in our allow-intent allow list. The url is correctly opened in the system browser. However after it is opened window.webkit.messageHandlers is undefined which causes runtime errors within the cordova exec.js file when it attempts to use the cordova message handler to post a message.

TypeError
null is not an object (evaluating 'window.webkit.messageHandlers.cordova')

### What is expected to happen?

The URL opened by the iframe should be opened in the system browser without triggering errors within the cordova app.

### What does actually happen?

After the URL is opened window.webkit.messageHandlers undefined errors occur

### Environment, Platform, Device
This issues appears to happen on any iOS mobile device.

### Version information

```
Cordova Packages:

    cli: 11.0.0
        common: 4.0.2
        create: 4.0.0
        lib: 11.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0

Project Installed Platforms:

    ios: 6.2.0
```

## Checklist
- [x] I searched for existing GitHub issues

- https://github.com/apache/cordova-ios/issues/1214 looks potentially related but does not callout the error being triggered by iframe calls to `window.open` or `window.top.location.href`

- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
To clarify: when you say "system browser" you mean opening in Safari (or Chrome, etc.) and leaving the Cordova app, right?

and then `webkit.messageHandlers` is undefined when you return to the Cordova app?

**Comment by dpogue** [comment]
Also, the linked bug has some mention of App-Bound Domains, which aren't something that has been thoroughly tested on the Cordova side. Is your app using App-Bound Domains?

**Comment by elisemn** [comment]
> To clarify: when you say "system browser" you mean opening in Safari (or Chrome, etc.) and leaving the Cordova app, right?
> 
> and then `webkit.messageHandlers` is undefined when you return to the Cordova app?

Correct

> Also, the linked bug has some mention of App-Bound Domains, which aren't something that has been thoroughly tested on the Cordova side. Is your app using App-Bound Domains?

It does look like our app is setting a number of `WKAppBoundDomains` and the iframe url is not one of them. I can investigate updating them.

**Comment by dpogue** [comment]
Having looked into this a bit more, it appears to be the intended behaviour when App-Bound Domains are involved.

From https://webkit.org/blog/10882/app-bound-domains/ (emphasis mine):
> Due to the asynchronous nature of the web, a SocialApp developer could see different errors if trying to use restricted APIs and navigate to non app-bound domains in the same `WKWebView`. If a `WKWebView` in SocialApp uses a restricted API before any navigations occur, and then tries to navigate to a domain outside of the set of “app-bound” domains, the navigation will fail with the error “App-bound domain failure.” **Conversely, if SocialApp first navigates to a non-app-bound domain then tries to use a restricted API, the API call will fail.**

I don't think there's anything Cordova can do here.
