### ISSUE TITLE
Config.xml name with non latin chars make build to fail

### ISSUE THREAD

**Issue by crazyserver** [apache/cordova-ios#1264]
# Bug Report

## Problem

Using non latin chars on config.xml on widget > name: ie Академия каббалы make build to fail.
The project and all folders will be named that way and then xcode returns this error:

** ARCHIVE FAILED **

The following build commands failed:
Ld /Users/travis/Library/Developer/Xcode/DerivedData/Академия_каббалы-hcomrxjqhzhqgbggoehucwvlpvgj/Build/Intermediates.noindex/ArchiveIntermediates/Академия\ каббалы/InstallationBuildProductsLocation/Applications/Академия\ каббалы.app/Академия\ каббалы normal (in target 'Академия каббалы' from project 'Академия каббалы')

(1 failure)

xcodebuild: Command failed with exit code 65

### What is expected to happen?

Build to be successful

### What does actually happen?

Build failed. A workarround is to use Latin chars on the name and specify a new display name, but this will make the android app to use the latin name.

<platform name="ios">    
    <edit-config file="*-Info.plist" mode="merge" target="CFBundleDisplayName">
            <string>NON LATIN here</string>
    </edit-config>
    ...
</platform>

## Information

Use Академия каббалы as name of the project.

### Command or Code

cordova build ios

### Environment, Platform, Device

iOS

### Version information

cordova@11.0
cordova-ios@6.2.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
It appears that Xcode might having issues with non-latin chars for directory paths. Maybe the path is not properly quoted.

But there is solutions for supporting of non-latin chars.

Before installing the platform or rechecking out the platform, add the following to config.xml

```xml
<name short="Академия каббалы">cordovaTestProject</name>
```

The name tag should already exist and should contain latin based chars. What you will be adding is the "short" attribute and this will contain the non-latin chars. This attribute should be used as the application's display name.
