### ISSUE TITLE
Planned Release Date for Cordova iOS 7?

### ISSUE THREAD

**Issue by teranpeterson** [apache/cordova-ios#1265]
Is there a planned release date for cordova-ios version 7? I've scoured the mailing list and I don't see anything. None of the links to the slack channel appear to work or I'd ask there.

**Comment by breautek** [comment]
As far as I know, there is nothing planned for Cordova iOS 7. Our current production I believe works with modern tooling, including with the recent XCode 14 release. So I guess the real question is why are you seeking cordova-ios 7? Is there breaking changes you're waiting for? 

> None of the links to the slack channel appear to work

You can try this link https://join.slack.com/t/cordova/shared_invite/zt-z70vy6tx-7VNulesO0Qz0Od9QV4tc1Q it doesn't expire but it does have a max invite count, so if it doesn't work let me know and I can generate a new link.

**Comment by teranpeterson** [comment]
Oh no nothing in particular. I just expect a Cordova update to each platform around summer time every year. Helps with some internal versioning we do. But nothing I can't work around. 

That slack link worked thanks.
