### ISSUE TITLE
Background push notifications isn't working as expected

### ISSUE THREAD

**Issue by yokeshchronus** [apache/cordova-ios#1270]
# Bug Report
    Whenever I click on push notifications when app is not in background, it is not getting redirected properly. 
## Problem
            Getting an error "Failed to load web page with error , The operation couldn't be completed. NSURLDomain error -999"
### What is expected to happen?
            App is expected to take the corresponding page of push notification but throws this error instead and shows the error page of cordova.
              
## Information
On debugging found out there was some problem in window.location.href = "requiredurltoopen" , this is the line failing and throwing such issues. The same works well in android and older cordova ios version. Would like to know what should we do to avoid such issue?

### Command or Code
   window.location.href = "requiredurltoopen" when app is not in background

### Environment, Platform, Device
  Problem is in all ios phones

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
> Can we prevent that in any way ?

I think we need to determine _why_ the document is being cancelled in the first place before that question can be answered.

**Comment by jcesarmobile** [comment]
cordova-ios has no push notification code and the navigation on push click must be some plugin code or your own code, so closing as not a cordova-ios bug.
