### ISSUE TITLE
convenience init behavior within `CDVPlugin.m` for conformance to Swift init and `let`

### ISSUE THREAD

**Issue by smallscript** [apache/cordova-ios#1288]
# Bug Report
Currently CDVPlugin.m uses a `self = [super init]` pattern within the `initWithWebViewEngine:` convenience initializer.

## Problem
The designated initializer pattern is used in place of a convenience initializer pattern.
🧶👷 `convenience` initializers should invoke required `designated initializers`
           using `self`, as in `self = [self init]` ｢not `self = [super init]`｣.
Specifically, when building a Swift based CDVPlugin subclass its `init` never gets invoked.

Additionally, on iOS, this has a negative impact on plugin design because `pluginInitialize` is
NOT an `init` method and it is only invoked (later) once the plugin has been initialized and registered.

Which leads to ⟨confusion in design patterns⟩ many temporal configuration times within the plugin architecture.
1) CDVPlugin subtype inst `self` being constructed and initialized. ｢designated init｣
    which DOES NOT happen now, but needs to for proper Swift `init` designs.
2) `pluginInitialize` when plugin is registered-as-ready
3) JavaScript **plugins** module/source has been loaded and configured the JS wrapper
4) `deviceReady` when JavaScript layer has been notified that Cordova itself is all configured.

### What is expected to happen?
The Objective-C/Swift `convenience` initializer pattern for `initWithWebViewEngine` invoking
`self = [self init]` ｢not `self = [super init]`｣.

### What does actually happen?
Currently the convenience-init `initWithWebViewEngine` is written as if it were a designated-init calling a convenience-init.

It is using  `self = [super init]`, which results in a Swift subclass never having its `init` member
called and thus it never gets properly initialized if it has an `override init` or any memberwise initializers.
Which, in turn, means it may not compile if it used `let` consts members or it may simply crash due
to being uninitialized.

## Information
explained in other parts of this submission...

### Command or Code
Try the following changes with the swift plugin example below.
`self = [super init]` vs `self = [self init]` within `CDVPlugin.m` method  `initWithWebViewEngine:`.

```swift
class example : CDVPlugin {
  let a: String = "never actually set";
  let b: String; // `let` can only be set in an `init` func
  override init() {self.b = "never actually set either";}
}
```
### Version information
- cordova platform version "ios 6.2.0"
- OSX version "Ventura 13.2.1"

## Checklist
- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by dpogue** [comment]
It seems like maybe the right thing to do is to mark `initWithWebViewEngine` with `NS_DESIGNATED_INITIALIZER` (to make it the designated initializer) and to mark `init` as `NS_UNAVAILABLE` so that it cannot be called directly.

That should allow member initializers in Swift plugins to work, but not allow overriding the `init` method. Plugins should always use `pluginInitialize`.

**Comment by smallscript** [comment]
Much as I would applaud that idea for unified behavior, doing what you suggest does not fix the problem.

A solution requires properly adhering to Objective-C and Swift object construction patterns. Which means that `init` must be invoked on the Swift classes instances; which currently is not happening. The `initWithWebViewEngine:` is a correctly named and factored to be a convenience-init method and is calling the **designated**  `init` it just isn't quite calling it correctly. It needs to call `self init` not `super init`.

That's why I provided the correct change to `self = [self init]` that does it the right way and conforms to the iOS required model.

To unify with `pluginInitialize` pattern would require that the `pluginInitialize` method invocation and signature be refactored to become the `NS_DESIGNATED_INITIALIZER`; which is quite a bit more refactoring than simply changing `super` to `self` in the `initWithWebViewEngine:`.

Whichever refactoring change is made, it still must ensure that `init` is properly invoked on Swift class construction.

Without that fix Swift based plugin classes are **unsafe**, **broken**, lead to very unexpected behavior. Which only someone who understands the internals of Swift and Cordova's plugin model would be able to figure out and once they did so they, in the end, would need to make the same basic ｢`super` changed to `self`｣ patch I tested and subsequently proposed. 🌈

**Comment by dpogue** [comment]
The intention is that `initWithWebViewEngine:` is the only initializer. It's not a convenience initializer, it is the initializer. It is not safe to call `init` because that will leave the WebViewEngine with a null value.

Plugin subclasses should never override `init`. Any work that needs to be done by a plugin on initialization of that plugin must happen in `pluginInitialize` (which is deliberately not an initializer).

**Comment by smallscript** [comment]
Well. Unless Cordova uses  `init` properly, it is a broken model. Try any Swift based CDVPlugin example and you will clearly see that the Swift class is NEVER initialized properly and leaves illegal null pointers instead. Which is 100% broken.

Fundamentally you're asking a plugin designer for Cordova on an iOS platform to subclass from CDVPlugin. The primary language of choice from Apple for iOS is Swift. Right now, the Cordova iOS design of CDVPlugin is violating the Swift `init` model for subclassing. That worked for Objective-C because it operates as effectively unsafe C/C++ and allowed calling an `init` function at any time from any place which safe Swift does not.

The statement that `WebViewEngine` will be left with a null value is 100% wrong. Please review and try the code change I provided and you will see that it DOES NOT leave it null, and it will NOT leave it null. That code is tested and being used in products we have now.

**Comment by oli06** [comment]
I completely agree with @smallscript here. I have just stumbled upon another null pointer error due to the incorrect design of swift plugins. 

Even if it's not planned to change the underlying design, you should consider mentioning this in a fundamental and prominent way.
