### ISSUE TITLE
The screen-orientation plugin does not work properly on iOS16

### ISSUE THREAD

**Issue by gee1k** [apache/cordova-ios#1304]
[cordova-plugin-screen-orientation](https://github.com/apache/cordova-plugin-screen-orientation)

The screen.orientation object is mounted under window to control the rotation of the device. Everything works fine under iOS14, but when I run it under iOS16, I don't get any compilation errors. screen.orientation object is empty, no properties or methods are available

Does anyone know what the problem is?

**Comment by gee1k** [comment]
I don't know if it's a cordova problem or a plugin problem

**Comment by jcesarmobile** [comment]
It’s probably a plugin problem, there are several issues reported in the plugin repository 
https://github.com/apache/cordova-plugin-screen-orientation/issues
