### ISSUE TITLE
Routing error in WKWebView on iOS16 and above when building with Xcode14.3

### ISSUE THREAD

**Issue by tanukki2929** [apache/cordova-ios#1324]
# Bug Report

### What does actually happen?

Routing error on iOS16 and above when building Angular app with Xcode14.3

> ERROR Error: Uncaught (in promise): SecurityError: Blocked attempt to use history.pushState() to change session history URL from file:///Users/appname/Library/Developer/CoreSimulator/Devices/zzzzzzzz-yyyy-dddd-cccccc-bbbbbbbb/data/Containers/Bundle/Application/xxxxxxxx-yyyy-zzzz-wwww-aaaaaaaaaaaaa/APPNAME.app/index.html/ to file:///Users/appname/Library/Developer/CoreSimulator/Devices/zzzzzzzz-yyyy-dddd-cccccc-bbbbbbbb/data/Containers/Bundle/Application/xxxxxxxx-yyyy-zzzz-wwww-aaaaaaaaaaaaa/APPNAME.app/index.html/dashboard. Only differences in query and fragment are allowed for file: URLs.

The same problem reported in the APPLE forum below occurs.
Please let us know if there is any way to solve this problem with Cordova.
https://developer.apple.com/forums/thread/728157

### Version information
Xcode バージョン 14.3 (14E222b)
"cordova-ios": "^6.3.0"

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by msmtamburro** [comment]
> The short answer is that you'll need to use a custom scheme instead of file URLs.

Hi @dpogue.  Is the scheme option currently broken?  I noticed this today: https://github.com/apache/cordova-ios/issues/1223#issuecomment-1608211672

**Comment by jcesarmobile** [comment]
It's not broken, I've just created a new app with cordova-ios 6.3.0 and it's working fine with a custom scheme.

**Comment by jcesarmobile** [comment]
In that case, can you create a new issue and provide a sample app that reproduces that issue?

But for regular use case, it's working fine.

**Comment by AlexBorsody** [comment]
I added this to my config.xml and it fixed the issue for me

**Comment by sathishavunoori** [comment]
Hi, We are also having the same issue with our Cordova iOS app, our app is working on iOS 15 devices but when we run the same app on iOS 16.4 devices, the navigation from www/index.html to www/pages/ui/page1.html using $.mobile.changePage API is not working. Can any one suggest us how to fix this problem in cordova ios app with cordova-ios:6.3.0 or 7.0.0 versions with target SDK 16+

**Comment by breautek** [comment]
The original reporter reported this issue in the context of using the history API with `file://` protocol and answer on that subject is: https://github.com/apache/cordova-ios/issues/1324#issuecomment-1542206012

> Hi, We are also having the same issue with our Cordova iOS app, our app is working on iOS 15 devices but when we run the same app on iOS 16.4 devices, the navigation from www/index.html to www/pages/ui/page1.html using $.mobile.changePage API is not working. Can any one suggest us how to fix this problem in cordova ios app with cordova-ios:6.3.0 or 7.0.0 versions with target SDK 16+

As noted above, if `$.mobile.changePage` is using the history API, then you either need to use schemes (see https://github.com/apache/cordova-ios/issues/1324#issuecomment-1613704842) or you need to use a hash-based routing. Without knowing what `$.mobile.changePage` actually does we can't provide further insights.

Closing as not-a-bug.
