### ISSUE TITLE
Cordova Platform add ios not working

### ISSUE THREAD

**Issue by prateekjsingh** [apache/cordova-ios#1338]
# Bug Report

## Problem
After the recent cordova update to 12.0.0 we are not able to create ios platform.

### What is expected to happen?
Cordova platform add ios should be able to add platforms folder to the hierarchy fetching the plugins from the config.xml.

### What does actually happen?
An error message is raised: Source and destination must not be the same.

## Information
We have updated the fs-extra module to the latest stable version 10.1.0.

### Command or Code
cordova platform add ios

### Environment, Platform, Device

Running on Microsoft Azure
Image : MacOS-12

### Version information

Node version : 18.16.0
NPM version : 9.5.1
Cordova version: 12.0.0 (cordova-lib@12.0.1)

### Logs from the failed step

I have attached the logs from the failed step with this issue
[Corodova platform add ios log.pdf](https://github.com/apache/cordova-ios/files/11667973/Corodova.platform.add.ios.log.pdf)

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by jcesarmobile** [comment]
can you provide a sample app? I can't reproduce, so it's probably some of your plugins causing the issues.
