### ISSUE TITLE
cordova_plugins.js not loading in 6.3.0, leaves app hanging on launch

### ISSUE THREAD

**Issue by pschinis** [apache/cordova-ios#1345]
# Bug Report
App is hanging on launch because cordova.js is trying to load cordova_plugins.js but it's not there.

### What is expected to happen?
Cordova should be putting cordova_plugins.js in the www directory so it's available for cordova.js to load.

### What does actually happen?
Cordova doesn't put cordova_plugins.js in the www directory so cordova.js can't load it and cordova errors out, leaving the app hanging.

## Information
This problem is new to 6.3.0. Versions 6.2.0 and 6.1.1 work as expected.

### Command or Code
Create a cordova app with plugins using cordova-ios 6.3.0. Try to run it and witness "Failed to load resource" error in the console for cordova_plugins.js

### Version information
Cordova 12
Cordova-ios 6.3.0
Mac OS ventura 13.4
iOS 16.5

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

This is the second major issue I've run into with cordova 6.3.0. I know 6.3.0 was created to backport the inspectable webview changes from cordova-ios 7, which is not yet released, to cordova-ios 6. Is it possible that in that process changes meant for version 7 were somehow leaked into version 6.3 in a way that's breaking it?

**Comment by dpogue** [comment]
> This is the second major issue I've run into with cordova 6.3.0. I know 6.3.0 was created to backport the inspectable webview changes from cordova-ios 7, which is not yet released, to cordova-ios 6. Is it possible that in that process changes meant for version 7 were somehow leaked into version 6.3 in a way that's breaking it?

You can see the exact diff between 6.2.0 and 6.3.0 here: https://github.com/apache/cordova-ios/compare/rel/6.2.0...rel/6.3.0
I don't see anything unexpected in there, or that would cause changes to cordova_plugins.js loading.

Are you able to reproduce this with the template Hello Cordova project?

**Comment by pschinis** [comment]
Looks like this and my other issue was specific to my allow-navigation setup (I had some invalid wildcards I guess) causing parseWhitelistUrlForATS to error out and interrupting the platform add. I'll close this and the other one, sorry for wasting your time.
