### ISSUE TITLE
iframe not send referrer header

### ISSUE THREAD

**Issue by SvyatoslavPozhydaev** [apache/cordova-ios#1350]
# Bug Report

## Problem
in `config.xml` I set hostname, hostname is origin for app, but iframe not send referrer.
I also tried different values of the referrerpolicy attribute of iframe.

### What is expected to happen?
iframe send http header "Referrer"

### What does actually happen?
iframe not send referrer.

### Version information
cordova: 11.0.0
cordova-ios: 6.3.0

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
This behaviour comes from Apple's WebKit library, not from Cordova, so there's probably nothing we can do to change it.
You can file bugs against WebKit at https://bugs.webkit.org and using Apple's Feedback Assistant.

You can also try setting a `referrerpolicy` on the iframe and see if that helps: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#integration_with_html
