### ISSUE TITLE
Loading HTML from the data directory with WKWebView results in an error

### ISSUE THREAD

**Issue by wulianpu** [apache/cordova-ios#1375]
Loading HTML from the data directory (cordova.file.cacheDirectory) with WKWebView results in an error. The error message is as follows: `WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox`

Issue details can be found in the discussion: #1011 

Does anyone know how to resolve this issue?

**Comment by breautek** [comment]
Closing as duplicate
