### ISSUE TITLE
Undefined symbols on Xcode

### ISSUE THREAD

**Issue by konguele** [apache/cordova-ios#1388]
Good Morning,

I created my game in Gdevelop and when I use Cordova and CocoaPods, I get the following error on Xcode. It has the necessary frameworks (at least it has downloaded them correctly) and I see that they are arm64. Could you help me? I attach some sample games, probably they have other errors because I have only put a part of the game, where you can reproduce the error that I indicate.

Gdevelop version: 5.2.176
Cordova Version: 12.0.0 (Cordova-lib@12.0.1)
Cocoapods version: 1.14.3

Thank you very much!

ld: Undefined symbols:
_GULIsLoggableLevel, referenced from:
-[APMMonitor isLoggableLevel:] in GoogleAppMeasurement[arm64][66](https://github.com/apache/cordova/issues/APMMonitor.o)
_GULLogBasic, referenced from:
-[APMASLLogger logMessage:logTag:messageCode:withLogLevel:] in GoogleAppMeasurement[arm64][11](https://github.com/apache/cordova/issues/APMASLLogger.o)
_GULLogError, referenced from:
-[APMPersistentDictionary initWithFileName:] in GoogleAppMeasurement[arm64][223](https://github.com/apache/cordova/issues/APMPersistentDictionary.o)
_APMWriteDictionaryToURL in GoogleAppMeasurement[arm64][223](https://github.com/apache/cordova/issues/APMPersistentDictionary.o)
-[APMUserDefaults synchronize] in GoogleAppMeasurement[arm64][274](https://github.com/apache/cordova/issues/APMUserDefaults.o)
_GULLogInfo, referenced from:
___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement[arm64][291](https://github.com/apache/cordova/issues/UIViewController+APMScreenClassName.o)
_GULLogWarning, referenced from:
+[APMMeasurement sharedInstance] in GoogleAppMeasurement[arm64][61](https://github.com/apache/cordova/issues/APMMeasurement.o)
-[APMPersistentDictionary objectForKey:] in GoogleAppMeasurement[arm64][223](https://github.com/apache/cordova/issues/APMPersistentDictionary.o)
-[APMPersistentDictionary setObject:forKey:] in GoogleAppMeasurement[arm64][223](https://github.com/apache/cordova/issues/APMPersistentDictionary.o)
-[APMUserDefaults objectForKey:] in GoogleAppMeasurement[arm64][274](https://github.com/apache/cordova/issues/APMUserDefaults.o)
-[APMUserDefaults setObject:forKey:] in GoogleAppMeasurement[arm64][274](https://github.com/apache/cordova/issues/APMUserDefaults.o)
-[APMUserDefaults synchronize] in GoogleAppMeasurement[arm64][274](https://github.com/apache/cordova/issues/APMUserDefaults.o)
___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement[arm64][291](https://github.com/apache/cordova/issues/UIViewController+APMScreenClassName.o)
...

[https://www.dropbox.com/scl/fi/hop9d6c3c64kibeckw6b3/Samples.zip?rlkey=ghdtyo7a4kfpcrjs6lk4rwtzo&dl=0](url)

**Comment by konguele** [comment]
@jcesarmobile I have create here the issue with the sample projects.

**Comment by jcesarmobile** [comment]
please, don't ping me, I check issues whenever I can, not by request.

The upload project is "corrupted", cordova-ios is not installed and the `platforms/ios` folder doesn't look like it should, which prevents cordova comments from working.

**Comment by jcesarmobile** [comment]
closing since the provided project is not valid
looks like a bug on Gdevelop
