### ISSUE TITLE
Cordova iOS How to inject local cordova.js to remote H5 calls.

### ISSUE THREAD

**Issue by stupidchou** [apache/cordova-ios#1396]
What if a remote h5 wants to reference my local cordova.js to get my locally injected js event?

**Comment by breautek** [comment]
Accessing or using native platform APIs from remote code breaks [Section 4.7.2](https://developer.apple.com/app-store/review/guidelines/#third-party-software) of Apple's App Store policy which reads:

> 4.7.2 Your app may not extend or expose native platform APIs to the software without prior permission from Apple.

Therefore supporting, or recommending the use of the `cordova.js` file remotely is not something that Apache can advise.

If you need to use native platform APIs, then the executable code must be bundled with your app.
