### ISSUE TITLE
The startURLSchemeTask method in CDVURLSchemeHandler was not executed

### ISSUE THREAD

**Issue by GymotgM** [apache/cordova-ios#1421]
Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

Start the app, enter CDVWebViewEngine, execute loadRequest, but do not proceed to CDVURLSchemeHandler to execute the startURLSchemeTask method. What should be done next

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at https://s.apache.org/cordova-slack)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by GymotgM** [comment]
I have reviewed Cordova plugin webview proxy
Operated in startURLSchemeTask, but the startURLSchemeTask method has not been executed yet
The loadRequest and decisionPolicyForNavigationAction in CDVWebViewEngine are both executed

**Comment by jcesarmobile** [comment]
please, don't use github issues to ask questions, you can use github discussions 
https://github.com/apache/cordova/discussions
