### ISSUE TITLE
Cordova ios 7.1.0 - Build failed with "Command failed with exit code 65"

### ISSUE THREAD

**Issue by FranGhe** [apache/cordova-ios#1431]
I updated my cordova-ios to 7.1.0 and start to build:

**After many warnings like these:**
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'Firebase' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'FirebaseCore' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'nanopb' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'FirebaseMessaging' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'GoogleDataTransport' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'PromisesObjC' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'FirebaseCoreInternal' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'CordovaLib' from project 'CordovaLib')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'FirebaseInstallations' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'GoogleUtilities' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'Firebase' from project 'Pods')
 failed after many warings like this

**The build failed as:**
Command failed with exit code 65: xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -configuration Debug -sdk iphonesimulator -destination platform=iOS Simulator,name=iPhone 15 Pro Max build SYMROOT=.../myApp/platforms/ios/build

Some suggestion?

**Comment by breautek** [comment]
There's likely an actual error (not a warning) somewhere in the xcode build output. Error code 65 is a general purpose error code that something in the build didn't work. It could mean pretty much anything.

> warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'GoogleUtilities' from project 'Pods')

These warnings will not produce a build failure by themselves. Sometimes xcode build errors are buried in the build output, so you may have to "scroll up" a ways before you see something of interest.

**Comment by FranGhe** [comment]
Problem found...as you suggested, I "scrolled up" and found it as "error:"

I thought the build would stop where the error is... but no... it continues and then stops.

The problem was in one setting in config.xml

Thanks again... you can close it

**Comment by breautek** [comment]
> I thought the build would stop where the error is... but no... it continues and then stops.

Yup... you would think, but objective-c, and really using any C / C++ compiler can do the same thing. They can print 1000 of errors and they are all usually a side-effect of the first error.

I'll close this issue since it looks like you solved your own issue but perhaps if you could explain what you had wrong and what you did to correct it, might help others who stumble on this ticket.

**Comment by FranGhe** [comment]
It is a wrong instructions on config.xml to assign an image in resource and this is in conflict with a plugin...
"error: Multiple commands produce..." I still have to fix it :(
