### ISSUE TITLE
Several version checks fail after cordova-ios platform add ios@7.1.0

### ISSUE THREAD

**Issue by anh1979** [apache/cordova-ios#1432]
# Bug Report

## Problem
A "platform add" and installing the plugins used gives warning, later usage of the version numbers might fail.

### What is expected to happen?
A "platform add" and installing the plugins used should give no warning

### What does actually happen?
cordova-ios platform add@7.1.0 is done, the plugins are then installed. 
The version-checks are performed and fail with
"apple-ios version check failed (/Users/uname/Jenkins/workspace/jobname/app/platforms/ios/cordova/apple_ios_version), continuing anyways."
or
"apple-xcode version check failed (/Users/uname/Jenkins/workspace/jobname/app/platforms/ios/cordova/apple_xcode_version), continuing anyways."

When I look into the scripts mentioned above it is referencing "lib/versions.js", **but there is no such a file**.
I got it from GitHub cordova-ios@6.2.0, added it to the lib directory manually and executed the above mentioned scripts without a problem.
But to be usable within the "platform add", it should be included, I guess.

### Command or Code

cordova-ios platform add@7.1.0

### Environment, Platform, Device

On my local Mac computer as well as on our Jenkins Mac buildslave, same project.

### Version information

Plugins used:
12:16:17 Installing "cordova-plugin-ionic-webview" for ios
12:16:17 apple-ios version check failed (/Users/uname/Jenkins/workspace/jobname/app/platforms/ios/cordova/apple_ios_version), continuing anyways.
12:16:17 Installing "cordova-plugin-network-information" for ios
12:16:17 Installing "cordova-plugin-screen-orientation" for ios
12:16:17 Installing "cordova-plugin-uniquedeviceid" for ios
12:16:17 Installing "onesignal-cordova-plugin" for ios
12:16:17 apple-xcode version check failed (/Users/uname/Jenkins/workspace/jobname/app/platforms/ios/cordova/apple_xcode_version), continuing anyways.
12:16:17 apple-ios version check failed (/Users/uname/Jenkins/workspace/jobname/app/platforms/ios/cordova/apple_ios_version), continuing anyways.

Ionic:

   Ionic CLI                     : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.3.9
   @angular-devkit/build-angular : 14.2.10
   @angular-devkit/schematics    : 14.2.3
   @angular/cli                  : 14.2.3
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : ios 7.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 21 other plugins)

Utility:

   cordova-res : 0.15.4 
   native-run  : not installed

System:

   ios-deploy : 1.12.2
   ios-sim    : 8.0.2
   NodeJS     : v16.20.2 (/usr/local/Cellar/node@16/16.20.2_1/bin/node)
   npm        : 8.19.4
   OS         : macOS Unknown
   Xcode      : Xcode 15.2 Build version 15C500b

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
I think this broke in 7.0.0 (but remains broken in 7.1.0).

We've got an existing ticket for it at #1415 and it should be an easy fix.

**Comment by anh1979** [comment]
Thank you, I will close the issue then.
