### ISSUE TITLE
`deviceReady` event not fire 

### ISSUE THREAD

**Issue by 192kobayashi** [apache/cordova-ios#1447]
##   problem 

After launching my app, the `deviceReady` event does not fire and the splash screen remains displayed.

## What is expected to happen?

After the splash screen you should see the home screen.

## What does actually happen?

It was working fine with cordova-ios@6.3.0 until now. In order to check the operation before updating to cordova-ios@7.1.0, I updated the Mac version, updated Xcode to 15.4, and built it, and this issue started occurring.

The iOS versions confirmed were 17.5.1 and 14.8.

The issue did not change with either iOS version.

When checking the device log in 17.5.1, multiple errors like the one below were found, and the `deviceReady` event was not fired.

```
Invalidating grant <invalid NS/CF object> failed
```

When checking the log in developer mode with Safari in 14.8, the following was displayed, and the `deviceReady` event was also not fired.

```
Error] Failed to load resource: The requested URL was not found on this server. (cordova_plugins.js, line 0)
```

To check, I tried building with cordova-ios@6.3.0 (the version that had been working fine until now), but the same issue occurred.

To check if the problem was caused by my app, I also checked the official sample code (`npx cordova create hello com.example.hello HelloWorld`), but the same issue occurred.

I'm having a hard time figuring out what the cause is.
I would be grateful if you could let me know if you have any hypotheses as to what the cause might be.

## information

- macOS  Sonoma  14.5
- Xcode 15.4 (15F31d)
- cocoaPods 1.15.2
- node.js 16.20.2
- ios-deploy 1.12.2
- cordova cli: 12.0.0
- cordova-ios 7.1.0 & 6.3.0
- iOS  17.5.1 &  14.8

**Comment by 192kobayashi** [comment]
sorry  

It seems there was an error in the build method.

Since it has been resolved, I will close it.

**Comment by SanamdeepSingh-826** [comment]
hey @192kobayashi , can u please let me know, how you fixed it as i am also having same issue (stucked at splash screen)
