### ISSUE TITLE
app gets stuck on the splash screen on its first run but works fine on subsequent runs 

### ISSUE THREAD

**Issue by jurahalas** [apache/cordova-ios#1453]
with this pugin "cordova-plugin-wkwebview-file-xhr": "3.1.1", If it's the first app install, it gets stuck on the splash screen, and
document.addEventListener('deviceready', startApp, false); is not triggered. If rerun the app it works fine.

```
"dependencies": {
		"cordova": "12.0.0",
		"cordova-ios": "7.1.1"
	},
	"devDependencies": {
		"cordova-plugin-wkwebview-file-xhr": "3.1.1"
	},
	"cordova": {
		"plugins": {
			"cordova-plugin-wkwebview-file-xhr": {}
		},
		"platforms": [
			"ios"
		]
	}
```

**Comment by dpogue** [comment]
If the issue is caused by the cordova-plugin-wkwebview-file-xhr plugin, please report the issue on the plugin's issue tracker.
