### ISSUE TITLE
Signing for "MyProject" requires a development team. Select a development team in the Signing & Capabilities editor. 

### ISSUE THREAD

**Issue by geoidesic** [apache/cordova-ios#1461]
# Bug Report

## Problem
Unless I edit this manually via Xcode, I can't deploy the iOS app

### What is expected to happen?
The cordova process shouldn't require manual editing of a project it created in order to run or build the project it created.

### What does actually happen?
```
** ARCHIVE FAILED **

Command failed with exit code 65: xcodebuild -workspace MyProject.xcworkspace -scheme MyProject -configuration Debug -destination generic/platform=iOS -archivePath MyProject.xcarchive archive
```

### Command or Code

`cordova platform add ios; cordova run iOS;`

### Environment, Platform, Device

Any emulator or device

### Version information

cordova --version
12.0.0 (cordova-lib@12.0.1)
```
 "cordova": {
        "platforms": [
            "browser",
            "android",
            "ios"
        ],
        "plugins": {
            "cordova-plugin-wkwebview-file-xhr": {},
            "cordova-plugin-badge": {},
            "cordova-plugin-camera": {},
            "cordova-plugin-deeplinks": {},
            "cordova-plugin-device": {},
            "cordova-plugin-dialogs": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-keyboard": {},
            "cordova-plugin-statusbar": {},
            "@havesource/cordova-plugin-push": {
                "IOS_FIREBASE_MESSAGING_VERSION": "~> 8.1.1"
            },
            "cordova-plugin-androidx-adapter": {}
        }
    },
    "devDependencies": {
        "cordova-android": "^13.0.0",
        "cordova-icon": "^1.0.0",
        "cordova-plugin-androidx-adapter": "^1.1.3"
    },
    "dependencies": {
        "cordova-ios": "^7.1.1"
    }
    ```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Have you seen https://cordova.apache.org/docs/en/12.x/guide/platforms/ios/index.html#signing-an-app?

You should be able to have a gitignored [build.json](https://cordova.apache.org/docs/en/12.x/guide/platforms/ios/index.html#using-buildjson) file which contains your signing information.
