### ISSUE TITLE
After upgrading to 7.0.0, the contents of config.xml cannot be read

### ISSUE THREAD

**Issue by abcss133** [apache/cordova-ios#1468]
# Bug Report

## Problem
I upgraded my project from cordova-ios@6.3.0 to @7.0.0 and built the project
However, when I run it on an iOS device, the contents of config.xml can no longer be read.
The following is set in config.xml.

```xml
<platform name="ios">
<!-- Set Swift version to 5 -->
<preference name="UseSwiftLanguageVersion" value="5" />
</platform>
```

When I check Build Settings>User-Defined>SWIFT_VERSION in Xcode, the value is not set to 5
and the contents of config.xml are not reflected.
The contents of config.xml were reflected in cordova-ios@6.3.0.
### What is expected to happen?
@7.0.0 should reflect the contents of config.xml as before.

### What does actually happen?
The contents of config.xml are not reflected.

### Environment, Platform, Device

cordova-ios  7.0.0
Mac OS, Ventura
Emulator of iOS 16.1.1

### Version information

cordova-ios  7.0.0
Mac OS Ventura, Xcode 15.0.1
Node.js 20.15.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
I don't think `UseSwiftLanguageVersion` is a supported preference in cordova-ios. Maybe a plugin or a hook was handling it?

The proper preference name to configure the Swift version is just `SwiftVersion`

**Comment by abcss133** [comment]
Mr.dpogue
Thank you for your reply.
I changed the setting name from UseSwiftLanguageVersion to SwiftVersion and the setting was reflected.

By the way, I set the following when setting the background mode,
but when I upgraded to @7.0.0 and built it, the setting was not reflected.

<platform name="ios">
<custom-config-file parent="UIBackgroundModes" platform="ios" target="*-Info.plist">
            <array>
                <string>bluetooth-central</string>
                <string>bluetooth-peripheral</string>
            </array>
        </custom-config-file>
</platform>

Is the setting name wrong here too?

**Comment by dpogue** [comment]
`custom-config-file` has never been supported, but Cordova does support a `config-file` option. I recommend reading the [`config.xml` documentation](https://cordova.apache.org/docs/en/12.x/config_ref/index.html) and making sure you're using the right elements and attribute values.

**Comment by abcss133** [comment]
Thank you for your reply.
We will check that you are using the correct elements and attribute values.
