### ISSUE TITLE
Double dash prevents forwarding platform-specific options

### ISSUE THREAD

**Issue by luxaritas** [apache/cordova-ios#1488]
# Bug Report

### What is expected to happen?

`npx cordova build ios --release --device -- --automaticProvisioning` would pass `-allowProvisioningUpdates` to `xcodebuild`

### What does actually happen?

`xcodebuild` is not passed `-allowProvisioningUpdates`

## Information

Both the [cordova-cli docs](https://cordova.apache.org/docs/en/12.x/reference/cordova-cli/index.html#cordova-build-command) and [cordova-ios docs](https://cordova.apache.org/docs/en/12.x/guide/platforms/ios/index.html#using-flags) specify you need to add an extra `--` in order to provide platform-specific options. This is indeed the case for `cordova-android`. However for `cordova-ios`, adding the extra double dash appears to prevent the extra arguments from being processed.

It's possible that because I use `npx` something weird is happening here, but as far as I can tell, the behavior is inconsistent with `cordova-android`, so that shouldn't be the issue.

### Command or Code

`cordova build`

### Environment, Platform, Device
N/A

### Version information

Node 20, cordova 12.0.0, cordova-ios 7.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
I've confirmed this, and confirmed that cordova-ios never actually handles the `options.argv` that are forwarded from the CLI.
