### ISSUE TITLE
App Stuck on Splash Screen in Xcode 16 only

### ISSUE THREAD

**Issue by moh1122** [apache/cordova-ios#1500]
# Bug Report

### What is expected to happen?
The app should launch normally as my build is succeeding. Its now freezing on launch screen without any errors in log. I faced this issue after updating xcode to v 16

### What does actually happen?
Its now freezing on launch screen without any errors in log. I faced this issue after updating xcode to v 16

### Command or Code

just running the app on a simulator its freezing on launch screen

### Environment, Platform, Device

iOS im using Xcode 16

### Version information

12.0.0 (cordova-lib@12.0.1)

xcode 16

## Checklist

- [ X] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by bitrxjs** [comment]
Check if you are using splash screen plugin, in newer its not required.
trying running navigator.splashscreen.hide() from console

**Comment by breautek** [comment]
Closing as stale.
