### ISSUE TITLE
ShowSplashScreenSpinner doesn't show spinner on iOS

### ISSUE THREAD

**Issue by giuseppelanzi** [apache/cordova-ios#1503]
# Bug Report

## Problem
Cordova@12 with cordova-ios@7.1.0.
Setting ShowSplashScreenSpinner to true in the config.xml preference tag doesn't give the attended result.

### What is expected to happen?
While showing a splashscreen the app should show a spinner too.

### What does actually happen?
The splash is shown, while the spinner is not.

## Information
Tested using this config.xml portion.
```
<platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <splash src="resources/ios/splash/Default@2x~iphone~anyany.png"/>
        <splash src="resources/ios/splash/Default@2x~iphone~comany.png"/>
        <splash src="resources/ios/splash/Default@2x~iphone~comcom.png"/>
        <splash src="resources/ios/splash/Default@3x~iphone~anyany.png"/>
        <splash src="resources/ios/splash/Default@3x~iphone~anycom.png"/>
        <splash src="resources/ios/splash/Default@3x~iphone~comany.png"/>
        <splash src="resources/ios/splash/Default@2x~ipad~anyany.png"/>
        <splash src="resources/ios/splash/Default@2x~ipad~comany.png"/>
    </platform>
    <preference name="AutoHideSplashScreen" value="false"/>
    <preference name="ShowSplashScreenSpinner" value="true"/>
```

### Command or Code
Create a new project, use the portion of configuration above and compile on iOS.

### Environment, Platform, Device
Tested with iPad with iOS 18.0.1.

### Version information
cordova@12
cordova-ios@7.1.0
iPad - iOS 18.0.1
XCode 16

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
The `ShowSplashScreenSpinner` preference isn't supported on iOS anymore after the move to Storyboard-based splashscreens. (It also, for what it's worth, doesn't appear to be supported on Android anymore with the newer splashscreens there.)

**Comment by breautek** [comment]
> The `ShowSplashScreenSpinner` preference isn't supported on iOS anymore after the move to Storyboard-based splashscreens. (It also, for what it's worth, doesn't appear to be supported on Android anymore with the newer splashscreens there.)

I'm gunna create an issue for the docs if that's the case because it's documented as supported [here](https://cordova.apache.org/docs/en/12.x/core/features/splashscreen/index.html#showsplashscreenspinner) which is the newer doc page for the core splashscreen implementations.

**Comment by giuseppelanzi** [comment]
Thanks everybody. Got it :)
