### ISSUE TITLE
Remove platform with 8.0.0 Beta1 fails

### ISSUE THREAD

**Issue by GitToTheHub** [apache/cordova-ios#1507]
# Bug Report

### What is expected to happen?
When I execute `cordova platform remove ios` after the beta was added by `cordova platform add ios@8.0.0-beta.1`, it should be removed normally

### What does actually happen?
I get an error:
```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ENOTEMPTY')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at /Users/[username]/.nvm/versions/node/v22.9.0/lib/node_modules/cordova/bin/cordova:32:22
```

## Information
When I do `cordova platform remove ios`for the second time, it works.

### Command or Code
```bash
cordova platform remove ios
cordova platform add ios@8.0.0-beta.1
cordova platform remove ios
```

### Environment, Platform, Device
OS: macOS 15.1.1

### Version information

Cordova: 12.0.2

## Checklist

- [ ] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by erisu** [comment]
I was unable to reproduce this issue, but I do not believe it is related to `cordova-ios`.
I believe it was a `cordova-cli` issue and has been resolved, though a new release has not yet been created.

Fix PR: https://github.com/apache/cordova-cli/pull/640

**Comment by GitToTheHub** [comment]
Ok thanks, maybe it has something to do with my plugins. But it's only happening on the beta version, on the iOS version 7.1.1 it's not happening.

**Comment by dpogue** [comment]
Can you try doing the same thing with `cordova@nightly` and see if it gives a more actionable error message?

Or, since it seems to be an `ENOTEMPTY` error, check what is left in the platforms/ios folder after trying to remove it?

**Comment by GitToTheHub** [comment]
I will test this tomorrow 🙂
________________________________
Von: エリス ***@***.***>
Gesendet: Thursday, November 21, 2024 7:06:21 PM
An: apache/cordova-ios ***@***.***>
Cc: Manuel Beck ***@***.***>; Author ***@***.***>
Betreff: Re: [apache/cordova-ios] Remove platform with 8.0.0 Beta1 fails (Issue #1507)


Could you try using ***@***.***?

npx ***@***.*** platform rm ios

If the issue persists, it should remove the generic error and instead provide the root cause.

Alternatively, if you could provide a reproduction repository, we could clone it and test against it, as I was unable to reproduce the issue in my test project.

**Comment by GitToTheHub** [comment]
Hi,

I coud successfully remove `8.0.0 Beta1`with `npx cordova@nightly platform rm iOS`

Thanks

**Comment by GitToTheHub** [comment]
Interestingly the normal `cordova platform remove ios` will now also work without an error
