### ISSUE TITLE
CocoaPods Improvement

### ISSUE THREAD

**Issue by knight9999** [apache/cordova-ios#391]
# Overview:
The purpose of this ticket is to improve Cocoapod support by:

* Deprecate the framework usage of `type="podspec"`

The current `framework` tag `type="podspec"` provided basic CocoaPods support in the beginning. Continuing to support this method but expand on the tag to support more features will become messy. Additionally, some configurations are not at an individual pod level.

In this case, the best option is to deprecate this method and implement a new method for handling CocoaPods.

* Improve readability

The new method/structure in `plugin.xml` will improve the readability. 

* Add missing default configurations

The new method/structure in `plugin.xml` will also provide the ability to give users flexibility with global pod configuration and down to the individual pods.

# Goals
* Allow users to configure the pod environment: For example use_framework!
  * https://issues.apache.org/jira/browse/CB-11893
* Provide support of private pod repositories
  * https://issues.apache.org/jira/browse/CB-12216

# Requirement Proposal
* https://github.com/apache/cordova-discuss/pull/108

**Comment by erisu** [comment]
### Pull Requests
- https://github.com/apache/cordova-common/pull/48
- https://github.com/apache/cordova-ios/pull/405

**Comment by erisu** [comment]
Closing out the ticket as all related PRs had been merged. This should be made available when Cordova 9 has been released.
