### ISSUE TITLE
Do not expand punctuation when entering on IOS

### ISSUE THREAD

**Issue by imgoddqp** [apache/cordova-ios#399]
![image](https://user-images.githubusercontent.com/24971545/44941444-2c219000-add0-11e8-96ab-66e28abdafc6.png)

but in safari  or other app, it look like this ,when click the button,punctuation will expand 

![image](https://user-images.githubusercontent.com/24971545/44941452-61c67900-add0-11e8-9002-5699c3a57c8c.png)

![image](https://user-images.githubusercontent.com/24971545/44941493-15c80400-add1-11e8-8f07-7ec4427886bc.png)

How can I make it？thank you

**Comment by jcesarmobile** [comment]
What keyboard are you using?

**Comment by imgoddqp** [comment]
thanks for reply。I use system-provided 【Chinese Simplified】

**Comment by imgoddqp** [comment]
> What keyboard are you using?

thanks for reply。I use system-provided 【Chinese Simplified】

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
