### ISSUE TITLE
Why is config.xml not being merged?

### ISSUE THREAD

**Issue by lyh2668** [apache/cordova-ios#400]
I wrote an ios plugin and add `<feature name="PluginName">
        <param name="ios-package" value="PluginName" />
    </feature>` to the root config.xml, then I execute `cordova build`, but I found that my custom plugin didn't take effect.then I wrote config to `staging/config.xml`, it look effect. but when I execute `cordova build` again, then `staging/config.xml` will be covered. so I thought there is a problem with the file coverage mechanism.
![image](https://user-images.githubusercontent.com/8433634/45006161-19a29300-b02a-11e8-931e-c46892f725d2.png)

**Comment by jcesarmobile** [comment]
In your plugin.xml you have to add this to make the plugin install add the feature tags to the staging config.xml

```
<platform name="ios">
    <config-file target="config.xml" parent="/*">
        <feature name="PluginName">
            <param name="ios-package" value="PluginName" />
        </feature>
    </config-file>
</platform>
```

never edit the staging config.xml manually.

**Comment by lyh2668** [comment]
@jcesarmobile  I don't have a file which the name of plugin.xml, so where can i use the plugin.xml?Just create this file in the Plugins dir ?
