### ISSUE TITLE
<config-file> isn't reflected in generated Info.plist

### ISSUE THREAD

**Issue by stupidawesome** [apache/cordova-ios#401]
Affected version: 4.5.5
Workaround: Downgrade to 4.5.4

The following extract from `config.xml` is no longer working in `cordova-ios@4.5.5`:
```xml
<platform name="ios">
  <config-file parent="NSMicrophoneUsageDescription" target="*-Info.plist">
    <string>We use the microphone to convert speech to text when composing messages.</string>
  </config-file>
  <config-file parent="NSSpeechRecognitionUsageDescription" target="*-Info.plist">
    <string>We use speech recognition to convert speech to text when composing messages.</string>
  </config-file>
</platform>
```

Expecting values in the generated `Info.plist`:
```xml
<key>NSMicrophoneUsageDescription</key>
<string>We use the microphone to convert speech to text when composing messages.</string>
<key>NSSpeechRecognitionUsageDescription</key>
<string>We use speech recognition to convert speech to text when composing messages.</string>
```

Actual result:
```xml
<key>NSMicrophoneUsageDescription</key>
<string>Request to use Speech Recognition</string>
<key>NSSpeechRecognitionUsageDescription</key>
<string>Request to use Microphone</string>
```

The scenario above works as expected in `cordova-ios@4.5.4`.

**Comment by oliversalzburg** [comment]
Just FYI, I think you'd want [`edit-config`](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config) instead. Like so:

```xml
<edit-config file="*-Info.plist" mode="overwrite" target="NSMicrophoneUsageDescription">
	<string>We use the microphone to convert speech to text when composing messages.</string>
</edit-config>
```

**Comment by lasselaakkonen** [comment]
I'm facing similar issues when trying to update an ancient cordova version to latest cordova 8.1.2 and cordova-ios 4.5.5.

Didn't try to downgrade cordova-ios, instead moved back to using  https://github.com/dpa99c/cordova-custom-config

**Comment by helzgate** [comment]
I had a space in my project name so I had to change it from `*-Info.plist` to the actual name of my `*.plist` file
