### ISSUE TITLE
Missing release info about v4.5.5 in RELEASENOTES.md

### ISSUE THREAD

**Issue by piotr-cz** [apache/cordova-ios#411]
As in title

**Comment by robjs827** [comment]
Absolutely!
It has been nearly over 2 months since v4.5.5 had got released, but there's no record of it in the RELEASENOTES.md.

https://cordova.apache.org/announcements/2018/07/26/cordova-ios-4.5.5.html

**Comment by janpio** [comment]
These exist in the release branch:
https://github.com/apache/cordova-ios/blob/4.5.5/RELEASENOTES.md#455-jul-23-2018

Should this be merged to `master` @brodybits?

**Comment by piotr-cz** [comment]
Default branch showing up on github is _master_.
However I can't see the _release_ branch?

**Comment by janpio** [comment]
Release branches are created for releases, this one called `4.5.x`: https://github.com/apache/cordova-ios/blob/4.5.x/RELEASENOTES.md I linked directly to the tag `4.5.5` above: https://github.com/apache/cordova-ios/blob/4.5.5/RELEASENOTES.md#455-jul-23-2018 (which of course exists on that release branch).

**Comment by piotr-cz** [comment]
Thank you.

**Comment by erisu** [comment]
Version 4.5.5 release notes is now in master.
https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md#455-jul-23-2018
