### ISSUE TITLE
cordova-ios and serviceworker

### ISSUE THREAD

**Issue by zeoc** [apache/cordova-ios#414]
Hi,

is there a way to implement a service worker in a cordova ios app ? 
symptom : navigator.serviceWorker do no exists at runtime.

My understanding is that the serviceworker is not available to webapp because of launching files under file:// protocol and webkitview do not allow serviceworker except under https protocol...

My app works fine outside of cordova on Ios device (wep shortcut) but a native webapp is my goal...

Is there a workaround ?

thanks

PS: I'm testing under ios 12 and Xcode 10

**Comment by zeoc** [comment]
Thanks for the answer, is there some plan to add S.W. in WKwebview ? Do you think it's possible to develop a plugin for that ? 3 years ago there was one but do not work with actual cordova...
Service Worker in Cordova would be one of the easiest way to implement PWA and offline app's ...

**Comment by Polm90** [comment]
Are there any news about this topic?
The old plugin is not working; service worker is an important feature!

Thank you

**Comment by dpogue** [comment]
The webview on iOS still does not support ServiceWorker.

**Comment by Polm90** [comment]
Ok but the old phonegap plugin worked once (not anymore but maybe it's enough to update it).
Moreover there are some libraries who use workers and they work on cordova (for example tesseract.js). So I think that it is possibile to develop something to let workers work again
