### ISSUE TITLE
Support serving local content with WKURLSchemeHandler

### ISSUE THREAD

**Issue by AshleyScirra** [apache/cordova-ios#415]
Ref: https://bugs.webkit.org/show_bug.cgi?id=154916#c17

Cordova apps tend to serve local content. On iOS with WKWebView, this causes severe issues with many features, such as the complete inability to XMLHttpRequest or fetch local files due to strict security restrictions. Apps can resort to `cordova-plugin-file`, but this forces them to write different code to handle iOS, defeating the purpose of Cordova to allow the same code to run everywhere.

According to an Apple engineer, apps ought to be using WKURLSchemeHandler instead: https://developer.apple.com/documentation/webkit/wkurlschemehandler

Please consider officially supporting this in Cordova on iOS.

**Comment by dpogue** [comment]
One challenge is that WKURLSchemeHandler is only available on iOS 11 and up, and Cordova currently supports as far back as iOS 9.

**Comment by AshleyScirra** [comment]
That is indeed an annoying compatibility quirk, but [Apple's data](https://developer.apple.com/support/app-store/) shows that 85% of devices are already on iOS 11+. So I think for some apps it will be acceptable to only support iOS 11+ with WKURLSchemeHandler.

**Comment by janpio** [comment]
We are aware of that, @dpogue just stated one of the challenges an implementation of this will have.

Do you have further input how exactly such an implementation could look like for `cordova-ios` (or `cordova-plugin-wkwebview-engine`, this is only relevant there, correct?)?

**Comment by guirip** [comment]
Currently at Mobile-Spot we plan on using :
 - UI webview for iOS 11 and below
 - WK webview + custom url scheme for iOS12 and above

Today we are able to build an app for iOS 10 that uses WK webview, and this app handles the custom url scheme only if it is available in the API of the running device:

```
- (void)webView:(WKWebView *)webView startURLSchemeTask:(id <WKURLSchemeTask>)task
API_AVAILABLE(ios(11.0)){
    ...
```

The downside is that we have to manually edit `CDVWKWebViewEngine.h` and `CDVWKWebViewEngine.m`.

We also have to include UI webview / WK webview switch on startup which seems more difficult.

**Comment by jcesarmobile** [comment]
iOS 9 is going away in next major release.
We officially only support current an previous iOS versions, so we could drop iOS 10 if we wanted to, but that will definitely piss users off.
As far as I remember, the only time we dropped support so soon was on cordova-ios 4.4.0 where we dropped support for iOS 8 by the end of 2016. (but was not really released until April 2017)

**Comment by sartrey** [comment]
WKURLSchemeHandler raised a lot of crash in our apps ( not cordova ).
And HTTPS main document can not load custom scheme resources.
Any idea to solve this two problems?
