### ISSUE TITLE
App crashes on iOS 12.0

### ISSUE THREAD

**Issue by anupamgovind1981** [apache/cordova-ios#422]
Description:
App start crashes on iPad after upgrade to iOS 12.0.
[ERROR] An error occurred while running subprocess cordova.

Steps to Reproduce:

Upgrade iOS to 12.0
Already install Ionic app launch start crash.
Output:
```
[cordova] error: process launch failed: Unspecified
[cordova] (lldb) safequit
[cordova]
[cordova] Application has not been launched
[cordova]
[cordova] CordovaError: Promise rejected with non-error: 'Error code 1 for command: ios-deploy with args: --justlaunch,--no-wifi,-d,-b,/Users/agovind/Anupam/IonicWorkspace/cueapp/platforms/ios/build/device/MPT.app'
[cordova] at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
[cordova] at 
[cordova] at process._tickCallback (internal/process/next_tick.js:188:7)
[ERROR] An error occurred while running subprocess cordova.
```

My ionic info:
Ionic:

ionic (Ionic CLI) : 4.0.3 (/usr/local/lib/node_modules/ionic)
Ionic Framework : ionic-angular 3.9.2
@ionic/app-scripts : 3.1.9

Cordova:

cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
Cordova Platforms : android 7.0.0, browser 5.0.3, ios 4.5.5

System:

ios-deploy : 1.9.2
NodeJS : v8.9.4 (/usr/local/bin/node)
npm : 5.8.0
OS : macOS High Sierra
Xcode : Xcode 10.0 Build version 10A255

Environment:

ANDROID_HOME : not set

**Comment by anupamgovind1981** [comment]
Thanks for reply. But this is not the case. This error message generated during --livereload mode of running app for debug.

**Comment by oliversalzburg** [comment]
I'm not aware of a `--livereload` option in Cordova _and_ the message in the posted output still refers to a build-related issue and not an app crash.

**Comment by janpio** [comment]
Try to build your app outside of Ionic, so just `cordova build ios`.

You should also upgrade your stuff:

```
Ionic Framework : ionic-angular 3.9.2
@ionic/app-scripts : 3.1.9
...
Cordova Platforms : android 7.0.0
```

All outdated.

**Comment by anupamgovind1981** [comment]
Thanks for your replies. I found it working. If I push build on iPad using USB. It crashes but I used Test Flight to test app. It worked. Looks like iOS 12.0 changed something. Which do not allow app development using USB.
