### ISSUE TITLE
Keyboard increases the size of the inputs and the background of the app (iOS 12 and XCode 10.0)

### ISSUE THREAD

**Issue by luisvillara** [apache/cordova-ios#426]
There is a weird behavior with the app when I focused an input, it zoom out (the inputs and the background). I need to disable this issue.

This only happens when I use a device with iOS 12 and XCode 10.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/2540621/46770686-01bbd000-ccb6-11e8-9490-741967df0111.gif)

So, I fixed the issue by removing the `viewport-fit=cover`, but this is used for the full-screen support of the iPhone X 😢

**Comment by dpogue** [comment]
What else is in your meta viewport tag? Do you have `maximum-scale=1.0`?

**Comment by Nyarly29** [comment]
I have this issue too, with iPhone SE (iOS12) and XCode 10. No issue with other iPhones. And i have this option in my meta viewport tag.

**Comment by maximeaiw** [comment]
I have the same issue on iPhone X, iOS 12 with viewport-fit=cover for fullscreen handling. It's a new issue, same code gave different behaviour weeks ago.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
