### ISSUE TITLE
Generating a manifest.plist for over-the-air 'enterprise' distribution

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [apache/cordova-ios#432]
We use Enterprise-distribution for our iOS app; and in the Xcode IDE, I configure the produced `manifest.plist` thusly:

![screen shot 2018-10-23 at 1 19 46 pm](https://user-images.githubusercontent.com/200/47381740-54d64f80-d6c6-11e8-995e-4d859fcdef0c.png)

While there's a `build.json` field for Enterprise distribution, `"packageType": "enterprise",` there doesn't appear to be any documented way to configure the required URLs and manifest for OTA distribution? At the moment, I'm stuck doing that manually, every time.

Is there a sanctioned methodology for this, and/or is it on the roadmap?

Thanks!

**Comment by jcesarmobile** [comment]
It's not supported and it's not on the roadmap. 
Take a look into fastlane, maybe they support this.
