### ISSUE TITLE
cordova compiling issues with xCode 10

### ISSUE THREAD

**Issue by nagthgr8** [apache/cordova-ios#445]
While there is a work-around to get away with cordova build for iOS xCode 10 as mentioned in this post https://github.com/apache/cordova-ios/issues/407
 yet there is a limitation that I cannot use --prod flag in the command line options while I use --prod flag throwing compiler errors, my App experiencing more than 2 mins load time while tested in one of iOS devices from TestFlight, I am hoping if I use --prod the load time will come down.

**Comment by janpio** [comment]
https://github.com/apache/cordova-ios/issues/446#issuecomment-434313954
