### ISSUE TITLE
prod flag not working in xCode 10

### ISSUE THREAD

**Issue by nagthgr8** [apache/cordova-ios#446]
The below command line option not working in xCode 10 environment it gives compiler errors

ionic cordova build ios --prod -- --buildFlag="-UseModernBuildSystem=0"

tried different combinations to put --prod flag but it didn't work for xCode 10 the buildFlag='UserModernBuildSystem=0' is needed to get away with build process as explained here https://github.com/apache/cordova-ios/issues/407

my issue is with the amount of time my app is taking while loading more than a minute I am guessing that it must be due to not combining --prod flag in the compiler options, I tired other optimization as recommended this blog https://blog.khophi.co/optimize-ionic-2-app-production/ but the performance issue remains same

please suggest

**Comment by dpogue** [comment]
There is no `--prod` flag in cordova-ios. It looks like you're using Ionic, so this might be an Ionic-specific option that should be reported to them.

**Comment by nagthgr8** [comment]
I just opened this in [ionic forum ](https://forum.ionicframework.com/t/ionic-cordova-build-prod-flag-not-working-in-ios-xcode-10/146203)
