### ISSUE TITLE
No inertial scroll on iOS with facebok plugin page

### ISSUE THREAD

**Issue by JoshTor** [apache/cordova-ios#453]
Hi, i have an app which displays a Facebook content page with the Facebook plugin page.

On iOS, there is no inertial scrolling and i need it. I use Cordova-ios 4.5.5 with Framework7 2.2.1.

There is the html who display it :

```
<div id="facebook" class="page-content tab tab-link">
      <iframe src="https://www.facebook.com/plugins/page.php?href=*thereIsTheValidHref*&tabs=timeline&width=340&height=500&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=false&appId" width="340" height="500" style="border:none;overflow:hidden;display:block;margin-left:auto;margin-right: auto" scrolling="yes" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
       <div class="block text-align-center">
                 <div class="preloader color-blue "></div>
        </div>
</div>
```
The iframe is well displayed. I saw that is possibly the inertial sroll on iframe with safari wich is a problem but I do not really know if it comes from cordova.
It can ?

**Comment by janpio** [comment]
>  I use Cordova 2.2 

What does that mean?

Cordova CLI 2.2 does not exist (and would be 4 years old), Cordova iOS 2.2 is from Oct 31, 2012.

**Comment by JoshTor** [comment]
Sorry, i use cordova-ios 4.5.5, updated on the post.
One more thing :
```
-webkit-overflow-scrolling: touch;
overflow-y: scroll;
```
not working when i set on the #facebook div or on the iframe ...

**Comment by JoshTor** [comment]
I don't have another iframe scrollable in my app, but i think if it were, it would be the same thing
I'll try to show an iframe in another page to be sure

**Comment by matthieugayon** [comment]
Hey @JoshTor did you end up finding a solution for that ? I have the same problem

**Comment by kongminh** [comment]
Hope to help you:
https://www.learningsomethingnew.com/how-to-solve-the-no-scrolling-issue-with-ionic-web-view-in-non-ionic-cordova-i-os-apps
Use Ionic Web View plugin with config ScrollEnabled for iOS:
<preference name="ScrollEnabled" value="true" />

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
