### ISSUE TITLE
Voiceover seeing textfield that does not exist when launching the app

### ISSUE THREAD

**Issue by Selma-Casteloes** [apache/cordova-ios#455]
Since updating to iOS 12, whenever you launch the app, voiceover says text field editing on the splash screen although it does not exist. This does not happen on lower iOS versions. 

cordova version: 8.0.0
cordova-ios@4.5.4

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
