### ISSUE TITLE
cordova run --list --device fails for Virtualhere devices

### ISSUE THREAD

**Issue by regiMario** [apache/cordova-ios#458]
I'm using Virtualhere for developing remotely.
While Safari and Xcode do see the device after connecting via Virtualhere, cordova does not.
The attached patch remedies the issue in cordova-ios@4.5.5

[list-devices.patch.txt](https://github.com/apache/cordova-ios/files/2565985/list-devices.patch.txt)

**Comment by janpio** [comment]
This VirtualHere? https://www.virtualhere.com/home

Could you maybe submit a PR for that patch? We prefer to get code submissions via PR, as it makes it much clearer who contributed which code (and might be able to help out fixing any future bugs for example). Thanks.

**Comment by regiMario** [comment]
Had to read up on that first.
Done as good as i could for the first time.
