### ISSUE TITLE
Beta versions of cocoapods cause adding of pod-dependent plugins to fail

### ISSUE THREAD

**Issue by Menardi** [apache/cordova-ios#459]
When using a beta version of Cocoapods, adding a plugin which uses pods will fail. In my case, the plugin is cordova-plugin-firebase-analytics. The error message is `Error: Version should contain only numbers and dots`.

It is caused by the `beta` in the Cocoapods version, which breaks the version checker. That function (see https://github.com/apache/cordova-ios/blob/master/bin/templates/scripts/cordova/lib/versions.js#L169), checks to see if the installed Cocoapods version is above Cordova's minimum requirement (around 1.0.1 I think). It expects only numbers and dots (just like the error says) -- when it reaches the `beta`, it errors out, leaving the plugin in a half-installed state.

For now the simple workaround is to not use a beta version of Cocoapods. I'm mainly filing this issue to help others who might be having the same problem. But, it would be good to fix this issue anyway because the cause is relatively simple. I am not sure of the best way to tackle these kinds of version numbers. Maybe just ignore the `beta` and anything that follows? I am open to suggestions.

To reproduce it:
```
sudo gem install cocoapods -v 1.6.0.beta.2
cordova create test
cordova platform add ios
cordova plugin add cordova-plugin-firebase-analytics
```

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
