### ISSUE TITLE
Issue in Cordova iOS 4.5.5 for xcode 10.0

### ISSUE THREAD

**Issue by kkjhamb01** [apache/cordova-ios#460]
I build successfully app in IOS12 / Xcode20 but I am facing many design related issues like header disappear after moving to a screen and click not working sometimes. So I want to ask you when you release cordova ios 5.0.0 major release to solve design layout related issue. Please reply as soon as possible because this is the very big issue for me and i am hardly waiting for your new release .

**Comment by oliversalzburg** [comment]
There is no ETA on the next major release and if you want to make sure that their issues are addressed in the next release, please provide more specific information regarding individual issues.

**Comment by janpio** [comment]
As @oliversalzburg said, please provide specific examples of problems you are encountering @kkjhamb01.

**Comment by jcesarmobile** [comment]
Closing since no more information was provided

Also, looks very similar to https://github.com/apache/cordova-ios/issues/417
