### ISSUE TITLE
Form control cursor stays at the same place on scroll

### ISSUE THREAD

**Issue by khatridev** [apache/cordova-ios#463]
My app with cordova-iOS version 4.3.1 has a form page with multiple controls. On any control focus, keyboard pops up. On page scroll , focused control gets scrolled but the cursor stays on the screen at the same place for a while, cursor vanishes after the scroll stop. 
I have a workaround to keep the cursor out of focus on scroll. But let me know if there is other workaround or it is gonna fix in further releases.

**Comment by dpogue** [comment]
Unfortunately, this is a bug in Apple's UIWebView and WKWebView components, and there's nothing we can do in Cordova to fix it. The bug has been reported to Apple, and you can follow that discussion at https://bugs.webkit.org/show_bug.cgi?id=138201

**Comment by techzavronfinserv** [comment]
I am having the same error. When scrolling cursor does fix its position into the input. Could you please help me to solve this?
Here is the Attached video.

https://user-images.githubusercontent.com/84716126/160067383-2b1b44b9-f7a3-4704-ba01-6ac82c801d6f.mp4

**Comment by dpogue** [comment]
This is not a Cordova bug, and there is nothing that can be done in Cordova or in the app JavaScript/CSS to address it. It is an iOS bug that must be fixed by Apple, see the linked bug report above.

**Comment by supriyamalusare** [comment]
I am having the same error. When scrolling cursor does fix its position into the input. Could you please help me to solve this?
Here is the Attached video

https://user-images.githubusercontent.com/27942586/160067863-8f17e684-68f0-4e72-ae3c-6bc2723e3c14.mp4

.
