### ISSUE TITLE
 Going back to Cordova from native iOS view 

### ISSUE THREAD

**Issue by OmgKevin** [apache/cordova-ios#464]
I wrote a plugin, using cordova to push from the html interface to the ios native interface, and then there is a UINavigation on the ios interface, I want to click leftnavbar to return to the html interface, what should I do with your code?

**Comment by janpio** [comment]
`cordova-plugin-inappbrowser` also opens a native view that has a "Close" button. You should be able to look at the code of that plugin to get an idea how this is solved there.
