### ISSUE TITLE
[iOS][Cocoapods] Setting deployment-target doesn't change the iOS version in Podfile

### ISSUE THREAD

**Issue by jonathantribouharet** [apache/cordova-ios#468]
Hi,
I'm working on a plugin which is only working for iOS 10 and superior.
I try to set the `deployment-target` preference but it doesn't seem to update the value `platform :ios, '8.0'` in the Podfile.

By checking the code it should be working:

https://github.com/apache/cordova-ios/blob/46da4bc34495ec7bfe13c1ec1b4074dd2e82641a/bin/templates/scripts/cordova/lib/Podfile.js#L36
and
https://github.com/apache/cordova-ios/blob/2cd93097ec5d5989bc758f15db75011829c84c2b/bin/templates/scripts/cordova/Api.js#L271

Env:
Mac OS 10.14.1
cordova 8.1.2 (cordova-lib@8.1.1)
cordova-ios 4.5.5

It may be related to https://github.com/apache/cordova-ios/pull/335

Regards,

**Comment by jonathantribouharet** [comment]
Sorry I just see the `deployment-target` preference is only used for Podfile in the master branch not in 4.5.x.

**Comment by nevalenny** [comment]
@shazron do you know any ETA for when this change will be released?

**Comment by CSobol** [comment]
I'd love an update on this...

**Comment by rossholdway** [comment]
I see version 5.0.0 is out 🎉, but this fix only seems to work if you directly install a plugin with `cordova plugin add ...`. If you run a `cordova prepare` the PodFile dosen't seem to update the deployment target.

**Comment by janpio** [comment]
(If you want someone to take a look at this @rossholdway, create a new issue please.)

**Comment by mohlsen** [comment]
@rossholdway did you find a workaround (or submit an issue) for the fact that the PodFile is only updated on `plugin add` and not on `plugin prepare`?

**Comment by rossholdway** [comment]
@mohlsen Have now ;)

**Comment by Leffe108** [comment]
It seems that the bug is not fixed in cordova-ios@5.0.1 but is currently in the milestone for [5.0.2](https://github.com/apache/cordova-ios/milestone/4)

**Comment by frenmanoj** [comment]
I just tested it agains `cordova-ios@5.1.1`. It seems to be working now.
