### ISSUE TITLE
Xcode Doesn't Show The Real Debug Stats (Cpu/Fps/MR)  Of Any Of My Cordova Builds

### ISSUE THREAD

**Issue by Gamedevolop** [apache/cordova-ios#471]
Hi Good Afternoon 

I can't manage to debug any of my Cordova Builds on Xcode, the Debugger that Displays the Actual (Cpu/Fps/MR) is not showing the Real Stats of the App, is like it doesn't recognise the Webkit where all the game code is running and instead it displays the Stats of the executable Exe which is always around  CPU =6% 
Example: it targets the >>>> AppName.exe
The App can be Running at **Cpu: 80%**  and it will display just **6%** on the Debugger and the same goes for the Memory.
I create a Demo Test if anyone can try it to see what I mean, Please help as I been more than one-month researching and testing and nothing worked.

Cordova Ver:  8.1.2 (cordova-lib@8.1.1)
ios@4.5.5

**Demo for the Project To Test:** The Xcode Project is located at (Platforms>>ios)
[Demo Test Project](https://www.dropbox.com/s/b1t0lgcl457nky3/Xcode%20Debugger%20Display%20Help%20Demo.zip?dl=0)

**I will leave some Pictures also to show you what I mean**
[CPU](https://www.dropbox.com/s/uy6l9so4iq9vuke/Balls%20Cpu.png?dl=0)

[MR](https://www.dropbox.com/s/xq5135vgns66u5q/Balls%20Memory.png?dl=0)

**And this is how much CPU & RAM was consuming The  App on an iPhone 6 Device**
[Test Game Stats](https://www.dropbox.com/s/0y6ejvy35x7q625/Game%20Display.png?dl=0)

It happens with any build that I build with Cordova and with any Device that I installed.
**I test it on iPhones(6,7,8)**

**Xcode Version Tested:**
Xcode 10
Xcode 9.2

Thanks for reading I hope that you help me

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date Xcode version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
