### ISSUE TITLE
xcode10

### ISSUE THREAD

**Issue by passwhl** [apache/cordova-ios#473]
[cordova]  ** ARCHIVE SUCCEEDED **
[cordova]  
[cordova]  2018-12-12 19:00:47.025 xcodebuild[15793:229894] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/tw/30811n4n6hj424n2cq98dkr00000gp/T/appname_2018-12-12_19-00-46.998.xcdistributionlogs'.
[cordova]  error: exportArchive: "appname.app" requires a provisioning profile.
[cordova]  
[cordova]  Error Domain=IDEProvisioningErrorDomain Code=9 ""appname.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="appname.app" requires a provisioning profiwanghailongMAC:app admin$ ionic info

Ionic:

   ionic (Ionic CLI)  : 4.5.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.1.1, (and 20 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.5.0 (/usr/local/bin/node)
   npm        : 6.1.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61

**Comment by passwhl** [comment]
"ios": {
    "debug": {
      "codeSignIdentity": "iPhone Developer:******",
      "developmentTeam": "******",
      "packageType": "development",
      "automaticProvisioning": true,
      "buildFlag": [
        "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
        "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
        "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\"",
        "-UseModernBuildSystem=0",
        "-exportOptionsPlist=\"/Users/admin/Desktop/work/ExportOptions.plist\""
      ]
    },
    "release": {
      "codeSignIdentity": "iPhone Distribution: ******",
      "developmentTeam": "******",
      "packageType": "app-store",
      "automaticProvisioning": true,
      "buildFlag": [
        "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
        "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
        "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\"",
        "-UseModernBuildSystem=0",
        "-exportOptionsPlist=\"/Users/admin/Desktop/work/ExportOptions.plist\""
      ]
    }
  }

**Comment by passwhl** [comment]
Specifying ExportOptions. plist with manual export is ineffective

**Comment by passwhl** [comment]
Change automaticProvisi.:trueto"provisioningProfile": "***-******-*******",the Export

**Comment by passwhl** [comment]
![image](https://user-images.githubusercontent.com/12857123/49910144-8e545b80-febc-11e8-9863-c794a3266524.png)

**Comment by passwhl** [comment]
![image](https://user-images.githubusercontent.com/12857123/49910242-e723f400-febc-11e8-921b-5e676f90f182.png)
New mistake！！！

**Comment by dpogue** [comment]
Cordova-iOS is not yet compatible with Xcode 10. See further discussion [here](https://github.com/apache/cordova-ios/issues/407).
