### ISSUE TITLE
cordova-ios-4.5.5 and XCode 10.1 entitlements issue ( background modes + healthkit )

### ISSUE THREAD

**Issue by guikeller** [apache/cordova-ios#475]
Hi guys,

If you could please have a look on my SO question that would be very much appreciated.
https://stackoverflow.com/questions/53800267/missing-entitlement-uibackgroundmodes-value-workout-processing-without-the

I have read #407 at least 5 times from beginning to end to see if I was missing a step, but can't seem to grasp what is still missing.

Happy to provide more info, logs, etc. Thanks!

**Comment by write2sv** [comment]
Hi @guikeller Just wondering if it is related. I had similar issue while doing a ionic cordova app release. I figured the <key>com.apple.developer.healthkit</key>
    <true/>
is missing in my platforms/ios/<my app>/Entitlements-Release.plist. It does exist in Entitlements-Debug.plist. All I did is copied the key from the debug file to release and app store accepted it.

Thanks,
Surya.

**Comment by guikeller** [comment]
Hi @write2sv

Thank you very much for sharing that. I have even tried using one of my TSI with Apple but they were quick to dismiss and say that’s to do with Cordova.

I will give that a go once I am back from my holidays and shall update here with the outcome.

Cheers! 👍

**Comment by guikeller** [comment]
Hello @write2sv 

Once again, many thanks for sharing your findings with me and that was the issue indeed.
I have copied the missing values from the Entitlements-Debug.plist into Entitlements-Release.plist and was once again able to validate my app successfully. Now, I can finally once again submit my app for review.

Not sure what the cordova-ios team wants to do about it; so I will leave up to them to maintain this issue open or close it as this previously did not happen on XCode 9.

Cheers! 🎉

**Comment by write2sv** [comment]
Hi @guikeller, I am glad it helped.

**Comment by dpogue** [comment]
It sounds like this was solved, so I'll mark this issue as closed.
