### ISSUE TITLE
CDVAppDelegate - missing application:openURL:options implementation

### ISSUE THREAD

**Issue by h4ck-rOOt** [apache/cordova-ios#476]
Our company is using a deep linking feature provided by the customurlscheme cordova plugin. In combination with LSSupportsOpeningDocumentsInPlace set to true, an external invocation leads to a crash of the application with NSInternalInconsistencyExecption due to missing implementation of UIApplication -> AppDelegate -> application:openURL:options method.

Our fallback implementation seems to work here, but is obviously incomplete:

```obj-c
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    return [self application:app openURL:url sourceApplication:nil annotation:(NSString*)@""];
}
```

Is there a default implementation which could be used in this use-case or is there something wrong with our handling of in place document editing?

Thanks in advance. I appreciate any advice how to handle this situation.

**Comment by dpogue** [comment]
CordovaLib in cordova-ios 5.0.0 defines an implementation for `application:openURL:options `: https://github.com/apache/cordova-ios/blob/6465a943a5cfc31d7a656954babbad42ea0a7c18/CordovaLib/Classes/Public/CDVAppDelegate.m#L76-L99
