### ISSUE TITLE
CLI usage is not emitted to log

### ISSUE THREAD

**Issue by oliversalzburg** [apache/cordova-ios#477]
None of command lines (like `xcodebuild`) that are invoked on the shell are logged. This is essential information when attempting to troubleshoot build issues and the information is completely lost.

At the very least, the essential `xcodebuild` commands should be logged.

**Comment by janpio** [comment]
`--verbose` or `--debug` has no influence there?

**Comment by oliversalzburg** [comment]
Correct. This is not logged at all. For example:

https://github.com/apache/cordova-ios/blob/004b8300456816cc614d229e85a35a8bc37d363d/bin/templates/scripts/cordova/lib/build.js#L174

**Comment by dpogue** [comment]
Note: cordova-ios is currently using [its own `spawn` method](https://github.com/apache/cordova-ios/blob/004b8300456816cc614d229e85a35a8bc37d363d/bin/templates/scripts/cordova/lib/spawn.js), when it should probably be using [cordova-common's `superspawn`](https://github.com/apache/cordova-common/blob/master/src/superspawn.js)

**Comment by oliversalzburg** [comment]
@dpogue I created https://github.com/apache/cordova-ios/pull/478 to resolve that

**Comment by oliversalzburg** [comment]
Fixed by #479
