### ISSUE TITLE
Prevent tap to touch element during scroll

### ISSUE THREAD

**Issue by mesqueeb** [apache/cordova-ios#490]
**Expected behaviour:**
Something that works really well in Mobile Safari:
When scrolling and stopping the scroll momentum by tapping the screen once, no `@click` event is ever fired. Eg. `@click` on an element with VueJS. Or a simple button listener in vanilla JavaScript.

**Behaviour on Cordova:**
On Cordova, when stopping the scrolling momentum by tapping, a `@click` event is also triggered if the element underneath has an `@click` listener.

See this gif below. I have a modal that pops up when you tap on a film. It does not pop up in Safari when stopping scrolling momentum. But in Cordova it does, making it reaaally awkward for the end user to browse through.

![scrolling momentum cordova](https://user-images.githubusercontent.com/3253920/50822615-79f96680-1375-11e9-8a2a-a9e6525f775b.gif)

**Comment by dpogue** [comment]
This is potentially a difference between UIWebView (which Cordova uses by default) and WKWebView (which Safari uses, and which is available as a Cordova plugin).

**Comment by mesqueeb** [comment]
@dpogue thanks for your great insight?
If you happen to have an idea, would it be possible to point me in the direction of a work around to prevent this?
I’m grateful for any information!!

I’m scared this might scare of some users for my first app. : )

**Comment by dpogue** [comment]
Firstly, are you using the WKWebView plugin?
Secondly, are you using a library like FastClick that removes the 300ms click delay (often with bugs)?

**Comment by mesqueeb** [comment]
Thanks so much!
The problem is solved by using [WKWebView](https://github.com/apache/cordova-plugin-wkwebview-engine).
