### ISSUE TITLE
Update minimum Xcode version in README.md & cordova-docs

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-ios#492]
Similar to apache/cordova-docs#863 but for upcoming release where we will drop Xcode 8 and possibly Xcode 9.

I raised the following thread to discuss whether and when to drop Xcode 9 support: <https://lists.apache.org/thread.html/070b7a5aefbc4145d6572590ec5e649e423117bf4d8db115aa54a87b@%3Cdev.cordova.apache.org%3E>

I already started PR #491 to make the update in README.md.

**Comment by jcesarmobile** [comment]
Since it’s updated in the readme, I’m closing the issue.
Reported the same in Cordova docs since it has to be fixed there
https://github.com/apache/cordova-docs/issues/1027
