### ISSUE TITLE
Cordova application considerably slower than mobile browser version of application

### ISSUE THREAD

**Issue by FarhadG** [apache/cordova-ios#495]
We have a web application that we've recently wrapped with Cordova. That being said, the overall experience is considerably slower from the web equivalent. What are the reasons for this?

Some examples include transitions, animations, touch interactions, etc.

I haven't been able to get `--prod` to work just yet, but I've only read that this feature improves build/start time of the application. Not sure about UI/UX interactions.

**Comment by FarhadG** [comment]
Thanks for the quick response, @dpogue! I've been looking at using a modern WebView but cannot find any info on how to do this properly (other than some deprecated repos)

**Comment by janpio** [comment]
(`--prod` is an Ionic build flag)

**Comment by dpogue** [comment]
There is no Cordova equivalent, because Cordova isn't involved in the generation of your web files.
Cordova is a tool that packages up the files you give it as mobile apps. It doesn't do anything to modify those files.

As for using WKWebView, see https://www.npmjs.com/package/cordova-plugin-wkwebview-engine (and note in particular the list of limitations)

**Comment by FarhadG** [comment]
Very strange! I've seen tutorials/documentation saying that `--production` or `--prod` builds Cordova in a more optimized manner. Is this all incorrect, @dpogue ?

**Comment by dpogue** [comment]
Cordova does not have a `--production` or `--prod` flag

**Comment by FarhadG** [comment]
Great! Thanks for the clarification, @dpogue. I'll close this issue.

**Comment by FarhadG** [comment]
Thanks for the quick response, @dpogue. If that's the case, not sure why the Cordova site documents the following:

```
CB-13303 added --production flag by default. This means that when the commands cordova platform add android or cordova plugin add cordova-plugin-device are run, under the hood we are running npm install cordova-android --production. The --production flag only installs dependencies from package.json and skips devDependencies. This should speed up installs (especially when installing local copies of platforms and plugins). You can turn the flag off by passing the --noprod flag or setting it off globally via cordova config set production false.
```

https://cordova.apache.org/news/2017/10/10/tools-release.html

**Comment by janpio** [comment]
The second part of the quote explains:

> ... we are running `npm install cordova-android --production`. The `--production` flag only installs dependencies from `package.json` and skips `devDependencies`.

So this is used on an external call for the `npm` CLI that supports `--production` (but has nothing to do with building a faster app, just what kind of dependencies are installed).
