### ISSUE TITLE
AppIcon44x44@2x.png not assigned to the correct icon

### ISSUE THREAD

**Issue by tombell** [apache/cordova-ios#497]
When adding the iOS platform, the icon `AppIcon44x44@2x.png` is not assigned to the correct icon in the `AppIcon` asset catalog:

<img width="228" alt="screenshot 2019-01-16 at 13 03 26" src="https://user-images.githubusercontent.com/129327/51250731-3b743500-198f-11e9-96c8-1a0ade62fb95.png">

And results in the following warning when building the Xcode project:

<img width="254" alt="screenshot 2019-01-16 at 13 12 40" src="https://user-images.githubusercontent.com/129327/51251127-732fac80-1990-11e9-9ec8-14e27eb25d87.png">

These are the icons that have not been assigned an icon file:

<img width="739" alt="screenshot 2019-01-16 at 13 10 51" src="https://user-images.githubusercontent.com/129327/51251059-42e80e00-1990-11e9-940e-028a018adb80.png">

I've also checked this with a new Cordova project from scratch after adding the `ios` platform to it.

<img width="219" alt="screenshot 2019-01-16 at 13 16 05" src="https://user-images.githubusercontent.com/129327/51251292-e3d6c900-1990-11e9-9f96-97efe84a4c4b.png">

Seems like there might be a mistake in the template `Content.json` for the `AppIcon` asset catalog.

**Comment by tombell** [comment]
I've checked up on https://developer.apple.com/library/archive/qa/qa1686/_index.html for what that icon size refers to, and it is **Long-Look notification on Apple Watch (42mm)**.

It appears this icon isn't in the `AppIcon` asset catalog for an iOS/iPad app, so should probably be removed from the template.

**Comment by erisu** [comment]
This was resolved and merged into the master branch.  (#512) 
The fix will be available in the next major release (5.0.0).
