### ISSUE TITLE
Nightly breaks existing plugins without pod dependencies

### ISSUE THREAD

**Issue by darkyen** [apache/cordova-ios#498]
I need the fix for `target-deployment` to be available in my project as an upstream dependency needs `minimum iOS 10`. Therefore, I tried to give `5.0.0-dev` a try, with the latest nightly when I run `cordova prepare ios` installation of every plugin fails with `TypeError: plugin.getPodSpecs is not a function` I am not sure what's causing this so looking into it atm. However, it seems to break all plugins, is there any other way to force 4.x.x to use `target-deployment`?

**Comment by dpogue** [comment]
cordova-ios 4.x.x (and probably older versions too) support setting the deployment target via a preference in config.xml:

```xml
<preference name="deployment-target" value="10.0" />
```

**Comment by darkyen** [comment]
> cordova-ios 4.x.x (and probably older versions too) support setting the deployment target via a preference in config.xml:
> 
> ```
> <preference name="deployment-target" value="10.0" />
> ```

I tried that, while the .xcodeworkspace is getting generated with iOS 10 as minimum, the Podspec file is stuck on 8.0.

**Comment by erisu** [comment]
The `getPodSpecs` method was introduced in `cordova-common@3.x`. Even though `cordova-ios` nightly meet this requirement, one of the CLI dependencies is not updated.

That dependency creates an instance of its own version of common which it also passes to `cordova-ios`. Nightly `cordova-ios` expected the method and tried to call it.

**Comment by darkyen** [comment]
> The `getPodSpecs` method was introduced in `cordova-common@3.x`. Even though `cordova-ios` nightly meet this requirement, one of the CLI dependencies is not updated.
> 
> That dependency creates an instance of its own version of common which it also passes to `cordova-ios`. Nightly `cordova-ios` expected the method and tried to call it.

That makes sense. For now, I have resorted to monkey patching the hardcoded template on 4.5.5.

**Comment by darkyen** [comment]
@erisu so the monkey patch isn't holding either it runs into npm issues and in general is a flakey solution. Is there any workaround you'd recommend or how can I use `5.0.0-dev`, what other dependencies should I update?

**Comment by dpogue** [comment]
Should be fixed in the latest nightly build
