### ISSUE TITLE
allow navigation breaks allow intent ?

### ISSUE THREAD

**Issue by RHinderiks** [apache/cordova-ios#499]
We recently added <allow-navigation href="*" /> to allow ios to load external urls to an iframe. However non of the links we had that opened systems seem to work. Links that open browsers dont seem to work. "tel" links dont seem to work. Xcode and the browser console both dont show any error messages. Removing allow navigation makes it work again but than our iframes wont load.

Am i missing something completely or is this a bug ?

**Comment by RHinderiks** [comment]
running latest cordova ios (4.5.5)

**Comment by RHinderiks** [comment]
Is this a known issue ?

**Comment by janpio** [comment]
Could you please rewrite your question in a way that makes it easier to understand what is happening? Use \` around code or tags to format them as code to make it easier to understand.

**Comment by RHinderiks** [comment]
We got it working in the end, it was something weird with using * inside allow-navigation which seemed to disable or remove all allow intents or something. We got it working by replacing allow-navigation * with about:*

**Comment by Durzan666** [comment]
@RHinderiks Can you explain your solution with a small example? I am fighting with this issue at the moment.

**Comment by RHinderiks** [comment]
We're using <allow-navigation href="about:*" />  instead of <allow-navigation href="*" />
