### ISSUE TITLE
Can not build the cordova.framework with carthage

### ISSUE THREAD

**Issue by vang123456** [apache/cordova-ios#500]
Hello,

   I am trying to build the cordova.framework with the Carthage, but it always failed! I had tried every version from 4.4.0 upon. what happened about that? you can see the detail followed.

[carthage-xcodebuild.dyciR3.log](https://github.com/apache/cordova-ios/files/2775083/carthage-xcodebuild.dyciR3.log)

**Comment by dpogue** [comment]
If you're trying to build cordova-ios 4.5.5 in Carthage, you'll need to turn off Xcode 10's Modern Build System.

We've done some work to fix this on the master git branch, which will be in the next major version.

**Comment by vang123456** [comment]
Thank you ! It works!

**Comment by vang123456** [comment]
By the way, another question, could cordova.framework be be build with some cordova-plugins via carthage? I am a newer.
