### ISSUE TITLE
CordovaError: Promise rejected with non-error: 'Error code 65 for command: xcodebuild with args: -xcconfig,/

### ISSUE THREAD

**Issue by spsaravananct** [apache/cordova-ios#502]
while running ionic build am getting cordova error i tried this  **cordova build ios --buildFlag=-UseModernBuildSystem=0**  but still am getting error.

The following build commands failed:
	CompileC /Users/themesoft/Library/Developer/Xcode/DerivedData/MyApp-fpvvhomfviegrebuixnjxmpzvxkc/Build/Intermediates/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/x86_64/IONAssetHandler.o MyApp/Plugins/cordova-plugin-ionic-webview/IONAssetHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
CordovaError: Promise rejected with non-error: 'Error code 65 for command: xcodebuild with args: -xcconfig,/Users/themesoft/Desktop/saravanan/testApp/platforms/ios/cordova/build-debug.xcconfig,-workspace,MyApp.xcworkspace,-scheme,MyApp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone SE,build,CONFIGURATION_BUILD_DIR=/Users/themesoft/Desktop/saravanan/testApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/themesoft/Desktop/saravanan/testApp/platforms/ios/build/sharedpch,-UseModernBuildSystem=0'
    at cli.catch.err (/Users/themesoft/.npm-global/lib/node_modules/cordova/bin/cordova:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --buildFlag=-UseModernBuildSystem=0 exited with exit code 1.

**Comment by vgorte** [comment]
Same error here

**Comment by dpogue** [comment]
This should be fixed in cordova-ios@5.0.0, which is now available.

**Comment by fgilio** [comment]
Thanks @dpogue !
