### ISSUE TITLE
Cordova log file path is empty

### ISSUE THREAD

**Issue by allnash** [apache/cordova-ios#503]
Log file PATH shown by CLI is empty for cordova-ios

```
$ cordova emulate ios --debug --buildFlag="-UseModernBuildSystem=0" --target="iPhone-X, 12.1"
...
io.fimp.moapp: 5820
logPath: /Users/gadre/workspace/fimp/platforms/ios/cordova/console.log

```

when I cd to the path, log file is empty. the CLI has quit and I don't know how to debug my process. Please advice.

**Comment by janpio** [comment]
I don't think this logfile is actually written by Cordova, but by `ios-sim` which is started by Cordova: https://github.com/apache/cordova-ios/blob/c2cab2730cd87f3830d22f5b7e09113e2e98ae18/bin/templates/scripts/cordova/lib/run.js#L197-L209

Does the simulating of your app actually work as expected?
What versions of everything are you using?

**Comment by allnash** [comment]
I was hoping that the path it provided had the a simlink with the sim log file. Or just provide the sim log.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date Xcode version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
