### ISSUE TITLE
Twitter embeds with videos is not working on IOS

### ISSUE THREAD

**Issue by christofferartmannmrf** [apache/cordova-ios#505]
When using Twitter's JavaScript library to load tweets in a Cordova application there is an issue with tweets containing a video.

When clicking play, you are presented with a cookie popup and after that, the video never plays. We have only been able to replicate this issue in our Cordova app running on IOS.

Here is an [example app](https://github.com/christofferartmannmrf/cordova-twitter-embed) that replicates the issue.

**Device**
iPhone 8

**OS Version** 
12.1

**Cordova version**
7.0.1

**Comment by schindler-nuuway** [comment]
Unfortunately I still have the same problem: embedding twitter works fine, but when you click on the play button (of a twitter video embed), you only see the loading animation.... the video never starts. 

Is there any solution to this 2.5 years later? Hope is high ;)

**Comment by NiklasMerz** [comment]
This sounds like a WKWebView / WebKit issue. You could try to build a repro app.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
