### ISSUE TITLE
File not found: ios-sim

### ISSUE THREAD

**Issue by rosenfeldalon** [apache/cordova-ios#509]
When running add ios platform I get an error runing cordova-ios@4.5.5:

> Using cordova-fetch for cordova-ios@latest
> Adding ios project...
> Creating Cordova project for the iOS platform:
>         Path: platforms/ios
>         Package: ------------
>         Name: -----------
> chmod: File not found: ......./platforms/ios/cordova/node_modules/.bin/ios-sim
> iOS project created with cordova-ios@4.5.5

in my IDEA I get the requested file as "broken link" - see attached image below

![screen shot 2019-01-30 at 10 52 09](https://user-images.githubusercontent.com/12997716/51969918-45616200-247e-11e9-97a4-397cc66183f5.png)

**Comment by janpio** [comment]
Where does this link to?

**Comment by rosenfeldalon** [comment]
@janpio all I get is "file not found" and the idea marks it as broken, other than that I have no more info.
This issue is new...

**Comment by janpio** [comment]
What does this output: `npm list --depth==0`?
You might be able to work around this with `npm install -g ios-sim`.

**Comment by rosenfeldalon** [comment]
janpio thanks for that - although it did not help, the issue accrued since my project has old dependencies and was migrated to yarn, returning to good old NPM and Bower seemed to work for now...
