### ISSUE TITLE
Iphone XS Max status bar text floats to view

### ISSUE THREAD

**Issue by pluckannfeel** [apache/cordova-ios#511]
Hello, I have a problem with my app where in status bar text of iphone xs max is floating around the app itself. here's a screenshot.  

![image](https://user-images.githubusercontent.com/14131170/52200184-07f83c80-28a3-11e9-823f-bbe6218ec819.png)

As you can see in the top and bottom of the screenshot it shows it appears to have floated with it. 
In iphone X, Xs works fine.
Is there a plugin or fix for this? thanks

**Comment by jcesarmobile** [comment]
This is not a bug.
I recommend you reading this article
https://webkit.org/blog/7929/designing-websites-for-iphone-x/
