### ISSUE TITLE
iOS:	App is vulnerable to reverse engineering attack?

### ISSUE THREAD

**Issue by pkachhaw** [apache/cordova-ios#514]
WE have created an app through the Ionic Cordova framework and before publishing, gone through the WhiteHat scan for  the app. They have found below vulnerability in the app "

> Vulnerability	Description
> The binary can be decrypted and hence, attacker can extract class interfaces(class info) from the binary. Theseinterface describes the underlying architecture and design of the application. This information greatly aids theattacker in identifying valuable targets within the application.

![screenshot 2019-02-05 at 3 09 21 pm](https://user-images.githubusercontent.com/43336557/52264601-12c0d900-2958-11e9-8dc4-7900d25b1cb2.png)

**Recommendations**
 Binary  should make use of Multi-pass check (multitudes of check at different locations) and always inline function to prevent attackers from decrypting the application

**Comment by dpogue** [comment]
According to [http://iphonedevwiki.net/index.php/Crack_prevention](http://iphonedevwiki.net/index.php/Crack_prevention#General_Crack_Protection) (which is the only reference I can find to "Multi-pass check" with regards to iOS), both multi-pass checks and inlining functions are now useless for preventing decryption of the application.

> All Crack Protections are generally rendered useless by either Clutch or Overdrive, these methods remain purely as interesting tidbits. They will not stop your application from being cracked. All anti-piracy checking is fairly useless as attackers have complete access to your binary and can patch them with relative ease.

It doesn't sound to me like this is something Cordova wants to spend time investing in, for no apparent benefit.
