### ISSUE TITLE
fetch ios@5.0.0 failed 

### ISSUE THREAD

**Issue by ansarikhurshid786** [apache/cordova-ios#516]
I am trying to fetch latest version of ios but i am getting error as below : 
```
cordova platform add ios@5.0.0 --save
Using cordova-fetch for cordova-ios@5.0.0
Failed to fetch platform cordova-ios@5.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cordova-ios@5.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
```

**Comment by janpio** [comment]
5.0.0 has not been released on npm yet, only tagged here on GitHub. You should probably wait a few days, as the CLI and other parts of Cordova are probably also no ready yet.

**Comment by ansarikhurshid786** [comment]
@janpio Thanks. You are right. I checked in npmjs.com.

**Comment by dwissmann** [comment]
hello, when I am running cordova platform add ios it doesn't fetch version 5 and if I enter cordova platform add ios@5.0.0, it still gives me "failed to fetch platform ...

what am I doing wrong?
on an up to date mac

**Comment by janpio** [comment]
Create your own issue please @dwissmann, we will not debug new problems in existing, closed issues. Thanks.
