### ISSUE TITLE
cannot turn on Push Notifications in cordova-ios @5.0.0 with modern build system

### ISSUE THREAD

**Issue by dmastag** [apache/cordova-ios#518]
I am using a CI (gitlab-ci to be specific) to build my ios App.
Problem is that the Push Notification is now not automatically set which was working using 4.5.5 and the old build system

Am not able to change the following setting using the CI as it means we have to go back to manual uploads
![image](https://user-images.githubusercontent.com/5745805/52542447-44132c00-2dd2-11e9-8a2b-76c418d08449.png)

**Comment by joeldhenry** [comment]
i'm getting a similar issue when i select a provisioning profile in CLI:
`error: "[app-name]" requires a provisioning profile with the Push Notifications feature. Select a provisioning profile for the "Debug" build configuration in the project editor. (in target '[app-name]')`

**Comment by janpio** [comment]
Can you explain a bit better what is goin on? Where does this screenshot come from? How does Gitlab CI play a role here?

**Comment by dmastag** [comment]
Hi @janpio 
So I am using gitlab-ci with a gitlab runner put an a Mac, it basically runs 
```
ionic build
cordova platform add ios@5.0.0
bundle exec fastlane ios beta
```

With fastlane using match and pilot to upload to the App Store

I finally figured out how to get Push Notifications to be enabled automatically by using the Tutorial from
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-ios-automatic-builds

I create an entitlement file names [yourProjectName].entitlements and put it into the root of my project with the following content

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
</dict>
</plist>
```

And then add this to my config.xml
```
<platform name="ios">
    <resource-file src="[yourProjectName].entitlements" />
</platform>
```
