### ISSUE TITLE
splashscreen hangs when using cordova-ios@5.0.0 with modern build system

### ISSUE THREAD

**Issue by hburrows** [apache/cordova-ios#520]
When using `cordova-plugin-splashscreen` to control the splashscreen it is unpredictably hanging (i.e. not disappearing) when built using cordova-ios@5.0.0 and xcode 10.  When the app is launched from xcode the splashscreen predictably disappears.  However, when the app is launched from the homescreen it will hang 80% of the time.  If you return to the home screen and then return to the app (NOT force quiting) the splashscreen disappears - something about an initial launch is interferring with splashscreen dismissal.  I tried to manually dismiss using `window.navigator.splashscreen.hide()` but that didn't work either.

The configuration uses all default settings and a universal storyboard image (i.e. only `<plugin name="cordova-plugin-splashscreen" spec="^5.0.2"/>` and `<splash src="res/screen/ios/Default@2x~universal~anyany.png"/>` exist in `config.xml` for this).

If I remove`cordova-plugin-splashscreen` entirely all is fine -- except I don't get my splashscreen.

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by hburrows** [comment]
My mistake with bad configuration.  I mistakenly dropped the wkwebview engine and reverted to uiwebview which resulted in this error.
