### ISSUE TITLE
In latest cordova ios(cordova-ios@5.0.0), failed to install Onesignal plugin

### ISSUE THREAD

**Issue by kkjhamb01** [apache/cordova-ios#521]
After adding cordova-ios@5.0.0, can't add onesingal plugin.

It shows this issue:

> cordova plugin add onesignal-cordova-plugin --save
> Installing "onesignal-cordova-plugin" for ios
> "framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
> Failed to install 'onesignal-cordova-plugin': undefined
> CordovaError: Promise rejected with non-error: '/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!\': \u001b[31m[!] You cannot run CocoaPods as root.\u001b[39m (CLAide::Help)\n\n\u001b[4mUsage:\u001b[24m\n\n    $ \u001b[32mpod\u001b[39m \u001b[32mCOMMAND\u001b[39m\n\n      CocoaPods, the Cocoa library package manager.\n\n\u001b[4mCommands:\u001b[24m\n\n    \u001b[32m+ cache\u001b[39m      Manipulate the CocoaPods cache\n    \u001b[32m+ env\u001b[39m        Display pod environment\n    \u001b[32m+ init\u001b[39m       Generate a Podfile for the current directory\n    \u001b[32m+ install\u001b[39m    Install project dependencies according to versions from a\n                 Podfile.lock\n    \u001b[32m+ ipc\u001b[39m        Inter-process communication\n    \u001b[32m+ lib\u001b[39m        Develop pods\n    \u001b[32m+ list\u001b[39m       List pods\n    \u001b[32m+ outdated\u001b[39m   Show outdated project dependencies\n    \u001b[32m+ repo\u001b[39m       Manage spec-repositories\n    \u001b[32m+ setup\u001b[39m      Setup the CocoaPods environment\n    \u001b[32m+ spec\u001b[39m       Manage pod specs\n    \u001b[32m+ update\u001b[39m     Update outdated project dependencies and create new Podfile.lock\n\n\u001b[4mOptions:\u001b[24m\n\n    \u001b[34m--silent\u001b[39m     Show nothing\n    \u001b[34m--version\u001b[39m    Show the version of the tool\n    \u001b[34m--verbose\u001b[39m    Show more debugging information\n    \u001b[34m--no-ansi\u001b[39m    Show output without ANSI codes\n    \u001b[34m--help\u001b[39m       Show help banner of specified command\n\tfrom /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:47:in `run'\n\tfrom /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>\'\n\tfrom /usr/local/bin/pod:22:in `load'\n\tfrom /usr/local/bin/pod:22:in `'\n'
> at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> [ERROR] An error occurred while running subprocess cordova.

cordova plugin add onesignal-cordova-plugin --save exited with exit code 1.
Re-running this command with the --verbose flag may provide more information.

**Comment by erisu** [comment]
@kkjhamb01 As your error message says, you can not run Cocopods as root. (`[!] You cannot run CocoaPods as root.`)

You will need to fix that.

I am able to create a new project, add the plugin, and build successfully.

```
Cordova version: 8.1.2 (cordova-lib@8.1.1)
Node version: v8.15.0
NPM version: 6.4.1

$ cordova platform add ios@5.0.0

Using cordova-fetch for cordova-ios@5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: 
	Name: iosTest
iOS project created with cordova-ios@5.0.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~5.0.0 into config.xml file ...


$ cordova plugin add onesignal-cordova-plugin --save
Installing "onesignal-cordova-plugin" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
     ...

Adding onesignal-cordova-plugin to package.json
Saved plugin info for "onesignal-cordova-plugin" to config.xml

$ cordova build ios
...
** BUILD SUCCEEDED **
```

**Comment by kkjhamb01** [comment]
Its working fine... Thanks... I thing it was access folder permission issue. That's why it shows CocoaPods's error.
