### ISSUE TITLE
If there are no simulators at all, `cordova build ios` crashes with `Cannot read property 'name' of undefined`

### ISSUE THREAD

**Issue by janpio** [apache/cordova-ios#526]
# Bug Report

### What is expected to happen?

Cordova iOS should fall back to some default device that is defined in the code.

### What does actually happen?

If there are no simulators at all on a machine, `cordova build ios` crashes:

```
λ patched_cordova build ios
Cannot read property 'name' of undefined
```

### Command or Code

`cordova build ios`

### Version information

```
λ cordova -v
8.1.2 (cordova-lib@8.1.1)
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by RamiAlmofleh** [comment]
` app:spawn Running "cordova run ios --buildFlag=-UseModernBuildSystem=0" +0ms`

Cannot read property 'name' of undefined
