### ISSUE TITLE
Cordova build failing with Xcode 10.1 and Cordova version 3.5

### ISSUE THREAD

**Issue by ashishkumar2804** [apache/cordova-ios#529]
# Cordova build fails with Xcode 10

## Cordova ios build used to run successfully till xcode 9.4, with upgrade to Xcode 10.1 it has started failing with below error
Running command: /Users/zs/Development/svn/ICFieldView/trunk/root/ICFieldView.Mobile/mJSCS/platforms/ios/cordova/build 
Cordova can only run in Xcode version 4.6 or greater.
Error: /Users/zs/Development/svn/ICFieldView/trunk/root/ICFieldView.Mobile/mJSCS/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Cordova version 3.5.0-0.2.7
Cordova ios version 3.5

###Please let me know how to get cordova build getting successful 

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by dpogue** [comment]
cordova-ios 3.5.x does not support Xcode 10.

You'll need to upgrade to cordova-ios 5.0.0 if you're using Xcode 10.
