### ISSUE TITLE
WKWebView pause audio/video when user is scrolling (iOS 12.X)

### ISSUE THREAD

**Issue by Tyki** [apache/cordova-ios#530]
# Bug Report

### What is expected to happen?
The html5 audio keep playing even when the user is scrolling the WebView (Issue only on iOS 12.X)

### What does actually happen?
Audio/video stop playing when the user is scrolling the webview and resume when the scroll ended

## Information

Some informations here : https://stackoverflow.com/questions/52941747/music-stops-while-scrolling-in-cordova-app
A video example found here : https://www.youtube.com/watch?v=08EZQHR5KYk&feature=youtu.be

### Environment, Platform, Device

iPhone 7/8 on iOS 12.X 

### Version information

xCode 10.1 
using   engine name="ios" spec="^4.5.1" 

## Checklist

- [x ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by dpogue** [comment]
See also https://twitter.com/JudahGabriel/status/1071069776666132480
One of the WebKit devs suspects it's a side-effect of  https://bugs.webkit.org/show_bug.cgi?id=186856

In any case, this probably needs to be fixed in WebKit and isn't something Cordova can do anything about.
