### ISSUE TITLE
v5.0.0 Custom URI schemes / deeplinks broken

### ISSUE THREAD

**Issue by olivermuc** [apache/cordova-ios#532]
# Bug Report

## Problem
With v5.0.0 the app would still popup (generally listening fine to the deeplink, eg "myapp://") - however, once the app has focus the cordova deeplink plugin **which works fine with v4.5.5** does not respond to the URI/path.

### What is expected to happen?
v5.0.0 should work the same as v4.5.5 and not only launch the app, but also "forward" the URI/path as it used to.

### What does actually happen?
The app is getting focus, but the callback is never made to pass on the URI/path:
`myapp://open/some/page`

`open/some/page` is never received by the deeplink plugin callback.

### Command or Code
See here: https://github.com/ionic-team/ionic-plugin-deeplinks for basic example.
This works fine with v4.5.5, not v5.0.0.

**Comment by janpio** [comment]
A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by olivermuc** [comment]
Completely agree, unfortunately I am completely swamped and have lost a ton of time troubleshooting this already. Even the most simplistic example (ionic starter app + deeplink) should do the trick.
If I find time on the weekend, I will post a GIT repo.

Thanks though for the speedy turnaround.

**Comment by dpogue** [comment]
This is probably because we updated cordova-ios CDVAppDelegate to use a non-deprecated API:
https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/Public/CDVAppDelegate.m#L76

and ionic-plugin-deeplinks is trying to override the (deprecated) method that we used to implement, but no longer do:
https://github.com/ionic-team/ionic-plugin-deeplinks/blob/master/src/ios/AppDelegate%2BIonicDeeplink.m#L20

**Comment by olivermuc** [comment]
@dpogue thanks for the insight.
this begs the question, could the plugin be updated (it's apparently community driven) - or would we have to see if there is a newer or different alternative available to implement custom uri schemes?

**Comment by janpio** [comment]
"Just" make the override code in the deeplinks plugin also override the "new" API that is used now. The PR and exact code that was changed on our side: https://github.com/apache/cordova-ios/pull/489/files#diff-c81743aea3e207e35fb596ccec5f8216L76

**Comment by olivermuc** [comment]
Fantastic, I think this can be done. Hate to admit it, but coding cordova plugins is right over my head. Hoping that someone with proper coding skills could jump in.

**Comment by olivermuc** [comment]
I think I did it, encouraged by @janpio last post with the direct diff, I essentially just replaced the function definitions and added the `!url` check in addition. Seems to work just fine!
I will submit a PR (to the deeplink plugin repo/author).

Thank you all for pointing me in the right direction!

**Comment by janpio** [comment]
That's exactly how we all got started, congratulations 🥇  Make sure to link back here in the PR so GitHub can connect, or even leave a comment to the PR ❤️
