### ISSUE TITLE
The Hello World template is not updated

### ISSUE THREAD

**Issue by DAnn2012** [apache/cordova-ios#533]
### Issue Type
- [x] Bug Report
- [x] Feature Request
- [ ] Support Question

## Problem
The Hello World template version in `cordova-ios/bin/templates/project/www/` is not the latest version 4.0.0 but a version of a few years ago.

### What is expected to happen?
The 4.0.0 version of the Hello World template should be included.

### What does actually happen?
A version of the Hello World template from a few years ago is included.

## Information
See here: [https://github.com/apache/cordova-app-hello-world/releases](https://github.com/apache/cordova-app-hello-world/releases)

**Comment by janpio** [comment]
What version of cordova-ios are you talking about?

> but a version of a few years ago.

Can you specify this please?

**Comment by DAnn2012** [comment]
Hello,

I explain better, in **cordova-ios** version **5.0.0** that was released a few days ago, the **Hello World template** (in `cordova-ios/bin/templates/project/www/`) was not updated to the latest version **4.0.0** that was released on **December 20, 2018**.

Thank you for your quick answer.

**Comment by janpio** [comment]
The version of `cordova-app-hello-world` to be used when creating a new project is not part of `cordova-ios`, but `cordova-create`. There the dependency has been updated: https://github.com/apache/cordova-create/blob/49e6abc7adce124481be658f4ddbba1cfa3cc080/package.json#L28 `cordova-create` is used by `cordova-lib`, which is used in `cordova-cli` - all those releases have to happen before the new hello world app will be used by default.

My understanding is that this will happen soon-ish with Cordova CLI 9.

**Comment by DAnn2012** [comment]
I thank you for the answer

So the step described here:

[https://github.com/apache/cordova-coho/blob/24555dcb2de2084226c59e0ed04f8fcf91995d27/docs/app-hello-world-release-process.md#update-hello-world-template-each-platform-ships-with-this-is-so-users-can-create-projects-without-the-cli](https://github.com/apache/cordova-coho/blob/24555dcb2de2084226c59e0ed04f8fcf91995d27/docs/app-hello-world-release-process.md#update-hello-world-template-each-platform-ships-with-this-is-so-users-can-create-projects-without-the-cli)

will occur with the release of Cordova CLI 9, I got it right?

**Comment by janpio** [comment]
I think the release process you linked to is majorly outdated, but yeah, something like that will happen and make sure that the new template will be used. (You can follow the release progress here: https://github.com/apache/cordova/issues/10)

**Comment by janpio** [comment]
Is there a specific reason why you are waiting for the new release of our hello world template?
