### ISSUE TITLE
Cordova overwrites bundleIdentifier for all existing targets

### ISSUE THREAD

**Issue by wolfmanfx** [apache/cordova-ios#538]
# Bug Report
When cordova (using 5.0.0) projects contains watch targets (watchkit, watch extension) which have their own bundle id setup correctly, cordova overwrites all targets with the same id.

## Problem
Its not possible to pack new targets in the project and use cordova cli build 
cordova build --platform ios --device --release

### What is expected to happen?
It should not overwrite the PRODUCT_BUNDLE_IDENTIFIER of all targets.

### What does actually happen?
Signing does not work anymore.

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

---

Updates by @brodybits:

This issue seems to also break functionality of plugins that do extensions to Xcode projects by using hooks. See below for discussions.

**Comment by janpio** [comment]
So did I understand correctly that using `cordova build ios --device --release` overwrite the bundle identifiers of other targets? 

Can you pinpoint which files are changed to do this (quickly create a temp git project in `platform/ios` with `git init`, commit everything, then do the build, then look at the changed files to exactly pinpoint what files got edited)?

**Comment by wolfmanfx** [comment]
Hi, 
I create the project with cordova (I mean the xcode project) than I am patching the project.pbxproj and add 2 targets (watchapp, watchapp extension) when I stay within xcode everything is correct. But we build within travis so I am using the cli to create and export the ipa - but the signing process fails.

When I open the project.pbxproj the PRODUCT_BUNDLE_IDENTIFIER for all 3 targets are different and correct when I run 
cordova build --platform ios --device --release
All PRODUCT_BUNDLE_IDENTIFIER within the project.pbxproj are overwritten which breaks all other targets.

Can you point to the code where the updates happen?

**Comment by dpogue** [comment]
That happens [here](https://github.com/apache/cordova-ios/blob/5e688ca4ddf698fad5d10185f7583dec49abcfe1/bin/templates/scripts/cordova/lib/prepare.js#L301-L304): https://github.com/apache/cordova-ios/blob/5e688ca4ddf698fad5d10185f7583dec49abcfe1/bin/templates/scripts/cordova/lib/prepare.js#L301-L304

**Comment by wolfmanfx** [comment]
Ok - 
pbxProject.prototype.updateBuildProperty = function(prop, value, build) calls 
    var configs = this.pbxXCBuildConfigurationSection();
which returns all targets and we do not pass the build param we overwrite just all targets so thats really a bug.

Looking here https://github.com/apache/cordova-node-xcode/blob/master/lib/pbxProject.js#L1128 I guess that function is not designed for the usecase to update just one target.

My vote would to not update the bundle id but if needed it should only update a specific target.

Any thoughts?

**Comment by dpogue** [comment]
We have to update the bundle ID because that's how it gets set in the Info.plist

**Comment by wolfmanfx** [comment]
The bundle id is set on creation but the overwrite happens on the build stage too - or does the cli can not distinct between initial creation and build step?

**Comment by wolfmanfx** [comment]
It could also help to disable this behaviour through a flag or so, just thinking loud :)

**Comment by wolfmanfx** [comment]
Another idea would to create a parameter for the build.json which defines the target project and we overwrite just the settings of the desired project instead of every target?

**Comment by wolfmanfx** [comment]
So I am open for input as I am going to fork and fix that issuse.

**Comment by janpio** [comment]
> The bundle id is set on creation but the overwrite happens on the build stage too - or does the cli can not distinct between initial creation and build step?

Probably because a `build` also runs the `prepare` command, which includes the code @dpogue linked to above.

**Comment by dpogue** [comment]
Whatever the default behaviour is must not require people to know about Xcode build targets or require manually configuring things in build.json. It needs to just work out of the box for the basic use case of packaging up web content with an auto-generated Xcode project for iOS.

**Comment by wolfmanfx** [comment]
Thx - I have created a PR which fixes the behavior, no new params added. I am open for feedback also for a better solution thx

**Comment by wolfmanfx** [comment]
So I have pushed a new PR https://github.com/apache/cordova-ios/pull/545 this time I have added a new parameter to the build.json (optional) which is needed to sign mutliple targets with different budleids.

**Comment by msari-ipe-ext-1** [comment]
@dpogue Did you had time to review the changes - I know there are some styling things needs to be addressed but if its not gonna merged I wont put extra time into it ;)

**Comment by tombell** [comment]
Experiencing this myself, after adding a call kit call directory extension to my project.

**Comment by janpio** [comment]
@tombell Have a look at PR #545 then - there is some discussion on how to best solve this. Any opinions are welcome in there.

**Comment by NiklasMerz** [comment]
As @tombell I also have this problem with the call directory plugin and the share/openwith plugin, too. 

What can I do the help this getting merged. My tests with the PR were successful.

**Comment by msari-ipe-ext-1** [comment]
I am using my branch in productive with an apple watch extension - everything working 👍

**Comment by NiklasMerz** [comment]
@msari-ipe-ext-1 Great to hear!

How do I use `multipleProvisioningProfiles`? What is the value paramter for? The UUID or the name of the provisioning profile?

**Comment by msari-ipe-ext-1** [comment]
Hi,

In the build.json you can get multiple key value pairs

`
            "multipleProvisioningProfiles": [
                { "key": "de.some.html5", "value": "SOME-Enterprise" },
                { "key": "de.some.html5.watchkitapp", "value": "SOMEWE-Enterprise" },
                { "key": "de.some.html5.watchkitapp.watchkitextension", "value": "SOMEWE Extension-Enterprise" }
            ],
`

**Comment by NiklasMerz** [comment]
Yes exactly that's what I am asking. What is `value`? I this the UUID or the name of the provisioning profile? It looks like you mean profile names, but this does not work for me. But I always need to set provisioning profiles in Xcode because Cordova and plugin hooks can't set them anyhow.

**Comment by NiklasMerz** [comment]
Just to add my perspective on this again shortly. For us this is a critical app because our app uses two plugins that have hooks to add extensions to the Xcode project (calldirectory and share extension). The changes in Cordova 5 mean that the extensions Xcode config gets broken every time the app builds.

I agree that @msari-ipe-ext-1 's solution is to broad and confusing with the prov. profile feature that's why my fork tries to solve this with #708 . This works for us with this fork and cordova-node-xcode forked around these issues (https://github.com/apache/cordova-node-xcode/pull/79).

I am open to polish #708 as much as possible to get that in a good state to be merged.

**Comment by brodybits** [comment]
I have updated the title, pushed the milestone to 6.0.0, and added an update to the description. Thanks again @NiklasMerz for your input and contributions so far.

I would like to target the next major release of any components to be updated due to the nature of what is being changed and potential risk of breaking something else.

I would like to find a smooth way to move this forward, unfortunately dealing with very limited maintainer resources (see apache/cordova#163) and lack of understanding of this functionality. I am getting ready to sign off, can take another look in the next day or so.

It would be extremely helpful if someone could walk me and others through:

- what exactly went wrong with this functionality
- how it went wrong
- what and how of what went wrong with the plugin functionality
- why we need to fix another component (`xcode`) now
- how it can be fixed with a proposal such as #708
- how a change such as #708 works
- how changes to other components such as `xcode` would work

**Comment by kapfab** [comment]
In case some of you are stuck while this issue is fixed, as a workaround, you can temporarily force the target value of the bundle identifier of the app extension directly in it's Info.plist, so the build does not use the bad project setting.

**Comment by ludufre** [comment]
> In case some of you are stuck until this issue is fixed, as a workaround, you can temporarily force the target value of the bundle identifier of the app extension directly in it's Info.plist, so the build does not use the bad project setting.

How?

**Comment by kapfab** [comment]
> > In case some of you are stuck until this issue is fixed, as a workaround, you can temporarily force the target value of the bundle identifier of the app extension directly in it's Info.plist, so the build does not use the bad project setting.
> 
> How?

There is a `CFBundleIdentifier` entry in the Info.plist file whose value usually references the associated project setting (`$(PRODUCT_BUNDLE_IDENTIFIER)`). Change this value to the expected bundle identifier.

**Comment by brodybits** [comment]
What is the status of this? Anyone?

**Comment by NiklasMerz** [comment]
I cannot get my head around how to fix this properly but this is definitly an issue and I hacked around it. 

Cordova iOS 5 definitly causes issues for the tiny percentage of apps that use more than the default target (watch, share, calldirectory extensions). But we should discuss this in the issue.

**Comment by HarelM** [comment]
I've sent a related to this: #956 and opened a relevant issue: #953 and a bug #955.
Would love your input on my findings and work.
