### ISSUE TITLE
File picker in landscape mode is displayed in portrait mode

### ISSUE THREAD

**Issue by StarStep** [apache/cordova-ios#541]
# Bug Report

## Problem
When clicking an <input type="file"> the file picker is opened.
The problem is with the landscape mode: the file picker is displayed in portrai mode.

### What is expected to happen?
The file picker should be in landscape mode too, like the app.

## Information
Not working even if the app is explicitly set in landscape mode trought preference.

### Environment, Platform, Device
iPhones

### Version information
Latest

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by StarStep** [comment]
Am I the only one having this problem? 😅

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

Please also provide the real versions of all the things you are using. "latest" changes, it is also unclear if this applies to _everything_ or just cordova-ios.

**Comment by StarStep** [comment]
Is this reproducible in a new, plain Cordova app? Sure, here we go.

create a blank cordova app:` cordova create test com.iosfilepickerbug test`
edit **index.html** and replace the body contents with `<input type="file" />`
rotate the device to landscape (+90 or -90) mode and then tap on the input.
At this point you should see the file picker... it will be in portrait mode,
so you will be forced to rotate the device.

Setting the orientation inside to config.xml does not work.

...applies to _everything_ or just cordova-ios? Only on  **cordova iOS on iPhone**

**Comment by janpio** [comment]
My last question was regarding this from your original issue:

> ### Version information
> Latest

But thanks for posting the reproduction steps, now someone can easily take a look.

**Comment by jcesarmobile** [comment]
I've tried in different iOS versions (11.0.1, 12.0 and 12.2 simulators, and 12.3.1 real device) and I couldn't reproduce.

But even if I could, the picker is handled by the webview, not by cordova, so we won't be able to fix this kind of issues, you should report them to Apple.
