### ISSUE TITLE
Add Podspecs for the Cordova library project

### ISSUE THREAD

**Issue by bhariharan** [apache/cordova-ios#542]
# Feature Request
Add a `podspec` file for the `Cordova` project.

## Motivation Behind Feature
- This allows projects to fetch `Cordova` through `Cocoapods` if they choose to use that instead of the `cordova` CLI.
- Upgrades are seamless and as simple as changing the version in the app's `podspec` file.
- Very easy to maintain. No overhead on the `Cordova` project either.

## Feature Description
- Consuming via `Cocoapods` would be a breeze.
- Adding `pod 'Cordova'` as one of the dependencies with the URL specified would fetch the `Cordova` library in the app and generate the workspace.
- I have tested this in my own environment and it works great.

## Alternatives or Workarounds
- Unfortunately, there are no workarounds if you want to use `Cocoapods` and `Cordova`.

**Comment by janpio** [comment]
Would this be a reincarnation of https://cocoapods.org/pods/Cordova?

**Comment by bhariharan** [comment]
@janpio Sort of. It doesn't incur the overhead of having to publish to `cocoapods.org`, but it allows libraries to consume `Cordova` through `Cocoapods` from this `GitHub` repo. Technically, you could publish these specs to `cocoapods.org` too. I'm not sure why `Cordova` stopped publishing pod specs.

**Comment by janpio** [comment]
> I'm not sure why `Cordova` stopped publishing pod specs.

As only 2 of the 7 names in the "maintained by" list ring a bell for me at all, this might probably have been the reason - it just happened.

I don't know to much about iOS and nothing about Cocoapods, what whould a command to use this look like when this is merged?

**Comment by bhariharan** [comment]
This will specify pod specs for releases.

- The release version is specified [here](https://github.com/apache/cordova-ios/pull/543/files#diff-15560928f1c9b8b7b7e964ae78c57858R3). All you have to do is bump up this version to the version you're releasing as part of your release process.

- [This tag](https://github.com/apache/cordova-ios/pull/543/files#diff-15560928f1c9b8b7b7e964ae78c57858R10) specifies which tag of the repo to fetch these pod specs from. It automatically pulls it in from the aforementioned version number. I am using Cordova's existing tagging convention, so it should just work out of the box.

- I have added some detailed notes [here](https://github.com/apache/cordova-ios/pull/543/files#diff-15560928f1c9b8b7b7e964ae78c57858R23), it's pretty straightforward.

- [Here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid/blob/dev/SalesforceHybridSDK.podspec#L16) is an example of how a library would consume these pod specs.

**Comment by janpio** [comment]
Thanks for the newbie friendly explainer here.

**Comment by bhariharan** [comment]
@janpio Glad to help. Could you help review [this PR](https://github.com/apache/cordova-ios/pull/543) and get it merged? It would unblock one of my projects.

**Comment by janpio** [comment]
Ha, definitely not - I should really understand what I merge. But @dpogue is on it, see his comments.

One last question: How does a project including Cordova this way use Cordova?

**Comment by bhariharan** [comment]
@janpio It would reference it like [this](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/blob/dev/plugin.xml#L97). Our project builds on top of `Cordova`, it's a complicated set of plugins that leverage a lot of native functionality.

**Comment by brodybits** [comment]
As a Podspec newbie, I do have a concern that the upgradable Podspec assumes that the interface between JavaScript and the native side will remain stable.

Normally, upgrading cordova-ios would upgrade both the JavaScript bundled in cordova.js and the native side. My concern is that the flexible Podspec would introduce a risk of newer native code that is not compatible with the existing JavaScript code in cordova.js.

While I do not expect this interface to change very much in the near future, I think we should be very careful about this kind of risk and hope we can find a good way to mitigate.
