### ISSUE TITLE
Available iOS simulators are empty

### ISSUE THREAD

**Issue by ejerskov** [apache/cordova-ios#547]
# Bug Report

### What is expected to happen?

`cordova run ios --list` should list the same devices as `ios-sim showdevicetypes`

### What does actually happen?

The list is empty:

```
Available ios devices:
Available ios virtual devices:
```

### Command or Code
New project. These are the commands:

`cordova create hello com.example.hello HelloWorld`
`cd hello/`
`cordova platform add ios`
`cordova run ios --list`

### Version information
`cordova info`

> Collecting Data...
> 
> Node version: v10.15.1
> 
> Cordova version: 8.1.1
> 
> Config.xml file: 
> 
> <?xml version='1.0' encoding='utf-8'?>
> <widget id="com.example.hello" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
>     <name>HelloWorld</name>
>     <description>
>         A sample Apache Cordova application that responds to the deviceready event.
>     </description>
>     <author email="dev@cordova.apache.org" href="http://cordova.io">
>         Apache Cordova Team
>     </author>
>     <content src="index.html" />
>     <plugin name="cordova-plugin-whitelist" spec="1" />
>     <access origin="*" />
>     <allow-intent href="http://*/*" />
>     <allow-intent href="https://*/*" />
>     <allow-intent href="tel:*" />
>     <allow-intent href="sms:*" />
>     <allow-intent href="mailto:*" />
>     <allow-intent href="geo:*" />
>     <platform name="android">
>         <allow-intent href="market:*" />
>     </platform>
>     <platform name="ios">
>         <allow-intent href="itms:*" />
>         <allow-intent href="itms-apps:*" />
>     </platform>
>     <engine name="ios" spec="^4.5.5" />
> </widget>
> 
> 
> Plugins: 
> 
> cordova-plugin-whitelist
> 
> iOS platform:
> 
> Xcode 10.1
> Build version 10B61

**Comment by janpio** [comment]
Same problem when you do `cordova platform add ios@5.0.0`?

**Comment by ejerskov** [comment]
Running `cordova platform remove ios` and `cordova platform add ios@5.0.0` gives the same result.

I initially thought it was a problem within ios-sim, but with a fix for that issue it's still not working.

Link to other ios-sim issue and fix: https://github.com/ios-control/ios-sim/issues/246#issuecomment-465913349

**Comment by janpio** [comment]
Ok, so not a problem with cordova-ios but ios-sim?

You can close this issue then please.

**Comment by ejerskov** [comment]
ios-sim is returning the ios devices, but cordova is not. That’s why I created this issue

**Comment by janpio** [comment]
Can you please add to your issue what `ios-sim showdevicetypes` returns then?

**Comment by ejerskov** [comment]
Running `ios-sim showdevicetypes` in the cordova project

> Apple-Watch-Series-2-38mm, com.apple.CoreSimulator.SimRuntime.watchOS-5-1
> Apple-Watch-Series-2-42mm, com.apple.CoreSimulator.SimRuntime.watchOS-5-1
> Apple-Watch-Series-3-38mm, com.apple.CoreSimulator.SimRuntime.watchOS-5-1
> Apple-Watch-Series-3-42mm, com.apple.CoreSimulator.SimRuntime.watchOS-5-1
> Apple-Watch-Series-4-40mm, com.apple.CoreSimulator.SimRuntime.watchOS-5-1
> Apple-Watch-Series-4-44mm, com.apple.CoreSimulator.SimRuntime.watchOS-5-1
> Apple-TV-1080p, com.apple.CoreSimulator.SimRuntime.tvOS-12-1
> Apple-TV-4K-4K, com.apple.CoreSimulator.SimRuntime.tvOS-12-1
> Apple-TV-4K-1080p, com.apple.CoreSimulator.SimRuntime.tvOS-12-1
> iPhone-5s, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-5s, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-6, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-6, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-6-Plus, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-6-Plus, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-6s, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-6s, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-6s-Plus, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-6s-Plus, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-7, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-7, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-7-Plus, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-7-Plus, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-8, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-8, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-8-Plus, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-8-Plus, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-SE, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-SE, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-X, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPhone-X, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-XS, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-XS-Max, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad-Air, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPad-Air, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad-Air-2, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPad-Air-2, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad--5th-generation-, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPad--5th-generation-, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad-Pro--9-7-inch-, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPad-Pro--9-7-inch-, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad-Pro, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPad-Pro, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad-Pro--12-9-inch---2nd-generation-, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPad-Pro--12-9-inch---2nd-generation-, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad-Pro--10-5-inch-, com.apple.CoreSimulator.SimRuntime.iOS-11-0
> iPad-Pro--10-5-inch-, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad--6th-generation-, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad-Pro--11-inch-, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPad-Pro--12-9-inch---3rd-generation-, com.apple.CoreSimulator.SimRuntime.iOS-12-1
> iPhone-XR, com.apple.CoreSimulator.SimRuntime.iOS-12-1

**Comment by shazron** [comment]
ios-sim@8 has the fixes for the new devices. The pinned version for cordova is ios-sim@7 https://github.com/apache/cordova-ios/blob/5e688ca4ddf698fad5d10185f7583dec49abcfe1/package.json#L54

**Comment by dpogue** [comment]
Thanks Shazron! We should probably do a follow-up patch release to bump that to ^8.

**Comment by styk-tv** [comment]
@dpogue @shazron any chance this is related to something else

```
$ ios-sim --version
8.0.1
```

and

```
$ ios-sim showdevicetypes
iPhone-5s, 12.2
iPhone-6, 12.2
iPhone-6-Plus, 12.2
iPhone-6s, 12.2
iPhone-6s-Plus, 12.2
iPad-Air, 12.2
iPad-Air-2, 12.2
iPad-Pro--9-7-inch-, 12.2
Apple-TV-1080p, tvOS 12.2
Apple-TV-4K-4K, tvOS 12.2
Apple-TV-4K-1080p, tvOS 12.2
Apple-Watch-Series-2-38mm, watchOS 5.2
Apple-Watch-Series-2-42mm, watchOS 5.2
Apple-Watch-Series-3-38mm, watchOS 5.2
Apple-Watch-Series-3-42mm, watchOS 5.2
Apple-Watch-Series-4-40mm, watchOS 5.2
Apple-Watch-Series-4-44mm, watchOS 5.2
iPhone-7, 12.2
iPhone-7-Plus, 12.2
iPhone-8, 12.2
iPhone-8-Plus, 12.2
iPhone-SE, 12.2
iPhone-X, 12.2
iPad--5th-generation-, 12.2
iPad-Pro, 12.2
iPad-Pro--12-9-inch---2nd-generation-, 12.2
iPad-Pro--10-5-inch-, 12.2
iPhone-XS, 12.2
iPhone-XS-Max, 12.2
iPhone-XR, 12.2
iPad-Air--3rd-generation-, 12.2
iPad--6th-generation-, 12.2
iPad-Pro--11-inch-, 12.2
iPad-Pro--12-9-inch---3rd-generation-, 12.2
```

and

```
$ cordova run ios --list
Available ios devices:
Available ios virtual devices:
```
