### ISSUE TITLE
Error: Uncaught, unspecified "error" event. (createPlatform is not callable from the iOS project API.)

### ISSUE THREAD

**Issue by WemsolDev** [apache/cordova-ios#548]
# Bug Report

## Problem
Error: Uncaught, unspecified "error" event. (createPlatform is not callable from the iOS project API.)

### What does actually happen?
I am unable to add cordova-ios 5.0.0 with the following commands 

cordova platform remove ios
cordova platform add ios@5.0.0

## Information

My Project info is:
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.9.2
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 3.1.0
ios-deploy version: 1.9.4 
ios-sim version: 5.0.13 
OS: macOS
Node Version: v6.16.0
Xcode version: Xcode 10.1 Build version 10B61

**Comment by kraazie** [comment]
Facing same issue while upgrading to v5.0.0 !! any leads ?

**Comment by dpogue** [comment]
> Cordova CLI: 6.5.0

This is several years out of date. Please upgrade to Cordova CLI 8.1.2. We'll be releasing Cordova CLI 9 in the next few weeks.

**Comment by janpio** [comment]
Any update on this @kraazie @WemsolDev when using a recent Cordova CLI version?

**Comment by kraazie** [comment]
> Any update on this @kraazie @WemsolDev when using a recent Cordova CLI version?

Yes, my Cordova CLI version was outdated which I've upgraded to CLI 8.1.2.
Problem solved !!

Thanks @dpogue 

I would suggest WemsolDev to do the same and close this issue.

**Comment by WemsolDev** [comment]
Thanks @dpogue. It works for me.
