### ISSUE TITLE
Xcode 10.1 deploying cordova-ios 4.5.4 to iOS 12.x devices

### ISSUE THREAD

**Issue by rolinger** [apache/cordova-ios#558]
I upgraded to Xcode 10.1 and compiled my app at cli still using cordova-ios 4.5.4.  It compiled cleanly and from within Xcode 10.1 it deployed cleanly to both simulator and iPhones running iOS 12.x.

What am I missing here?  I thought cordova-ios 5.0.0 was needed to compile apps into Xcode 10 to support iOS 12.1  I expected it to break at compile time or break deploying to iOS 12.x devices...but that did not happen and everything seems just fine.

Oh, and I am still running cordova base 7.1.0

**Comment by rolinger** [comment]
Anyone have an update or be able to answer this?

**Comment by dpogue** [comment]
If it's working for you, great!

It's been the experience for many of us that we needed to make significant changes to the build process and project structure as part of cordova-ios@5.x in order to correctly support Xcode 10.
