### ISSUE TITLE
Deprecate (and later remove) `--codesignResourceRules`

### ISSUE THREAD

**Issue by janpio** [apache/cordova-ios#563]
From the docs at https://cordova.apache.org/docs/en/8.x/guide/platforms/ios/index.html#using-flags:

Parameter | Flag | Description
-- | -- | --
Code Sign Resource Rules | --codesignResourceRules | (Optional) Used to control which files in a bundle should be sealed by a code signature. For more details, read [The OS X Code Signing In Depth article](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG206)

Following that link I only find things like:

> Resource Rules
>
> Systems before OS X Mavericks 10.9 documented a signing feature (--resource-rules) to control which files in a bundle should be sealed by a code signature. This feature has been obsoleted for Mavericks. Code signatures made in Mavericks and later always seal all files in a bundle; there is no need to specify this explicitly any more. This also means that the Code Signing Resource Rules Path build setting in Xcode should no longer be used and should be left blank.
>
> It is thus no longer possible to exclude parts of a bundle from the signature. Bundles should be treated as read-only once they have been signed.

Is this parameter deprecated or even unsupported and can be removed then?

**Comment by dpogue** [comment]
It is [still supported](https://github.com/apache/cordova-ios/blob/master/bin/templates/scripts/cordova/lib/build.js#L184-L186) from a cordova-ios sense, but we should probably move to deprecate and remove it.

Maybe add a deprecation warning message in the next minor, and remove in v6?

**Comment by janpio** [comment]
So I understood the documentation correct that it doesn't do anything in recent Xcode versions? Then I fully agree - cleaning up there is a very great idea.
