### ISSUE TITLE
ios-CFBundleIdentifier not working in cordova-ios 5.0.0

### ISSUE THREAD

**Issue by malwatte** [apache/cordova-ios#565]
# Bug Report

## Problem
I was using ios-CFBundleIdentifier to set the app id for iOS. I needed to use that because Android app id is different. I was using xcode 9.4 cordova-ios 4.5.5 and the build worked fine. I updated Xcode to 10.1 and cordova-ios to 5.0.0 yesterday. When I open the Xcode project I see the Bundle Identifier is set as my.cordova.project, not the ios-CFBundleIdentifier in config.xml.

### What is expected to happen?
Bundle Identifier to be set to ios-CFBundleIdentifier in config.xml

cordova-cli 8.0.0
cordova-ios 5.0.0
xcode 10.1

Any help is greatly appreciated.

**Comment by janpio** [comment]
Could you please make sure this is not just specific to your project and setup and recreate it for a new Cordova project created with `cordova create`? Thanks.

**Comment by malwatte** [comment]
You are correct. I does not happen when I did it in a new project.
I cannot see any issue in my project. Maybe I'll remove other dependancies (plugins and libraries) and see.
Thanks

**Comment by janpio** [comment]
It might just be a hickup on your project. 
Have you tried removing and re-adding the ios platform?

**Comment by malwatte** [comment]
yes. I removed and added the platform. But didn't work.
But it works when I do `cordova prepare` twice.

After the first `cordova prepare`, value of project.pbxproj/PRODUCT_BUNDLE_IDENTIFIER is my.cordova.project. When I run `ionic prepare again`, it shows the correct value.

I have to idea. :(

**Comment by malwatte** [comment]
Although it worked in a new Cordova project, I see an issue.

Here is the config.xml values.
`<widget android-packageName="com.test.android" ios-CFBundleIdentifier="com.test.ios" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">`

then I do `cordova prepare`

this is the log

```
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: my.cordova.project
        Name: HelloWorld
iOS project created with cordova-ios@5.0.0
Discovered platform "android@7.1.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@7.1.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.test.android
        Name: HelloWorld
        Activity: MainActivity
        Android target: android-27
```

As you can see in the logs, ios project is always created with `Package: my.cordova.project` which is wrong. But Android is fine.

**After adding id to config.xml**
If I add an additional id="" to the config.xml, it works fine.
`<widget android-packageName="com.test.android" id="com.test.id" ios-CFBundleIdentifier="com.test.ios" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
`
Logs when doing `cordova prepare`

```
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: com.test.id
        Name: HelloWorld
iOS project created with cordova-ios@5.0.0
Discovered platform "android@7.1.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@7.1.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: com.test.android
        Name: HelloWorld
        Activity: MainActivity
        Android target: android-27
```

It looks like android-packageName overrides id, but  ios-CFBundleIdentifier does not.

**Comment by janpio** [comment]
What did you mean with "it works" if you never get the correct value?
Or does it only output that wrong value, but actually set the correct one?
Is this different from what cordova-ios.x did?

**Comment by malwatte** [comment]
I added few console.logs to `prepare.js` and `create.js`

I think what happens in the new project is this,

1. Xcode project is create with app id = my.cordova.project when a platform is added.
2. App id updated with the correct value (which is `ios-CFBundleIdentifier`) when the plugin cordova-plugin-whitelist added.

Now I'm trying to see why step 2 is not happening in my project. I use many plugins.

**Comment by dpogue** [comment]
This line needs to change to try to find `ios-CFBundleIdentifier` before falling back to `config.packageName()`: https://github.com/apache/cordova-ios/blob/f8b99a9fe5aa253770900db2ca38d53f87b747fd/bin/templates/scripts/cordova/Api.js#L134

**Comment by dpogue** [comment]
Fixed with #566. This will be released as part of cordova-ios@5.0.1.

**Comment by frederikbosch** [comment]
Would this bug also apply to 4.5.x?

**Comment by frederikbosch** [comment]
I guess so. When looking up the same line that was changed through #566 is [the same for 4.5.4](https://github.com/apache/cordova-ios/blob/rel/4.5.4/bin/templates/scripts/cordova/Api.js#L122).
