### ISSUE TITLE
[Documentation] indexedDb

### ISSUE THREAD

**Issue by mesqueeb** [apache/cordova-ios#574]
Sorry if this is not the place for documentation issues.

The current documentation on [indexedDb](https://cordova.apache.org/docs/en/latest/cordova/storage/storage.html#disadvantages) says:
> Disadvantages
> - Not supported on iOS.

Is this really still the case?

**Comment by brodybits** [comment]
You should probably file this on cordova-docs. It would be ideal if someone wants to raise a PR. And I think we should research the current state.

**Comment by mesqueeb** [comment]
https://github.com/apache/cordova-docs/issues/948
