### ISSUE TITLE
Cordova Build successful, phone launched, app not launched 

### ISSUE THREAD

**Issue by ctfrancia** [apache/cordova-ios#576]
# Bug Report

## Problem
When running `$ sudo ionic cordova run ios -- --buildFlag="-UseModernBuildSystem=0"` the emulator is launched but the app is not showing. This is just the TODO app... following the let's get started tutorial.

### What is expected to happen?
The TODO app to show on the iOS emulator

### What does actually happen?
the iPhone XR 12.1 is shown on the homescreen, but, that's all

### Command or Code

`$ sudo ionic cordova platform add ios`
`$ sudo ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"` as per #407 
>** BUILD SUCCEEDED **

`$ sudo ionic cordova run ios -- --buildFlag="-UseModernBuildSystem=0"` as per #407 

__note I have also replaced `run` with `emulate` as the ionicframework docs say__ 

> ** BUILD SUCCEEDED **
> 
> No target specified for emulator. Deploying to iPhone-X, 12.1 simulator
> logPath: /Users/c.francia/Desktop/path/to/todo/platforms/ios/cordova/console.log

the phone is launched, however, neither the app is launched nor is there a possibility for the app to be clicked on to open. 
I've checked the logs that it says are produced to but they are empty so there is nothing more to go on.

### Environment, Platform, Device

I'm experience this issue while on my laptop

### Version information

OSX: macOS Mojave 10.14
Ionic: ionic 4.12.0
Cordova: cordova 8.1.2
Xcode: 10.1
Simulator: 10.1 

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
What "TODO app" are you talking about? This doesn't exist for Cordova.

In general you should not need `sudo` to use Ionic or Cordova CLI. If you do, you did something wrong before.

**Comment by ctfrancia** [comment]
the todo app that is on the ionic [website](https://ionicframework.com/docs/v1/guide/installation.html). and I need to run `sudo` for else I get a permission issue (even though I'm on root) my permissions are messed up but that's a problem for another day.

**Comment by janpio** [comment]
Try with `ios@5.0.0` and without the build flag, maybe this is enough to solve the problem.

**Comment by ctfrancia** [comment]
Unfortunately not. I tried using both `sudo ionic cordova build ios@5.0.0` and `sudo ionic cordova build ios@5.0.0 -- --buildFlag="-UseModernBuildSystem=0` both failed to compile

**Comment by janpio** [comment]
You have to add the `ios@5.0.0` platform, then build normally. Only when adding you can specify a version, later you just build whatever you installed/added before.

**Comment by ctfrancia** [comment]
I think that the issue that I'm having is that I am following a tutorial that is designed for ionic1 using AngularJS (stupidly) and not Angular2. Could these versions not be playing nice with each other?

**Comment by janpio** [comment]
AngularJS and Angular 2+ (3, 4, 5, 6, ...) are totally incompatible. But that should not influence your use of Cordova at all. It might break your app of course, but you should still be able to start the app and then see a white screen that represents a broken web app.

**Comment by janpio** [comment]
Did you fix the problem in the meantime @ctfrancia?

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
