### ISSUE TITLE
Snyk report: High severity vulnerability found in shelljs -> Command Injection

### ISSUE THREAD

**Issue by gabriele-sacchi** [apache/cordova-ios#578]
# Bug Report

## Problem

Snyk (https://www.npmjs.com/package/snyk) querying a database of known vulnerabilities revealed this critical security vulnerability:

```
✗ High severity vulnerability found in shelljs
  Description: Command Injection
  Info: https://snyk.io/vuln/npm:shelljs:20140723
  Introduced through: cordova-android@8.0.0, cordova-ios@5.0.0, cordova-custom-config@5.0.3
  From: cordova-android@8.0.0 > shelljs@0.5.3
  From: cordova-ios@5.0.0 > shelljs@0.5.3
  From: cordova-custom-config@5.0.3 > shelljs@0.7.8
```

### What is expected to happen?
No security vulnerabilities should be found by Snyk

### What does actually happen?
High severity security vulnerability found by Snyk

## Information

**Steps to reproduce:**
- Add latest version of cordova-ios to a package.json file
- Install `npm snyk`
- Run `snyk test`

### Command or Code
See above

### Environment, Platform, Device
Any

### Version information

This is the case both for
`"cordova-ios": "^4.0.0",`
and
`"cordova-ios": "^5.0.0",`.

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by NiklasMerz** [comment]
`npm audit` does not report an issue for master

**Comment by NiklasMerz** [comment]
@gabriele-sacchi  Are you sure this is still an issue? 

>After discussions with the maintainer, and added safety warnings to the package for users- this was deemed not a vulnerability.

https://snyk.io/vuln/npm:shelljs:20140723

**Comment by NiklasMerz** [comment]
Please see: https://github.com/shelljs/shelljs/issues/945#issuecomment-505094896

>For an update for you all. It must be understood that if you use the exec function in this library you must sanitize the input yourself. From what I understand, library itself isn't vulnerable, it is the usage of the library that has the potential*.
> I've reached out to whitesource software (where the origin of the github security alert is coming from) and let them know that this might be a NOOP.
> At this point, the resolution is to use the github tooling or snyk tooling and ignore the alert. For github, you can view https://help.github.com/en/articles/viewing-and-updating-vulnerable-dependencies-in-your-repository (look for the dismiss button)

I did a quick check of the usage of `shelljs` in this project and could not find any commands that looked dangerous.

To all others looking at this issue please feel free to check, too just to make sure. But I am closing this now since it is not a real issue as far as I can tell.
