### ISSUE TITLE
loading cache using iframe on ios [android is ok]

### ISSUE THREAD

**Issue by matrixreal** [apache/cordova-ios#579]
Hello,
i use cordova ios to iframe my website & game
but it seem that on ios it not load from cache inside the iframe
on android it's working perfect
any fix for that ? thanks

**Comment by matrixreal** [comment]
any idea guys ?
thanks for reply

**Comment by matrixreal** [comment]
it's working good on android
but not on ios
any help guys ? 
thanks

**Comment by AndruC** [comment]
Which version of `cordova-ios` are you using?

**Comment by matrixreal** [comment]
> Which version of `cordova-ios` are you using?

4.5.4 and 4.5.5

**Comment by jcesarmobile** [comment]
can you provide a sample project?

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
