### ISSUE TITLE
IONIC 3 buttons and toggle are not working properly in iPhone 6s with XCODE 10.1

### ISSUE THREAD

**Issue by RamyaAshika** [apache/cordova-ios#584]
# Bug Report
Hi all,
    I'm trying to take an application using XCode 10.1 in my iPhone 6s but buttons are not working properly and toggle buttons on single tap. It requires two or more clicks but the same thing works fine with iPad and iPhone 5
## Problem
Buttons and toggles buttons are not working properly on a single click.
### What is expected to happen?
It should work on a single click

### What does actually happen?
Not working in iPhone 6s

### Command or Code

ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"

### Environment, Platform, Device

iPhone 6s

### Version information

IONIC Framework 3.19

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to the most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
