### ISSUE TITLE
iOS device list is empty

### ISSUE THREAD

**Issue by areanet-schmid** [apache/cordova-ios#586]
# Bug Report
_cordova run ios --emulator --list_ returns an empty list "Available ios virtual devices:"

### What is expected to happen?
_ios-sim showdevicetypes_ returns the correct list

_Available ios virtual devices:
Apple-Watch-Series-2-38mm, watchOS 5.2
Apple-Watch-Series-2-42mm, watchOS 5.2
Apple-Watch-Series-3-38mm, watchOS 5.2
Apple-Watch-Series-3-42mm, watchOS 5.2
Apple-Watch-Series-4-40mm, watchOS 5.2
Apple-Watch-Series-4-44mm, watchOS 5.2
Apple-TV-1080p, tvOS 12.2
Apple-TV-4K-4K, tvOS 12.2
Apple-TV-4K-1080p, tvOS 12.2
iPhone-5s, 11.1
iPhone-5s, 12.2
iPhone-5s, 10.1
iPhone-6, 11.1
iPhone-6, 12.2
iPhone-6, 10.1
iPhone-6-Plus, 11.1
iPhone-6-Plus, 12.2
iPhone-6-Plus, 10.1
iPhone-6s, 11.1
iPhone-6s, 12.2
..._

### Version information

We have tested the latest nightly build

└─┬ cordova-ios@5.1.0-nightly.2019.3.29.55654972
  └── ios-sim@8.0.0 

### Environment, Platform, Device

- XCode 10.2
- macOS 10.14.3
- NodeJS  v8.9.1 (/usr/local/bin/node)
- npm 6.6.0
- ios-deploy 1.9.4

**Comment by shazron** [comment]
Related: https://github.com/ios-control/ios-sim/issues/253

**Comment by eyeswideopen** [comment]
If you install ios-sim@next LOCALLY it worked for me.

**Comment by shazron** [comment]
`ios-sim@8.0.1` has been released that fixes this issue. I'll send a PR
