### ISSUE TITLE
The visibilitychange api is not working

### ISSUE THREAD

**Issue by adipascu** [apache/cordova-ios#588]
I expected the [visibilitychange api](https://developer.mozilla.org/en-US/docs/Web/Events/visibilitychange) to work inside the cordova webview on ios.

It does not emit any events. I tried prefixing the event as  `webkitvisibilitychange`, it still does not emit any events. It works fine inside mobile safari.

```js
window.document.addEventListener(
  'visibilitychange',
  () => {
    console.log('Visibility Changed!');
  },
  false
);

```

I am running `cordova-ios 5.0.0` with `cordova 8.1.2`. This can be reproduced using a simulator.

As a workaround I am using the `paused` and `resumed` events from [here](https://cordova.apache.org/docs/en/9.x/cordova/events/events.html).

**Comment by dpogue** [comment]
UIWebView on iOS does not support the page visibility API.

I believe it is supported in WKWebView.
