### ISSUE TITLE
Application freezes after moving from Background to Foreground from iOS version 12.x

### ISSUE THREAD

**Issue by msanilkumar2020** [apache/cordova-ios#591]
Hi Cordova team, 

Ours is Phone gap based application, we are using WKWebivew to load UI.

Keep application in background for more than 5 min (after suspension of 180 seconds) and move app to Foreground. We are receiving one exception in wkwebview( [ProcessSuspension] Background task expired while holding WebKit ProcessAssertion (isMainThread? 0).)after moving App to foreground. 

After this exception, UI is not able to render and App got freezed. This issue is always reproduced.  This
### What is expected to happen?
Application should not freeze

### What does actually happen?
Application is getting freeze

### Environment, Platform, Device
All iOS devices running on OS version>=12.x

### Version information
All iOS devices running on OS version>=12.x

**Comment by msanilkumar2020** [comment]
@janpio ,
Could you please help us on this issue.

Thanks,
Anil Kumar

**Comment by FlippingWork** [comment]
Same issue here

**Comment by jcesarmobile** [comment]
This was an Apple bug, they fixed it on 12.3
