### ISSUE TITLE
More insight into device/simulator deployment

### ISSUE THREAD

**Issue by janpio** [apache/cordova-ios#594]
# Feature Request

## Motivation Behind Feature

As long as the iOS simulator chosen to emulate the app on works, everything is fine. But as soon as it does not work any more, it becomes really difficult to understand at what level things go wrong.

Example: https://github.com/apache/cordova-paramedic/issues/98#issuecomment-482651348 

## Feature Description

Output more information about the "deployment" bits of `cordova run`:

- More information about simulator that is chosen to build for (Simulator ID, iOS version)
- Highlight when "deploy to device/simulator" bit starts
- Output command that is used to select simulator
- Output command that is used to run on simulator

## Alternatives or Workarounds
None

**Comment by janpio** [comment]
https://github.com/apache/cordova-ios/pull/596 does a few things about that.

**Comment by NiklasMerz** [comment]
I just did a PR two add some more logging but this not really necessary since the log is already pretty good. Most of the features above were done in #596
