### ISSUE TITLE
NSURLErrorDomain Code=-999 not processed

### ISSUE THREAD

**Issue by CrazyRoy** [apache/cordova-ios#598]
# Bug Report

## Problem
NSURLErrorDomain Code=-999 not processed
### What is expected to happen?
jump next webView success

### What does actually happen?
invoke didFailLoadWithError and webViewDidFinishLoad

## Information

I need to addobserver CDVPageLoadNotification to get webView title.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by yazoury** [comment]
I am facing the same issue ,did you find a solution?

**Comment by CrazyRoy** [comment]
> I am facing the same issue ,did you find a solution?

Now im change the cordova source code by myself, but the reason will forget sometimes. so i hope them can deal the problem!

**Comment by yazoury** [comment]
Did you manage to solve it, can your share yoir input.

**Comment by CrazyRoy** [comment]
> Did you manage to solve it, can your share yoir input.
> […](#)

in CDVUIWebViewDelegate file line 380
Commented code: _state = STATE_CANCELLED 
then return normal response.

**Comment by mluis** [comment]
I'm facing the same issue.

**Comment by janpio** [comment]
What is the issues? The current problem description doesn't really tell me anything.

**Comment by CrazyRoy** [comment]
The phenomenon is that a web page that redirects is opened, and then the CDVPageDidLoadNotification notification is not received; and the error message of the status code -999 is reported.

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by mluis** [comment]
I think this might be related to the installation of `cordova-plugin-ionic-webview` because after installing it in my project this error disappeared.

**Comment by CrazyRoy** [comment]
oh no , it not everytime disappear , 5time or more will appear


发自我的iPhone

------------------ Original ------------------

**Comment by VYRNACH** [comment]
my issue turns out to be a missing/corrupted plugin. Easiest way to remedy this is to start fresh

**Comment by timbru31** [comment]
Closing due to lack of feedback and missing example app that shows the bug. If the issue persists, please create a new one and fill in the issue template completely. Thanks!
