### ISSUE TITLE
Custom url scheme redirect does not work with cordova platform ios @5.0.0

### ISSUE THREAD

**Issue by gambarle** [apache/cordova-ios#599]
# Bug Report

## Problem
Using ionic cordova platform ios @5.0.0
Url scheme redirect for OAuth log in, does not work, when app is accessed from within another app.
This is working with cordova ios @4.5.4

### What is expected to happen?
Installing my app from Test Flight, clicking the 'open' button inside Test Flight, opens the app and presents a login view.
Clicking 'log in' redirects the app using SafariViewBrowser plugin to an OAuth login.
Entering credentials, the user are logged in and redirected back to the app, using CustomUrlScheme plugin.

### What does actually happen?
After entering credentials the view goes blank and does not return to the app

## Information

This might be a plugin issue with SafariViewBrowser or CutstomUrlScheme, however I have tried to reinstall these plugins with different release versions, without luck.
the issue is not present if I use cordova ios @4.5.4

### Version information

`ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.2.3
    Cordova Platforms  : android 7.0.0 browser 5.0.4 ios 5.0.0
    Ionic Framework    : ionic-angular 3.9.4

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.3 
    Node       : v8.11.1
    npm        : 5.6.0 
    OS         : macOS
    Xcode      : Xcode 10.2 Build version 10E125  `

## package.json
`{
    "name": "printix-app-user",
    "author": "Printix",
    "homepage": "http://iprintix.net/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "ionic:build": "ionic-app-scripts build",
        "ionic:watch": "ionic-app-scripts watch",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "5.2.6",
        "@angular/compiler": "5.2.6",
        "@angular/compiler-cli": "5.2.6",
        "@angular/core": "5.2.6",
        "@angular/forms": "5.2.6",
        "@angular/platform-browser": "5.2.6",
        "@angular/platform-browser-dynamic": "5.2.6",
        "@ionic-native/core": "4.11.0",
        "@ionic-native/device": "4.11.0",
        "@ionic-native/in-app-browser": "4.11.0",
        "@ionic-native/keyboard": "4.11.0",
        "@ionic-native/network": "4.11.0",
        "@ionic-native/qr-scanner": "4.11.0",
        "@ionic-native/safari-view-controller": "^4.11.0",
        "@ionic-native/screen-orientation": "4.11.0",
        "@ionic-native/splash-screen": "4.11.0",
        "@ionic-native/sqlite": "4.11.0",
        "@ionic-native/status-bar": "4.11.0",
        "@ionic-native/vibration": "4.11.0",
        "@ionic/storage": "^2.2.0",
        "@ngx-translate/core": "9.1.1",
        "@ngx-translate/http-loader": "2.0.1",
        "@types/lodash": "^4.14.109",
        "angular-2-local-storage": "1.0.1",
        "angular2-moment": "^1.9.0",
        "bootstrap-sass": "^3.3.7",
        "chart.js": "2.7.1",
        "cordova-android": "7.0.0",
        "cordova-browser": "5.0.4",
        "cordova-ios": "4.5.5",
        "cordova-plugin-add-swift-support": "^2.0.2",
        "cordova-plugin-customurlscheme": "^4.4.0",
        "cordova-plugin-inappbrowser": "^3.0.0",
        "cordova-plugin-network-information": "^2.0.1",
        "cordova-plugin-qrscanner": "^2.6.2",
        "cordova-plugin-safariviewcontroller": "^1.5.4",
        "cordova-plugin-screen-orientation": "^3.0.1",
        "cordova-plugin-splashscreen": "^5.0.2",
        "cordova-plugin-statusbar": "^2.4.2",
        "cordova-plugin-vibration": "^3.1.0",
        "cordova-plugin-whitelist": "^1.3.3",
        "cordova-sqlite-storage": "^3.2.0",
        "es6-promise-plugin": "^4.2.2",
        "fast-json-patch": "2.0.6",
        "flag-icon-css": "3.0.0",
        "immutable": "^3.8.2",
        "ionic-angular": "3.9.4",
        "ionic-plugin-deeplinks": "^1.0.17",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "ios-sim": "^6.1.2",
        "list": "^2.0.13",
        "lodash": "^4.17.10",
        "ngx-order-pipe": "^2.0.1",
        "rxjs": "5.5.6",
        "zone.js": "0.8.20"
    },
    "devDependencies": {
        "@angular/cli": "^7.3.0",
        "@ionic/app-scripts": "3.2.3",
        "postcss": "6.0.14",
        "typescript": "^2.7.2"
    },
    "cordova": {
        "platforms": [
            "browser",
            "android",
            "ios"
        ],
        "plugins": {
            "cordova-plugin-network-information": {},
            "cordova-plugin-statusbar": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-screen-orientation": {},
            "cordova-plugin-vibration": {},
            "cordova-plugin-whitelist": {},
            "cordova-plugin-add-swift-support": {},
            "cordova-plugin-qrscanner": {},
            "cordova-plugin-splashscreen": {},
            "cordova-sqlite-storage": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-customurlscheme": {
                "URL_SCHEME": "printixapp",
                "ANDROID_SCHEME": " ",
                "ANDROID_HOST": " ",
                "ANDROID_PATHPREFIX": "/"
            },
            "cordova-plugin-safariviewcontroller": {}
        }
    }
}`

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
The `ionic info` you posted shows you using `cordova-ios` 4.5.5, not 5.0.0.

Also, please include at least some hints of code so we can try to understand what your app is actually doing. How are you opening what exactly as login view? What exactly plugin (Github link, version installed) are you using with what code to handle the return that is failing?

**Comment by gambarle** [comment]
cordova-ios corrected (was on 4.5.4 at the time of writing).
package.json added.
Plugin ["cordova-plugin-safariviewcontroller": "^1.5.4"](https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller)
is used to show web content with login.microsoftonline.com, with a redirect url, that is used after credentials are submitted and authorised.
Plugin ["cordova-plugin-customurlscheme" spec="^4.4.0"](https://github.com/EddyVerbruggen/Custom-URL-scheme)
are used to handle the redirect URL, putting the app back into focus after login.
If I install cordova-ios 5.0.0 and open the app from within another app (Test Flight), after credentials are submitted, the view stops in the web content view on microsoft onlilne, with a blank screen.
So the issue only occurs using cordova-ios 5.0.0 and opening the app from within another app

**Comment by janpio** [comment]
> and opening the app from within another app

what are the alternatives where it works normally?

**Comment by dpogue** [comment]
It's definitely something wrong with how your plugins are set up, because I've successfully done an OAuth flow in Cordova-iOS 5.0.0 and the redirection via the app ID scheme worked properly. I found several of the existing plugins unreliable, and wrote my own [cordova-plugin-oauth](https://www.npmjs.com/package/cordova-plugin-oauth), but the URL scheme stuff was inspired almost directly from what cordova-plugin-customurlscheme was doing.

**Comment by Durzan666** [comment]
This issue could be associated with my [issue](https://github.com/apache/cordova-ios/issues/581).

**Comment by gambarle** [comment]
> > and opening the app from within another app
> 
> what are the alternatives where it works normally?

After installing from Test Flight, close the Test flight app, and open my app from the home screen.

My bet is that it is the plugin(s) that are responsible as @dpogue says, but it seems odd enough that I would mention it.

**Comment by gambarle** [comment]
@dpogue 
Thanks for the input, looks like I should try your plugin instead of the custom-url-scheme I'm using

**Comment by gambarle** [comment]
@Durzan666 
Thanks for the input, 
I can't say if it is related.
My -info.plist file looks the same in regard to CFBundleURLTypes / CFBundleURLSchemes
between cordova-ios 5.0.0 and 4.5.5
But I also don't change anything in my plugin.xml

**Comment by Durzan666** [comment]
@gambarle 
So there is a value for CFBundleURLTypes oder CFBundleURLSchemes in your *-info.plist?

**Comment by gambarle** [comment]
@Durzan666 
Yes there is.

**Comment by zhangjingle** [comment]
cordova-ios, CDVAppDelegate.m post openurl notifiycaiton before observer(CDVHandleOpenURL.m) register notification

fix:
in AppDelegate.m
#import "AppDelegate.h"
#import "MainViewController.h"

@interface AppDelegate()
@property (nonatomic) BOOL pageDidLoad;
@property (nonatomic, strong) NSURL * openURL;
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions {
    // ... your code
    [self fixOpenURL];
    return YES;
}

-(void)fixOpenURL {
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(applicationPageDidLoad:) name:CDVPageDidLoadNotification object:nil];
}

-(void)applicationPageDidLoad:(NSNotification*)notification {
    self.pageDidLoad = YES;
    [self postMessageForOpenURL];
}

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {
    self.openURL = url;
    [self postMessageForOpenURL];
    return YES;
}

-(void)postMessageForOpenURL {
    if (self.openURL && self.pageDidLoad) {
        [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPluginHandleOpenURLNotification object:self.openURL]];
    }
}

@end

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
