### ISSUE TITLE
`cordova run ios --target ... --emulator` builds for different target

### ISSUE THREAD

**Issue by janpio** [apache/cordova-ios#603]
# Bug Report

### What is expected to happen?

When I specify a `--target`, I expect the build to be for this target.

### What does actually happen?

When using `--target` to specify a target, it builds for another simulator anyway.

```
$ cordova run ios --no-telemetry --no-update-notifier --target iPhone-X --emulator
Building for "iPhone SE" Simulator (com.apple.CoreSimulator.SimDeviceType.iPhone-SE, iPhone-SE)
Building project: /private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/tmp-1908WVzCBEz79LN5/platforms/ios/HelloCordova.xcworkspace
	Configuration: Debug
	Platform: emulator
	Target: iPhone SE
Running command: xcodebuild -workspace HelloCordova.xcworkspace -scheme HelloCordova -configuration Debug -sdk iphonesimulator -destination platform=iOS Simulator,name=iPhone SE build ...
```
(from https://travis-ci.org/apache/cordova-paramedic/jobs/519983893)

Fortunately this is often fine, as in the linked CI build, as the built app still can deploy and run on the simulator. 

But in cases like #602 it breaks the deployment of the built app later.

### Version information

CLI 9, cordova-ios 5.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
The ticket will be closed as it's no longer an issue.

When executing the commands `cordova run ios --target=iPhone-X` and `cordova run ios --target=iPhone-XR`, I can confirm that the target value was used correctly. The application built and deployed to the respective target values.

I have tested this on the latest cordova-ios release (7.0.1).
