### ISSUE TITLE
Cordova libraries built on xCode 10.1+ swift projects give the error 'include of non-modular header inside framework module'.

### ISSUE THREAD

**Issue by jtcreative** [apache/cordova-ios#604]
# Feature Request

## Motivation Behind Feature
This increases issues of integrating the library as a carthage or cocoapods dependency in projects. Anyone who uses swift as a project language will eventually hit this issue.

## Feature Description
If you add this repo as a dependency to a carthage file of a project being run on xCode 10.1 or 10.2, reference an imported header in the project, and build, you'll receive an error mentioning non modular headers being referenced.

## Alternatives or Workarounds
The alternative workaround is to compile the code in an earlier version of xCode (9.4.1 for example) and reference the compiled source in the list of linked frameworks.

**Comment by jtcreative** [comment]
I'm willing to make a fix regarding this. Please let me know your thoughts on the issue.

**Comment by dpogue** [comment]
Is it possible that this is fixed in the upcoming 5.0.1 release by https://github.com/apache/cordova-ios/pull/553?

**Comment by jtcreative** [comment]
Why yes! Yes it is! When is this being released?

**Comment by dpogue** [comment]
Should be within the next week. I'm hoping to get it tagged today and posted to the mailing list for voting.

**Comment by jtcreative** [comment]
Nice! Thanks

**Comment by jtcreative** [comment]
@dpogue does that mean that this should be closed?

**Comment by dpogue** [comment]
Yes, cordova-ios@5.0.1 has been released, and should include the fix for this issue. Please let me know if you're still running into problems.
