### ISSUE TITLE
WKWebView CORS support

### ISSUE THREAD

**Issue by gisongeorge** [apache/cordova-ios#605]
Hi, I'm trying to load an HTML that is in the main Bundle with WKWebView this worked perfectly with UIWebView. Now I migrated UIWebView to WJKWebView and I have an error, the files in the HTML does not load send an error in the console: "XMLHttpRequest cannot load"

How I can resolve this problem?

**Comment by vg0x01** [comment]
<plugin name="cordova-plugin-wkwebview-file-xhr" spec="^2.1.1" />

**Comment by vg0x01** [comment]
cordova plugin install cordova-plugin-wkwebview-file-xhr

**Comment by jcesarmobile** [comment]
That’s one of the known WKWebView issues.
Should work once we implement url scheme handlers
https://github.com/apache/cordova-ios/issues/415

In the meantime you can use ionic webview plugin that already have the url scheme handlers implemented or use a plugin like the proposed by vg0x01
