### ISSUE TITLE
UI unusable when app is placed back in foreground

### ISSUE THREAD

**Issue by pbenschop** [apache/cordova-ios#609]
# Bug Report

As of iOS 12.2, our WKWebView-based Cordova app, when placed back in the foreground, no longer responds properly to touch events. The app is still alive (a timed sync of records with the server still works fine) but the UI is no longer useable (the keyboard pops up, for example, when tapping a button). Upgrading to Cordova iOS 5.0.0 made the problem more pronounced i.e. instead of it happening in certain scenarios, it pretty much always happen. The problem does not occur with UIWebView. Could Cordova or any of its plugins be the cause of this problem?

## Checklist
- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Looks like https://github.com/apache/cordova-ios/issues/417

Or could be some plugin resizing the screen internals. Can you provide your plugin list?

**Comment by pbenschop** [comment]
@jcesarmobile Thanks for the suggestion. I tried all the workarounds mentioned in #417 but unfortunately none made a difference. Our plugin list contains pretty much all the standard Cordova plugins that have been shipping with our app for many years.

**Comment by dpogue** [comment]
Are you using an old (or custom) version of something like Fastclick? IIRC there was an issue where event timestamps in WKWebView could get reset when the view was hidden and re-shown, and some libraries that tried to compare event timestamps would get negative numbers and cause all clicks to be ignored.

**Comment by pbenschop** [comment]
Hi @dpogue, thanks so much for trying to help us. We are not using FastClick or anything like it.

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by pbenschop** [comment]
Thanks, @janpio. I did try with a fresh new Cordova app with the same plugin list but that does not show the problem.

**Comment by janpio** [comment]
Ok, thanks for testing that so quickly. That would point to something in your web app causing the problems. 

Another thing to rule out would be interactions betweens plugins and your web app - easiest way to test this would probably be to remove all the installed plugins and see if you still can reproduce the problematic behavior.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
