### ISSUE TITLE
 unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by mluis** [apache/cordova-ios#611]
# Bug Report

## Problem
The application shows a white screen forever.
### What is expected to happen?
Show the contents of index.html

### What does actually happen?
The application's screen keeps white.

## Information

Deployment target set to : 8.0
Deployed on an ios 9.3.5 device.

> 2019-05-06 16:16:21.258 MyApp[1676:707916] CDVWKWebViewEngine: trying to inject XHR polyfill
2019-05-06 16:16:21.274 MyApp[1676:707916] -[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x16e4ccd0
2019-05-06 16:16:21.275 MyApp[1676:707916] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x16e4ccd0'
*** First throw call stack:
(0x21e1b91b 0x215b6e17 0x21e212b5 0x21e1eee1 0x21d4a238 0x4909d 0x498eb 0x617c3 0x60f63 0x61401 0x5ea9d 0x458cf 0x26396d8b 0x26396971 0x2639d639 0x2639ab3d 0x2640fa5d 0x54893 0x456a5 0x2640b785 0x266332d1 0x26637285 0x2664b83d 0x266347b3 0x234bec07 0x234beab9 0x234bedb9 0x21ddddff 0x21ddd9ed 0x21ddbd5b 0x21d2b229 0x21d2b015 0x26404c3d 0x263ff189 0x455a3 0x219d3873)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

### Command or Code

$ ionic start myApp blank --type ionic1
$ ionic cordova platform add ios
$ open platforms/ios/MyApp.xcodeproj/
then choose deployment target 8.0
deploy on a 9.3.5 iOS ipad

### Environment, Platform, Device

9.3.5 iOS ipad

### Version information

$ ionic version
4.10.3

## Checklist

- [x] I searched for existing GitHub issues
- [  ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
> Deployment target set to : 8.0

What does that mean exactly?

**Comment by timbru31** [comment]
Are you using Ionic's WebView plugin? Seems related to the error message
```
2019-05-06 16:16:21.275 MyApp[1676:707916] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x16e4ccd0'
```

e.g.:
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/8
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/16

Please test again without this plugin if this is a cordova-ios issue and not a plugin issue.

**Comment by mluis** [comment]
> > Deployment target set to : 8.0
> 
> What does that mean exactly?

An iOS app has an option to set the minimum iOS supported version by the application you're developing.

On Xcode you have to set the Minimum iOS Version supported by the application. That's the Deployment target.

Please see under General > Deployment Info :
![Screen Shot 2019-05-06 at 17 11 51](https://user-images.githubusercontent.com/162384/57242190-6d82d300-7022-11e9-8198-053c94c45d9e.png)

**Comment by mluis** [comment]
I don't think I could use ionic's without the ionic-webview. Perhaps this issue should be linked to ionic's issues?

Those issues seems related, specially ionic-team/cordova-plugin-ionic-webview#8 although it seems fixed in 2017.

Waiting your suggestions.

Thank you.

> Are you using Ionic's WebView plugin? Seems related to the error message
> 
> ```
> 2019-05-06 16:16:21.275 MyApp[1676:707916] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WKWebViewConfiguration setMediaTypesRequiringUserActionForPlayback:]: unrecognized selector sent to instance 0x16e4ccd0'
> ```
> 
> e.g.:
> [ionic-team/cordova-plugin-ionic-webview#8](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/8)
> [ionic-team/cordova-plugin-ionic-webview#16](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/16)
> 
> Please test again without this plugin if this is a cordova-ios issue and not a plugin issue.

**Comment by dpogue** [comment]
`WKWebViewConfiguration mediaTypesRequiringUserActionForPlayback` only exists in iOS 10.0 and newer according to [Apple's documentation](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1851524-mediatypesrequiringuseractionfor). Trying to call it on iOS 8 or 9 will result in a crash.

Worth noting that the latest version of cordova-ios only supports iOS 10.0 and higher, but it also sounds like this is an Ionic plugin problem rather than a Cordova-iOS issue.

**Comment by janpio** [comment]
> I don't think I could use ionic's without the ionic-webview. Perhaps this issue should be linked to ionic's issues?

Ionic works perfectly fine in UIWebView instead of WKWebView, so you can also use it without that plugin. Performance characteristics might be different though.

But as @dpogue said, targeting iOS 8 is not a great idea.

**Comment by janpio** [comment]
The plugin also has explicit requirement of iOS 11+: https://github.com/ionic-team/cordova-plugin-ionic-webview#plugin-requirements

**Comment by mluis** [comment]
By default the latest versions are downloaded but not all concurrent versions seem to be compatible with each other.

Is there information about which cordova-ios versions are compatible with iOS 9.3.5 ?

Thank you for your support.

**Comment by dpogue** [comment]
cordova-ios @ 4.5.x should be compatible with iOS 9, but you'll also need to confirm that any plugins are also compatible.

**Comment by arjunkalburgi** [comment]
I have: 
```
    "cordova-ios": "5.0.1",
```

@mluis Did you get it to work? I don't have any plugins right now...

**Comment by giacomodeglinnocenti** [comment]
Still having this issue

https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/8
