### ISSUE TITLE
Swift Static Libraries causing build error only with cordova build command (works fine in Xcode UI)

### ISSUE THREAD

**Issue by sachinmobstac** [apache/cordova-ios#617]
# Bug Report

## Problem
Can't compile a project which has Pod distributed as Swift Static Library.
### What is expected to happen?
The Project should compile without any errors
### What does actually happen?
The Project compiles with the below error:
```
<unknown>:0: error: module map file '/Users/sachinvas/Library/Developer/Xcode/DerivedData/MyApp-djlbvgkjcelsaocynsvraskofynn/Build/Products/Debug-iphonesimulator/Starscream/Starscream.modulemap' not found
<unknown>:0: error: module map file '/Users/sachinvas/Library/Developer/Xcode/DerivedData/MyApp-djlbvgkjcelsaocynsvraskofynn/Build/Products/Debug-iphonesimulator/Starscream/Starscream.modulemap' not found
<unknown>:0: error: underlying Objective-C module 'SocketIO' not found
/Users/sachinvas/Projects/Private/myapp/platforms/ios/Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:27:8: error: cannot load underlying module for 'Starscream'
import Starscream
```
## Information
I am trying to run the example app in [here](https://github.com/Beaconstac/cordova-plugin-nearbee).

The `-fmodule-map-file` flag has two different path's

`xcodebuild`
```
-fmodule-map-file=/Users/sachinvas/Library/Developer/Xcode/DerivedData/MyApp-djlbvgkjcelsaocynsvraskofynn/Build/Products/Debug-iphonesimulator/Starscream/Starscream.modulemap
```
`Xcode UI`
```
-fmodule-map-file=/Users/sachinvas/Projects/Private/myapp/platforms/ios/Pods/Headers/Public/Starscream/Starscream.modulemap
```

### Command or Code
```
cordova platforms add ios
cordova build ios (Device Only)
```
### Environment, Platform, Device
iOS 10.0 or higher
iPhone 7

### Version information
cordova-ios 5.0.1
cordova-cli latest

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by sachinmobstac** [comment]
Any updates on this issue?

**Comment by janpio** [comment]
No, as you can see there are not comments or other changes.

Your issue doesn't show any errors in "The Project compiles with the below error:" by the way.

**Comment by sachinmobstac** [comment]
@janpio, Sorry for that. I will add more details. Looks like there is a path issue when using the xcodebuild command vs the Xcode UI. I know Xcode UI uses the xcodebuild command to build the project, however I am not sure why the path gets resolved when using the Xcode UI and throws error when using the xcodebuild command.

**Comment by sachinmobstac** [comment]
@janpio, I have updated the issue which reflects the error which I am facing and added additional information.

**Comment by janpio** [comment]
Thanks, that might give an user or contributor that knows more about Swift/Pods/iOS something to go on.

**Comment by j3k0** [comment]
It's probably due to this CocoaPods bug: https://github.com/CocoaPods/CocoaPods/issues/10675 (which has been sitting there for 1 year, so I'm not sure how long before, or if, it will be fixed...

A workaround would be to run xcodebuild without a `CONFIGURATION_BUILD_DIR`. Would that be possible?

**Comment by breautek** [comment]
> A workaround would be to run xcodebuild without a CONFIGURATION_BUILD_DIR. Would that be possible?

Not sure how far this will get you, or if you can unset `CONFIGURATION_BUILD_DIR`, but you should be able to configure it via `buildFlags` which can set in either [build.json](https://cordova.apache.org/docs/en/11.x/guide/platforms/ios/index.html#using-buildjson) or via [--buildFlag](https://cordova.apache.org/docs/en/11.x/guide/platforms/ios/index.html#xcode-build-flags) CLI argument.

So if something expects a specific build directory, then in theory you should be able to set it to the expected value. I don't know if this will cause any other unwanted side effects however.
