### ISSUE TITLE
ios <<icon> label No other attributes error 

### ISSUE THREAD

**Issue by gaowenzhen** [apache/cordova-ios#623]
Hello, anyone can help me.

I installed 9.0.0 (cordova-lib@9.0.1) under mac os

I am doing the following to create a project

1. Run following commands
```shell
cordova create hello com.example.hello HelloWorld
cd hello
```

2. I have created the directory and files. --icon.png
modify  config.xml 

```xml
<widget>
  .....
  .....
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <icon src="res/icon.png" />
</widget>
```

3. Run following commands
```shell
cordova platform add ios
cordova run ios
```

4. Found icon can't change or default icon

**Comment by jcesarmobile** [comment]
iOS requires different icons with the size attributes, a single icon without attributes is not supported. 
This is a docs problem because [here](https://cordova.apache.org/docs/en/latest/config_ref/images.html) it says a single icon can be used
