### ISSUE TITLE
Not able to browse using file uploader in ios 12.2 using cordova application which is working till version 12.1?

### ISSUE THREAD

**Issue by VamsiKrishna451** [apache/cordova-ios#624]
# Bug Report

## Problem
Not able to browse using file uploader in ios 12.2 using cordova application which is working till version 12.1?

### What is expected to happen?

file uploader should give options to browse and select.

### What does actually happen?
not allowing to browse on click of file uploader.

## Information

from ios 12.2 version file uploader not working in cordova.

### Environment, Platform, Device

ios 12.2,XCODE

## Checklist

- [x] I searched for existing GitHub issues
- [ 
![IMG_20190517_162140](https://user-images.githubusercontent.com/51230491/58695840-f8ea4c80-83b3-11e9-8265-5f25f04c427f.jpg)
![IMG_20190517_162140](https://user-images.githubusercontent.com/51230491/58695875-0dc6e000-83b4-11e9-9635-14b6c31a1772.jpg)

] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
I suppose you mean input with type file.
In that case it's an Apple bug and it works fine again on 12.3 and newer, so looks like they fixed it

**Comment by VamsiKrishna451** [comment]
Hii Thanks for the update but it is still the same in 12.3.1 also.
Any help regarding this very appreciable.

Thank You.
