### ISSUE TITLE
I have uploaded app using xcode  but still i am not able to submit for review.

### ISSUE THREAD

**Issue by Ramesh23iphone** [apache/cordova-ios#627]
<img width="1148" alt="Screenshot 2019-06-07 at 8 10 18 PM" src="https://user-images.githubusercontent.com/32629390/59112285-55bfa700-8960-11e9-913b-141e515bd26d.png">

**Comment by timbru31** [comment]
Processing takes some time until you can submit it for a review (you should get an email). This has nothing to do with Cordova anymore. ;)
