### ISSUE TITLE
Support for Dark Mode iOS

### ISSUE THREAD

**Issue by Ebrahim-Merchant** [apache/cordova-ios#629]
I was wondering if Cordova would support the new iOS Dark Mode? If it does how do we currently know that the system has dark mode activated?

**Comment by dpogue** [comment]
You should be able to do this entirely in CSS using `@media (prefers-color-scheme: dark)`.
For more information, see https://webkit.org/blog/8840/dark-mode-support-in-webkit/

**Comment by dlee** [comment]
the webview in cordova doesn't seem to support `@media (prefers-color-scheme: dark)`. Testing the app in Safari properly reflects dark mode, but once the app is built in cordova, the media query doesn't seem to be kicking.

**Comment by dpogue** [comment]
I believe you need to build the app with Xcode 11 for it to support the dark mode media queries.

**Comment by GeorgeD19** [comment]
If you wish to influence your app programmatically you can use something like:

`var isDarkMode = window.matchMedia('(prefers-color-scheme:dark)');`

**Comment by uandco** [comment]
`@media (prefers-color-scheme: dark` works a treat but the overscroll colour remains white (or per your preference's `BackgroundColor` value). Is there any simple way to make that dynamic, apart from patching `CDVViewController.m`?

**Comment by Thul999** [comment]
> the webview in cordova doesn't seem to support `@media (prefers-color-scheme: dark)`. Testing the app in Safari properly reflects dark mode, but once the app is built in cordova, the media query doesn't seem to be kicking.

Were you able to solve the issue? I'm having the same problem using WKWebview and the media query doesn't trigger.

**Comment by StefanRein** [comment]
@Thul999 Could it be you have set anywhere the following setting `UIUserInterfaceStyle` in the **config.xml** or manually in Xcode? Then the CSS / Media Queries (also JS!) will always return the value there.

Which in my case was:

```xml
<config-file parent="UIUserInterfaceStyle" platform="ios" target="*-Info.plist">
    <string>Light</string>
</config-file>
```

See also following post with a screenshot:
https://github.com/mariusbackes/cordova-plugin-theme-detection/issues/3#issuecomment-561969305
