### ISSUE TITLE
"onReset" not called when page reload on ios12

### ISSUE THREAD

**Issue by lvyou214** [apache/cordova-ios#630]
# Bug Report

## Problem
When load a new page,  plugin function 'onReset' are not called when cordova-ios 5.0.1 on ios 12.x
### What is expected to happen?
'onReset' should be called.

### What does actually happen?
'onReset' is not called.

## Information

This may has something to do with #447 
When I use cordova-ios 5.0.1, I found that when I do page navigation or just do page refresh, the plugin function 'onReset' is not called. 
When I switch back to 5.0.0, everything is fine.
Here is the result table I tested:

 version | 11.2.6(Device) | 12.2(Simulator) | 12.3.1(Device)
------------ | ------------- | ------------- | -------------
5.0.0 | OK | OK | OK
5.0.1 | OK | FAILED | FAILED

Then I try to revert just #477 modification on 5.0.1 and confirmed that the 'onReset' is called as it should be.

### Command or Code

Just create an empty project ,add cordova-ios@5.0.1  then add an plugin that has 'onReset' callback (ex:cordova-plugin-statusbar).
Start xcode,build and run project with debugging.
Set a breakpoint on 'onReset'.
Use safari to refresh the default page to observe if the breakpoint hit.

### Version information

Cordova 9.0.0 (cordova-lib@9.0.1)
cordova-ios@5.0.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by bentomas** [comment]
This is effecting us as well.  Sometimes `onReset` gets called, sometimes not.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
