### ISSUE TITLE
IOS app crashes on multiple upload of files

### ISSUE THREAD

**Issue by mehthabt** [apache/cordova-ios#634]
IOS app crashes when uploading multiple file(especially those captured in iOS camera).
---

i created the Cordova project using

-Reactjs and Redux

-Axios for server calls

the App crashes when there is too much to sent to server side.for eg: App crashed when i upload more than 10 photos at time, but wont have any issue when uploading less than 8 photos.

in Xcode its showing there is a memory pressure and app gets crashed.

So i don't know how to debug this, tried to cut down memory leak by reducing the loops.

but still no hope

has anyone had the same issue or do you guys know how to solve it?

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by jcesarmobile** [comment]
how are you uploading the photos? a plugin? a form POST? POST of the base64 representation of the photo?

**Comment by pynner** [comment]
@mehthabt ever find a solution?

**Comment by jcesarmobile** [comment]
Closing as the reporter didn't answer to the questions
