### ISSUE TITLE
"cordova run" get "NameError: name 'run_one_line' is not defined "

### ISSUE THREAD

**Issue by chunjil** [apache/cordova-ios#636]
NameError: name 'run_one_line' is not defined
error: python failed attempting to evaluate 'fruitstrap_device_app="/private/var/containers/Bundle/Application/**/**.app"'

Please.Thx~

**Comment by GedasGa** [comment]
I suspect it's an issue with your development environment. I think it might be related to how you installed `python` and probably related to module`six` import error.

 Please, next time, include a more detailed description and steps needed to reproduce an issue.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date Xcode version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
