### ISSUE TITLE
loading page white screen

### ISSUE THREAD

**Issue by CrazyRoy** [apache/cordova-ios#638]
# Bug Report

### What is expected to happen?

Normal display

### What does actually happen?

white screen

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by janpio** [comment]
What is a "H5 page"?
What does "all other open pages" refer to?
Can you show us some screenshots and/or code of what you are seeing and doing?

**Comment by CrazyRoy** [comment]
Is to use cordova to load a web page, the web is redirected to another url by js, and then all the web pages are blank after exiting cordova. Is the lock after the redirect not released?

**Comment by janpio** [comment]
Please answer my questions instead of telling me other things and asking new questions. I have to understand what you are asking first before I can try to help.

**Comment by CrazyRoy** [comment]
Hello, I am very sorry that I can't express it clearly. The process is like this, start to open a web page A that does not redirect, the display is normal, then return to a web page B that re-opens a js code to control the redirect, and then return to open before A or all web pages are blank. The status may be caused by the processing of the redirect? The code is the normal setting cordova's startpage into the web page.

**Comment by janpio** [comment]
I think it would be easiest if you create a quick test app with `cordova create`, implement what you describe, and put it on Github. Here are some instructions: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md This way we can just try what you are describing and experience it ourselves.

**Comment by CrazyRoy** [comment]
Thank you, for your suggestion, I created a demo, please help review the problem.
The Reproduct demo project address : [CordovaReproduct](https://github.com/CrazyRoy/CordovaReproduct)

**Comment by janpio** [comment]
Unfortunately I can't see from the commit history what the changes are you did to the original, unchanged project. Also `www` seems to be missing an `index.html`, so this project should never work at all.

**Comment by CrazyRoy** [comment]
Oh no, 
The project is uploaded after I modified it locally. The rootViewController is a CDVViewController, and it can be run for the assignment of startPage. It is only a few restarts and sometimes it will be white screen, and I will not call the method I wrote in the self-report README.md.

**Comment by CrazyRoy** [comment]
I have provided recorded recurring question videos and pictures.
https://github.com/CrazyRoy/CordovaReproduct/blob/master/HD-Recurring-video.mp4 and https://github.com/CrazyRoy/CordovaReproduct/blob/master/afterLongTime.jpg

**Comment by CrazyRoy** [comment]
Sometimes it takes a long time for a white screen to show the content. At this time, the log output is as follows: 
Task <43DF4949-60E5-4C5A-8F85-39BB9431BD1C>.<0> HTTP load failed (error code: -1005 [4:-4]).
NSURLConnection finished with error - code -1005.
Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)
Finished load of: xxx.html.

The point is that the screen will be white for a long time !!!
Ask for help !!! 
thanks very much.

**Comment by shiqian123** [comment]
> 有时，白屏需要很长时间才能显示内容。此时，日志输出如下：
> 任务<43DF4949-60E5-4C5A-8F85-39BB9431BD1C>。<0> HTTP加载失败（错误代码：-1005 [4：-4]）。
> NSURLConnection完成，错误-代码-1005。
> 加载网页失败，出现错误：操作无法完成。（NSURLErrorDomain错误-999。）
> 完成以下项的加载：xxx.html。
> 
> 关键是屏幕将长时间保持白色！！！
> 请求帮忙 ！！！
> 非常感谢。

Have you solved him? I have this problem, too

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
