### ISSUE TITLE
UIWebView listening canGoBack

### ISSUE THREAD

**Issue by CrazyRoy** [apache/cordova-ios#640]
Cordova UIWebView listening for canGoBack attributes listening for KVO is invalid. What is the solution?

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
