### ISSUE TITLE
Build fails with Xcode 10.3 and iOS target

### ISSUE THREAD

**Issue by alextkd** [apache/cordova-ios#652]
# Bug Report
```
The following build commands failed:
	CompileXIB MyProject/Classes/MainViewController.xib
(1 failure)
CordovaError: Promise rejected with non-error: 'Error code 65 for command: xcodebuild with args: -xcconfig,/Users/alexandrulazar/MyProject/platforms/ios/cordova/build-debug.xcconfig,-workspace,MyProject.xcworkspace,-scheme,MyProject,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,MyProject.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/alexandrulazar/MyProject/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/alexandrulazar/MyProject/platforms/ios/build/sharedpch,-UseModernBuildSystem=0,EMBEDDED_CONTENT_CONTAINS_SWIFT = YES,ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO,LD_RUNPATH_SEARCH_PATHS = "@executable_path/Frameworks"'
    at cli.catch.err (/Users/alexandrulazar/.nvm/versions/node/v10.13.0/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```

## Problem

Doesn't build

**Comment by janpio** [comment]
What is the bug? This looks like a failed build, because any of many reasons. Please post the complete build output and fill the issue template instead of deleting it. We need that information.

**Comment by guanxun14** [comment]
Getting the exact same here, agree that the failure to build is very abrupt. As far as I can tell, there is no other information to glean from the failed logs which might provide clues. Attempting to rollback to 10.2 now to see if that works.

Xcode 10.3 [release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_3_release_notes?language=objc) don't seem to show that anything should break though.

**Comment by codinronan** [comment]
@janpio Just upgraded Xcode and got this too. The actual error is:

```
<my app filepath>platforms/ios/Rolamix/Classes/MainViewController.xib:-1: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7fc7ab7860e0> System content for IBCocoaTouchFramework-NineOneAndLater <IBScaleFactorDeviceTypeDescription: 0x7fc7ab786530> scaleFactor=2x'. These intermediate objects were non-nil: (
```

Looks like something for iOS 9.1 has been removed from Xcode and is causing the MainViewController.xib to fail the build.

**Comment by alextkd** [comment]
If I try to upgrade the MainViewController.xib that doesn't work either. I'm prompted with this:
![image](https://user-images.githubusercontent.com/373321/61727465-19170600-ad7c-11e9-8f07-3bfdc256df72.png)

**Comment by alextkd** [comment]
Guys I was able to get over this if I ran this in the console `sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService`

**Comment by codinronan** [comment]
Can confirm, @alextkd's fix worked. Make sure Xcode is closed when you do this.

**Comment by ConsiderCode** [comment]
Had this exact same issue. This morning I was prompted to update Xcode. Once update, I noticed that my simulators were missing. I restarted my computer and retrieved my simulators. Then I had to update my mac to Mojave version 10.14.6 and update my iPhone to iOS 12.4. After that I upgraded npm and cordova (not sure if there was another version). I removed the ios platform from my cordova project and re-added it (I believe it was 5.0.0). After doing all of that I was able to get rid of this error. 

I don't know how much of that was necessary but I'm sure if you update everything you own and use everything should be fine. Fingers crossed for iOS 13.

**Comment by codinronan** [comment]
Confirming that a reboot, Mojave version 10.14.6 and updating your iPhone are not necessary.

All that was necessary is this command. https://github.com/apache/cordova-ios/issues/652#issuecomment-514284852

Both my updates are still outstanding, haven't rebooted my mac in weeks and simulators (and device) build and work without issue.

**Comment by frankvazk** [comment]
Confirm @alextkd's fix worked. Thank you my friend!!!

**Comment by frankvazk** [comment]
> Guys I was able to get over this if I ran this in the console `sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService`

Confirm @alextkd's fix worked. Thank you my friend!!!

**Comment by driiftkiing** [comment]
> Guys I was able to get over this if I ran this in the console `sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService`

And do a reboot :)

**Comment by jay34fr** [comment]
Thx a lot for the command line, it works !!!! You saved my life !!!

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date Xcode version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
