### ISSUE TITLE
build/device folder contains invalid symbolic links

### ISSUE THREAD

**Issue by nsteenbeek** [apache/cordova-ios#654]
# Bug Report
Build/device folder contains invalid symbolic link to .app file (which seems to be removed during build process).

## Problem
Wrong symbolic link is not nice and seems easily to fix during deletion of the .app file during build process. Problem seems to be small, but folder can't be deleted using DevOps in my case.

### What is expected to happen?
Instead of only remove the .app file, also remove corresponding symbolic link file

### What does actually happen?
Symbolic link file stays in device folder and gives delete problems (in DevOps in my case)

### Command or Code
cordova build ios --device --debug

### Environment, Platform, Device
MacOS Mojave 10.14.2

### Version information
What are relevant versions you are using?
Cordova: Cordova CLI 

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date Xcode version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
