### ISSUE TITLE
App freezes after LinkedIn login

### ISSUE THREAD

**Issue by amiralgazi** [apache/cordova-ios#655]
Hello,

I am using Cordova v8.1.1 and I have an issue every first installation of my app.
The app freezes after the credentials page of LinkedIn is closed.
When I close the app and open again, LinkedIn login process works good

Any idea why this happens?

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
