### ISSUE TITLE
iOS platform install errors from config

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-ios#656]
# Bug Report

## Problem
iOS platform install plugins errors when adding plugins to xml

### Command or Code
1- cordova create test com.test.app
2- Add a bunch of plugins to config.xml such as

```
    <plugin name="cordova-plugin-whitelist" spec="^1.3.4" />
    <plugin name="cordova-plugin-device" spec="^2.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.3" />
    <plugin name="cordova-plugin-file" spec="^6.0.2" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.2" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.2" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.1.0" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.3" />
    <plugin name="cordova-plugin-camera" spec="^4.1.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="23.+" />
    </plugin>
```

3- cordova plaform add ios@latest
4- all plugins installation fail

> Plugin '[plugin_name]' found in config.xml '... Migrating to package.json
> discovered plugin [plugin_name]. adding it to the project'
> installing  [plugin_name] for ios
> Failed to install '[plugin_name]' : Error: Cannot find module 'glob' (or) 'superspawn'

5- cordova platform rm ios
6- cordova plaform add ios@latest (this time it works, no plugin error)

You can also at this point add more plugins to config.xml and do` cordova prepare ios` and you will be back at 4.

### Environment, Platform, Device
Cordova 9 (lib 9.0.1)
iOS 5.0.1
npm 6.10.3
node 10.15.3
Mac OS Catalina 10.15b
iPhone 6S + iOS 12.4
npm cache verify : ok

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by JesseNaranjo** [comment]
Hi @globules-io - I am running into this same exact issue. You closed this, so I can only hope (assume) that you found a solution.

Would you be able to share your resolution, please?

Thanks!

**Comment by globules-io** [comment]
@JesseNaranjo "solved" by deleting node_modules, platform and plugins folders, deleted package and package lock. Then cordova platform add ios might work.

**Comment by newuser44** [comment]
delete package seems to cause more issues.
