### ISSUE TITLE
iOS watch icons generated without 44mm

### ISSUE THREAD

**Issue by godexsoft** [apache/cordova-ios#657]
# Bug Report
When i add my 100x100 icon for 44mm watch the icon is not used

## Problem
If i want to support 44mm watch icon it appears to not be possible

### What is expected to happen?
Icons in AppIcon.appiconset should be generated correctly with all watch icons covered

### What does actually happen?
All watch icon slots are filled in but the 44mm one

## Information
I don't actually need to have watch icons at all. just thought i would let you know it's broken

### Command or Code
-

### Environment, Platform, Device
macosx

### Version information
cordova 9.0.1, cordova-ios 5.0.1

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by godexsoft** [comment]
My bad. was actually referring to the 108x108 @x2 icon.. i was providing 100x100 looking in the wrong place. I now provide 216x216 icon but it still does not appear. It's the QuickLook icon for 44mm watch. If i inspect the generated AppIcon Contents.json the item is there but it got no filepath, hence it's empty in Xcode.

**Comment by dakotaJang** [comment]
It appears that this icon has not been configured at all.
I noticed that the icons get the default corodva icons when they are not configured but this 44mm 2x icon (216 x 216px) does not get any icon.
This part needs to be manually in Resources>Images.xcassets>AppIcon at the moment as far as I can tell.
![image](https://user-images.githubusercontent.com/22528264/72182299-092dc580-33a0-11ea-8383-1634d8b5d95b.png)

**Comment by HansKrywaa** [comment]
As you can see [here](https://github.com/apache/cordova-ios/blob/59d0dd712ff362e5165ce9a50f078425f83e637d/bin/templates/project/__PROJECT_NAME__/Images.xcassets/AppIcon.appiconset/Contents.json#L224) the filename is missing for this, so it can't be set automatically. But i don't know why...
