### ISSUE TITLE
How can I add the lib which the version greater than 4.5.4 

### ISSUE THREAD

**Issue by Ryan0520** [apache/cordova-ios#660]
# Feature Request

## Motivation Behind Feature

I can not found the version greater than 4.5.4 by cocoapods, how can I add the newest version to my podfile?

**Comment by jcesarmobile** [comment]
We don't really do the CocoaPods publishing, check the authors on the CocoaPods website and try to contact them.

**Comment by emanuelandrada** [comment]
@Ryan0520 Have you been able to contact the pod's authors?
