### ISSUE TITLE
Random app crash in iOS 12.4 on iPad

### ISSUE THREAD

**Issue by Wallethub** [apache/cordova-ios#665]
Hello,

In our production app, we see random app crashes in iOS 12.4 on the iPad. They are very rare, but the pattern remains consistent and the stack trace is always like so :

<img width="898" alt="Screen Shot 2019-09-07 at 3 22 18 AM" src="https://user-images.githubusercontent.com/20915786/64467251-a2fa1300-d11f-11e9-9146-9c124366305f.png">

Is there any way to determine the cause and possibly fix it?
There is no alteration done to main.m so the starting point is :
```Objective-C
int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate");
```

**Comment by janpio** [comment]
What is displaying native UIPopover in your app? That's where I would start looking into plugins and other customizations - afaik there is nothing that does this in `cordova-ios` itself.

**Comment by pitAlex** [comment]
We can close this issue. The problem comes from an extension we use called 1passwordextension. We figured it out.
