### ISSUE TITLE
Touch events are less responsive with iOS 13.1

### ISSUE THREAD

**Issue by gabrielprzb** [apache/cordova-ios#666]
# Bug Report

## Problem
Touch events respond less effectively on iOS 13.1, immediately after finishing scrolling, something that did not happen with previous versions of iOS. The user must wait between 0.5-1 seconds after scrolling for a touch event to emit.

### What is expected to happen?
Touch events should fire immediately after finishing scrolling.

### What does actually happen?
Touch events fire 0.5-1 sec after finishing scrolling.

### Environment, Platform, Device
ionic, Angular, ios13

### Version information

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.803.3
   @angular-devkit/schematics    : 8.3.3
   @angular/cli                  : 8.3.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 7.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 17 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.10.0 (/usr/local/Cellar/node/10.10.0/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
```

## Checklist

- [X ] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by dpogue** [comment]
This sounds like an iOS 13 bug that should be reported to Apple. Cordova has no control over the behaviour of touch events.
