### ISSUE TITLE
UIApplicationExitsOnSuspend deprecation in iOS 13

### ISSUE THREAD

**Issue by chawax** [apache/cordova-ios#667]
Hello,

iOS 13 changelog tells about deprecation of `UIApplicationExitsOnSuspend` :

https://developer.apple.com/documentation/ios_ipados_release_notes/ios_ipados_13_beta_8_release_notes

> The UIApplicationExitsOnSuspend key is no longer supported in iOS & iPadOS 13. Update your apps to handle modern multitasking. (43958234)

But it is still used in some Cordova iOS files : `CDVLocalStorage.m` and `CVDViewController.

I saw no problems for the moment using my apps on iOS 13 emulators, so should we care about this ?

**Comment by jcesarmobile** [comment]
The value is only read in case it’s there, but cordova apps don’t have it by default. So this is not an issue.
