### ISSUE TITLE
iOS 13 - Bluetooth keyboard arrow keys not working

### ISSUE THREAD

**Issue by frenmanoj** [apache/cordova-ios#669]
# Bug Report

## Problem

The arrow keys (UP, DOWN, LEFT, RIGHT) of the external bluetooth keyboard do not work in iOS 13. It was working fine in earlier versions.  Other keys are working fine. 

Note that, the arrow keys work fine in other iOS native apps.

### What is expected to happen?
The Arrow keys of the external keyboard should work fine.

### What does actually happen?
The Arrow keys of the external keyboard are not working.

## Information

I see the following console error in Xcode when I press one of the arrow keys.

```
2019-09-17 16:06:08.114428-0500 My_APP_NAME[375:30929] -[UIThreadSafeNode canPerformAction:withSender:]: unrecognized selector sent to instance 0x283523040
2019-09-17 16:06:08.115002-0500 My_APP_NAME[375:30929] *** WebKit discarded an uncaught exception in the handleKeyTextCommandForCurrentEvent delegate: <NSInvalidArgumentException> -[UIThreadSafeNode canPerformAction:withSender:]: unrecognized selector sent to instance 0x283523040
```

### Environment, Platform, Device

   Cordova : **9.0.0**
   Xcode    : **11.0**
   iPad        : **iOS 13.1**     
   NodeJS : **v10.14.2**
   npm       : **6.4.1**
   OS          : **macOS Mojave**

**Comment by dpogue** [comment]
This sounds like an issue outside the scope of Cordova. Please file a bug report with Apple.

**Comment by harshith7823** [comment]
Does this project use UIWebView? I'm seeing a similar issue on my UIWebView app. Replacing UIWebView with WKWebView seems to solve the issue.

**Comment by breautek** [comment]
> Does this project use UIWebView? I'm seeing a similar issue on my UIWebView app. Replacing UIWebView with WKWebView seems to solve the issue.

The default webview for `cordova-ios` is the `UIWebView`. `WKWebView` will be the new default sometime soon since `UIWebView` is deprecated.

**Comment by frenmanoj** [comment]
@harshith7823 , yes, the issue exists only with the UIWebView. I just updated the note section.

**Comment by shortercode** [comment]
I appear to also be having this issue with WKWebView on ipados 13.2.3. Confirmed that it was WKWebView using the "debug view hierarchy" tool in xcode.

Did anyone file a report about this with Apple?
