### ISSUE TITLE
ITMS-90809: UIWebView API Deprecation

### ISSUE THREAD

**Issue by Sagarkhenat** [apache/cordova-ios#670]
After uploading our ionic app to apple,we got the following error message:
We identified one or more issues with a recent delivery for your app, [App Name & version number]. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage – Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

So, the apple team wants to remove all the references to UIWebView in their plugins code or hey will always issue a warning,as currently it still accepts the apps submitted.They might change the behavior in near future. We are currently using cordova-ios and cordova ionic in app browser plugin in our app.

**Comment by erisu** [comment]
Closing as duplication.
https://github.com/apache/cordova-ios/issues/661
https://github.com/apache/cordova-discuss/pull/110
