### ISSUE TITLE
Can't build carthage

### ISSUE THREAD

**Issue by Skorpeo** [apache/cordova-ios#672]
# Bug Report

## Problem
I am following instructions on embedding webview in carthage: https://cordova.apache.org/docs/en/latest/guide/platforms/ios/webview.html

I get error dyld: Library not loaded: /Library/Frameworks/Cordova.framework/Cordova
 Referenced from:....
 Reason: image not found

### What is expected to happen?
It should build

### What does actually happen?

I get error dyld: Library not loaded: /Library/Frameworks/Cordova.framework/Cordova
 Referenced from:....
 Reason: image not found

### Command or Code

Following carthage instructions from readme: https://github.com/Carthage/Carthage#getting-started

Cartfile: github "apache/cordova-ios" == 5.0.0
input.xcfilelist: $(SRCROOT)/Carthage/Build/iOS/Cordova.framework
output.xcfilelist: $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Cordova.framework

### Environment, Platform, Device

Xcode 10.1
Cordova 5.0.0
Carthage 0.33.0

Tried both new and legacy build system
## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date Xcode version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
