### ISSUE TITLE
cordova build command tries to run app when a device is connected

### ISSUE THREAD

**Issue by chawax** [apache/cordova-ios#677]
When I have a iPhone device connected to my desktop and I run `cordova build ios` command, it tries to run the app on device while it should just build the application.

So I have an error message because `ios-deploy` is not installed on my desktop.

```
[Error] Error: Command failed: cordova build --buildFlag='-UseModernBuildSystem=0' ios
CordovaError: Promise rejected with non-error: 'ios-deploy was not found. Please download, build and install version 1.9.2 or greater from https://github.com/ios-control/ios-deploy into your path, or do \'npm install -g ios-deploy\''
    at cli.catch.err (/Users/othierry/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/bin/cordova:29:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

I use Cordova 9 with Cordova iOS platform 5.0.1.

I had not this problem with previous Cordova releases.

**Comment by brodybits** [comment]
Correction: cordova-ios checks for `ios-deploy` tool during build stage

I am adding the **help wanted** label. Maintainers are pretty overloaded and busy with work on major release updates. Maintainers are almost or completely 100% unpaid volunteers.
