### ISSUE TITLE
Binary make use of malloc Function

### ISSUE THREAD

**Issue by oxr463** [apache/cordova-ios#679]
# Bug Report

Cordova iOS Applications scanned with [MobSF](https://github.com/MobSF/Mobile-Security-Framework-MobSF) report use of unsafe `malloc` function, (See also: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/372).

## Problem

See: [CWE-789: Uncontrolled Memory Allocation](https://cwe.mitre.org/data/definitions/789.html)

### What is expected to happen?

Memory should be allocated via `calloc`.

### What does actually happen?

Memory is allocated via unsafe `malloc`.

## Information

See below.

### Command or Code

Searching the repository leads me to the following line of code:

```
Byte* buffer = (Byte*)malloc((unsigned long)[assetRepresentation size]);
```

Source: https://github.com/apache/cordova-ios/blob/46da4bc34495ec7bfe13c1ec1b4074dd2e82641a/CordovaLib/Classes/Public/CDVURLProtocol.m#L65

### Environment, Platform, Device

iOS

### Version information

Cordova

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jd048** [comment]
I am facing same issue with latest iOS cordova project, can any one give me solution for same 
Thanks

**Comment by brodybits** [comment]
I am sorry but this really looks like a false positive to me. I am becoming increasingly suspicious of the many code scanning tools that assert this kind of message without sufficient analysis to back it up. See this reply on a SQLite thread: http://sqlite.1065341.n5.nabble.com/Coding-standard-tc109945.html#a109956

This kind of report diverts time and attention away from important issues that we **do** need to resolve.

I did take a look at how the code in PR #7741 is using ALAssetLibrary and would say we can expect it to go away once we drop UIWebView support: #551

**Comment by oxr463** [comment]
> I am sorry but this really looks like a false positive to me. I am becoming increasingly suspicious of the many code scanning tools that assert this kind of message without sufficient analysis to back it up. 

In my experience, many of these tools are not sophisticated enough to determine how `malloc` is being used, just that it is present. However, after examining the code for myself this looks to be a trivial fix; whether or not it is a false positive, there is no detriment by switching to `calloc`, and this is better than trying to patch dozens of tools, some of which are proprietary in nature.

> This kind of report diverts time and attention away from important issues that we do need to resolve.

Hence my creation of a PR to address said issue. I would also argue that I probably wouldn't have contributed to this project if not for seeing this issue in my work, so in a way these tools are helping you.

**Comment by breautek** [comment]
> there is no detriment by switching to calloc

I don't have the experience with this code base to say exactly how significant this is, but `calloc` is slower. Because `calloc` zero-fills the allocated memory first, which you then overwrite a second time. 

This is why @brodybits says it's not necessary to use `calloc` over `malloc` because we allocate memory and immediately write to it completely.

If this API is not invoked very often then obviously the consequence of this would be negligible, but if it is a high traffic API, then the performance hit could be noticeable.

**Comment by dpogue** [comment]
CDVURLProtocol has been removed on master as part of dropping UIWebView support, so this issue no longer applies.
