### ISSUE TITLE
My App is getting stuck on Splash Screen in iOS 13

### ISSUE THREAD

**Issue by eaglesiar** [apache/cordova-ios#680]
# Bug Report

## Problem

Ionic cordova App is working fine with iOS< 13 and all the androids. But after updating to iOS 13, It is getting stuck at splash screen.

Here is the list of plugins.

## Information

cordova-background-geolocation-lt 2.9.1 "BackgroundGeolocation"
 cordova-custom-config 4.0.2 "cordova-custom-config"
 cordova-plugin-actionsheet 2.3.3 "ActionSheet"
 cordova-plugin-app-event 1.2.1 "Application Events"
 cordova-plugin-app-version 0.1.9 "AppVersion"
 cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
 cordova-plugin-badge 0.8.8 "Badge"
 cordova-plugin-camera 3.0.0 "Camera"
 cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
 cordova-plugin-device 1.1.7 "Device"
 cordova-plugin-dialogs 2.0.1 "Notification"
 cordova-plugin-geolocation 4.0.1 "Geolocation"
 cordova-plugin-ionic-webview 4.1.2 "cordova-plugin-ionic-webview"
 cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
 cordova-plugin-network-information 1.3.4 "Network Information"
 cordova-plugin-splashscreen 4.1.0 "Splashscreen"
 cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
 cordova-plugin-statusbar 2.3.0 "StatusBar"
 cordova-plugin-whitelist 1.3.3 "Whitelist"
 cordova.plugins.diagnostic 4.0.12 "Diagnostic"
 ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
 ionic-plugin-keyboard 2.2.1 "Keyboard"
 phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"
 phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
 uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
### Version information

Ionic 3.20.0
Cordova 8.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Can you provide your `cordova-ios` platform version? (`cordova platform ls` will show this information)

Also can you use the safari web developer tools, are there any javascript errors?

**Comment by dsullivan-creare** [comment]
Just chiming in that this is occurring for me, too. Here is some info:

`cordova plugin ls`:
```bash
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-ble-central 1.2.2 "BLE"
cordova-plugin-bluetooth-serial 0.4.7 "Bluetooth Serial"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-creare-sensors 0.3.4 "Sensors"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-media 5.0.4-dev "Media"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
cordova-sqlite-storage 3.3.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
```
`cordova platform ls`:
```bash
Installed platforms:
  android 8.0.0
  ios 5.0.1
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0
```
`Some ionic info:
```bash
Ionic:

   Ionic CLI                     : 5.4.1
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : 0.803.5
   @angular-devkit/schematics    : 8.3.5
   @angular/cli                  : 8.3.5
   @ionic/angular-toolkit        : 2.0.0

Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
```

**Comment by eaglesiar** [comment]
> Can you provide your `cordova-ios` platform version? (`cordova platform ls` will show this information)
> 
> Also can you use the safari web developer tools, are there any javascript errors?

    "cordova-ios": "5.0.0"
error: 
Error: Uncaught (in promise): Error: Invalid Adapter: websql
PouchDB@http://localhost:8080/Users/dhsingh/Library/Developer/CoreSimulator/Devices/BDE5A939-CD69-4186-B581-6222ADEB1782/data/Containers/Bundle/Application/DE067ED9-C925-4075-AE55-A94D9C2C9AAD/TMS%20Mobile.app/www/build/vendor.js:86083:20
http://localhost:8080/Users/dhsingh/Library/Developer/CoreSimulator/Devices/BDE5A939-CD69-4186-B581-6222ADEB1782/data/Containers/Bundle/Application/DE067ED9-C925-4075-AE55-A94D9C2C9AAD/TMS%20Mobile.app/www/build/main.js:3043:65
Storage@http://localhost:8080/Users/dhsingh/Library/Developer/CoreSimulator/Devices/BDE5A939-CD69-4186-B581-6222ADEB1782/data/Containers/Bundle/Application/DE067ED9-C925-4075-AE55-A94D9C2C9AAD/TMS%20Mobile.app/www/build/main.js:3035:22
DocStorage@http://localhost:8080/Users/dhsingh/Library/Developer/CoreSimulator/Devices/BDE5A939-CD69-4186-B581-6222ADEB1782/data/Containers/Bundle/Application/DE067ED9-C925-4075-AE55-A94D9C2C9AAD/TMS%20Mobile.app/www/build/main.js:3186:32
LogStorage@http://localhost:8080/Users/dhsingh/Library/Developer/CoreSimulator/Devices/BDE5A939-CD69-4186-B581-6222ADEB1782/data/Containers/Bundle/Application/DE067ED9-C925-4075-AE55-A94D9C2C9AAD/TMS%20Mobile.app/www/build/main.js:7796:32
http://localhost:8080/Users/dhsingh/Library/Developer/CoreSimulator/Devices/BDE5A939-CD69-4186-B581-6222ADEB1782/data/Containers/Bundle/Application/DE067ED9-C925-4075-AE55-A94D9C2C9AAD/TMS%20Mobile.app/www/build/main.js:11992:106

**Comment by eaglesiar** [comment]
I found the problem with my code. I was using websql adopter in pouchdb.

      new PouchDB("name of the db", {adapter: 'websql'}):
Turns out, Apple discontinued the support for WebSQL in Progressive Web Apps. So instead of using websql, I'm using cordova-sqlite. This solves my problem.

      PouchDB.plugin(require('pouchdb-adapter-cordova-sqlite'));

      new PouchDB("name of the db", {adapter: 'cordova-sqlite'}):

**Comment by breautek** [comment]
Glad you found a solution.

For reference if anyone is curious here is where Apple stated that `websql` is removed on their [Release Notes](https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes)

**Comment by dsullivan-creare** [comment]
Note: our app was hanging because iOS 13 loads our services at a different rate and/or in a different order, which exposed a bug in our code. One of our services was trying to initialize the SQLite database before the platform was ready.

**Comment by daveshirman** [comment]
I've been having this problem too this last week.  It turned out to be that my app didn't have bluetooth permission, despite never needing it.

I had to add `NSBluetoothAlwaysUsageDescription ` to my config.xml file in the ios section:

```
        <config-file parent="NSBluetoothAlwaysUsageDescription" platform="ios" target="*-Info.plist">
            <string>Some reason that apple will accept here, not just anything!</string>
        </config-file>
```

D

**Comment by cgs** [comment]
Had the same problem and in my case it was cordova-plugin-google-analytics. In my init code I was trying to initialize that plugin which was failing due to that version of GA being deprecated.
