### ISSUE TITLE
Add iPhone XR & iPhone XS Max splashscreens

### ISSUE THREAD

**Issue by mobidev111** [apache/cordova-ios#681]
# Bug Report

### What is expected to happen?
iPhone XR & iPhone XS Max splashscreens do get copied over if specified in config.xml

### What does actually happen?
Images don't get copied

root cause: prepare.js doesn't include the new splash screen dimensions

### Extend prepare.js
`https://github.com/apache/cordova-ios/blob/master/bin/templates/scripts/cordova/lib/prepare.js#L428`

```javascript
-        { dest: 'Default-Landscape-2436h.png', width: 2436, height: 1125 }
+        { dest: 'Default-Landscape-2436h.png', width: 2436, height: 1125 },
+        { dest: 'Default-1792h.png', width: 828, height: 1792 },
+        { dest: 'Default-Landscape-1792h.png', width: 1792, height: 828 },
+        { dest: 'Default-2688h.png', width: 1242, height: 2688 },
+        { dest: 'Default-Landscape-2688h.png', width: 2688, height: 1242 }
```

### Extend config.xml
```xml
+        <splash height="828" src="res/screen/ios/Default-Landscape-1792h.png" width="1792" />
+        <splash height="1792" src="res/screen/ios/Default-1792h.png" width="828" />
+        <splash height="2688" src="res/screen/ios/Default-2688h.png" width="1242" />
+        <splash height="1242" src="res/screen/ios/Default-Landscape-2688h.png" width="2688" />
```

### In the generated project: Extend Contents.json
platforms/ios/AirSec/Images.xcassets/LaunchImage.launchimage/Contents.json

```json
{
      "orientation": "portrait",
      "idiom": "iphone",
      "extent": "full-screen",
      "filename": "Default-2688h.png",
      "minimum-system-version": "12.0",
      "subtype": "2688h",
      "scale": "3x"
    },
    {
      "orientation": "landscape",
      "idiom": "iphone",
      "extent": "full-screen",
      "filename": "Default-Landscape-2688h.png",
      "minimum-system-version": "12.0",
      "subtype": "2688h",
      "scale": "3x"
    },
    {
      "orientation": "portrait",
      "idiom": "iphone",
      "extent": "full-screen",
      "filename": "Default-1792h.png",
      "minimum-system-version": "12.0",
      "subtype": "1792h",
      "scale": "2x"
    },
    {
      "orientation": "landscape",
      "idiom": "iphone",
      "extent": "full-screen",
      "filename": "Default-Landscape-1792h.png",
      "minimum-system-version": "12.0",
      "subtype": "1792h",
      "scale": "2x"
    },
```

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
While Apple hasn't deprecated static image launch splash screens yet, they don't recommend them anymore and they are pushing developers to use storyboards. Which the [splashscreen plugin](https://github.com/apache/cordova-plugin-splashscreen#ios-specific-information) supports. Note that you can achieve the same affect using storyboards. Because of this, I don't think this will be implemented or fixed.

A workaround is probably just to update your app to use the storyboard method instead of the legacy launch image method.

You can read more at https://github.com/apache/cordova-plugin-splashscreen#launch-storyboard-images.

**Comment by mobidev111** [comment]
I know about the legacy status & the better storyboard method.

I'd like consistency in the cordova-ios code base. So either:
* add the up-to-date set of images - for people still using it OR
* remove the managing code from the cordova-ios code / or clearly deprecate it as unmaintained

**Comment by breautek** [comment]
> add the up-to-date set of images

Personally I agree with this (only because it's not currently marked as deprecated). Then add deprecation notice to state that no further updates will be added.

@jcesarmobile we had a brief chat regarding this the other day on slack, what are your thoughts?

**Comment by mobidev111** [comment]
(and the corresponding splashscreen plugin pull request to support those devices hasn't been merged yet: https://github.com/apache/cordova-plugin-splashscreen/pull/159)

**Comment by spinninghamster** [comment]
I use this in `config.xml`:

`<splash src="resources/ios/screens/Default@2x~universal~anyany.png" />`

and it works perfectly on all devices (at least in the simulator, which I somewhat trust to be accurate). 2732x2732 pixels. Why make it difficult if it can be easy?

**Comment by goutamreddy** [comment]
in cleanSplashScreens, the resoursemap is using the Icon as opposed to Resources function:
`var resourceMap = mapIconResources(splashScreens, splashScreensDir);
`
should be:
`var resourceMap = mapSplashResources(splashScreens, splashScreensDir);`

This probably only pertains to the old way of splash screens, but just for completeness.

**Comment by jacobweber** [comment]
Hi guys. What's the status of this? We're seeing messages from Apple saying that by April, apps "must also support the all-screen design of iPhone XS Max or the 12.9-inch iPad Pro (3rd generation), or later."

If we use the `Default@2x~universal~anyany.png` approach, are we covered?

**Comment by breautek** [comment]
I'm using `Default@2x~universal~anyany.png`, no problems so far.

**Comment by breautek** [comment]
Because Apple is deprecating support for legacy splashscreens this issue is no longer relevant.

**Comment by jacobweber** [comment]
Thanks @breautek.

I do hope that if Cordova stops supporting this method, we get some advance notice. As far as I can tell from the [docs](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html#single-image-launch-screen), the single-image launch screen is under the Launch Storyboard Images section. so it's a supported method.

**Comment by breautek** [comment]
> Or does "deprecating support for legacy splashscreens" mean the Default@2x~universal~anyany.png approach is deprecated as well?

No, what you linked is the new "storyboard" system. That is what Apple is pushing for.  What apple is deprecating is [Launch Images](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html#legacy-launch-images).

`Default@2x~universal~anyany.png` is the storyboard launch that is mostly compatible to the old legacy image system, the difference is that you can use that image for all iOS devices, so you don't need several copies of different resolutions.

> I do hope that if Cordova stops supporting this method, we get some advance notice. 

Unfortunately our hands are bound by Apple. The restriction is coming from Apple, not from Cordova. And Apple only gave us a few months notice (I think they started notifying users in January 2020). Starting in `cordova-ios@6` (still a WIP), legacy image support will be completely removed.

**Comment by jacobweber** [comment]
No problem -- the docs are clear that the legacy approach is going away; I just wanted to make sure the "Single-image launch screen" approach isn't. Thanks!
