### ISSUE TITLE
iOS 13 / Xcode 11 Text Input Errors - Breaks iOS Dictation

### ISSUE THREAD

**Issue by newlegendmedia** [apache/cordova-ios#682]
# Bug Report
iOS 13 / Xcode 11 Text Input Errors - Breaks iOS Dictation

## Problem
In the simplest HelloWorld iOS 13 app I can create using latest cordova (v5), an error is logged in Xcode 11 console on each keystroke (see error below). I believe the error is also causing dictation to fail (see error below). As soon as you start speaking, the dictation ends immediately. (dictation is by tapping the iOS 13 keyboard microphone icon to speak text into a field)

This simple app is using the simple HelloWorld app with nothing but a textarea in the body. The textarea has no classes or attributes added. The file includes NO css or js files other than cordova.js

### What is expected to happen?
Normal editing and dictation functions.

### What does actually happen?

On every keystroke while editing, The following error is logged in the console:
"-[UIThreadSafeNode _axResetFKAFocusToFirstResponder]: unrecognized selector sent to instance 0x281f87820"

Using Dictation, the dictation ends immediately upon speaking - the following error is logged in Xcode console:
"Given text range '(null)' we could not find the last hypothesis "W". The likely cause is that something modified the text store or the hypothesis during dictation."

### Environment, Platform, Device

- Cordova HelloWorld App - Cordova 9.0 
- Add a simple TextArea element in the body in index.html
- Build with Xcode 11 and Run on iOS 13.1 Phone

### Version information

- Cordova HelloWorld App - Cordova 9.0 
- Add a simple TextArea element in the body in index.html
- Build with Xcode 11 and Run on iOS 13.1 Phone

## Checklist

- [ X] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by pnasser** [comment]
Our app also has this issue

**Comment by dpogue** [comment]
Are you using UIWebView or WKWebView? Are you seeing this on a device or can you reproduce it in the simulator?

**Comment by ssmithereens** [comment]
For us, it does not work on UIWebView. We just tried wkwebview and the issue is resolved.

**Comment by newlegendmedia** [comment]
Fixed when using wkwebview for me as well. Looks like an issue with UIWebView only.

**Comment by Anuj-logiciel** [comment]
Anybody have a solution how can we get this working with UIWebview because I cannot add WKWebview to my project? Kindly suggest if any success with UIWebview.

**Comment by iampavanarora** [comment]
I also have same isue in our application i can't move from UIWebview to WKWebview is any quick fix to make chnages in UIWebview?

**Comment by dimitriadamou** [comment]
Also experiencing this at the moment

**Comment by ashihminaval** [comment]
We can't use moving from UIWebView to WKWebView as quick fix too. So, does anybody have a solution for that?

**Comment by wynhou** [comment]
I'm also experiencing this in UIWebView, cannot upgrade to WKWebView right now (WKWebView messes up some things)

**Comment by dpogue** [comment]
This is an Apple bug that should be reported at https://feedbackassistant.apple.com/

There's probably nothing Cordova can do to resolve this.

**Comment by JeffBerman** [comment]
Has anyone reported this yet to Apple?

**Comment by dpeacock** [comment]
I reported it to Apple on Oct 16, 2019 (Reference FB7385596), no response from Apple to date.  I think everyone should be reporting this to them so it gets more traction.

**Comment by Anuj-logiciel** [comment]
Hi @dpeacock - Can You give us link of your reported issue so we can also link that to our follow?

**Comment by dpeacock** [comment]
@Anuj-logiciel the links for Apple's feedback aren't publicly accessible, you can only view your own reported items.  I think the best you'll be able to do is reference my item FB7385596.

**Comment by JeffBerman** [comment]
FWIW, I also reported it to Apple (FB7510638). Thanks for all the info on this!

**Comment by Anuj-logiciel** [comment]
Thanks @dpeacock @JeffBerman Your reference codes will help to knock apple to fix the issue by mentioning these codes. Maybe they can take it seriously and fix it.

**Comment by JeffBerman** [comment]
Since UIWebView is deprecated, do we really think they will fix this, though? I'm more hopeful that the Cordova folks will move forward with getting WKWebView working as well as it can with Cordova.

**Comment by Roshan6194** [comment]
> Fixed when using wkwebview for me as well. Looks like an issue with UIWebView only.

Hi can you provide me the details of what all changes you did for this dictation breaking in ios. Like I am using cordova 10 and ios6.1.1 which is by default taking  wkwebview but dictation is still failing for me. In config.xml i have provided the permission for microphone but its not working.

**Comment by dimitriadamou** [comment]
> > Fixed when using wkwebview for me as well. Looks like an issue with UIWebView only.
> 
> Hi can you provide me the details of what all changes you did for this dictation breaking in ios. Like I am using cordova 10 and ios6.1.1 which is by default taking wkwebview but dictation is still failing for me. In config.xml i have provided the permission for microphone but its not working.

What version iOS are you testing on?

**Comment by Roshan6194** [comment]
I am testing on iOS14.3. I tried on various other platform also like 14.2,
13.3 doesnt seem to work on any of them.
Thanks,
Roshan

**Comment by Roshan6194** [comment]
Hi Dimitri,
Please can you give me details on how to fix this dictation issue, it has
become a show stopper for my project.
Regards,
Roshan
