### ISSUE TITLE
XPC connection interrupted Error 

### ISSUE THREAD

**Issue by devjva** [apache/cordova-ios#683]
# Bug Report

## Problem

 XPC connection interrupted

### What is expected to happen?

application running several hours in the background

### What does actually happen?

After several hours, the application freezes and issues the broken XPC connection error and invalidating cache.

## Information

Just leave APP in the background communicating with a SIP client

### Command or Code

Just leave the APP running doing some light processing with the network

### Environment, Platform, Device
íos 12.4.0

### Version information

cordova-ios@5.0.0
Xcode 11.0 
cordova-plugin-sip

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by Alfer-Star** [comment]
Hello 
XPC connection interrupted Error alos happened in our Ionic Cordova App, after running 1,5h.
Triggered through opening View with[ Cordova Plugin Camera Preview](https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview). App freezes after push Button to routing next View and start Plugin in Background. Plugin seems to stop and  App Freezes in View with button. 
In Konsole: XPC connection interrupted Error
No other Life Sign anymore. 
Perhaps Problem with Plugin or Cordova himself, plugin should not freeze app without an error Message.

Versions:
IOS 14.1
Cordova 8
Cordova IOS 6.1.0
Ioinc Angular 4

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
