### ISSUE TITLE
inappbrowser errors out without logging in

### ISSUE THREAD

**Issue by mnnguy23** [apache/cordova-ios#684]
# Bug Report

## Problem

inappbrowser doesn't allow users to log in

### What is expected to happen?
successful login by users

### What does actually happen?
and error and the authwindow never closes.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Please finish filling out the form, and include the error message. Also include stacktrace if available.

**Comment by jcesarmobile** [comment]
Also, the proper place for reporting inappbrowser issues is the inappbrowser repo https://github.com/apache/cordova-plugin-inappbrowser

**Comment by jcesarmobile** [comment]
Closing since the requested information was not provided
