### ISSUE TITLE
bug: Not able to generate .xcarchive file after updating xCode version to 11.0

### ISSUE THREAD

**Issue by AbhishekQliktag** [apache/cordova-ios#688]
**Ionic version:**
[x] **3.x**

**Current behavior:**
Only build is happening, no archive process

**Expected behavior:**
Should generate .xcarchive after build succeed 

**Related code:**

```
cordova build ios --buildConfig build.json --noSign=true
```

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI          : 5.2.6 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 2.5.2, (and 12 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/Abhishek/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.12.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.0 Build version 11A420a
```

Please help

**Comment by brodybits** [comment]
@AbhishekQliktag I suggest you try it on a plain Cordova project, no Ionic and no other plugins. Additional plugins and frameworks make it harder for us to support.

Unfortunately I still don't have my mac back from repair, hope another committer can take a look at this one.

**Comment by britta-g** [comment]
@AbhishekQliktag: Did you change the Build System setting in Xcode ? 
File -> Project Settings -> Build System -> Legacy Build System (select) 

The build command must also be adjusted: 
cordova build ios --buildFlag='-UseModernBuildSystem=0'

**Comment by erisu** [comment]
You may also want to try and upgrade your version of Cordova CLI. 

I see that you are using an older version of Cordova CLI `8.1.2` and we are currently on `9.0.0`. 

The version of the Cordova iOS platform that you are using was released for Cordova CLI version 9.x and it may not work as intended on the older versions.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date Xcode version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
