### ISSUE TITLE
Unable to launch com.example.hello

### ISSUE THREAD

**Issue by sophiekruijt** [apache/cordova-ios#689]
# Bug Report

## Problem
When I follow the steps at https://cordova.apache.org/docs/en/latest/guide/cli/index.html and open the project in XCode the project right away crashes when it starts on my iOS device. I tried this on several devices and keep seeing the same error.

"iPad has denied the launch request.
Internal launch error: process launch failed: Unspecified"

### What is expected to happen?

The application should launch.

### What does actually happen?

The application launches and I can see the Cordova logo for 1 second before it crashes.

## Information

macOS Mojave 10.14.5

Xcode: 10.3
ios-deploy: 1.9.4
CocoaPods: 1.7.5
Node version: v10.15.1
Cordova version: 9.0.0 (cordova-lib@9.0.1)
I also tried using the xCode11 beta and got the same error.

I'm using an iPad Air 2 (and also have tried a newer and an older device with the same result)

When I upload the app to the App store I'm able to run this same app on my iPad through TestFlight. 

### Command or Code
Follow the steps at https://cordova.apache.org/docs/en/latest/guide/cli/index.html  and try to launch the application in Xcode.

### Environment, Platform, Device
See above for environment, platform and device.

### Version information
See the list of version numbers above.

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

I have spent a long time googling this error and tried all suggestions I found through Google.
- https://forums.developer.apple.com/thread/68746
- https://stackoverflow.com/questions/43091562/xcode-8-3-could-not-launch-application-process-launch-failed-unspecified

**Comment by akildemir** [comment]
Hello @stefankruijt  It seems I am getting the same error. Whenever I tried to launch the app  it is  auto closed while in the splash screen. Did you manage the solve the issue? and also from where exactly do you get this error ```Pad has denied the launch request.
Internal launch error: process launch failed: Unspecified" ```

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS/Xcode version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
