### ISSUE TITLE
Failed to launch on iPhone after building

### ISSUE THREAD

**Issue by sts-ryan-holton** [apache/cordova-ios#690]
I have built a Cordova app, I've recently been able to build the app and run it on my phone prior to adding a new paid Apple Developer account to Xcode (not a Personal Team account).

Since adding this account, I am encountering the issue where the app will successfully build, but won't launch on the iPhone, it will continuously close every time I tap the app icon, in addition the error I get in Xcode is:

```
iPhone has denied the launch request.
Internal launch error: process launch failed: Unspecified
```
I'm running Xcode 10.2.1, building to an iPhone 6S Plus running iOS 12.4 (the latest), and am using Cordova 8.0.0

I've tried deleting the Apple Worldwide certificate, adding a new account, adding a new user to the system, restarting the machine, changing the Bundle Identifier.

Inside of the signing tab in general I have:

Team: [name of team]
Provisioning Profile: Xcode Managed Profile
Signing Certificate: iPhone Developer: [name of person] ([some ID])

In addition, I have currently got the following command: `cordova run ios --buildFlag='-UseModernBuildSystem=0'`

But the build system shouldn't matter here.

**EDIT**

Updating to Xcode 10.3 doesn't solve the issue.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS/Xcode version, please let us know. Otherwise, this issue will be closed.
