### ISSUE TITLE
clicks on text inputs not always trigger focus - ios

### ISSUE THREAD

**Issue by nirushz** [apache/cordova-ios#691]
# Bug Report

### What is expected to happen?
click on text inputs should trigger the focus on these inputs

### What does actually happen?
Quick or weak click not always trigger the focus. more longer click works fine.
On android it works fine.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by spinninghamster** [comment]
I noticed the same problem.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
