### ISSUE TITLE
Xcode 11 issue while building cordova app with ios platform v4.5.5

### ISSUE THREAD

**Issue by nnsn** [apache/cordova-ios#692]
Hi getting the below issue while building cordova application when running "cordova build ios". Also I am using ios platform v4.5.5 and Xcode 11

(node:22769) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at Project location/platforms/ios/cordova/lib/list-emulator-build-targets:54:45
    at Array.forEach (<anonymous>)
    at Project location/platforms/ios/cordova/lib/list-emulator-build-targets:52:44
    at Array.reduce (<anonymous>)
    at Project location/platforms/ios/cordova/lib/list-emulator-build-targets:50:57
    at Array.reduce (<anonymous>)
    at Project location//platforms/ios/cordova/lib/list-emulator-build-targets:45:28
    at _fulfilled (Project location/platforms/ios/cordova/node_modules/q/q.js:854:54)
    at Project location/platforms/ios/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Project location/platforms/ios/cordova/node_modules/q/q.js:816:13)
(node:22769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by dpogue** [comment]
Cordova iOS v4.5.x is not compatible with Xcode 11. You'll need to update to Cordova iOS 5.x.
