### ISSUE TITLE
Can't control SplashScreenView's ModalPresentationStyle in iOS 13

### ISSUE THREAD

**Issue by bebeebee** [apache/cordova-ios#694]
# Bug Report

### What is expected to happen?
Change SplashScreenView's ModalPresentationStyle

### What does actually happen?
ModalPresentationStyle in iOS 13 default is UIModalPresentationAutomatic
How do I control SplashScreenView's ModalPresentationStyle?
Thanks!

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
The Splashscreen is not presented as a ViewController, so it has no ModalPresentationStyle
