### ISSUE TITLE
Cordova 9.0.0 build error with XCode 11.1 on macOS Catalina (10.15)

### ISSUE THREAD

**Issue by aceroni75** [apache/cordova-ios#696]
# Bug Report

## Problem
After upgrading our MacBooks to macOS Catalina (10.15), XCode 11.1 and Cordova 9.0.0, we cannot build our app anymore, as an unexpected error occur when calling xcodebuild.

### What is expected to happen?
Successfull build

### What does actually happen?
CordovaError: Promise rejected with non-error: 'Error code 1 for command: xcodebuild with args: -xcconfig,/Users/xxx/Development/xxx/platforms/ios/cordova/build-release.xcconfig,-project,xxx.xcodeproj,ARCHS=i386,-target,xxx,-configuration,Release,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/xxx/Development/xxx/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/xxx/Development/xxx/platforms/ios/build/sharedpch'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

## Information
cordova build verbose output:

No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
PlatformApi successfully found for platform ios
Checking for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in ios platform
No differences found between plugins added to project and installed in ios platform. Continuing...
Generating config.xml from defaults for platform "ios"
Wrote out iOS Bundle Identifier to "xxx"
Wrote out iOS Bundle Version to "xxx"
iOS Product Name has not changed (still "xxx")
updated project successfully
No scripts found for hook "after_prepare".
No scripts found for hook "before_compile".
Building project  : /Users/xxx/Development/xxx/platforms/ios/xxx.xcodeproj
	Configuration : Release
	Platform      : emulator
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Users/xxx/Development/xxx/platforms/ios/build/emulator
    SDKROOT = iphonesimulator13.1
    SHARED_PRECOMPS_DIR = /Users/xxx/Development/xxx/platforms/ios/build/sharedpch
    VALID_ARCHS = i386

Build settings from configuration file '/Users/xxx/Development/xxx/platforms/ios/cordova/build-release.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_IDENTITY = iPhone Distribution
    ENABLE_BITCODE = NO
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    IPHONEOS_DEPLOYMENT_TARGET = 8.0
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h
    TARGETED_DEVICE_FAMILY = 1,2

FIXME: Implement XCBuild support for macros in overriding parameters with condition sets:

	CODE_SIGN_IDENTITY[sdk=iphoneos*] = iPhone Distribution

### Command or Code
cordova build ios

### Environment, Platform, Device
macOS 10.15, MacBook Pro

### Version information
Xcode 11.1
Cordova 9.0.0
Cordova CLI 1.0.0
Cordova iOS 5.0.1

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by aceroni75** [comment]
Was solved by:
cordova platform remove ios
cordova platform add ios

**Comment by martincpt** [comment]
I was having a similiar issue with an old cordova project that required some update. I had to readd all platforms and now working like a charm.

**Comment by Datalux** [comment]
Same error. Anyone solved this issue?
