### ISSUE TITLE
XML External Entity

### ISSUE THREAD

**Issue by trangnt-bkhn** [apache/cordova-ios#697]
# Bug Report

## Problem
We have scanned the code and finded the issue at line 168. Can you check more in photos.
### What does actually happen?
![image](https://user-images.githubusercontent.com/56822255/67352911-dbe13080-f583-11e9-8627-aa3a03350d20.png)

### Risk - What might happen
An application that will parse and replace DTD entity references, in an XML document that the user controls,
can allow an attacker to craft an XML document to read arbitrary server files. This XML document could
contain an XML entity reference, which refers to an embedded DTD entity definition that points to any local
file. This would enable the attacker to retrieve any arbitrary system file on the server.

### Cause - How does it happen
An attacker could upload an XML document that contains a DTD declaration, in particular an entity defintion
that refers to a local file on the server's disk, e.g. <!ENTITY xxe SYSTEM "file:///c:/boot.ini">. The
attacker would then include an XML entity reference that refers back to that entity definition, e.g.
<div>&xxe;</div> . If the parsed XML document is then returned to the user, the result will include the
contents of the sensitive system file.
This is caused by the XML parser, which is configured to automatically parse DTD declarations and resolve
entity references, instead of disabling both DTD and external references altogether.

### General Recommendations
How to avoid it
#### Generic Guidance:
PAGE 943 OF 966
o Avoid processing user input directly, where possible.
o If necessary to receive XML from the user, ensure the XML parser is restricted and
constrained.
o In particular, disable DTD parsing and resolving of entities. Apply a strict XML schema on the
server, and validate the input XML accordingly.
#### Specific Recommendations:
o Use safe XML parsers, and disable DTD parsing and entity resolving.
o Do not enable DTD parsing or entity resolving.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Can you explain exactly how this is a problem?

**Comment by trangnt-bkhn** [comment]
Our application didn't pass security scanning because the lines 168 and 169 use configParser.

**Comment by trangnt-bkhn** [comment]
Could I know this issue will be fixed? Thanks!

**Comment by dpogue** [comment]
I still don't understand *what* the issue is...

You've given us a file and line number, but not explained what the problem is or what we should be doing to fix it.

**Comment by trangnt-bkhn** [comment]
> I still don't understand _what_ the issue is...
> 
> You've given us a file and line number, but not explained what the problem is or what we should be doing to fix it.

I have updated the problem. Please check for more detail in the post. Thanks!

**Comment by jcesarmobile** [comment]
The config.xml path can be configured by the app developer, but not by the app user, same for the Config.xml content. So I don’t think this is a vulnerability.
