### ISSUE TITLE
Format String Attack

### ISSUE THREAD

**Issue by trangnt-bkhn** [apache/cordova-ios#698]
# Bug Report

## Problem
We have scanned the code and finded the issue at line 768. Can you check more in photos.
### What is expected to happen?
![image](https://user-images.githubusercontent.com/56822255/67353664-a6d5dd80-f585-11e9-8274-c9a393eb3071.png)

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Cordova doesn't maintain the `cordova-plugin-x-socialsharing` package. You should contact the author of the plugin instead.
