### ISSUE TITLE
Catalyst for ios platform ?

### ISSUE THREAD

**Issue by jhjulkun** [apache/cordova-ios#699]
Hi 
Has anyone tried building an ios project using 'Catalyst' for macOS Catalina ?

If I try enabling that build, I get:
 
CDVURLProtocol.m:20:9: AssetsLibrary is deprecated and is not available when building for Mac Catalyst. Consider migrating to Photos instead, or use `#if !TARGET_OS_MACCATALYST` to conditionally import this framework, first importing TargetConditionals.h if necessary.

Seems like the AssetsLibrary has been deprecated, and has been fixed in ionic, are you guys planning on removing it too ?
https://github.com/ionic-team/capacitor/pull/1825

Going forward, should Catalyst be used or the 'osx' platform ?

Thanks

**Comment by jcesarmobile** [comment]
moved to cordova-ios repo

**Comment by dpogue** [comment]
> Going forward, should Catalyst be used or the 'osx' platform ?

Once it works, I think we'd want to encourage using Catalyst for macOS to avoid needing to maintain a similar-but-separate cordova-osx platform.

See also https://github.com/apache/cordova-ios/issues/551.

We'd definitely like to address this, but it's not clear if that code is actually being used (it probably is, by someone, somewhere) and whether removing it (like Ionic did) is the right step.

**Comment by jcesarmobile** [comment]
It was removed in Capacitor, was not really being used there.

Since it's in CDVURLProtocol.m and that won't work on WKWebView, I think it's safe to remove once we remove UIWebView.

**Comment by brodybits** [comment]
Unfortunately the maintainers are overloaded due to lack of resources, see apache/cordova#163.

**Comment by erisu** [comment]
`CDVURLProtocol` was removed in #783 and will be in next major release.

**Comment by jcesarmobile** [comment]
Have you tried to run the app in Catalyst after that change?
If so, maybe we should enable it by default on the project template or add a way of easily adding it

**Comment by dpogue** [comment]
Catalyst is only supported in Xcode 11 on macOS Catalina, so I'm not sure we'd want to enable it by default.

**Comment by erisu** [comment]
From `master`, I believe it was decided to only support Xcode 11+ as all apps starting April 2020 requires to be built with Xcode 11.

I am not sure what we say about macOS requirements.

**Comment by jcesarmobile** [comment]
What happens if you add macOS target and then you open the project on Mojave? I updated both of my computers, so I can’t test anymore.
If not by default, then maybe a command that adds catalyst instead of cordova-osx

**Comment by dpogue** [comment]
Had a bit of time to play with the HelloCordova app in Catalyst tonight, and it doesn't work out of the box but it should be easy to make it compatible.

Namely, we currently use [a bash script](https://github.com/apache/cordova-ios/blob/master/bin/templates/project/__PROJECT_NAME__/Scripts/copy-www-build-step.sh) to copy the config.xml and www folders into the root of the .app bundle.
On Catalyst, those need to be copied into a subfolder instead of the root, otherwise CodeSign fails.

If we instead moved those to the [Copy Bundle Resources](https://github.com/apache/cordova-ios/blob/master/bin/templates/project/__TEMP__.xcodeproj/project.pbxproj#L257-L268) step of the Xcode project, then it works.

I don't know off-hand the historical reasons for not relying on Copy Bundle Resources, so there's probably some investigation to do there to see if this is a safe change to make.

**Comment by brodybits** [comment]
Sounds like we would need breaking changes to use the Copy Bundle resources and drop the AssetsLibrary, or am I mistaken on this?

**Comment by dpogue** [comment]
Random links/notes for whoever decides to investigate whether this is feasible:

* https://github.com/apache/cordova-ios/commit/2988f029ff13f80ddc8fc910bebb1bd69eefd74f looks like it was trying to do the right thing...
* https://github.com/apache/cordova-ios/commit/ec2d51ddfa3407075ea0be9e48b1257157ed901a added a step to touch the www folder to ensure it exists
* https://github.com/apache/cordova-ios/commit/3c3b0c00f9a7021cd7df1bd5c0353809fabde9fc moved to a script to copy files because of https://issues.apache.org/jira/browse/CB-2207
* https://github.com/apache/cordova-ios/commit/806651d674a970a7d22ed9c3132f206d88594f0c moved the config.xml copying into the shell script, due to https://issues.apache.org/jira/browse/CB-5397

**Comment by dpogue** [comment]
> Sounds like we would need breaking changes to use the Copy Bundle resources and drop the AssetsLibrary, or am I mistaken on this?

The ALAssetLibrary stuff (and all of CDVURLProtocol was dropped in 6.0)

**Comment by jhjulkun** [comment]
So just tested Catalyst for on a new 'hello' cordova project, using ios@6.1.0
Project builds (and runs on iOS), but after enabling Catalyst I get this codesign error:
unsealed contents present in the bundle root
  Command CodeSign failed with a nonzero exit code

Has someone gotten a Catalyst ios build to work ?

**Comment by BRadHoc** [comment]
> So just tested Catalyst for on a new 'hello' cordova project, using ios@6.1.0
> Project builds (and runs on iOS), but after enabling Catalyst I get this codesign error:
> unsealed contents present in the bundle root
> Command CodeSign failed with a nonzero exit code
> 
> Has someone gotten a Catalyst ios build to work ?
> Update: just saw the post from dpogue above, unfortunately I can't get around the codesign issue, can you share some more detail where you copied the config.xml and www directory ? (not familiar with codesign)

CodeSign error means your app isn't signed properly, you need to select a development team in the target root node.

The build fails for another reason

**Comment by kisonay** [comment]
> > So just tested Catalyst for on a new 'hello' cordova project, using ios@6.1.0
> > Project builds (and runs on iOS), but after enabling Catalyst I get this codesign error:
> > unsealed contents present in the bundle root
> > Command CodeSign failed with a nonzero exit code
> > Has someone gotten a Catalyst ios build to work ?
> > Update: just saw the post from dpogue above, unfortunately I can't get around the codesign issue, can you share some more detail where you copied the config.xml and www directory ? (not familiar with codesign)
> 
> CodeSign error means your app isn't signed properly, you need to select a development team in the target root node.
> 
> The build fails for another reason

I unfortunately have this same error. Cannot find a way around it. The app is set to automatically sign and a team is selected from both dropdowns.

**Comment by dpogue** [comment]
Yes, currently Cordova-iOS cannot generate successful builds with Catalyst. Catalyst is not supported.

**Comment by pedroadame** [comment]
Is this still on sight for cordova-ios 7.0.0? @dpogue

**Comment by dpogue** [comment]
It's on our list of things we hope to do for v7.0.0, but there's nobody currently looking into it and no timeline

**Comment by jhjulkun** [comment]
if you guys can fix it that would be great, with the M1 being able to run "mobile" type of apps on a laptop would be awesome!

**Comment by jcesarmobile** [comment]
That’s a separate thing, M1 is supposed to run iOS/iPadOS apps, catalyst creates macOS apps and works on any Mac.

**Comment by Leandropintogit** [comment]
> > > So just tested Catalyst for on a new 'hello' cordova project, using ios@6.1.0
> > > Project builds (and runs on iOS), but after enabling Catalyst I get this codesign error:
> > > unsealed contents present in the bundle root
> > > Command CodeSign failed with a nonzero exit code
> > > Has someone gotten a Catalyst ios build to work ?
> > > Update: just saw the post from dpogue above, unfortunately I can't get around the codesign issue, can you share some more detail where you copied the config.xml and www directory ? (not familiar with codesign)
> > 
> > 
> > CodeSign error means your app isn't signed properly, you need to select a development team in the target root node.
> > The build fails for another reason
> 
> I unfortunately have this same error. Cannot find a way around it. The app is set to automatically sign and a team is selected from both dropdowns.

Hy guys

With just a few changes, it is possible to generate a simple cordova app supporting catalyst without changing ios behavior
In the script copy-www-build-step.sh, change the variable DST_DIR based on build platform

```
DST_DIR="$BUILT_PRODUCTS_DIR/$FULL_PRODUCT_NAME"
if [[ "$PLATFORM" == "macosx" ]]; then
  //In case build ios directories exists
  rm -rf "$DST_DIR_WWW"
  rm -f  "$DST_DIR/config.xml"

  DST_DIR="$BUILT_PRODUCTS_DIR/$FULL_PRODUCT_NAME/Contents/Resources"
fi
```

**Comment by BRadHoc** [comment]
> > > > So just tested Catalyst for on a new 'hello' cordova project, using ios@6.1.0
> > > > Project builds (and runs on iOS), but after enabling Catalyst I get this codesign error:
> > > > unsealed contents present in the bundle root
> > > > Command CodeSign failed with a nonzero exit code
> > > > Has someone gotten a Catalyst ios build to work ?
> > > > Update: just saw the post from dpogue above, unfortunately I can't get around the codesign issue, can you share some more detail where you copied the config.xml and www directory ? (not familiar with codesign)
> > > 
> > > 
> > > CodeSign error means your app isn't signed properly, you need to select a development team in the target root node.
> > > The build fails for another reason
> > 
> > 
> > I unfortunately have this same error. Cannot find a way around it. The app is set to automatically sign and a team is selected from both dropdowns.
> 
> Hy guys
> 
> With just a few changes, it is possible to generate a simple cordova app supporting catalyst without changing ios behavior
> In the script copy-www-build-step.sh, change the variable DST_DIR based on build platform
> 
> ```
> DST_DIR="$BUILT_PRODUCTS_DIR/$FULL_PRODUCT_NAME"
> if [[ "$PLATFORM" == "macosx" ]]; then
>   //In case build ios directories exists
>   rm -rf "$DST_DIR_WWW"
>   rm -f  "$DST_DIR/config.xml"
> 
>   DST_DIR="$BUILT_PRODUCTS_DIR/$FULL_PRODUCT_NAME/Contents/Resources"
> fi
> ```

Do you know how it's possible to stop this from happening:

> /Project/platforms/ios/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector(FIRAnalyticsConnector_c162bpf6emcd173ef13757bsd7ebe6f7.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Project/platforms/ios/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector' for architecture x86_64

**Comment by Leandropintogit** [comment]
FirebaseAnalytics does not suport catalyst yet, but other frameworks do. I built a catalyst app with firebasemessaging successfully. Try update pods with latest version.

**Comment by pulpgrinder** [comment]
The suggestion from @Leandropintogit didn't quite work for me (iMac M1, XCode  12.5.1)... 

While it enabled me to build the "My Mac (Designed for iPad)" configuration, it broke the "My Mac" and "My Mac  (Rosetta) builds.

After diffing the script outputs from the three available Mac configurations and looking for different environment variables, I found an EFFECTIVE_PLATFORM_NAME environment variable. Checking whether this is set to "-maccatalyst" seems to do the trick. At least it builds and runs in all three configurations. No idea if this is the official Apple way of distinguisghing or not, but it seems promising. Relevant lines from the works-for-me copy-www-build-step.sh file:

```
SRC_DIR="www"
DST_DIR="$BUILT_PRODUCTS_DIR/$FULL_PRODUCT_NAME"
DST_DIR_WWW="$DST_DIR/www"
if [[ "$EFFECTIVE_PLATFORM_NAME" == "-maccatalyst" ]]; then
  rm -rf "$DST_DIR_WWW"
  rm -f  "$DST_DIR/config.xml"
  DST_DIR="$BUILT_PRODUCTS_DIR/$FULL_PRODUCT_NAME/Contents/Resources"
fi

COPY_HIDDEN=

(etc.)
```

**Comment by pulpgrinder** [comment]
My understanding of the three configurations (which may not be fully accurate -- I've just started playing with this):
"My Mac" -- builds a native Mac app which can run only on M1 Macs, but is otherwise functionally identical to the iPad app.
"My Mac (Rosetta)" -- builds a Rosetta-compatible Mac app that will run on M1 under Rosetta emulation. I think this may also run on Intel Macs. If not, maybe I'm not understanding what the use case is for this.
"My Mac (Designed for iPad)" -- builds a Catalyst-enabled Mac app which can run on any Mac that supports Catalyst apps. I believe the use case for this is that you can use the extra Catalyst goodies (normal Mac menu stuff and so on).

Corrections welcome.

**Comment by NiklasMerz** [comment]
@pulpgrinder I just a did a quick test on a M1 Mac and your code seems fine. It works for all Mac configurations for me.

As this is a minimal change I would go for this. Would you like to create a pull request for this or can we take the code from the comment?

Thank you for your comments and testing. This helped me to get it working.

**Comment by NiklasMerz** [comment]
Good point. I tested the "Copy files" build setting in Xcode for a bit and it seems to work fine.

I am not sure if the reasons for this script in the past are still strong enough to not change it.
