### ISSUE TITLE
Fonts and images linked in css files not loading on app start

### ISSUE THREAD

**Issue by cclobo** [apache/cordova-ios#701]
# Bug Report

## Problem
Fonts and images linked in css files not loading. 

### What is expected to happen?
Fonts and images should be requested when css file is loaded

### What does actually happen?
Fonts and images aren't loaded and no requests are vivible in safaris dev tools. They are loaded after manually refreshing the page

## Information
Basic structure:
index.html links index.css wich loads fonts and images:

After close inspection it seems like a cache issue. On cordova-ios 5+ it seems like the webview is reloaded when the app enters the active state ( onAppDidBecomeActive ) wich also happens when the app first starts.  Could it be that the css files are getting cached before all the font and image files are requested and on the reload it just assumes they actually were loaded?

#363 seems to be related to this fix

Note: The files are loaded when debugging in xcode, it only happens when running the app directly on the phone

### Command or Code
//index.html head
<link rel="stylesheet" type="text/css" href="index.css">

//index.css
@font-face {
    font-family: Text-Regular;
    src: url('../fonts/text_regular.ttf');
}

### Environment, Platform, Device
cordova-ios 5+
using default cordova webview

### Version information
cordova-ios 5.0+
xcode 11
tested on ios12 and ios13

cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-calendar 5.1.4 "Calendar"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-is-debug 1.0.0 "IsDebug"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.0 "SocialSharing"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.3.0 "PushPlugin"

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by gabrielsclimaco** [comment]
+1

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
