### ISSUE TITLE
iOS 13 prompt not waiting for input

### ISSUE THREAD

**Issue by DaleCantwell** [apache/cordova-ios#707]
# Bug Report

On iOS 13 when calling prompt, the prompt appears with the text field however it appears to not wait for the input to execute the following lines. For example

```
      var emailAddress = prompt("Type in an email address", "");
      console.log('Successfully logged in with : ' + emailAddress);
```

### What is expected to happen?

The expectation is a prompt appears, I type in an email lets say john@mail.com and then I get a log saying: Successfully logged in with : john@mail.com

This works perfectly on Android and iOS 12 and below.

### What does actually happen?

What happens on iOS 13 is that the prompt opens and immediately in the console I can see the message Successfully logged in with : null

If I then type in an email and tap ok, it does not execute the console.log line again.

### Command or Code
Something like this should do the job.
```
      var emailAddress = prompt("Type in an email address", "");
      console.log('Successfully logged in with : ' + emailAddress);
```
To see a full example, I'm currently updating the Intercom Cordova library here: https://github.com/intercom/intercom-cordova/blob/master/Example/www/js/index.js#L76
when I ran into the issue

### Environment, Platform, Device
iPhone 11 Pro Max 13.1 Simulator
iPhone XR 12.0 Simulator

### Version information
cordova 9.0.0
cordova ios 5.0.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Can reproduce with UIWebView
Can't reproduce with WKWebView

So looks like a bug on UIWebView, you can report it to Apple, but I doubt they will fix it considering UIWebView is deprecated and they want people to move to WKWebView as soon as possible
