### ISSUE TITLE
Redirect while doing Form POST is being swallowed by CDVIntentAndNavigationFilter

### ISSUE THREAD

**Issue by FergalMohan** [apache/cordova-ios#709]
# Bug Report
While doing a Form POST the Redirect is being swallowed by CDVIntentAndNavigationFilter's shouldOpenURLRequest:navigationType: 
## Problem
While doing a Form POST the Redirect is being swallowed by CDVIntentAndNavigationFilter's shouldOpenURLRequest:navigationType: because the navigationType is UIWebViewNavigationTypeFormSubmitted
### What is expected to happen?
The Cordova WebView would launch the redirectedURL in an external Mobile Browser since it's not on the WhiteList

### What does actually happen?
The Cordova WebView gets stuck on the Form submission screen

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
