### ISSUE TITLE
App Rejected - ITMS-90534: Invalid Toolchain Error

### ISSUE THREAD

**Issue by distinctdan** [apache/cordova-ios#711]
# Bug Report

## Problem
Apple rejected my build in TestFlight with the following error:

> ITMS-90534: Invalid Toolchain - Your app was built with an unsupported version of Xcode or SDK. If you plan to submit this build to the App Store, make sure you are using the GM version of Xcode 10.1 and the SDK for iOS 12.1 and watchOS 5.1, Xcode 7.1 and the SDK for tvOS 9, or Xcode 6 and the SDK for macOS 10.9 or later. If you are using an Xcode beta version to test your app, make sure you are using the latest supported version. For more information about supported beta versions, view the App Store Connect What's New page (https://developer.apple.com/app-store-connect/whats-new/).

## Information

From a little googling, it looks like the project format needs to be set higher than 3.2, which is what it's set to by default:
https://stackoverflow.com/questions/44323009/error-itms-90534-invalid-toolchain

### Version information

XCode: 11.2
cordova-ios: 5.0.1
macOS Mojave 10.14.6

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Are you using Xcode 11.2.1 GM Seed that was released today?

**Comment by distinctdan** [comment]
No, just 11.2.

**Comment by distinctdan** [comment]
Buuut, if they just released a new version, that would explain why mine's not working, since my version is no longer the latest. I'll poke around some more and see if updating helps.

**Comment by breautek** [comment]
You can try 11.2.1 available as a GM seed at https://developer.apple.com/download/

11.2 appears to be the latest version in the app store so I would think 11.2 should still work though... Maybe they are prepping a release?

**Comment by SimonBrazell** [comment]
I experienced this issue myself today, was 11.2.1 released yet? I see no updates available for my machine yet, I'm running Xcode 11.2 (11B52) which appears to be the latest.

**Comment by distinctdan** [comment]
It does not require Catalina. I didn't see it in the app store either, but I downloaded it from the link breautek posted. I deleted the old xcode from my apps folder, emptied trash (not sure if it's necessary), then dragged the new one in, and it worked. My app has now passed verification and is still pending review in testflight, but it wasn't passing verification before the update, so it's looking like the new version fixed it.

**Comment by SimonBrazell** [comment]
Cool thanks @distinctdan I might wait and see if there is a release coming on the App Store, my build isn't super urgent.

**Comment by chenyongze** [comment]
App Store Connect Operation Error
ERROR ITMS-90534: "Invalid Toolchain. Your app was built with an unsupported version of Xcode or SDK. If you plan to submit this build to the App Store, make sure you are using the GM version of Xcode 10.1 and the SDK for iOS 12.1 and watchOS 5.1, Xcode 7.1 and the SDK for tvOS 9, or Xcode 6 and the SDK for macOS 10.9 or later. If you are using an Xcode beta version to test your app, make sure you are using the latest supported version. For more information about supported beta versions, view the App Store Connect What's New page (https://developer.apple.com/app-store-connect/whats-new/)."

**Comment by chenyongze** [comment]
So did I

**Comment by SimonBrazell** [comment]
Download the latest Xcode version from [here](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_11.2.1_GM_Seed/Xcode_11.2.1_GM_Seed.xip), and build with it instead, it will work, just did so myself and submitted the build for TestFlight.

**Comment by chenyongze** [comment]
Thanks,Let me try.

**Comment by distinctdan** [comment]
Ok, the latest xcode 11.2.1 fixed it for me. It was confusing at first for me because apple did the xcode requirement update after my app had already been uploaded to testflight, so that version got past the initial verification, but then later got rejected. Since this doesn't appear to be an issue with cordova-ios, I'm going to close this issue, thanks for the help.

**Comment by vauruk** [comment]
Works for me!

**Comment by elviseas1** [comment]
I downloaded 11.2.1 released. How can I use?

**Comment by SimonBrazell** [comment]
Just drag the extracted `.app` file into your `/Applications` folder and replace the existing Xcode install with it, then run it.

**Comment by Sroose** [comment]
@elviseas1, the correct way to do this is:
`sudo xcode-select --switch /Users/yourname/Downloads/Xcode.app/Contents/Developer`
(or whatever path to the new Xcode)

To return to default xcode:
`sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`

To see which one you’re using:
`xcode-select -p`
