### ISSUE TITLE
inputmode not working when custom keyboard is active

### ISSUE THREAD

**Issue by soskarsson** [apache/cordova-ios#713]
# Bug Report

### What is expected to happen?

When inputmode="decimal" is set on an input field the decimal keyboard is shown.

### What does actually happen?

When inputmode="decimal" is set on an input field & the user has installed a custom keyboard that was active in the previous application, the decimal keyboard is not shown & there is no way to close the custom keyboard.

## Information

This happens when a user has installed a custom keyboard (for instance the Giphy keyboard) and this keyboard was active in the last application used.

https://apps.apple.com/us/app/giphy-the-gif-search-engine/id974748812
![IMG_E8946908F3C9-1](https://user-images.githubusercontent.com/29313806/68480278-b7987b80-0234-11ea-960c-a252623e688c.jpg)
![IMG_59FC627FC83E-1](https://user-images.githubusercontent.com/29313806/68480277-b7987b80-0234-11ea-9181-a10d00b76b38.jpg)
![IMG_FBF567C2F651-1](https://user-images.githubusercontent.com/29313806/68480279-b7987b80-0234-11ea-97ba-a5657fe6a237.jpg)

### Command or Code

```<input type="number" inputmode="decimal" min="0" step="0.01" name="amount" placeholder="" />```

### Environment, Platform, Device

iPhone X, iOS 13.1.2

### Version information

Cordova 8.1.2 on Meteor 1.8.1

Plugins installed:
cordova-plugin-camera-preview@0.11.0
cordova-plugin-file@6.0.1
cordova-plugin-inappbrowser@3.1.0
cordova-plugin-keyboard@1.2.0
cordova-plugin-qrscanner@3.0.1
cordova-plugin-statusbar@2.4.3
onesignal-cordova-plugin@2.4.7

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Does this work in normal safari with the custom keyboard? I was under the impression that custom keyboards usually breaks these kind of features if they don't have an implementation for them.

**Comment by soskarsson** [comment]
@breautek This problem does not occur in Safari itself. I could not reproduce the problem there.

**Comment by breautek** [comment]
Ok, that's interesting. Unfortunately I don't have easy access to a mac so I can't really provide much more assistance myself.

But if it works in a normal browser, then I think it is reasonable to believe that there is some level of control we can have in in the webviews in dealing with custom keyboards, however this is still an assumption.

I've added the help wanted tag to signal that more investigation needs to be done by someone else. I can't promise when someone else will take a look at it as the community is entirely volunteer driven. If you're able to find anymore information that could help please do share here.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
