### ISSUE TITLE
The document "project.xcodeproj" could not be opened

### ISSUE THREAD

**Issue by mebibou** [apache/cordova-ios#716]
# Bug Report

## Problem
After building the app using `cordova build ios` and trying to open the `xcodeproj` file, I always get the error `The document "project.xcodeproj" could not be opened`.
I did not have this error before I upgraded to MacOS Catalina, so maybe that's why.

I tried `cordova platform remove ios && cordova platform add ios` but still the same error. I tried on many different projects but I always get the same error.

I also tried the simple hello world project as described here for the `osx` platform: https://cordova.apache.org/docs/en/latest/guide/platforms/osx/

```bash
cordova create hello com.example.hello "HelloWorld"
cd hello
cordova platform add osx
cordova prepare
open platforms/osx/HelloWorld.xcodeproj/
```
Error `The document “project.xcworkspace” could not be opened. `

## Information

Running MacOS `10.15.1`
Xcode `11.2`
Cordova `9.0.0 (cordova-lib@9.0.1)`
Node `v12.5.0`

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by DarkDust** [comment]
This seems to be an Apple bug… https://forums.developer.apple.com/thread/125608

**Comment by mebibou** [comment]
@DarkDust oh yes you are right, people said it worked after restarting but only once, had to restart again to have it work. I just tried today and it opened. Seems like another typical Apple bug, I'll close this then
