### ISSUE TITLE
Invalid toolchain error after updating xcode 11.2.

### ISSUE THREAD

**Issue by venkatmcajj** [apache/cordova-ios#718]
# Bug Report
Invalid toolchain. Your application has been builded with unsupported version of Xcode or Sdk.
## Problem
Invalid toolchain. Your application has been builded with unsupported version of Xcode or Sdk.
### What is expected to happen?
Successfully upload the build to appstoreconnect.

### What does actually happen?
Invalid toolchain. Your application has been builded with unsupported version of Xcode or Sdk.While upload a build.

### Environment, Platform, Device

XCode - 11.2
Ios Sdk - 13.2

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by DAnn2012** [comment]
Hi @venkatmcajj ,

Check if your problem is related to this:

https://stackoverflow.com/questions/58743828/app-archived-with-xcode-11-2-11b52-rejected-itms-90534-invalid-toolchain

**Comment by breautek** [comment]
See https://github.com/apache/cordova-ios/issues/711
