### ISSUE TITLE
Xcode tmp/strip error when trying to make an archive

### ISSUE THREAD

**Issue by aquinn637** [apache/cordova-ios#720]
I am working on a project written in AngularJS, Cordova, and Ionic.

When I try to build my project in XCode to put on the apple store I get this error:

```
Strip /Users/swdev/Library/Developer/Xcode/DerivedData/Self_Service-dmwurawdbtvnmpgdsjvsyxoxafvo/Build/Intermediates.noindex/ArchiveIntermediates/Self\ Service/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a (in target 'CordovaLib' from project 'CordovaLib')
    cd /Users/swdev/Documents/SelfServiceApp/platforms/ios/CordovaLib
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -S -T /Users/swdev/Library/Developer/Xcode/DerivedData/Self_Service-dmwurawdbtvnmpgdsjvsyxoxafvo/Build/Intermediates.noindex/ArchiveIntermediates/Self\ Service/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libCordova.a

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open temporary file: /tmp/strip.AH03t9 (No such file or directory)
Command Strip failed with a nonzero exit code
```

ionic info

Ionic:

   Ionic CLI         : 5.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.5
   @ionic/v1-toolkit : 1.0.22

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : no whitelisted plugins (15 plugins total)

Utility:

   cordova-res : not installed
   native-run  : 0.2.5

System:

   Android SDK Tools : 26.1.1 (/Users/swdev/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.11.3
   OS                : macOS Catalina
   Xcode             : Xcode 11.0 Build version 11A420a

cordova requirements
Requirements check results for ios:
Apple macOS: installed darwin
Xcode: installed 11.0
ios-deploy: installed 1.9.4
CocoaPods: installed 1.8.0

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by aquinn637** [comment]
@timbru31 What other information do you need?

**Comment by breautek** [comment]
Does the issue occur in a fresh cordova project?

**Comment by aquinn637** [comment]
@breautek Yes, the same error occurs.

**Comment by breautek** [comment]
> @breautek Yes, the same error occurs.

This suggests that the problem has something to do with your environment then. It's however not very clear on what exactly. 

You can try `cordova clean ios` or more extreme measures...

```
rm -rf platforms
rm -rf plugins
cordova plugin add ios
cordova build ios
```

If that doesn't do anything useful then...

> can't open temporary file: /tmp/strip.AH03t9 (No such file or directory)

This is a bit weird, if it's trying to read a file, then it must have tried to create a file before. If it did, where did it go? If it failed to create it, perhaps there is another error somewhere in your output?

**Comment by aquinn637** [comment]
@breautek I'm still getting this error. I followed the steps.

**Comment by aquinn637** [comment]
![Screenshot 2019-11-22 at 09 15 37](https://user-images.githubusercontent.com/52042381/69413415-af4a4100-0d08-11ea-844f-d91019b4dbb0.png)

That's all I get in Xcode.

**Comment by breautek** [comment]
> Xcode : Xcode 11.0 Build version 11A420a

Maybe consider upgrading xcode. The latest is `11.2.1` which is a version you need anyway to distribute to iTunes connect.

**Comment by aquinn637** [comment]
@breautek I updated my XCode: Version 11.3 beta (11C24b) and I'm still getting the same error.

**Comment by jcesarmobile** [comment]
Looks like your problem was a missing tmp folder as you accepted the answer on this SO question
https://stackoverflow.com/questions/58973163/xcode-tmp-strip-error-when-trying-to-make-an-archive
