### ISSUE TITLE
Variable specified in podspec pods are not getting replaced

### ISSUE THREAD

**Issue by sagrawal31** [apache/cordova-ios#721]
# Bug Report

(Apologies if I had created this issue here instead of `cordova-cli` or `cordova-ios`)

## Problem

Variables defined in `plugin.xml` which are being used `podspec` -> `pods` -> `pod` are not being replaced after installation. Running a command like:

```bash
cordova plugin add ../cordova-plugin-firebase-dynamiclinks \
    --variable IOS_FIREBASE_CORE_VERSION="5.20.2" \
    --variable IOS_FIREBASE_DYNAMIC_LINKS_VERSION="5.20.2" \
    --variable APP_DOMAIN="example.com" \
    --variable PAGE_LINK_DOMAIN="example.page.link"
```

### What is expected to happen?

The variables passed should be replaced at the time of platform/plugin installation.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'HelloCordova' do
	project 'HelloCordova.xcodeproj'
	pod 'Firebase/Core', '5.20.2'
	pod 'Firebase/DynamicLinks', '5.20.2'
end
```

### What does actually happen?

The variables are not getting replaced for Cocoapods.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'HelloCordova' do
	project 'HelloCordova.xcodeproj'
	pod 'Firebase/Core', '$IOS_FIREBASE_CORE_VERSION'
	pod 'Firebase/DynamicLinks', '$IOS_FIREBASE_DYNAMIC_LINKS_VERSION'
end
```

## Information

A pull request reproducing this problem: https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/pull/42/files#diff-53f390d375398624afe1cfe1125f42bfR106

### Command or Code

In `plugin.xml`, inside `<platform name="ios">`:

```xml
<preference name="IOS_FIREBASE_CORE_VERSION" default="~> 6.3.0"/>
<preference name="IOS_FIREBASE_DYNAMIC_LINKS_VERSION" default="~> 6.3.0"/>

<podspec>
    <config>
        <source url="https://github.com/CocoaPods/Specs.git"/>
    </config>
    <pods>
        <pod name="Firebase/Core" spec="$IOS_FIREBASE_CORE_VERSION"/>
        <pod name="Firebase/DynamicLinks" spec="$IOS_FIREBASE_DYNAMIC_LINKS_VERSION"/>
    </pods>
</podspec>
```

### Environment, Platform, Device

- **Environment:** MacOS Mojave
- **Platform:** iOS
- **Deivce:** Does not matter

### Version information

- **Cordova**: 9.0.0 (cordova-lib@9.0.1)
- **cordoav-ios**: 5.0.1

## Checklist

- [x] I searched for existing GitHub issues in (`cordoav-cli`, `cordova-lib`, `cordova-ios` & `cordova-common`
 - [x] Tried to look up the existing code where this replacement is working for Android
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by bmherold** [comment]
Any update here? I'm also looking for a solution to override cocoapod plugin.xml spec versions from my config.xml with no luck. Is there any documentation on how to do this? Currently the only workaround I've found is to directly edit the platforms/ios/Podfile and re-run `pod install`. Any pointers would be much appreciated. Thanks!
