### ISSUE TITLE
Build fails with multiple "Redefinition of Module" errors

### ISSUE THREAD

**Issue by joneill87** [apache/cordova-ios#724]
# Bug Report
When trying to build a cordova-ios project for any ios device simulators, the build fails with multiple "Redefinition of Module" errors.

## Problem
The conflict seems to be stemming from two files, *macOS 10.15/usr/include/module.modulemap* and *Simulator - iOS 13.2/usr/include/module.modulemap*. I'm guessing that the macOS 10.15 modulemap shouldn't be included, but I can't see where it's being included in the project.

### What is expected to happen?
Building a new cordova-ios project should complete successfully.

### What does actually happen?
Build failure with multiple errors (see screenshot)
<img width="1406" alt="Screenshot 2019-11-24 at 23 00 43" src="https://user-images.githubusercontent.com/3017896/69503117-8398a800-0f0e-11ea-8451-d08ee68b824a.png">

## Information

Cordova , cordova-ios and Xcode have all been freshly installed at the latest versions

Steps to recreate -
Create a new project
Add cordova-ios
Open the xcodeproj file and set codesigning identity
Build against iPhone 11 Pro Max (or any other iOS simulator)

### Command or Code

`cordova create test com.test.cordova test`

### Environment, Platform, Device

`% cordova --version
9.0.0 (cordova-lib@9.0.1)`

`% cordova platform ls
Installed platforms:
  ios 5.0.1`

Xcode Version 11.2.1 (11B500)

Build Target: any iOS simulator

Mac OS Catalina 10.15.1

### Version information

See above

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by joneill87** [comment]
## Workaround
I found a workaround for this. Following the build errors, I renamed the the folder at
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include`
to
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include_old`
and the problem seems to have gone away. Doesn't feel like a very robust fix, but it works for now. I'm no longer sure if this is a bug in cordova-ios...

**Comment by brodybits** [comment]
I really do not understand this, leaving it open for discussion for now.

**Comment by jcesarmobile** [comment]
Looks like a bad xcode install, I can’t reproduce on a new project on my computer, I don’t think this is a cordova issue
