### ISSUE TITLE
 No suitable application records were found verify your bundle identifier is correct

### ISSUE THREAD

**Issue by tamsel12** [apache/cordova-ios#729]
While uploading build i am getting  "No suitable application records were found verify your bundle identifier is correct"

**Comment by breautek** [comment]
you need to log into https://itunesconnect.apple.com/ and create a new app before you can upload your binaries via xcode.

**Comment by tamsel12** [comment]
It is not new app @breautek. It works perfectly on lastweek. In this week only i am having this problem while uploading to itunes.

**Comment by breautek** [comment]
All that I can really suggest is to:

- Ensure you're logged into the proper account in XCode
- Ensure you built your app in xcode using the proper team setting & signing certificate
- Login to developer.apple.com and ensure that you're Certificates -> Identifiers looks right

I've closed this issue as it doesn't really involve cordova-ios. If you still need assistance, a better place to ask a question like this is [Cordova Slack](http://slack.cordova.io/) or you may get more traction at the [Apple Developer Forums](https://forums.developer.apple.com/welcome)

**Comment by jesphinpt** [comment]
I am facing the above error. I have checked the bundle identifier in the General tab as well as the settings. Everything if fine but it shows the error as "No suitable application records were found. Verify your bundle identifier ‘com.facebook.sdk.FBSDKCoreKit’ is correct."

Note: It works fine still yesterday,

**Comment by AndresdoSantos** [comment]
I generated the ipa using Expo eas and now I'm trying to upload the app with transporter and I can't.
