### ISSUE TITLE
ENOENT: no such file or directory, open '... \platforms\ios\CordovaLib\CordovaLib.xcodeproj\project.pbxproj'

### ISSUE THREAD

**Issue by vitaliykoziy** [apache/cordova-ios#730]
`cordova platform rm ios`
`cordova platform add ios@5.1.0`

Returns error 

> ENOENT: no such file or directory, open ' ... \platforms\ios\CordovaLib\CordovaLib.xcodeproj\project.pbxproj'

Looks like the issue in the file "...\node_modules\cordova-ios\bin\templates\scripts\cordova\lib\prepare.js" line 333

`xcodeproj.parseSync();`

**Comment by erisu** [comment]
Duplicate: https://github.com/apache/cordova-ios/issues/725
