### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by yan2750** [apache/cordova-ios#732]
# Bug Report

### What is expected to happen?
用的cordova 4.1.1版本；
uiwebview有的时候会闪退，不是毕现的；
UIWebview的加载过程中闪退；

cordova in version 4.1.1
UIWebview crash;

my english is not very good, Please help to solve the problem quickly，very thanks！

error message:
0   libobjc.A.dylib               	0x00000001bd9b0670 objc_opt_respondsToSelector + 20
1   UIKitCore                     	0x00000001c22a0e48 -[_UIWebViewScrollViewDelegateForwarder forwardInvocation:] + 136
2   CoreFoundation                	0x00000001bdc7ffcc ___forwarding___ + 680
3   CoreFoundation                	0x00000001bdc823f0 _CF_forwarding_prep_0 + 96
4   UIKitCore                     	0x00000001c21931f4 -[UIScrollView _getDelegateZoomView] + 108
5   UIKitCore                     	0x00000001c2199ef4 -[UIScrollView _zoomScaleFromPresentationLayer:] + 48
6   UIKitCore                     	0x00000001c226b288 -[UIWebDocumentView _zoomedDocumentScale] + 60
7   UIKitCore                     	0x00000001c226f964 -[UIWebDocumentView _layoutRectForFixedPositionObjects] + 108
8   UIKitCore                     	0x00000001c226fb34 -[UIWebDocumentView _updateFixedPositionedObjectsLayoutRectUsingWebThread:synchronize:] + 64
9   UIKitCore                     	0x00000001c225e51c -[UIWebBrowserView _updateFixedPositioningObjectsLayoutAfterVisibleGeometryChange] + 64
10  UIKitCore                     	0x00000001c226bff4 -[UIWebDocumentView _updateSize] + 1088
11  Foundation                    	0x00000001be04607c __57-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_2 + 28
12  CoreFoundation                	0x00000001bdbd3ae0 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
13  CoreFoundation                	0x00000001bdbd3b30 ___CFXRegistrationPost1_block_invoke + 68
14  CoreFoundation                	0x00000001bdbd2e28 _CFXRegistrationPost1 + 396
15  CoreFoundation                	0x00000001bdbd2ac0 ___CFXNotificationPost_block_invoke + 108
16  CoreFoundation                	0x00000001bdb4ba58 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1424
17  CoreFoundation                	0x00000001bdbd23f0 _CFXNotificationPost + 1268
18  Foundation                    	0x00000001bdf34c1c -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
19  CoreFoundation                	0x00000001bdc825a4 __invoking___ + 148
20  CoreFoundation                	0x00000001bdb4b1d0 -[NSInvocation invoke] + 344
21  WebCore                       	0x00000001c5d888dc HandleDelegateSource+ 4434140 (void*) + 128
22  CoreFoundation                	0x00000001bdbf724c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
23  CoreFoundation                	0x00000001bdbf71a0 __CFRunLoopDoSource0 + 84
24  CoreFoundation                	0x00000001bdbf690c __CFRunLoopDoSources0 + 184
25  CoreFoundation                	0x00000001bdbf17d8 __CFRunLoopRun + 1068
26  CoreFoundation                	0x00000001bdbf1084 CFRunLoopRunSpecific + 480
27  GraphicsServices              	0x00000001c7e3f534 GSEventRunModal + 108
28  UIKitCore                     	0x00000001c1d61670 UIApplicationMain + 1940

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Could you please 
a) fill in the issue template
b) try to use an English description and title? (Even Google Translate would be better than Chinese - most of the team unfortunately can't understand this)

**Comment by jcesarmobile** [comment]
Your cordova version is very old, so try updating and if the problem persists create a new issue providing more information and a sample project if possible
