### ISSUE TITLE
cordova-ios @5.1.1  wkwebview not working

### ISSUE THREAD

**Issue by GHYuan928** [apache/cordova-ios#734]
iI introduced **cordova-ios** in the project, and set `<preference name="WKWebViewOnly" value="true" />` in config.xml, but I found that UIWebvView is still used when running the project. I saw that WkWebView is built-in in cordova-ios 5.1.1 version. You should not need to use a plug-in. **cordova-plugin-ionic-webview**, I don’t know what to do now, how to make WKWebView take effect

**Comment by dpogue** [comment]
You do need to use a plugin. Either the `cordova-plugin-wkwebview-engine` or `cordova-plugin-ionic-webview` will work.

**Comment by GHYuan928** [comment]
As you suggested, I added the plugin `cordova-plugin-wkwebview-engine`， 
and 
```
<preference name="WKWebViewOnly" value="true" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```
  Included in config.xml ,   Run the project ，and that UIWebvView is still used

**Comment by tamvcspk** [comment]
You need to add `<preference name="WKWebViewOnly" value="true" />` too.
