### ISSUE TITLE
App only runs fine at the first time on ios and then stucks at splash screen

### ISSUE THREAD

**Issue by sid-ihycq** [apache/cordova-ios#735]
I build my app on ios, first time i run it, everything just fine whether run in xcode or via a ipa. But when I kill the progress and restart the app, it seems the index.html hasn't been loaded. i can see 
[CDVTimer][TotalPluginStartup] in log, but i cannot find any error in it. 
both output at main.ts or script in index.html are absent, so it stucked at the splash.
this problem doesn't appears on android.

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 5.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 14 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.13.0 (/usr/local/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 11.2.1 Build version 11B500

**log of the 1st time i run it**
23:17:18.993311 +0800	MyApp	[CDVTimer][statusbar] 7.143021ms
23:17:18.993349 +0800 MyApp	[CDVTimer][mobileaccessibility] 0.170946ms
23:17:18.993387 +0800 MyApp	[CDVTimer][TotalPluginStartup] 29.050946ms
23:17:18.993871 +0800	MyApp	0x283b796c0 - NavigationState is taking a process network assertion because a page load started
23:17:18.993913 +0800	MyApp	-[WKWebView 0x14a01fc00 _scheduleVisibleContentRectUpdateAfterScrollInView]: _hasScheduledVisibleRectUpdate is true but haven't updated visible content rects for 1.09s (last update was 1.09s ago) - valid 1
23:17:18.995528 +0800	MyApp	0x14a02e418 - UIProcess is taking a foreground assertion because the view is visible
23:17:19.002477 +0800	MyApp	-[WKWebView 0x14a01fc00 _scheduleVisibleContentRectUpdateAfterScrollInView]: _hasScheduledVisibleRectUpdate is true but haven't updated visible content rects for 1.09s (last update was 1.09s ago) - valid 1
23:17:19.002526 +0800	MyApp	-[WKWebView 0x14a01fc00 _scheduleVisibleContentRectUpdateAfterScrollInView]: _hasScheduledVisibleRectUpdate is true but haven't updated visible content rects for 1.09s (last update was 1.09s ago) - valid 1
23:17:19.002569 +0800	MyApp	-[WKWebView 0x14a01fc00 _scheduleVisibleContentRectUpdateAfterScrollInView]: _hasScheduledVisibleRectUpdate is true but haven't updated visible content rects for 1.10s (last update was 1.10s ago) - valid 1
23:17:19.002609 +0800	MyApp	0x14a01fc00 -[WKWebView _updateVisibleContentRects:] finally ran 1.14s after being scheduled
23:17:19.155693 +0800	MyApp	HTHangEventCreate: HangTracing is disabled. Not creating a new event.
23:17:19.514296 +0800	MyApp	0x106858128 - ProcessThrottler::didConnectToProcess(2237)
23:17:19.514340 +0800	MyApp	0x2805043c0 - ProcessAssertion() Acquiring assertion for process with PID 2237
23:17:19.525017 +0800	MyApp	0x10685c208 - ProcessThrottler::didConnectToProcess(2236)
23:17:19.525156 +0800	MyApp	0x28051d600 - ProcessAssertion() Acquiring assertion for process with PID 2236
23:17:19.525549 +0800	MyApp	0x281e06550 - WKProcessAssertionBackgroundTaskManager - beginBackgroundTaskWithName
23:17:19.525739 +0800	MyApp	0x10685c000 - WebProcessProxy::didSetAssertionState(Foreground) taking foreground assertion for network process
23:17:19.540757 +0800	MyApp	0x106858128 - ProcessThrottler::updateAssertionNow() updating process assertion state to 2 (foregroundActivities: 1, backgroundActivities: 0)
23:17:19.540963 +0800	MyApp	0x2805043c0 - ProcessAssertion::setState(2)
23:17:19.754525 +0800	MyApp	0x14a01fc00 -[WKWebView _updateVisibleContentRects:] - scroll view state is non-stable, bailing (_dynamicViewportUpdateMode 0, _needsResetViewStateAfterCommitLoadForMainFrame 1, sizeChangedSinceLastVisibleContentRectUpdate 0, [_scrollView isZoomBouncing] 0, _currentlyAdjustingScrollViewInsetsForKeyboard 0)
23:17:19.898137 +0800	MyApp	Ionic Native: deviceready event fired after 62 ms

**log of the 2nd time i run it**
...
23:17:27.254759 +0800	MyApp	[CDVTimer][statusbar] 7.503033ms
23:17:27.254788 +0800	MyApp	[CDVTimer][mobileaccessibility] 0.133991ms
23:17:27.254817 +0800	MyApp	[CDVTimer][TotalPluginStartup] 31.901956ms
23:17:27.254905 +0800	MyApp	0x281f8a680 - NavigationState is taking a process network assertion because a page load started
23:17:27.255096 +0800	MyApp	0x11c837218 - UIProcess is taking a foreground assertion because the view is visible
23:17:27.303577 +0800	MyApp	HTHangEventCreate: HangTracing is disabled. Not creating a new event.
23:17:27.327059 +0800	MyApp	0x10093c128 - ProcessThrottler::didConnectToProcess(2242)
23:17:27.327180 +0800	MyApp	0x2821b9840 - ProcessAssertion() Acquiring assertion for process with PID 2242
23:17:27.342906 +0800	MyApp	0x100940208 - ProcessThrottler::didConnectToProcess(2241)
23:17:27.342935 +0800	MyApp	0x2821ba5c0 - ProcessAssertion() Acquiring assertion for process with PID 2241
23:17:27.342989 +0800	MyApp	0x283a9cc90 - WKProcessAssertionBackgroundTaskManager - beginBackgroundTaskWithName

**Comment by timbru31** [comment]
[...] Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, **(and 14 other plugins)**

I guess this is a plugin issue. Unfortunately, you have to debug it yourself, what plugin causes this behavior. You can also check if the problem exists in a new, plain Cordova app.

**Comment by jcesarmobile** [comment]
Yeah, agree with timbru31, I can’t reproduce on a new app, so must be a problem in your code or one of the plugins, you’ll have to do the debugging yourself.

**Comment by tryhardest** [comment]
@timbru31 did you determine what plugin it was?

**Comment by timbru31** [comment]
No, that’s something I can’t with information missing.
