### ISSUE TITLE
Problems with 5.1.1 and cordova-plugin-antitampering 0.4.2 - too many files in the release?

### ISSUE THREAD

**Issue by massic80** [apache/cordova-ios#737]
# Bug Report
## Problem
I got an app that works perfectly with cordova-ios@5.0.1 and https://github.com/duddu/cordova-plugin-antitampering 0.4.2. I attempted to update cordova-ios to 5.1.1

### What is expected to happen?
Everything works as expected (and as it did).

### What does actually happen?
Antitampering blocks the app saying that
```Anti-Tampering check failed! PathNotFoundException: No readable path retrieved for file cordova-js-src/.eslintrc.yml```

## Information
Looks like this file is present in 5.1.1 release, but not in 5.0.1; is that a release mistake (hence the file shouldn't be included, and the problem is on cordova-ios), or should the file be added (hence the problem is on cordova-plugin-antitampering)?

### Command or Code
Just build and run the app: it crashes due to expected behavior of antitampering plugin.

### Environment, Platform, Device
iOS

### Version information
Cordova 9
cordova-ios 5.1.1
cordova-plugin-antitampering 0.4.2

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
The eslint config has no purpose to the end user. It's a file for the package development only. Packages were cleaned up to remove files that has no purpose for users.

So that eslint file may not be the only file that was removed/npm ignored.

**Comment by massic80** [comment]
Wow, what a quick response! :)
I'm not sure I got what you mean: I figured out that it was for development only, but I had a doubt about possible evolutions of npm or node.
So, may we remove it from the release?

**Comment by timbru31** [comment]
Ping @erisu

**Comment by massic80** [comment]
Thanks @timbru31 : I confirm the _the file was added and was not present before_

**Comment by breautek** [comment]
Ah my bad, I think the error tripped me. Reading through the error again, it's clear I originally misunderstood.

**Comment by martinrichterlondon** [comment]
I have the same problem, how can I fix it?

**Comment by massic80** [comment]
@martinrichterlondon While it's being solved, just set
`"cordova-ios": "~5.0",`
in package.json in order to force a version less than 5.1 and `npm install` again

**Comment by martinrichterlondon** [comment]
I cannot due to UIWebView API Deprecation (https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/).

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
