### ISSUE TITLE
input type=date does not use system locale

### ISSUE THREAD

**Issue by JaegerJens** [apache/cordova-ios#740]
# Bug Report

## Problem

My app has the following input field:
```html
<input type="date" value="2019-12-15" />
```
And the system language of the iPhone is German.

### What is expected to happen?

When the user clicks on the date he expects a German date picker like in any other native app, like "15.12.2019"

### What does actually happen?

The selected date in the date picker is: "December 15 2019"

## Information

The bug is also visible in Android.

### Command or Code

Bug is reproducible with a new Cordova sample app and the HTML code from above.

### Environment, Platform, Device

iPhone 11 Pro Max emulator and real device 

### Version information

* Cordova 9.0.0
* Cordova-ios 5.1.1
* Build on macOs 10.15.2 with xCode 11.3
* run on iOS 13.1.1

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
iOS projects are in English by default. For native dialogs to be displayed in different languages your project has to support them first. For supporting languages you have to add CFBundleLocalizations to the info.plist with the supported languages.
