### ISSUE TITLE
UIWebView Warning still appears even after adding <WKWebViewOnly> to 'true' in cordova-ios@5.1.1

### ISSUE THREAD

**Issue by Sagarkhenat** [apache/cordova-ios#753]
# Bug Report

## Problem
After adding the platform to cordova-ios@5.1.1 and adding the line <preference name="WKWebViewOnly" value="true" /> in config.xml,ran cordova prepare iOS command, still received the warning mail from the apple team

### What is expected to happen?
Even after updating the platform and running the prepare command, the UIWebView should not occur and we should not receive warning mail from the apple team

### What does actually happen?
Receiving ITMS-90809 UIWebView API Deprecation warning mail

## Information
Plugins used for my ionic3 app are as follows:
cordova-plugin-camera-with-exif 1.3.1 "cordova-plugin-camera-with-exif"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.1.1-dev "InAppBrowser"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"
cordova-plugin-firebase 2.0.5 "Firebase"

Of the above plugins, I still the warnings are raised due to the firebase and inappbrowser plugins.Please do look into this issue.

**Comment by jcesarmobile** [comment]
That should be fixed in firebase and InAppBrowser plugins, in InAppBrowser is already reported and have a few pending pull requests.

**Comment by Sagarkhenat** [comment]
@jcesarmobile Do you think after the Cordova-ios@6 update comes, this issue will not occur ,I mean the warning flag being raised due to the plugins used in the project.

**Comment by breautek** [comment]
`cordova-ios` has no influence over plugin code. So if there are plugins that references the deprecated APIs, it is up to the plugin maintainers to update their plugin.

Cordova is aware that their InAppBrowser plugin still have UIWebView usages that needs to be addressed, and there are pending PRs to solve them. For the Firebase plugin, you'll have to raise the issue with their maintainers.

**Comment by rajashekaranugu** [comment]
@Sagarkhenat how did you identify the plugins that use, "UIWebView" deprecated class??

**Comment by desmeit** [comment]
In my case the folowwing plugins caused the issue:

facebook4 3.1.0
Googleplus 7.0.1
cordova-plugin-decimal-keyboard
