### ISSUE TITLE
Input button with keyboard produces error on IOS devices - Not Ioniq

### ISSUE THREAD

**Issue by fixdaddy** [apache/cordova-ios#755]
## Problem

When a page has both a keyboard and an input button (Submit), errors are reported by Xcode.

### What is expected to happen?

No errors reported

### What does actually happen?

Xcode reports this error: API error: <_UIKBCompatInputView: 0x15bd44ff0; frame = (0 0; 0 0); layer = <CALayer: 0x281b6c480>> returned 0 width, assuming UIViewNoIntrinsicMetric

## Information

List of plugins as per the config.xml file.

<plugin name="cordova-plugin-device" spec="~1.1.6" />
    <plugin name="cordova-plugin-dialogs" spec="~1.3.3" />
    <plugin name="cordova-plugin-globalization" spec="~1.0.7" />
    <plugin name="cordova-plugin-network-information" spec="~1.3.3" />
    <plugin name="cordova-plugin-vibration" spec="~2.1.5" />
    <plugin name="phonegap-nfc" spec="~1.0.4" />
    <plugin name="cordova-plugin-whitelist" />
    <plugin name="cordova-plugin-screen-orientation" spec="~3.0.2" />
    <plugin name="cordova-plugin-screensize" spec="~1.3.1" />

Attempt made without casting plugin versions (spec) with the same result.

I'm pretty sure that an earlier version of the code worked fine with a submit button, rather than an image with submit event.

I have seen people using Ionig plugin report this issue (https://github.com/ionic-team/capacitor/issues/835) , however I'm not using Ioniq plugin.

I added the cordova keyboard plugin, which didn't fix the issue.

Note that the error is generated as soon as the keyboard is "opened" when the focus in on the text field.

### Command or Code

HTML 
`	<div id="game_name_field" class="result_frame">
			<label for="form_game_name" id = "game_name_label">Game Name</label>
			<input type="text" name="form_game_name" id="form_game_name" class = "wheat_field"> 
		</div> 
		<div id="game_name_btn_div">
			<input id = "game_name_btn" type="image" src="./img/submit_button.png" border="0" alt="submit"/>	
		</div> `

Javascript

`$("#game_name_btn").click(function(){
			document.getElementById("game_name_field").style.display = 'none';
			document.getElementById("game_name_btn_div").style.display = 'none';
			function_treating_content_of_textfield(); 
			});`

### Environment, Platform, Device

Mac +
Devices : Iphone 6 Plus and Iphone 8 plus (same problem)

### Version information

Cordova CLI 9.0.0
Xcode 11.3

## Checklist

- [X ] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Those are Apple issues than only Apple can fix, so report it in their tracker.
Anyway, other than the ugly message on Xcode, doesn’t really seem to cause any issues on the app (or I haven’t noticed anything at least)
