### ISSUE TITLE
Focus on input skip to the next one or lose focus, keyboard flickers

### ISSUE THREAD

**Issue by samuelbeaulieu** [apache/cordova-ios#757]
# Bug Report
After multiple tests, I think it's safe to say this problem only affect iOS.
Clicking on input fields makes the keyboard flickers, sometimes the focus jump to the next input, the input doesn't always stay focused(sometimes the keyboard stay while not focused, sometimes it disappear).

### What is expected to happen?
When I click on an input field, it should focus on the right input, stay focused.

### What does actually happen?
When I click on an input, the input doesn't always stay focus.
When I click on an input, the input sometimes jump to the next one under it.
When I switching inputs, the keyboard flickers.

## Information
Create a new cordova project.
Add the iOS platform.
Add 10-20 inputs.
Click on them from top to bottom.

### Command or Code
```
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="initial-scale=1, width=device-width, viewport-fit=cover">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title>Hello World</title>
    </head>
    <body>
        <div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
                <input type="text" style="background-color: #f00;">
                <input type="email" style="background-color: #0f0;">
                <input type="password" style="background-color: #00f;">
                [ ... ]
            </div>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </body>
</html>
```

### Environment, Platform, Device
Problem occurs on iOS only.
Tested with different phones on different versions.
iPhone 11 Pro iOS 13.2.3
iPhone X iOS 13.2.3
iPhone 8 Plus iOS 13.1.1
iPhone 7 iOS 12.4.1
iPhone SE iOS 12.3

### Version information
Cordova CLI: 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms: iOS@5.0.1 &  iOS@5.1.1
Operating System: MacOS Mojave version 10.14.6 (18G103)
Xcode: Version 11.2.1 (11B500)

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by brodybits** [comment]
This issue is transferred to cordova-ios. It would really help if you could post a demo Cordova project on GitHub (no plugins or platforms directories should be included in the demo Cordova project).

The cordova-ios and other Cordova maintainers are pretty overloaded. I would highly recommend that you continue to followup with us on Slack or on the mailing list, please follow the links in the footer of cordova.io or cordova.apache.org.
