### ISSUE TITLE
How to replace 'CDVRemoteNotification' in platform ios@5.1.1

### ISSUE THREAD

**Issue by chary2060** [apache/cordova-ios#758]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
I add plugin cordova-plugin-push-baidu in my cordova project,and then run cmd 'cordova build ios'
It goes wrong .I open the ios project to see the error: Use of undeclared identifier 'CDVRemoteNotification'.

I find that  'CDVRemoteNotification' has been removed in cordova ios@5.1.1.
I'm an entry-level Cordova programmer.So how to deal with it? can anyone help me?tks
### Version information

Cordova CLI - 8.0.0
Cordova Platforms ios - 5.1.1
Cordova Plugins : cordova-plugin-push-baidu - 5.6.1
Xcode - 11.2.1

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
I looked in the 4.5.x branch and even the 3.x and saw no `CDVRemoteNotification` class in the sources. Are you sure that file originally comes from `cordova-ios`?

**Comment by breautek** [comment]
This may help:

https://github.com/apache/cordova-ios/blob/master/guides/API%20changes%20in%204.0.md#deprecated

> These constants were unfortunately not removed in 4.0, but will be removed in 5.0. Local and remote push notification functionality was removed in the core in 4.0.

Any plugins that rely on these constants will need to be updated to support 5.x. Since the functionality has been removed, you probably will have to find a plugin that introduces that functionality again.

I'm not sure of any notification plugins myself, but you can probably ask on our [slack](http://slack.cordova.io/)

**Comment by chary2060** [comment]
> This may help:
> 
> https://github.com/apache/cordova-ios/blob/master/guides/API%20changes%20in%204.0.md#deprecated
> 
> > These constants were unfortunately not removed in 4.0, but will be removed in 5.0. Local and remote push notification functionality was removed in the core in 4.0.
> 
> Any plugins that rely on these constants will need to be updated to support 5.x. Since the functionality has been removed, you probably will have to find a plugin that introduces that functionality again.
> 
> I'm not sure of any notification plugins myself, but you can probably ask on our [slack](http://slack.cordova.io/)

Thank you very much for your help.I finally decide to replace the previous  plugin with  a different one that doesn't use ‘ CDVRemoteNotification’.

**Comment by jcesarmobile** [comment]
Yeah, you need a different plugin, those constants were deprecated in 2015, so if that plugin was last updated in 2017, it shouldn't have been using it.

This is the JIRA ticket for reference:
https://issues.apache.org/jira/browse/CB-8474
