### ISSUE TITLE
Some requests are failing with error NSURLConnection finished with error - code -1015

### ISSUE THREAD

**Issue by ctaque** [apache/cordova-ios#759]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
Some request from the app are failing : "NSURLConnection finished with error - code -1015"

Case:
If have have an app, witch from the index redirects to a website.
in this website, there is a script which loads a payment form on a specific page (hipay sdk js)
this script, should create for each form field an iframe with the field.

debug: 
Emulate the app with xcode, open device inspector in safari
You can try by yourself with the app from the app store : [https://apps.apple.com/fr/app/cinewest/id1484930134](https://apps.apple.com/fr/app/cinewest/id1484930134)

What I see : 

Sometimes some fields load correctly but most of the time, they all fails to load with theses errors : 
is safari console : "Failed to load resource: cannot decode raw data" at the urls pointing to 
"libs.hipay.com/hostedfields/index.html#type=card&element=value&instanceId=value"
in xcode console: "NSURLConnection finished with error - code -1015"

### Environment, Platform, Device

Environment iphone 6s 12.1 & 13 (unknown with other versions)
Platform ios only

### Version information

Cordova platform ios version 5.0.1 & 5.1.1
Cordova version 9.0.0

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by vagnersabadi** [comment]
I am also facing this problem.
When running in test mode with **ionic cordova run ios -l** it runs smoothly, but when I compile and run it through xocde a white screen occurs

![Captura de Tela 2020-02-03 às 18 13 52](https://user-images.githubusercontent.com/12532889/73691353-f2357700-46b0-11ea-9062-e9e6b92dd620.png)

**Comment by breautek** [comment]
`Cannot decode raw data` generally means that the server sent something that is unexpected, or not supported by iOS.

https://developer.apple.com/documentation/foundation/1508628-url_loading_system_error_codes/nsurlerrorcannotdecoderawdata?language=objc

I see this often when the content is gzipped, which the safari implementation appears to have buggy support for. If possible, I'd try to disable gzip encoding on the server, to at least confirm that this is the issue.

**Comment by vagnersabadi** [comment]
Try it
https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d
