### ISSUE TITLE
ITMS-90809 UIWebView API deprecation notice on Cordova-iOS 5.1.1 (still)

### ISSUE THREAD

**Issue by erikyuzwa** [apache/cordova-ios#761]
There are a few related support issues already, but I'm only creating this new one to try and prevent the existing ones from being open forever while people are attempting to address this issue in their own projects.

I've been going through the existing issues and am still getting the deprecation warning email from Apple.

`./config.xml`
```
<platform name="ios">
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>

        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
        <preference name="WKWebViewOnly" value="true" />
       <!-- // snip -->
</platform>
```
and my `plugins` from `package.json`:
```
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-file": {},
      "cordova-plugin-zip": {},
      "cordova-plugin-file-downloader": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-sqlite-storage": {},
      "cordova-plugin-google-analytics": {
        "GMS_VERSION": "11.0.1"
      }
    },
```
Just wondering if there's anything obvious I've really missed in the configuration, as it sounds like the updated `cordova-ios` is helping some (most?) already -- which is great!

**Comment by jcesarmobile** [comment]
It’s google analytics plugin

**Comment by erikyuzwa** [comment]
You had me all excited @jcesarmobile but that **wasn't** it. Plugin removed, project cleaned and resubmitted. Same deprecation email.

**Comment by jcesarmobile** [comment]
Remove the platform and add it again, maybe the analytics framework wasn’t removed

**Comment by erikyuzwa** [comment]
amazing @jcesarmobile - I think that was it. I'm getting it into Testflight now, without receiving the deprecation email. Thank you so much 🙇
