### ISSUE TITLE
iOS Sms textfield resigned instantly.

### ISSUE THREAD

**Issue by VishnuV02** [apache/cordova-ios#762]
While trying to send SMS using SMS plugin method,
this.sms.send(this.smsTo, this.SMSMessage).then((data) => {});
SMS Textfield resigned instantly. What may be the reason?

Step 1: I am calling this.sms.send(this.smsTo, this.SMSMessage).then((data) => { alert("SMS SUCCESS3"); }, (err) => { alert("SMS FAILED3"); }); from ionic

Step 2: MessageViewController opened successfully and the recipient and message passed got displayed .

Step 3: Instantly message dialog(keypad) got disappeared.
Step 4: If i clicks on recipient field(To field), message dialog getting appeared.

Please let me know the reason, why keypad is disappearing while loading SMS plugin?

**Comment by brodybits** [comment]
This looks like an issue with a third-party plugin, please seek support there.
