### ISSUE TITLE
WebGL2 experimental support on iOS?

### ISSUE THREAD

**Issue by onelsonic** [apache/cordova-ios#772]
With Safari on iOS, we can unable webGL2 as an experimental feature and it works.

With Cordova iOS, is there a way to do the same?
It seems like webGL2 is not working.

The Webview used by Cordova iOS, is not the one from Safari/WebKit ?

Is there a way or a workaround to make it work?

**Comment by timbru31** [comment]
There are two types of webviews a Cordova app can use currently: UIWebView (default, deprecated) and WKWebView. Have you tried if the feature is supported on WKWebView? You'll need this plugin https://github.com/apache/cordova-plugin-wkwebview-engine, though. However, I'm not sure what effect the "Experimental Features" have on WebViews besides Safari.

Given that's an **exerpimental** feature, I'll doubt that Apple will enable it outside of Safari, even if WKWebViews are used.

**Comment by jcesarmobile** [comment]
No, experimental features don't have any effect on webviews.

**Comment by onelsonic** [comment]
ok thank you for your feedback. Only hope is waiting for it to not be experimental anymore....
too bad
