### ISSUE TITLE
New podspec syntax not adding to Podfile

### ISSUE THREAD

**Issue by jacobg** [apache/cordova-ios#776]
# Bug Report

### What is expected to happen?

Plugins use new `podspec` syntax, and the dependencies get added to Podfile.

### What does actually happen?

The dependencies are not added to the Podfile.
Plugins using the old `<framework type="podspec"` syntax do get aded.

All dependencies do get added to pods.json though.

## Information
Here's an example where the new syntax doesn't work, and old one does.

New syntax:
```xml
        <podspec>
            <config>
                <source url="https://cdn.cocoapods.org/">
            </config>
            <pods>
                <pod name="Firebase/MLVision" spec="~> 6.3.0" />
                <pod name="Firebase/MLVisionFaceModel" spec="~> 6.3.0" />
                <pod name="OpenCV2" spec="~> 4.2.0" />
            </pods>
        </podspec>
```

Old syntax:
```xml
        <framework src="Firebase/MLVision" type="podspec" spec="~> 6.3.0" />
        <framework src="Firebase/MLVisionFaceModel" type="podspec" spec="~> 6.3.0" />
        <framework src="OpenCV2" type="podspec" spec="~> 4.2.0" />
```

### Command or Code
```
cordova prepare
cordova build ios --buildConfig=./build.json
```

### Environment, Platform, Device
MacOS Catalina

### Version information
I am running:
```
jacob$ cordova -v
9.0.0 (cordova-lib@9.0.1)
```
```
jacob$ cordova platform
Installed platforms:
  android 8.1.0
  browser 6.0.0
  ios 5.1.1
Available platforms:
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0
```
```
jacob$ pod --version
1.8.4
```

I also tried `cordova-ios` versions 5.0.0 and 5.1.0, and those don't work either.

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by brodybits** [comment]
I am not an expert in this area, hope another maintainer can take a look at this. I would *highly* recommend that you post a [minimal, reproducible example ([1])](https://stackoverflow.com/help/minimal-reproducible-example) projects with plugins that can demonstrate what does and does not work correctly. I am adding the **help wanted** label for now.

[1] https://stackoverflow.com/help/minimal-reproducible-example

**Comment by jacobg** [comment]
Hi @brodybits. Hope you're well. Thanks for forcing me to make a minimal example! I quickly discovered the problem was that my project was using the plugin `cordova-plugin-cocoapod-support`. I don't even remember when I added that plugin. My project is 5 years old. But it's definitely not necessary anymore, and in fact breaks the new podspec syntax. Removing it  resolves the issue. Thanks again!

**Comment by robations** [comment]
> I quickly discovered the problem was that my project was using the plugin `cordova-plugin-cocoapod-support`

Same issue here — many hours of confusion. Thanks for documenting the solution.
