### ISSUE TITLE
Source type must be UIImagePickerControllerSourceTypeCamera

### ISSUE THREAD

**Issue by hamcher** [apache/cordova-ios#778]
I'm using `<input type="file" accept="image/png, image/jpeg" capture="environment" />` in html, but i have this execption in console when i clicked in Photo library
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Source type must be UIImagePickerControllerSourceTypeCamera'

**Comment by jcesarmobile** [comment]
input file is handled by the webview, not by Cordova.

Make sure you are using WKWebView, and you are, report the issue to Apple
