### ISSUE TITLE
*-Info.plist & config.xml - general

### ISSUE THREAD

**Issue by brodycj** [apache/cordova-ios#793]
__updated:__

There seem to be quite a few outstanding issues with *-Info.plist and config.xml, not sure if they are all the same or not:

- <https://github.com/apache/cordova-common/issues/88>
- #764
- #775
- #826 - testing: removing an internal *-Info.plist filter does not cause a test failure (BREAKING TEST PR #792 does not cause a failure)

I personally do not understand this mechanism so well, raising this issue with the **help wanted** label for now. In case this issue is a duplicate, we can close it.

**Comment by brodybits** [comment]
I wonder if <https://github.com/apache/cordova-common/pull/148> may be related
