### ISSUE TITLE
Want to remove UIWebView from my Cordova Project in monaca for the latest issue from the Apple which was it cannot be accepted after April 2020. 

### ISSUE THREAD

**Issue by anishadh3892** [apache/cordova-ios#804]
# Bug Report
We identified one or more issues with a recent delivery for your app,
"XXXXX" 1.0 (1.0). Your delivery was successful, but you
may wish to correct the following issues in your next delivery:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions
of apps that use UIWebView APIs starting from April 2020 . See
https://developer.apple.com/documentation/uikit/uiwebview for more
information.
After you've corrected the issues, you can upload a new binary to App
Store Connect.

## Problem
Even Im not using the InApp Browser in my app I get this message from apple when I try to release my app.

### What is expected to happen?
It wanna be uploaded(released without error message)

### What does actually happen?
I try to release my app and the above Error Occurred.

## Information
Even I'm not using in app browser why i wanna change UIWebView to WKWebView.
No need of it. So I need a solution for the people who don't use InAppBrowser plugin cordova

### Version information
Cordova9 in Monaca

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
With the versions that are currently released, make sure that you are:
* using `cordova-ios@5.1.1`
* add plugin `cordova-plugin-wkwebview-engine`, preferably the latest version `1.2.1`
* add the following `preference` flag `WKWebViewOnly` to the `config.xml` iOS platform element.

E.g.

```
<platform name="ios">
    <preference name="WKWebViewOnly" value="true" />
</platform>
```

If you are still getting the warning, most likely one of the plugins you are using still references `UIWebView` which the plugin developers will need to fix.

**Comment by anishadh3892** [comment]
Thank you so much for your reply. It helped me a lot.

**Comment by anishadh3892** [comment]
Sorry to interrupt you so many times.
If i do that my login screen disappeared.
any suggestions?

**Comment by anishadh3892** [comment]
> With the versions that are currently released, make sure that you are:
> 
> * using `cordova-ios@5.1.1`
> * add plugin `cordova-plugin-wkwebview-engine`, preferably the latest version `1.2.1`
> * add the following `preference` flag `WKWebViewOnly` to the `config.xml` iOS platform element.
> 
> E.g.
> 
> ```
> <platform name="ios">
>     <preference name="WKWebViewOnly" value="true" />
> </platform>
> ```
> 
> If you are still getting the warning, most likely one of the plugins you are using still references `UIWebView` which the plugin developers will need to fix.

Sorry to interrupt you so many times.
If i do that my login screen disappeared.
any suggestions?

**Comment by breautek** [comment]
> If i do that my login screen disappeared.

There is likely an error that is happening. We'll need to see it to provide more insight. First I'd start with the javascript console for javascript errors, which you can find by using the Safari Remote Inspector.

If nothing shows up there, then I'd use xcode to debug your app as the problem might be on the native side.

**Comment by erisu** [comment]
I also forgot to mention that you need to add to `config.xml` the WKWebView plugin configurations. Example below shows what is needed in the ios platform element:

```
<platform name="ios">
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>

    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
</platform>
```

Also, Monaca just released the ability to set the WKWebView easily within the app setting screen. It would add the plugin and set the configurations for you.

If you still see the white screen even with the WKWebView plugin configurations added, I would also recommend following what @breautek suggested above.

**Comment by anishadh3892** [comment]
Thank you So much for your reply. Your Method worked and helped me a lot.

**Comment by biswas123** [comment]
> > With the versions that are currently released, make sure that you are:
> > 
> > * using `cordova-ios@5.1.1`
> > * add plugin `cordova-plugin-wkwebview-engine`, preferably the latest version `1.2.1`
> > * add the following `preference` flag `WKWebViewOnly` to the `config.xml` iOS platform element.
> > 
> > E.g.
> > ```
> > <platform name="ios">
> >     <preference name="WKWebViewOnly" value="true" />
> > </platform>
> > ```
> > 
> > 
> > If you are still getting the warning, most likely one of the plugins you are using still references `UIWebView` which the plugin developers will need to fix.
> 
> Sorry to interrupt you so many times.
> If i do that my login screen disappeared.
> any suggestions?

Hey there! How did you fix the login screen disappearing issue after installing the plugin..
I also put the configuration on config.xml file but still get white screen after app startup.. And I cannot find any error logs on xcode or safari logs.

**Comment by jagovea** [comment]
Hello, I still have a lot of problems. I have my XML as follows

`<?xml version="1.0" encoding="UTF-8" ?>
<widget xmlns       = "http://www.w3.org/ns/widgets"
        xmlns:gap   = "http://phonegap.com/ns/1.0"
        id          = "com.midi"
        versionCode = ""
        version     = "0.12.35" >
 <engines>
	<engine name="cordova-ios" version="=5.1.1" />
  </engines>

	<name>TEST</name>
	<description>TEST</description>
	<author href="https://www.llorenteycuenca.com" email="agovea@llorenteycuenca.com">LLYC</author>
	
	<platform name="ios">
		<feature name="CDVWKWebViewEngine">
			<param name="ios-package" value="CDVWKWebViewEngine" />
		</feature>
		
		<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
		<preference name="WKWebViewOnly" value="true" />
	</platform>
	
	<plugin name="cordova-plugin-wkwebview-engine" source="npm" />
</widget>
`

I would appreciate your help. Thank you

**Comment by jagovea** [comment]
Hello, I still have a lot of problems. I have my XML as follows

<name>TEST</name>
<description>TEST</description>
<author href="https://www.test.com" email="mail@mail.com">TEST</author>

<platform name="ios">
	<feature name="CDVWKWebViewEngine">
		<param name="ios-package" value="CDVWKWebViewEngine" />
	</feature>
	
	<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
	<preference name="WKWebViewOnly" value="true" />
</platform>

<plugin name="cordova-plugin-wkwebview-engine" source="npm" />

I would appreciate your help. Thank you

**Comment by jagovea** [comment]
Hello, I still have a lot of problems. I have my XML as follows
`



<name>TEST</name>
<description>TEST</description>
<author href="https://www.test.com" email="mail@mail.com">TEST</author>

<platform name="ios">
	<feature name="CDVWKWebViewEngine">
		<param name="ios-package" value="CDVWKWebViewEngine" />
	</feature>
	
	<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
	<preference name="WKWebViewOnly" value="true" />
</platform>
<plugin name="cordova-plugin-wkwebview-engine" source="npm" />`

I would appreciate your help. Thank you

**Comment by jagovea** [comment]
Hello, I still have a lot of problems. I have my XML as follows

`<name>TEST</name>
<description>TEST</description>
<author href="https://www.test.com" email="mail@mail.com">TEST</author>

<platform name="ios">
	<feature name="CDVWKWebViewEngine">
		<param name="ios-package" value="CDVWKWebViewEngine" />
	</feature>
	
	<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
	<preference name="WKWebViewOnly" value="true" />
</platform>

<plugin name="cordova-plugin-wkwebview-engine" source="npm" />
`

I would appreciate your help. Thank you
