### ISSUE TITLE
ITMS-90381: Too many symbol files

### ISSUE THREAD

**Issue by sebastian-zarzycki-apzumi** [apache/cordova-ios#806]
# Bug Report

## Problem
I'm not sure if this is the correct place to submit, but I couldn't think of any better.
Basically, I've recently switched to cordova-ios 5.1.1 and cordova 9.0.0 for my Ionic app. I'm using the modern build system for iOS (no legacy system). I'm using several plugins that use cocoapods (firebasex, login via facebook, login via google, etc.). After submitting a build to Apple, they've responded with "Too many symbol files" warning. Usually, this was solved by

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end
```

added the Podfile, but it doesn't seem to be working now. 

I've noticed that when I open the XCode workspace and select the Pods project, every Pod has indeed set debug information format to DWARF, but only for Debug target, where for Release target, it says "DWARF with dSYM". Switching it manually back to just "DWARF" seems to solve it (Apple doesn't complain about the symbols).

Perhaps this should be some kind of array, i.e. `config.build_settings['DEBUG_INFORMATION_FORMAT'] = ['dwarf', 'dwarf']?` - I'm not familiar with the format here.

![Screenshot 2020-03-04 at 18 31 48](https://user-images.githubusercontent.com/11352013/75906701-60539200-5e47-11ea-868a-5b7177cbd6ee.png)

Should this be supported by cordova-ios by default?

Also: Cocoapods version - 1.9.0 - might be relevant.

### What is expected to happen?
No warnings from Apple.

### What does actually happen?
I understand that some additional symbols are copied to the resulting release binary, and they shouldn't. I'm confused as to which part of the compilation stack should be responsible for it (cordova? cordova-ios? plugin author?)

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by th3hamm0r** [comment]
+1

**Comment by timbru31** [comment]
Have you followed, e.g., https://github.com/dpa99c/cordova-plugin-firebasex#strip-debug-symbols?

@th3hamm0r - +1 comments are not helpful, please use GitHub's reaction system instead, otherwise you trigger notifications (and event emails) for many people.

**Comment by sebastian-zarzycki-es** [comment]
Yes, I did.

**Comment by th3hamm0r** [comment]
@timbru31 I'm not using this plugin, I think cordova-ios needs this or some other handling to avoid unnecessary dsyms from CocoaPods. In my case those UUIDs from the ITMS warning all reference armv7-dsyms, which are not needed starting with iOS 11

@sebastian-zarzycki-es fyi, for me it worked by adding those lines to the Podfile AND executing `pod install` inside the "platforms/ios" folder. But of course, this is only a temporary solution.

**Comment by sebastian-zarzycki-es** [comment]
`pod install` does nothing for me. The Release subvalue is still pointing to Dwarf with dSYM. I have to switch this manually every time for now.

**Comment by th3hamm0r** [comment]
I've now tried some other things and it seems like the issue is already solved by CocoaPods (see referenced [GH](https://github.com/CocoaPods/CocoaPods/issues/7111) issue in https://stackoverflow.com/a/50582315), so instead of the `post_install` code I did the following:
1. change the platform in the `Podfile` from 10.0 to 11.0 (my xcode project is already set for 11.0, only the Podfile is set to 10.0)
2. execute `pod install` inside the "platforms/ios" folder

Now the generated app archive only contains dsyms for the relevant archs (arm64).
@sebastian-zarzycki-es Is this working for you?

But changing the deployment target in the Podfile is still a temporary solution. Actually there is a "deployment-target" preference for the config.xml, but changing this to "11.0" does not change the Podfile atm. I've found a related issue: https://github.com/apache/cordova-ios/issues/580

**Comment by HansKrywaa** [comment]
Any further information about this? Happened to me now and i don't what change caused this. I don't want to enable Firebase's `IOS_STRIP_DEBUG` to keep the Crash Reports. But it is just a warning and can be used for production?

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
