### ISSUE TITLE
Cordova iOS App battery draining in iOS 13.3.1

### ISSUE THREAD

**Issue by cvinodhkumar77** [apache/cordova-ios#807]
# Bug Report

## Problem
We have a developed a Angular App packaged with Cordova framework. After the initial release, we got complaints like battery getting drained too fast and phone is getting warmer after using it for sometime. We have analysed the issue and found this happens when I try to use camera for scanning (using JUMIO plguin) the document. And we also noticed when I keep scrolling in any page where I can scroll up and down I can feel the device getting warmer. I have analyzed further using iOS tool Instrument and noticed that when performing above two mentioned action I can see the spikes in the Instrument logs. We are not sure how to resolve this or is there any way we can dig much deeper on this. Below is the plugins and iOS versions we are using.

### What is expected to happen?
Battery should not drain faster or phone should not get warmer

### What does actually happen?
Battery is draining faster and phone is getting warmer

## Information

Plugins Used:

"cordova-ios": "^5.1.1",
"cordova-open-native-settings": "^1.5.2",
"cordova-plugin-device": "^2.0.3",
"cordova-plugin-device-name": "^1.3.5",
"cordova-plugin-dialogs": "^2.0.2",
"cordova-plugin-firebase-crashlytics": "^1.0.0",
"cordova-plugin-geolocation": "^4.0.2",
"cordova-plugin-inappbrowser": "^3.2.0",
"cordova-plugin-infineasdk": "file:InfineaSDKCordova",
"cordova-plugin-ios-keychain": "git+https://github.com/ionic-team/cordova-plugin-ios-keychain.git",
"cordova-plugin-jumio-mobilesdk": "git+https://github.com/Jumio/mobile-cordova.git#v3.5.0",
"cordova-plugin-network-information": "^2.0.2",
"cordova-plugin-statusbar": "^2.4.3",
"cordova-plugin-touch-id": "^3.4.0",
"cordova-plugin-whitelist": "^1.3.4",
"ios": "^5.1.1",
"ncp": "^2.0.0",
"phonegap-plugin-barcodescanner": "^8.1.0"

### Version information

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by NiklasMerz** [comment]
Please make sure this is not a plugin issue. You could remove third party plugins and test your app again. If you find the plugin that causes the problem open an issue there.

I don't think is a cordova-ios issue.

**Comment by jcesarmobile** [comment]
yeah, not a cordova-ios issue, closing

**Comment by cvinodhkumar77** [comment]
Thanks for the response.  We will test and update
