### ISSUE TITLE
CSS Fonts, CSS Font Icons and CSS Background Images not loaded

### ISSUE THREAD

**Issue by angjelkom** [apache/cordova-ios#811]
# Bug Report

## Problem
PNG images referenced in css files, and css fonts and css font icons don't get loaded sometimes on ios

### What is expected to happen?
CSS font icons, css fonts and png images referenced in css files should get loaded and displayed normally

### What does actually happen?
Sometimes the png images referenced in css files don't get loaded so users reported seeing empty area in the place of the image, also css fonts doesn't get loaded so the user sees the fallback standard font, and in the case of css font icons the user sees outlined square box in the place of the image

## Information

The issue happens only on iOS

### Command or Code

- CSS Fonts
- CSS Font icons
- CSS PNG images

### Environment, Platform, Device

- Iphone 8
- iOS 13.3.1

### Version information

Cordova: 9.0.0 (cordova-lib@9.0.1)
Cordova Platform: ios 5.1.1
Cordova Plugins:
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-calendar 5.1.5 "Calendar"
cordova-plugin-chooser 1.2.6 "Chooser"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-deeplinks 1.1.1 "Cordova Deeplinks Plugin"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 7.0.2 "Google Firebase Plugin"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-network-information 2.0.3-dev "Network Information"
cordova-plugin-printer 0.8.0 "Printer"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"

XCode: 11.3.1

## Checklist

- [ x ] I searched for existing GitHub issues
I've found only this similar case #701 
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

**Comment by gabrielsclimaco** [comment]
+1

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
