### ISSUE TITLE
Pause/Resume Event for iOS after phone call

### ISSUE THREAD

**Issue by anujdevzone** [apache/cordova-ios#815]
* **Problem**
Does the iOS app go to the background when we make the call using tel://123456789
How to push the app in background while making a call functionality.
---
I have an iOS app that requires to log any outbound event happening through our app (like sending mail, calling, etc).
we use some thing like : ```<a href="tel://123456789"></a>```
In this case dialler opens up and makes the call and when we disconnect the call app is already on foreground and either of  pause or resume events never gets triggered . So basically we dont have hook/event after the call was ended to make the log entry for call . Though while replicating the same flow on android proper events(resume, pause) gets fired.

**Comment by webcodepl** [comment]
I had the same problem, how to hook after the call was ended. Finally i used active/resign events which on iOS works similar to resume/pause

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
