### ISSUE TITLE
App's webview goes underneath statusbar.

### ISSUE THREAD

**Issue by colonelpopcorn** [apache/cordova-ios#817]
# Bug Report

## Problem
When the application webview is resized, the app can end up underneath the status bar on iOS > 7. See this help article.
https://developer.apple.com/library/archive/qa/qa1797/_index.html
### What is expected to happen?
Expect that the statusbar is taken into account with cordova's webview. My app should not slide underneath the statusbar.

### What does actually happen?
When native elements (photo picker, permissions modal, etc.) cause the webview to resize the app slides underneath the statusbar. Even when I use the statusbar plugin to set overlaysWebView to false.

## Information

Want to make sure that the changes from iOS 7 forward are taken into account? Is the statusbar supposed to be handled via a plugin? If so, how can we verify that the window will not slide under the statusbar.

### Version information

cordova-ios: ^5.1.1
iOS 13.1-13.4
Ionic 5.4.16

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
I think that problem was fixed in statusbar plugin (but not released yet), anyway, not a cordova-ios issue.
Also, I wouldn't recommend using statusbar plugin to avoid the statusbar, nowadays you can use css safe areas
