### ISSUE TITLE
Element hierarchy missing/load html elements for wkWebView for iOS 13.0 or newer versions on real devices and simulators

### ISSUE THREAD

**Issue by shivani-rana** [apache/cordova-ios#818]
Issue with iOS 13.0 or newer versions.

HTML elements are not loaded for inspection with appium inspector

Steps to reproduce :
1. Open appium inspector 
2. Add capabilities for app with list items on iOS 13.0 device or newer iOS versions
3. Add capabilities in Appium desktop and inspect elements

![Picture 1](https://user-images.githubusercontent.com/58557232/78221901-dd733500-74e1-11ea-927c-322eec251728.png)

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
