### ISSUE TITLE
Text selection does not happen on iOS 13.4

### ISSUE THREAD

**Issue by murilospinoza** [apache/cordova-ios#819]
# Bug Report

## Problem

After updating the iPad and iPhone to version 13.4, selecting the text by holding and dragging is no longer working. we've tested it in 2 ionic 4 apps and in both, the text selection didn't work.

https://drive.google.com/file/d/12f-TX9VKKhXyt0hXb5bJCuKQhizGeZb0/view?usp=sharing

### Code

```html
<div class="selectable">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, se
  eiusmod tempor incididunt ut labore et dolore magna aliqua.
  Ut enim ad minim veniam, quis nostrud exercitation laboris.
</div>
```
```css
.selectable {
  -webkit-user-select: text;
  -moz-user-select: text;
  -ms-user-select: text;
  user-select: text;
}
```

### Environment, Platform, Device

Latest iOS version (13.4) in iPad or iPhone

### Version information

```
Ionic:
   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.13.10
   @angular-devkit/schematics    : 7.3.10
   @angular/cli                  : 7.3.10
   @ionic/angular-toolkit        : 1.5.1

Cordova:
   Cordova CLI       : 8.0.0
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 23 other plugins)

Utility:
   cordova-res : 0.11.0
   native-run  : not installed

System:
   NodeJS : v12.14.1 (/usr/local/bin/node)
   npm    : 6.14.2
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61
```

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by taozhzzl** [comment]
Yes, but selection with an iPad connected to a mouse or trackpad still works. I think it’s a problem due to the new cursor system and updated touch interactions. Looking forword to a solution.

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by taozhzzl** [comment]
I tried another time, selection with a tap and tap-drag still works. But the original long-tap gesture no longer triggers selection. And the long-tap gesture still works in Safari and InappBrowser. All in all, there is a little bit different with selection in iOS 13.4 (along with iPadOS 13.4).

**Comment by jcesarmobile** [comment]
This is an Apple bug, it's already reported https://bugs.webkit.org/show_bug.cgi?id=210191
As workaround you can add this preference in the config.xml `<preference name="AllowLinkPreview" value="true" />`

**Comment by taozhzzl** [comment]
> This is an Apple bug, it's already reported https://bugs.webkit.org/show_bug.cgi?id=210191
> As workaround you can add this preference in the config.xml `<preference name="AllowLinkPreview" value="true" />`

Thanks! But I followed your instructions the problem still exists. Text selection could only be triggered with a tap + tap-hold gesture (Only tap-hold originally.) Will this be solved by Apple in the future?

**Comment by jcesarmobile** [comment]
Ah, sorry, that's for ionic wkwebview plugin, in Apache wkwebview plugin the preference is `<preference name="Allow3DTouchLinkPreview" value="true" />`, but true is the default value.

If you are using a different wkwebview plugin or UIWebView might be a different preference or not configurable.

According to the link it's been fixed by Apple already, but not released yet, not sure in which iOS version will be included.

**Comment by taozhzzl** [comment]
Thanks and that's the case! I'm using Apache wkwebview plugin, developers who encountered this problem, set two preferences in Cordova config.xml, and disable 'dragstart' event in javascript, text selection works fine and 3D touch gesture is disabled as usual in iOS 13.4 (along with iPadOS 13.4):

config.xml :
```
<preference name="Suppresses3DTouchGesture" value="true" />
<preference name="Allow3DTouchLinkPreview" value="true" />
```

your app.js :
```
$$('body').on('dragstart', 'a, img', function (e) {
  e.preventDefault();
});
```
