### ISSUE TITLE
WkWebView breaks iframe working from "cordova.file.dataDirectory" file://

### ISSUE THREAD

**Issue by jurihahn** [apache/cordova-ios#827]
# Bug Report

## Problem
if i use WkWebView loading HTML file to iframe I get error:
WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox
its happened only if I try to load HTML file not from app self. I download a HTML file and start it from App-Data folder "cordova.file.dataDirectory".

### What is expected to happen?
iframe should load HTML page from "file://" protocol. May be its need an Option to allow some URL's

### What does actually happen?
Error: WebPageProxy::Ignoring request to load this main resource because it is outside the sandbox

## Information
I try to switch from UIWebView to WkWebView and this is last Problem.
I have found information about this Problem https://stackoverflow.com/questions/40123321/wkwebview-run-local-html-in-document-received-an-unexpected-url-from-the-web-p
but how can I provide my URL to this function to allow loading?
this is added to config
< allow-navigation href="*" / >
< allow-navigation href="file://*" / >
< allow-intent href="file://*" / >
< allow-intent href="*" / >

Test Project https://github.com/jurihahn/cordova-ios-wkwebview-iframe-test

### Command or Code
create HTML File in App-Data "cordova.file.dataDirectory" and load this file in iFrame NOT InAppBrowser

### Environment, Platform, Device
iPhone iOS 13.4.1

### Version information
Cordova 9.0.0, 
Cordova iOS 5.1.1, 
cordova-plugin-file 6.0.2, 
Xcode 11.4.1

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by katzlbt** [comment]
You may try the setting ...
 [webView.configuration.preferences setValue:@YES forKey:@"allowFileAccessFromFileURLs"];
I do not know if this fixes issues related to iframes, too, but is definitely necessary to display file:// URLs at all in WKWebView

**Comment by adamdport** [comment]
I'm not sure if you noticed [this page](https://cordova.apache.org/news/2018/08/01/future-cordova-ios-webview.html), sounds like iframes might not be supported with wkwebview.

**Comment by GMK82** [comment]
> I do not know if this fixes issues related to iframes, too, but is definitely necessary to display file:// URLs at all in WKWebView

**Comment by GMK82** [comment]
It works for WKWebView but not for iframe.

**Comment by GMK82** [comment]
> I'm not sure if you noticed [this page](https://cordova.apache.org/news/2018/08/01/future-cordova-ios-webview.html), sounds like iframes might not be supported with wkwebview.

It works for WKWebView but not for iframe. Now it is possible to load content only by http pre-add url to the whitelist in config file: <allow-navigation href="https://domain" />

**Comment by GMK82** [comment]
> You may try the setting ...
> `[webView.configuration.preferences setValue:@YES forKey:@"allowFileAccessFromFileURLs"];`
> I do not know if this fixes issues related to iframes, too, but is definitely necessary to display file:// URLs at all in WKWebView

It works for WKWebView but not for iframe. Now it is possible to load content only by http pre-add url to the whitelist in config file: <allow-navigation href="https://domain" />

**Comment by blukis** [comment]
I ran into a similar issue with migration to WkWebView.  (Additionally, I needed iframes to run as same origin, despite WkWebView treating anything in file:// as unique-origin.)  This is my workaround:
```
frameEl_injectHtml = function(frameEl, injectHtml) {
	// frameEl must exist in DOM before its contentWindow is accessible.
	if (!frameEl.contentWindow) { alert("frameInjectHtml() but frameEl not (yet or anymore) in DOM."); return; }

	frameEl.contentWindow.document.open('text/htmlreplace');
	frameEl.contentWindow.document.write(injectHtml);
	frameEl.contentWindow.document.close();
}

// Create <frame>, insert into DOM, and inject content.
var frameHtml = "<html><head></head>" +
	"<body style='background-color:#eee; color:#000;'>" +
		"iframe body" +
		"<script>window.parent.alert('iframe even same-origin as parent.');</script>" +
	"</body></html>";
var frameEl = document.createElement('iframe');
frameEl.src = "about:blank";
document.body.appendChild(frameEl);
frameEl_injectHtml(frameEl, frameHtml);
```

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version (using WKWebView with schemes) and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
