### ISSUE TITLE
Can not load Html file in local sandbox

### ISSUE THREAD

**Issue by LynGao** [apache/cordova-ios#828]
Hi,I had download the source code (6.0.0-dev) and Integrated into my project .
I need to load a local h5 by Cordova, but i found it did not work. 
Here is my code to load h5:

MySubCDVViewController.m :
- (void)viewDidLoad {
      NSString *path =  @"file:///Users/xxxx/Library/Developer/CoreSimulator/Devices/BE86-4FAA-9664-E8E6A73F9249/data/Containers/Data/Application/BD80A056-F436-4AE4-B0F9-D7B3BC194CCE/Documents/xxx/xxx/ss/version/textH5";

      self.wwwFolderName = [NSString stringWithFormat:@"file://%@",path];
      [super viewDidLoad];
}

Here is the final url which create in CDVViewController.m :
NSURL* appURL = [self appUrl];
//appurl = file:///Users/xxxx/Library/Developer/CoreSimulator/Devices/BE86-4FAA-9664-E8E6A73F9249/data/Containers/Data/Application/BD80A056-F436-4AE4-B0F9-D7B3BC194CCE/Documents/xxx/xxx/ss/version/textH5/index.html

So,the url seem is good, but cordova cannot load this index.html ? 
Can give a help? 
Thanks a lot.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
