### ISSUE TITLE
cordova-iOS现在还在维护嘛

### ISSUE THREAD

**Issue by YoungLeung** [apache/cordova-ios#830]
苹果爸爸要求新上架APP使用WKWebview 弃用UIWebview

**Comment by NiklasMerz** [comment]
Please submit your issue in English for more people to understand it.

**Comment by taozhzzl** [comment]
Cordova‘s blog already posted that:
[https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html](https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html)
