### ISSUE TITLE
Execution policy exception registration failed and was skipped

### ISSUE THREAD

**Issue by hemangshah** [apache/cordova-ios#832]
# Bug Report

## Problem

I am trying to run our angular-ionic project using cordova to run for the iOS platform. So for that I'm using this command `ionic cordova run ios` I also tried adding these commands separately for example `ionic cordova run ios -l --verbose` with this, I can see that ** BUILD SUCCEEDED ** but after this it's not opening the Xcode emulator (simulator). However when I use ( command + tab ) I can see that it is running but it is not showing up. Inside Microsoft Visual Studio Code (VS Code) IDE I can see following information just before the build succeeded message which I've included in *what does actually happen?* section.

### What is expected to happen?

I can expect that it should start my Xcode and also starts the emulator (simulator) but this is not happening for me. I think this is surely because below error. Please check *what does actually happen section?* for this information.

### What does actually happen?

RegisterExecutionPolicyException /Users/hemangshah/BitBucket/io-wfe-ionic-2/platforms/ios/build/emulator/MyApp.app (in target 'MyApp' from project 'MyApp')
    cd /Users/hemangshah/BitBucket/io-wfe-ionic-2/platforms/ios
    builtin-RegisterExecutionPolicyException /Users/hemangshah/BitBucket/io-wfe-ionic-2/platforms/ios/build/emulator/MyApp.app
note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'MyApp' from project 'MyApp')

## Information

I'm very new to hybrid development so this is the information I can provide with best of my knowledge, please let me know if I can answer to your specific questions. 

There is also someone asked question on StackOverflow: https://stackoverflow.com/questions/58686708/execution-policy-exception-registration-failed-and-was-skipped-error-domain-nsp but it doesn't help.

### Command or Code
I've tried with below commands but none of this works and end up with the same error.

ionic cordova run ios
ionic cordova run ios -l --verbose
ionic cordova run ios -cls --verbose
ionic cordova run ios --target="EMULATOR_TARGET_VALUE_IN_MY_SYSTEM"

### Environment, Platform, Device

**Platform**

- macOS Catalina 10.15.3

**Xcode**

- 11.3.1 (11C504)

**Microsoft Visual Studio Code**
 - Version: 1.37.0
 - Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
 - Date: 2019-08-08T01:22:37.660Z
 - Electron: 4.2.7
 - Chrome: 69.0.3497.128
 - Node.js: 10.11.0
 - V8: 6.9.427.31-electron.0
 - OS: Darwin x64 19.3.0

### Version information

@angular/cli@9.1.4
@ionic/cli@6.8.0
cordova@9.0.0
eslint@6.8.0
n@6.5.1
native-run@1.0.0
npm@6.14.4
typescript@3.8.3

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by hemangshah** [comment]
This command just worked for me.

ionic cordova run ios --target="EMULATOR_TARGET_VALUE_IN_MY_SYSTEM"

but this command will not work

ionic cordova run ios --l --target="EMULATOR_TARGET_VALUE_IN_MY_SYSTEM"

Live reload is not working application will get stuck.

**Comment by jcesarmobile** [comment]
Since you are using Ionic CLI you should report it in Ionic's CLI repository.

But I don't think this is a bug, for passing additional params from Ionic CLI to Cordova CLI you have to use `--`. i.e `ionic cordova run ios --l -- --target="EMULATOR_TARGET_VALUE_IN_MY_SYSTEM"`

**Comment by hemangshah** [comment]
@jcesarmobile Thanks for the update! I wasn't sure if I have to use extra `--` between two commands ?
