### ISSUE TITLE
Conflicting provisioning settings in barebone Cordova app

### ISSUE THREAD

**Issue by derwaldgeist** [apache/cordova-ios#836]
I am trying to upgrade a Cordova app from a fairly old version to the latest and greatest. The build worked now, but I noticed that Xcode is complaining about conflicting provisioning settings once I enable automatic signing. So I created a blank Cordova app using `cordova create` and found out the same problem occurs in a barebone Cordova app, so it doesn't seem to be related to my code.

Here's how it looks like:

![image](https://user-images.githubusercontent.com/3984535/81510093-afb6b280-930f-11ea-809e-0368985c9cbf.png)

It's also worth mentioning the Xcode shows two different sections for Debug and Release.

The root cause of this is that Cordova has set-up the Code Signing Identities like this:

![image](https://user-images.githubusercontent.com/3984535/81510053-55b5ed00-930f-11ea-84fd-338429419494.png)

If I set both to `Apple Developer` (as would be the standard in a blank Xcode project), everything works fine:

![image](https://user-images.githubusercontent.com/3984535/81510106-c826cd00-930f-11ea-9b7b-1591eb005ee0.png)

and there's only one section now.

What is the reason behind this mixed configuration, and how can I avoid it?

**Comment by jcesarmobile** [comment]
cordova apps are meant to be built from the terminal, not from Xcode, if you want to build from Xcode you'll have to edit this settings, but it's not a bug.

**Comment by derwaldgeist** [comment]
Thanks for your feedback. I am actually using the Cordova integration offered by Meteor, which automatically spins up Xcode to let you build the app.
