### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

### ISSUE THREAD

**Issue by yanglijunwang** [apache/cordova-ios#838]
# Bug Report

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by karlAlnebratt** [comment]
I get the same report from my latest App submission to Apple

ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by timbru31** [comment]
Please follow https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html - if the issue persists, you can try to completely remove the ios platform and re-add it. When the issue still persists, another non Apache Cordova plugin causes the warning and you need to identify and contact their author(s).
