### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

### ISSUE THREAD

**Issue by juanludukeboss** [apache/cordova-ios#841]
Hi, 
I has a Cordova App with:

- Cordova 9.0.0.
- ios 5.1.1.
- plugin "cordova-plugin-wkwebview-engine"
- plugin "cordova-plugin-wkwebview-file-xhr"
- plugin "cordova-plugin-fcm" 

Always has in my config.xml file, the next:

`<platform name="ios">
        <preference name="WKWebViewOnly" value="true" />
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
        <preference name="AllowBackForwardNavigationGestures" value="true" />
        <preference name="Allow3DTouchLinkPreview" value="false" />
    </platform>`

The last plugin is perfect for PUSH firebase message. I like this plugin, with it's very easy for implementate. 
The problem now is that Apple not allow upload more updates of my App, but the message is: 

**_ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview)._**

I read that this plugin "fcm" is not update to WKWebView and the people is using the other plugin "**cordova-plugin-fcm-with-dependecy-updated**", but this other plugin has some error with Pods in XCode. 

Exists the posibility that my App working with my current plugin "**fcm**" and WkWebView?
The new plugin "**cordova-plugin-fcm-with-dependecy-updated**" is possible install without pods similar with the actual plugin?

I hope your help, I'm 2 days trying changes and it's impossible for me find the solution with my actual plugin or the new plugin.

Thanks.

**Comment by breautek** [comment]
This isn't the appropriate place for your question, `cordova-plugin-fcm-with-dependecy-updated` is not a plugin maintained by Apache.

For cordova-ios you need to use 5.1.1 and use the `WKWebViewOnly` plugin, which I see you are already using. UIWebView problems with third-party plugin should be raised with their respective maintainers through their support channels.
