### ISSUE TITLE
Templates have not been upgraded for XCode 10

### ISSUE THREAD

**Issue by landabaso** [apache/cordova-ios#844]
For example, this file:

https://github.com/apache/cordova-ios/blob/master/bin/templates/project/__TEMP__.xcodeproj/project.pbxproj

still uses `developmentRegion = English;` (which is deprecated) instead of `developmentRegion = en;`

Compare it to:
https://github.com/dpogue/cordova-ios/blob/master/CordovaLib/CordovaLib.xcodeproj/project.pbxproj

They do not match. `master` fixes some of these inconsistencies (not all of them such as developmentRegion). What is worse, last release 5.1.1 targets `compatibilityVersion = "Xcode 3.2";`, which is pretty old.
See: https://github.com/apache/cordova-ios/blob/rel/5.1.1/bin/templates/project/__TEMP__.xcodeproj/project.pbxproj

There were many fixes applied in pull request https://github.com/apache/cordova-ios/pull/489 for CordovaLib.

But templates did not get those changes or got them partially wrong.

I'm not an expert in Cordova but I believe these templates are used to create the XCode project.

I found XCode was warning about a bunch of issues in my project which had been already solved for CordovaLib. I believe that the templates should have been upgraded accordingly.

**Comment by erisu** [comment]
Templates were updated and released.
