### ISSUE TITLE
返回上一个H5页面，插件不能调用

### ISSUE THREAD

**Issue by LionBuer** [apache/cordova-ios#856]
# Bug Report

## Problem
返回上一个H5页面，插件不能调用
### What is expected to happen?
返回上一个H5页面，插件能正常调用

### Environment, Platform, Device

 cordova --v
9.0.0 (cordova-lib@9.0.1)

cordova-ios 5.1.1

iPhone7，iOS11.3

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Please use English.
