### ISSUE TITLE
Cannot read property 'attrib' of null

### ISSUE THREAD

**Issue by damianlluch** [apache/cordova-ios#857]
Hi, I'm working on an app with Cordova, and I have this problem with IOS.

8.1.2 (cordova-lib@8.1.1)

thanks for everything

![image](https://user-images.githubusercontent.com/1463804/82354541-3b5fcb80-9a01-11ea-9f85-c99ec2259276.png)

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by damianlluch** [comment]
What do you need to happen to you?
Just show me that on the console.

I share my config.xml with you

https://pastebin.com/B1ZURwkM

**Comment by timbru31** [comment]
That does not help, please create a new issue and follow the issue template.
