### ISSUE TITLE
Plug in cannot call

### ISSUE THREAD

**Issue by LionBuer** [apache/cordova-ios#858]
# Bug Report

When I enter page B from page A and return to page a from page B, all plug-ins on page a cannot be called.

And I found that the navigator at this time was not the one replaced by Cordova.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by NiklasMerz** [comment]
Could you please post sample code to reproduce this issue. I don't really understand the problem here.

**Comment by timbru31** [comment]
Closing due to lack of feedback and missing information. If the issue persists, please create a new one and fill in the issue template completely. Thanks!
