### ISSUE TITLE
cordova_plugins.js stops loading after 1st app launch

### ISSUE THREAD

**Issue by siddharthhudda** [apache/cordova-ios#867]
# Bug Report

## Problem
cordova_plugins.js stops loading after 1st app launch
### What is expected to happen?

Plugins should work on every app launch

### What does actually happen?
When we launch ios app for the first time then everything works fine. But when we close and reopen the app then cordova_plugins.js stops loading hence all the installed plugins stops working in the app.

Plugins:- cordova-camera-plugin, cordova-statusbar-plugin, cordova-file-plugin

## Information

Cordova v9.0.0
"cordova-ios": "^5.1.1",
"cordova-plugin-add-swift-support": "^2.0.2",
"cordova-plugin-camera": "^4.1.0",
"cordova-plugin-statusbar": "^2.4.3",

### Command or Code

cordova run ios

### Environment, Platform, Device

iphone 11 pro max

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
