### ISSUE TITLE
SVG no longer shown in ios 13.5

### ISSUE THREAD

**Issue by ronligt** [apache/cordova-ios#868]
# Bug Report

### What is expected to happen?
An *mathjax* equation is converted to SVG with *mjpage*. This rendered html file is used in cordova app on iPhone (7). In ios < 13.5 app is started and shows equation as intended.

### What does actually happen?
In ios 13.5 app is started and equation is not shown

## Information

* Rendered html file **does** show equation in browser.
* mjpage is cli from https://github.com/pkra/mathjax-node-page

### Command or Code

* setup cordova:

    ```bash
    $ cordova init test
    $ cd test
    $ cordova platform add ios
    $ cordova plugin add cordova-plugin-wkwebview-engine
    ```

* add ios settings to `config.xml`:

    ```xml
    <platform name="ios">
       <allow-intent href="itms:*" />
       <allow-intent href="itms-apps:*" />    
       <preference name="WKWebViewOnly" value="true" />
       <feature name="CDVWKWebViewEngine">
           <param name="ios-package" value="CDVWKWebViewEngine" />
       </feature>
       <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />      
       <preference name="BackupWebStorage" value="local"/>
    </platform>
    ```

* in default `index.html` the equation ($e=mc^2$) is added:

    ```html
    ...
    <p class="event received">Device is Ready</p>
    <p>$e=mc^2$</p>
    ...
    ````

* `index.html` is rendered to SVG:

    ```bash
    $ mjpage --dollars --font=STIX --output=SVG < input.html > input_svg.html
    $ mv input_svg.html input.html
    ```

* build and run app on device or emulate:

    ```bash
    $ cordova run
    $ cordova emulate
    ````
### Environment, Platform, Device

* Build on MacBook Pro (15", 2016) with 10.15.4
* Tested on iPhone 7 with 13.5

### Version information

* Cordova 9.0.0
* Platform ios 5.1.1
* Plugin cordova-plugin-wkwebview-engine 1.2.1
* Xcode 11.5 (11E608c)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mosabab** [comment]
Please update to ios@6.0.0
and remove the wkwebview plugin, there is no need for it anymore (it is already integrated to ios@6.0.0).

And take in your mind that SVG may take long to appear in simulator, but in real device it appear fast .

Regards

**Comment by timbru31** [comment]
Well, if it works in iOS <13.5, I suspect that Apple has changed something. Have you read the WebKit release notes for 13.5 or searched in their BugTracker? Does the SVG get rendered in a plain Safari tab?

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
