### ISSUE TITLE
Cordova iOS App is not picking correct splash screen in iOS 13.4.1. (latest iOS)

### ISSUE THREAD

**Issue by Sunil509** [apache/cordova-ios#870]
Hi,

Ionic Cordova iOS App is not picking correct splash screen in iOS 13.4.1 eventhough correct splash is available in the app. UI is adjusting wrongly due to splash screen issue.

Could you anybody help me on this issue. Please find details as mentioned below.

Ionic:

Ionic CLI : 5.4.9 (/usr/local/lib/node_modules/ionic)
Ionic Framework : @ionic/angular 5.0.1
@angular-devkit/build-angular : 0.803.25
@angular-devkit/schematics : 8.3.25
@angular/cli : 8.3.25
@ionic/angular-toolkit : 2.1.2

Cordova:

Cordova CLI : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 8.1.0, ios 5.1.1
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.0, (and 15 other plugins)

Utility:

cordova-res : 0.9.0
native-run : not installed

System:

ios-deploy : 1.10.0
ios-sim : 8.0.2
NodeJS : v10.16.0 (/usr/local/bin/node)
npm : 6.13.7
OS : macOS Catalina
Xcode : Xcode 10.2.1 Build version 10E1001

Plugins List:

cordova-plugin-advanced-http 2.4.0 "Advanced HTTP plugin"
cordova-plugin-appminimize 1.0.1 "AppMinimize"
cordova-plugin-dbcopy 2.1.2 "sqlDB"
cordova-plugin-decimal-keyboard 1.0.0 "Decimal Keyboard"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
cordova-plugin-youtube-video-player 2.4.0 "CordovaYoutubeVideoPlayer"
cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"

Please let me know, if any additional details required.

**Comment by erisu** [comment]
Do not open up multiple tickets across multiple repos with the exact same information and issue. That does not help.
