### ISSUE TITLE
Does cordova-ios v6.0.0 supports watchOs?

### ISSUE THREAD

**Issue by ksp143** [apache/cordova-ios#879]
Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

As cordova-ios v5.1.1 doesn't support watchos/mulitple targets, I am using cordova-ios v6.0.0 to setup my project with multiple targets/watchos but prepare command working fine without renaming bundleId but cordova build failed with exit code 65.

```
The following build commands failed:
	Check dependencies
(1 failure)
xcodebuild: Command failed with exit code 65
```

How to build app target after adding watchos target?

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by timbru31** [comment]
No https://github.com/apache/cordova-ios/issues/876#issuecomment-636128934
