### ISSUE TITLE
cordova-ios v6.0.0: cordova build command failed with multiple targets/watchos. 

### ISSUE THREAD

**Issue by ksp143** [apache/cordova-ios#880]
# Bug Report

## Problem

My cordova project has watchos target and trying to run `cordova build` command. But failed execute the task.

```
builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -exclude Headers -exclude PrivateHeaders -exclude Modules -exclude *.tbd -resolve-src-symlinks /Users/Library/Developer/Xcode/DerivedData/ProjectName-bjwnwzepdrcztravufjlklyrdvdr/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/BuildProductsPath/Debug-watchos/ProjectNameWatch.app /Users/Documents/development/tyfone/workspace/ProjectName/mb-ProjectName-greypath/platforms/ios/build/device/ProjectName.app/Watch
error: /Users/Library/Developer/Xcode/DerivedData/ProjectName-bjwnwzepdrcztravufjlklyrdvdr/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/BuildProductsPath/Debug-watchos/ProjectNameWatch.app: No such file or directory

** ARCHIVE FAILED **


The following build commands failed:
	PBXCp /Users/Library/Developer/Xcode/DerivedData/ProjectName-bjwnwzepdrcztravufjlklyrdvdr/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/BuildProductsPath/Debug-watchos/ProjectNameWatch.app build/device/ProjectName.app/Watch/ProjectNameWatch.app
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --device --buildConfig build.json exited with exit
        code 65.

```

### What is expected to happen?
cordova build task should complete without an error.

### Command or Code

cordova build ios

### Environment, Platform, Device

ios

### Version information

cordova-ios v6.0.0

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by timbru31** [comment]
Please stop creating new issues, Cordova does not support watchOS.

**Comment by ksp143** [comment]
> Please stop creating new issues, Cordova does not support watchOS.

But Cordova Project should run without fail after adding native watchOS target! Not asking about cordova support for watchOS.

**Comment by breautek** [comment]
We cannot provide support for something Cordova doesn't support. If it works, it works. If not, then you're on your own.

If you want to add support, you're free to fork `cordova-ios` and add support yourself for your own use. But considering that WatchOS doesn't appear to support [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) you probably need an entire new custom platform. And that's assuming `WatchOS` even have a webview you can use.
