### ISSUE TITLE
IntersectionObserver experimental support in iOS?

### ISSUE THREAD

**Issue by LordPachelbel** [apache/cordova-ios#884]
IntersectionObserver is enabled by default in iOS Safari's Experimental Features list, but it doesn't seem to work in a Cordova app:

```
let observer = new IntersectionObserver(entries => {
  if (entries[0].boundingClientRect.y < 0) {
    document.body.classList.add("header-not-at-top");
  } else {
    document.body.classList.remove("header-not-at-top");
  }
});
observer.observe(document.querySelector("#top-of-site-pixel-anchor"));
```
The `new` line throws an exception: `ReferenceError: Can't find variable: IntersectionObserver`

It probably doesn't work for the same reason [WebGL2 stuff doesn't work](https://github.com/apache/cordova-ios/issues/772), right?

**Comment by breautek** [comment]
> It probably doesn't work for the same reason WebGL2 stuff doesn't work, right?

Correct, experimental features are not enabled in app webviews, so they cannot be used.
