### ISSUE TITLE
Can not search 6.0.0 version With 'pod search ' command

### ISSUE THREAD

**Issue by LynGao** [apache/cordova-ios#887]
After i update my local repo, i still cannot find out 6.0.0 version in cococaspod.
The search result was showed the latest version is '5.1.1'.

**Comment by jcesarmobile** [comment]
it wasn't published because of errors in the podspec file, and won't be able to publish until next release because it needs a github tag with the correct podspec

**Comment by LynGao** [comment]
ok，I close this issue.
