### ISSUE TITLE
Scroll issue with fixed position in iOS 12 

### ISSUE THREAD

**Issue by vukhacbiet** [apache/cordova-ios#889]
# Bug Report

## Problem
My App have a fixed div (a popup), it overlay body (and this div in #app) .
When I show popup, I can not "overscroll" to top or bottom and if I tried to pull down from top, my page can not scroll at least 1s.

First, I think it was an issue of my code, so I make a test cordova app to verify, and it happen the same.

**It always happen in iOS 12, and doesn't in iOS 13**

## Information

Video I tested in simulator iPhone 6 - 12.4 (build in Xcode 11.5)
`https://vimeo.com/426500132`
[![Watch the video](https://user-images.githubusercontent.com/43400653/83942203-ab50bd00-a81b-11ea-93a6-6bdb2deb9d56.png)](https://vimeo.com/426500132)

### Command or Code
My test app git: 
> https://github.com/vukhacbiet/test-cordova

### Environment, Platform, Device
Cordova iOS 6.0.0
Xcode 11.5

Tested in real iPhone 6 - iOS 12.4.3 and iPhone 6 simulator - 12.4

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by NiklasMerz** [comment]
If this happens only on iOS 12 this sounds more like a WebKit bug by Apple and not a Cordova bug. I would advise your users to update.

**Comment by vukhacbiet** [comment]
We know that some older device such as iPhone 6, iOS 12 is the last version, so I hope find a temporary solution

**Comment by NiklasMerz** [comment]
Maybe you are lucky and find JavaScript code to work around that. Feel free to post here for others.

Closing this since this is no Cordova issue.
