### ISSUE TITLE
Problem with splashscreen and cordova-ios 6.0.0

### ISSUE THREAD

**Issue by mathieucaralp** [apache/cordova-ios#890]
# Bug Report

## Problem

The version 6.0.0 of cordova-ios integrates the  [splashscreen plugin](https://github.com/apache/cordova-plugin-splashscreen). Accordingly, the team of cordova-plugin-splashscreen removed the support of this version with [the latest version of the plugin](https://github.com/apache/cordova-plugin-splashscreen/blob/master/RELEASENOTES.md). 

With that in mind I decided to update cordova-ios to version 6.0.0, but the integrated splashscreen does not work the same way as the plugin one.

### What is expected to happen?

The splashscreen should be displayed the same way as before.

### What does actually happen?

The splash screen is hidden very quickly, it does not use the settings of the config.xml file. It is hidden even if the _AutoHideSplashScreen_ option is set to false, and the _SplashScreenDelay_ option does not change the delay.

## Information

I looked at the [CDVViewController.m file](https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/Public/CDVViewController.m) file with the Xcode debugger, and it seems that the options of the config.xml file are correctly interpreted, but it does not change nothing. 

Moreover when I call the `navigator.splashscreen.hide()` function, the splashscreen is not displayed and I cannot click on the screen anymore.

Some people from the splashscreen plugin team seem to have spotted [the same problem](https://github.com/apache/cordova-plugin-splashscreen/issues/268).

### Environment, Platform, Device

I use Xcode 11.4 and an IPhone 6S with iOS 13.5.

### Version information

I use cordova-ios 6.0.0.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mosabab** [comment]
@dpogue Could you please look at this issue:

Cordova-ios does not read the settings for splas screen.
This happend since the plugin integrated to cordova-ios.
Regards

**Comment by mosabab** [comment]
> # Bug Report
> ## Problem
> The version 6.0.0 of cordova-ios integrates the [splashscreen plugin](https://github.com/apache/cordova-plugin-splashscreen). Accordingly, the team of cordova-plugin-splashscreen removed the support of this version with [the latest version of the plugin](https://github.com/apache/cordova-plugin-splashscreen/blob/master/RELEASENOTES.md).
> 
> With that in mind I decided to update cordova-ios to version 6.0.0, but the integrated splashscreen does not work the same way as the plugin one.
> 
> ### What is expected to happen?
> The splashscreen should be displayed the same way as before.
> 
> ### What does actually happen?
> The splash screen is hidden very quickly, it does not use the settings of the config.xml file. It is hidden even if the _AutoHideSplashScreen_ option is set to false, and the _SplashScreenDelay_ option does not change the delay.
> 
> ## Information
> I looked at the [CDVViewController.m file](https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/Public/CDVViewController.m) file with the Xcode debugger, and it seems that the options of the config.xml file are correctly interpreted, but it does not change nothing.
> 
> Moreover when I call the `navigator.splashscreen.hide()` function, the splashscreen is not displayed and I cannot click on the screen anymore.
> 
> Some people from the splashscreen plugin team seem to have spotted [the same problem](https://github.com/apache/cordova-plugin-splashscreen/issues/268).
> 
> ### Environment, Platform, Device
> I use Xcode 11.4 and an IPhone 6S with iOS 13.5.
> 
> ### Version information
> I use cordova-ios 6.0.0.
> 
> ## Checklist
> * [x]  I searched for existing GitHub issues
> * [x]  I updated all Cordova tooling to most recent version
> * [x]  I included all the necessary information above

Please change the title of this issue to:
cordova-ios 6.0.0 not read the preferences from config.xml for splashscreen

**Comment by ajberasategui** [comment]
I'm experiencing the same issue. 
What my debugging shows is preferences are correctly read from config.xml. The subview created to "emulate" the Launch Screen after the OSs one is hidden is there but it's transparent. I guess that's the reason why it's not possible to interact with the Web App.

A quick way to prove what I say is to call navigator.splashscreen.show().

I'm still trying to figure out why the launch screen is "transparent" as this is blocking me from upgrading and we really want to.

**Comment by dpogue** [comment]
Ahhhh okay, I know what's happening here: The splashscreen will use the `BackgroundColor` preference configured in config.xml. If that is not configured, it will be transparent.

I will open a PR in the next few days to make it default to white.

**Comment by antikalk** [comment]
Updating cordova-plugin-splashscreen to version 5.0.4 changed the experience for me, as this does not include anymore ios related code. I am now able to click again (seems like the transparent layer is gone then) but the problem with the early hiding of the splashscreen still exists for me. As this is now a fully cordova-ios thing I closed [my issue at cordova-plugin-splashscreen](https://github.com/apache/cordova-plugin-splashscreen/issues/268).
