### ISSUE TITLE
Can't install Cordova 6.0.0

### ISSUE THREAD

**Issue by ej-dunne** [apache/cordova-ios#895]
Hi, Im am currently using Cordova CLI 9.0.0 and cordova-ios 5.1.1. We have an automated script for building projects, at a certain point in that script we install the set version of cordova-ios (or cordova-android) I can't seem to install cordova 6.0.0, even though that version is now the latest on npm. Do I need to wait until there is a new release of cordova CLI to be able to move forward?

Current setup for IOS: 
 * Cordova CLI - 9.0.0
 * Cordova IOS - 5.1.1
 * Xcode - 11.5 (Latest release)
 * cordova-plugin-wkwebview-engine - 1.2.1
* I am also setting the flag in config so that the old webview is not included

The above details are allowing us to continue submitting IOS apps for now, but I would like to get cordova-ios 6.0.0 installed so I don't need to worry as much about issues with WKWebView

The error I'm seeing:
> Unhandled "error" event. (The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.)
> [ERROR]   Command '['cordova', 'platform', 'add', 'ios@6.0.0']' returned non-zero exit status 1

**Comment by breautek** [comment]
Appears to be working for me...

```
norman@norman-ThinkPad:~/ttt$ cordova platform add ios@6.0.0
Using cordova-fetch for cordova-ios@6.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@6.0.0
Installing "cordova-plugin-whitelist" for ios
norman@norman-ThinkPad:~/ttt$ cordova -v
9.0.0 (cordova-lib@9.0.1)
```

are you able to add `-v` flag verbose output?

**Comment by ej-dunne** [comment]
when I added -v

>>> Initializing Cordova project: DevelopmentTestProject
Creating a new cordova project.

>>> [INFO]    Adding iOS Platform for Cordova
9.0.0 (cordova-lib@9.0.1)

>>> [INFO]    Adding cordova-plugin-file@6.0.2 plugin for Cordova
Unhandled "error" event. (The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.)
>>> [ERROR]   Command '['cordova', 'plugin', 'add', 'cordova-plugin-file@6.0.2']' returned non-zero exit status 1

**Comment by breautek** [comment]
My bad, it's actually `--verbose` for verbose output.

**Comment by ej-dunne** [comment]
> My bad, it's actually `--verbose` for verbose output.

Ahhhh that’s probably why haha, it just showed the version with -v, I’ll run it with `-- verbose` an

**Comment by ej-dunne** [comment]
@breautek 

> `>`cordova platform add ios@6.0.0
>Using cordova-fetch for cordova-ios@6.0.0
>Adding ios project...
>Unable to load PlatformApi from platform. SyntaxError: Unexpected token {
>Unhandled "error" event. (The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.)

**Comment by breautek** [comment]
What's your node version?

**Comment by ej-dunne** [comment]
I got it working, had to update nvm to 10.21.0, then npm install, finally: 
npm uninstall -g cordova
npm install -g cordova@latest

Note: For some reason, upgrading to the latest nvm (14.3.0) stopped the install from working

Thanks for your help!

**Comment by breautek** [comment]
Oh yes, I think node v8 was dropped in cordova-ios@6. Supported versions are node v10, and node v12.

Node v14 isn't supported (yet), but will be supported in the future as it will become the new LTS later this year.
