### ISSUE TITLE
CDVURLSchemeHandler.m `startURLSchemeTask` data can be nil

### ISSUE THREAD

**Issue by msmtamburro** [apache/cordova-ios#903]
# Bug Report

## Problem

A potentially nil value is passed to a method with a non-null specifier.  

### What is expected to happen?

`didReceiveData` should not be called with a nil value

### What does actually happen?

nil can be passed

## Information

This is a quick fix: just wrap line 78 with an if statement.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by NiklasMerz** [comment]
Thank you for this report. This is indeed a problem I just submitted a pull request to fix this.
