### ISSUE TITLE
white space after update cordova 6.0.0

### ISSUE THREAD

**Issue by kamhawy4** [apache/cordova-ios#905]
appeared me white space after update cordova 6.0.0

![Image from iOS](https://user-images.githubusercontent.com/25951080/84922403-16c14700-b0c6-11ea-9e29-735bc44aef50.jpg)

\\\\\\\

and  after close keyboard. appearing in large more

\\\\\\\\

![Image from iOS-2](https://user-images.githubusercontent.com/25951080/84922678-7d466500-b0c6-11ea-95f3-ff966c0407d4.jpg)

**Comment by dpogue** [comment]
See https://github.com/apache/cordova-ios/issues/417.

This was a bug in iOS between iOS 12.0 and iOS 13.4 when using WKWebView.
https://www.npmjs.com/package/cordova-plugin-wkkeyboardfix is available as a unofficial/unsupported workaround.

**Comment by lovelyelfpop** [comment]
Add some code in `CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m`
```
    // re-create WKWebView, since we need to update configuration
    WKWebView* wkWebView = [[WKWebView alloc] initWithFrame:self.engineWebView.frame configuration:configuration];
    // add begin
    #if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
    if (@available(iOS 11.0, *)) {
        [wkWebView.scrollView setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];
    }
    #endif
    // add end
    wkWebView.UIDelegate = self.uiDelegate;
```

**Comment by dpogue** [comment]
@lovelyelfpop We have said many times, we **will not** set `UIScrollViewContentInsetAdjustmentNever` because it removes control from the app author. Every app should define their content inset behaviour with the `viewport-fit` meta tag.

**Comment by lovelyelfpop** [comment]
We've already set `viewport-fit=cover`, but there is still white space.
Maybe add a new preference to control it?

**Comment by 21pg** [comment]
Agree with @lovelyelfpop ,
I can confirm `viewport-fit=cover` not resolving this problem.
At first launch there is a white space below to notch on iPhone X and iPhone XR and it goes when we switch App in background/foreground 
I also tried height: 100vh in body/html tag. It giving me result like this-
![IMG1](https://user-images.githubusercontent.com/64975861/102246119-67561780-3f24-11eb-8b36-0f7942d52e8a.jpeg)
While i expected this-
![IMG2](https://user-images.githubusercontent.com/64975861/102246243-88b70380-3f24-11eb-8414-48b79679894f.jpeg)
