### ISSUE TITLE
cordova-ios 6.x: Why iOS 11 support instead of directly iOS 12?

### ISSUE THREAD

**Issue by GitToTheHub** [apache/cordova-ios#911]
Hi,

with cordova-ios 6.x you set the minimum iOS-Version to 11. But why not directly to iOS 12? Because every iOS 11 device supports iOS 12. See: https://en.wikipedia.org/wiki/IOS_12#Supported_devices

Regards,

Manuel

**Comment by breautek** [comment]
It's not Cordova's place to force users to a higher minimum version than necessary.

Cordova's default minimum is what we support, and is chosen based on a number or different factors.

You can always increase the minimum version using the `deployment-target` preference.

**Comment by GitToTheHub** [comment]
Sorry, you shouldn't misunderstand that I want the user force to something. I thought, it makes some things less complicate, if the minimum version is iOS 12. I know, i can set by myself the minimum Version. It was only to give some good thoughts to this project here..

**Comment by breautek** [comment]
It makes the framework more confusing to use. The framework should assume the lowest minimum possible for simplicity.

Generally speaking we first look at the market share to determine what the minimum SDK we should support, which currently it is definitely at least  iOS 12. Then we look at what we can support at a technical level, and ensure that every API that the framework uses is available.

In this case, every API that the framework uses is available as of iOS11, so there is no technical reason to not support iOS 11. By supporting iOS 11, we also implicitly support all the versions that comes after.

Also keep in mind that even if every ios11 device is upgradable to iOS 12, doesn't mean everyone actually updates.

**Comment by GitToTheHub** [comment]
Thank you really much for your explanation. So technically it makes no difference for cordova if it supports iOS 11 or 12. I was only thinking, that you have less to test, if you start with iOS 12.

I know some people don't want to update, or even not caring about updating. Thank you for your hints :)
