### ISSUE TITLE
Calling `navigator.splashscreen.hide()` does not hide the splashscreen

### ISSUE THREAD

**Issue by FireLizard** [apache/cordova-ios#918]
# Bug Report

### What is expected to happen?
Hiding the splashscreen by calling `navigator.splashscreen.hide()`.

### What does actually happen?
Its not hiding the splashscreen.

### Config
```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="..." version="...">
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="AutoHideSplashScreen" value="false" />
</widget>

```

### Version information
* cordova 9.0.0 (cordova-lib 9.0.1)
* cordova-ios 6.1.0
* cordova-plugin-splashscreen 5.0.4
* cordova-android 8.1.0
* cordova-plugin-inappbrowser 4.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by eun-choi** [comment]
Same issue.
I would like to hide the splashscreen after all the features of the app have been loaded.
If the developer has integrated splash screen functionality, provide a way to use the show and hide functionality.

**Comment by zmalter99** [comment]
According to cordova-plugin-splashscreen [documentation](https://github.com/apache/cordova-plugin-splashscreen), you can use the following code within the deviceready event handler:
```
document.addEventListener("deviceready", function () {
    setTimeout(function () {
        navigator.splashscreen.hide();
    }, 2000);
});
```
A few things to note, the AutoHideSplashScreen preference in your config.xml must be set to false (which you already did) and of course you must link the cordova.js file to your HTML document: `<script src="cordova.js"></script>`
I've forgotten to do that before. Would you mind sharing your code if the above doesn't work?

**Comment by FireLizard** [comment]
I've tried that already :(
Here my most minimal index.html
```html
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="cordova.js"></script>
</head>
<body>
    <script>
        document.addEventListener('deviceready', function () {
            alert('deviceready');
            setTimeout(function () {
                alert('hide now');
                navigator.splashscreen.hide();
            },4000);
        })
    </script>
</body>
</html>
```
Both alerts were shown, but the splashscreen stays there.

I've built it with **Xcode v11.3.1** and testet on an **iPhone 7, iOS 13.5.1**.

**Comment by zmalter99** [comment]
I created a test project with the code above and the splashscreen successfully faded away after four seconds from the device ready alert. Here's my code:

index.html
```
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="cordova.js"></script>
</head>
<body>
    <script>
        document.addEventListener('deviceready', function () {
            alert('deviceready');
            setTimeout(function () {
                alert('hide now');
                navigator.splashscreen.hide();
            },4000);
        })
    </script>
    Content goes here...
</body>
</html>
```

confix.xml
```
<?xml version="1.0" encoding="UTF-8" ?>
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" id="com.example.app" version="1.0">
  <name>Example App</name>
  <description>N/A</description>
  <author href="http://example.com" email="app@example.com">Example App</author>

  <preference name="ShowSplashScreenSpinner" value="false" />
  <preference name="SplashShowOnlyFirstTime" value="false" />
  <preference name="AutoHideSplashScreen" value="false" />
</widget>
```

I then ran the following commands in the root of my project:
```
cordova plugin add https://github.com/apache/cordova-plugin-splashscreen/archive/5.0.4.tar.gz
cordova platform add https://github.com/apache/cordova-ios/archive/6.1.0.tar.gz
cordova build ios
```

**Comment by FireLizard** [comment]
I can not tell why but after removing an reinstalling cordova-ios and splashscreen-plugin it works now:
```bash
$ cordova platform remove ios

$ cordova plugin remove cordova-plugin-splashscreen

$ rm -rf platforms/ plugins/

$ cordova platform add ios@^6.1.0
Using cordova-fetch for cordova-ios@^6.1.0
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: com.example.app
        Name: My App
iOS project created with cordova-ios@6.1.0
Installing "cordova-plugin-file" for ios
Installing "cordova-plugin-whitelist" for ios

$ cordova plugin add cordova-plugin-splashscreen
Unmet project requirements for latest version of cordova-plugin-splashscreen:
    cordova-ios (6.1.0 in project, <6.0.0 required)
Current project does not satisfy the engine requirements specified by any version of cordova-plugin-splashscreen. Fetching latest version of plugin anyway (may be incompatible)
Installing "cordova-plugin-splashscreen" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 6.1.0, failed version requirement: <6.0.0
Skipping 'cordova-plugin-splashscreen' for ios
Adding cordova-plugin-splashscreen to package.json
```

**Comment by brassier** [comment]
For others seeing this issue, similar impacts are being noted in this issue:
https://github.com/apache/cordova-plugin-splashscreen/issues/192

**Comment by jptrainor** [comment]
Here is the key point: "... you don't need the cordova-plugin-splashscreen since it's added to cordova-ios since 6.0.0".

Removing the old plugin fixed this for me.
