### ISSUE TITLE
White bar at the bottom when using iPhone X

### ISSUE THREAD

**Issue by LAP0109** [apache/cordova-ios#919]
# Bug Report

### What is expected to happen?
The whole screen should be used from iPhone X. No bar at the bottom.

### What does actually happen?
A white bar appears at the bottom.
![iphoneX_white_bar](https://user-images.githubusercontent.com/41615338/85554308-11637f80-b625-11ea-9db3-ff3f887a1725.png)

## Information

I followed everything from this SO answer https://stackoverflow.com/a/46232813
Interestingly, the config appears to be fine, when I rotate the screen and then rotate it back, the white bar is gone.
![iphoneX_no_bar](https://user-images.githubusercontent.com/41615338/85554384-20e2c880-b625-11ea-9a36-fecf0d1cbf45.png)

### Environment, Platform, Device

iPhone X (iOS 13.5.1)

### Version information

Cordova v9
Cordova-ios 6.1.0
Xcode 11.5
macOS 10.15.5

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by LAP0109** [comment]
Similar to this SO post, but he used an older cordova-ios version: https://stackoverflow.com/questions/47467176/cordova-iphone-x-launch-image-initially-shows-white-area-at-bottom

**Comment by zmalter99** [comment]
I had this same issue as you and spent many long hours troubleshooting. After comparing my project the the Hello World project created by running:  `cordova create hello com.example.hello HelloWorld` I figured out that I needed to set a height of `100vh` to my HTML element like so:

`html {
    height: 100vh;
}`

And assuming you added the correct meta viewport tag, it seems to be working now.

**Comment by LAP0109** [comment]
@zmalter99 I am sorry, but that didn't do the trick.

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by LAP0109** [comment]
[test.app.zip](https://github.com/apache/cordova-ios/files/4835573/test.app.zip)
@jcesarmobile there you go. For clarification, it is a node project with vue as js framework (not that it really matters what the content is). You should be able to get it going by running "npm install" and then "cordova prepare". Tested the behaviour with iPhone 11 simulator

**Comment by zmalter99** [comment]
I simulated your app on an iPhone 11 and also saw the white bar at the bottom of the screen. I fixed it by adding the following to your CSS file. 
`.app { height: 100vh; }`

**Comment by jcesarmobile** [comment]
Thanks zmalter99, that’s what I thought.
