### ISSUE TITLE
RE: WkWebView full Screen in iphone X 

### ISSUE THREAD

**Issue by 75341704** [apache/cordova-ios#924]
# Feature Request
WkWebView full Screen in iphone X 

## Motivation Behind Feature

Get full cover in the iphone.

Use safe-area-inset-*  instead to handle the notch  

## Alternatives or Workarounds

//Append the code in CDVWebViewEngine.m
//line no:205
    #if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
    if (@available(iOS 11.0, *)) {
      [wkWebView.scrollView setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];
    }
    #endif

**Comment by dpogue** [comment]
Control of safe-area-insets should be up to the application author to determine with the `viewport-fit=cover` meta directive.

Cordova will not take that control away from application authors by enforcing particular viewport behaviour.
