### ISSUE TITLE
Preflight response is not successful

### ISSUE THREAD

**Issue by happyi** [apache/cordova-ios#925]
Preflight response is not successful

XMLHttpRequest cannot load http://jm.yongdianbao.com.cn/employee/rest/api/login due to access control checks.

**Comment by timbru31** [comment]
You need to configure proper CORS headers.

**Comment by renanbandeira** [comment]
@timbru31 do you have any tutorial to configure it? Is that possible to configure only from client side or we will need a server side change?

**Comment by breautek** [comment]
> @timbru31 do you have any tutorial to configure it? Is that possible to configure only from client side or we will need a server side change?

This is a server thing. Providing a tutorial is not really possible, specific instructions will depend on your server stack.

Over simplified instructions would be:

- Respond to the `OPTIONS` method request (reply with no data, but do set `Access-Control` headers).
- Set `Access-Control-Allow-Methods`, `Access-Control-Allow-Origin`, and `Access-Control-Allow-Headers` in your response headers for `OPTIONS`, `GET`, and `POST` request methods. This is to support both "preflight" request and "simple" requests.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for more detailed information on how CORS protocol works. I would recommend reading.

**Comment by renanbandeira** [comment]
Gotcha, @breautek , thanks. But as far as I can see, the OPTIONS method request is not sent by WkWebview:
![image](https://user-images.githubusercontent.com/1872284/86167720-70296d00-baed-11ea-99c8-3e7f5460988b.png)

**Comment by breautek** [comment]
The MDN article lays out the difference between simple requests and non-simple requests. Simple requests do not send a preflight response (the `OPTIONS` request).

And I don't think the web inspector also actually shows the preflight request in the network tab if my memory recalls properly (but I could be wrong... it's been awhile for me). I used postman to debug CORS response issues by hitting the URL endpoint using `OPTIONS` and checking to make sure my response was as expected.

**Comment by renanbandeira** [comment]
Thanks, buddy, I could kinda make it work. My server already accepts some cross-origin requests, when origin is file or http://localhost . My problem is that, when I add `<preference name="scheme" value="file"/>` on my `config.xml`, origin header is null. If I add like release notes (scheme app and hostname localhost), origin header is `app://localhost`, but I can't load internal files, such as pictures taken.
