### ISSUE TITLE
cordova ios@6.1.0 reject app ios

### ISSUE THREAD

**Issue by vedatozkanTr** [apache/cordova-ios#926]
---- cordova create Sample com.sample.app Samples

Config.xml add

<platform name="ios">
<preference name="WKWebViewOnly" value="true"/>

<feature name="CDVWKWebViewEngine">
<param name="ios-package" value="CDVWKWebViewEngine"/>
</feature>

<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine"/>
</platform>

---- cordova platform add ios@6.1.0

LaunchStoryBoard add image with size 2732x2732
background color : white

when build app then app  is open but all button click not working.

what is missing, is my config.xml error??. Is it necessary to install Cocoapods on the mac side?

**Comment by breautek** [comment]
Please don't delete the issue form and instead fill out the details requested as it contains important information for us to troubleshoot and help.
