### ISSUE TITLE
6.1.0 Splash screen doesn't repect delay default

### ISSUE THREAD

**Issue by eradin** [apache/cordova-ios#927]
# Problem

The splash screen appears but only for about a second.  The default in the splash screen plugin documentation states

SplashScreenDelay=3000

It does delay for 3 seconds if the directive is present but not if the directive is omitted.  Default should be the same as android, 3 seconds with the directive omitted.

This is the second issue with defaults.  The first being the orientation.  I would suggest checking other defaults to make sure they are set.

**Comment by mosabab** [comment]
> # Problem
> The splash screen appears but only for about a second. The default in the splash screen plugin documentation states
> 
> SplashScreenDelay=3000
> 
> It does delay for 3 seconds if the directive is present but not if the directive is omitted. Default should be the same as android, 3 seconds with the directive omitted.
> 
> This is the second issue with defaults. The first being the orientation. I would suggest checking other defaults to make sure they are set.

Same problem, this happened after splash screen plugin migration to cordova iOS 6.0.0

**Comment by dpogue** [comment]
I'll try to review the docs as part of https://github.com/apache/cordova-docs/pull/1348 and make sure they're accurate
