### ISSUE TITLE
Update all the plugin with WKWebView still getting the App rejection and Also have \CDVUIWebViewEngine

### ISSUE THREAD

**Issue by ladaniavadh** [apache/cordova-ios#928]
Hello,
I have updated ma cordova-ios to 5.1.1 still I have \CDVUIWebViewEngine folder in private plugins.  Can someone help me to solve the issue?
![Capture](https://user-images.githubusercontent.com/30779077/86107506-8defd580-badf-11ea-94ea-d5cd3752ae85.PNG)

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by ladaniavadh** [comment]
I have updated cordova-ios to 6.1.0, all the plugins are updated with the latest version, 

This below mentioned are my plugin with its version
cordova-admob-sdk 0.24.1 "AdMob SDK"
cordova-plugin-admob-free 0.27.0 "Cordova AdMob Plugin"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-apprate 1.5.0 "AppRate"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.6.8 "SocialSharing"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
es6-promise-plugin 4.2.2 "Promise"

Also when executing 'grep -r "UIWebView" .', there is an only binary file for I can is from Cordova-AdMob-SDK but it has the latest version

Now I have the latest version of all the plugins then also my build is getting rejected due to 'ITMS-90809- use of UIWebView' i am not able to solve the issue, your help will be appreciated
![Capture1](https://user-images.githubusercontent.com/30779077/86125670-ae795900-bafa-11ea-8b95-419e563597bd.PNG)

**Comment by timbru31** [comment]
>  there is an only binary file for I can is from Cordova-AdMob-SDK but it has the latest version

Then ask the Cordova-AdMob-SDK plugin authors. We can't help you with non Apache core plugins and all of those are migrated/updated to WKWebView.
