### ISSUE TITLE
Splash screen not visible, instead appears a white screen after upgrading to cordova-ios: 6.1.0 from 5.1.1

### ISSUE THREAD

**Issue by Astha-Anand** [apache/cordova-ios#939]
# Bug Report

### What is expected to happen?
Splash screen should appear instead of a white screen.

### What does actually happen?
White screen appears instead of splash screen. 

## Information

No error is displayed on the Xcode console. Splash and webview plugin version:
"cordova-plugin-ionic-webview": "5.0.0",
"cordova-plugin-splashscreen: "^5.0.0",

No splash images in plaforms/ios/project-name/Images.xcassets/ after upgarding to ios 6.1.0 using:
**ionic cordova platform add ios@latest**

### Environment, Platform, Device

MacOs Mojave: 10.14.5

### Version information

Ionic cli : 4.12.0
cordova: 9.0.0 (cordova-lib@9.0.1)
cordova-ios: 6.1.0
cordova-plugin-splashscreen: "^5.0.0",

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by antikalk** [comment]
Please try updating cordova-plugin-splashscreen to version 5.0.4.

**Comment by timbru31** [comment]
The SplasSchreen has been integrated into cordova-ios@6.0.0. Like Oliver said, please upgrade the plugin.

**Comment by angelofan** [comment]
@timbru31 By the way, I have updated cordova-ios to @6.1.0, should I uninstall cordova-plugin-splashscreen?

**Comment by timbru31** [comment]
Depends. If you develop only for iOS then yes, otherwise no.
