### ISSUE TITLE
Plugins stop working in version 6.X

### ISSUE THREAD

**Issue by videmort** [apache/cordova-ios#940]
# Bug Report
## Problem
many plugins have stopped compiling
Example
create a cordova application and add the plugin --> https://github.com/apache/cordova-plugin-file-transfer

### Command or Code

Add platform with this plugin (https://github.com/apache/cordova-plugin-file-transfer, just an example because a lot of plugins are not working), and try to build (cordova build ios --device)

### Environment, Platform, Device

iOS platform

### Version information

Cordova 9
Cordova-ios 6.X 
NodeJs 10
xCode 11.5

## Checklist

- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by timbru31** [comment]
cordova-ios@5 --> cordova-ios@6 is a **major** version bump - that indicates it contains breaking changes. The `file-transfer` plugin is deprecated since 2017. You'll need to ask other plugin authors to update their plugins.

**Comment by videmort** [comment]
@timbru31  thanks for the quick response and for the info about that the file-transfer plugin is deprecated.

**Comment by brodybits** [comment]
> You'll need to ask other plugin authors to update their plugins.

Given the potential impact of the changes in cordova-ios@6, I think it would have been good to highlight more clearly the increased probability of broken plugins in the release notes https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html
