### ISSUE TITLE
iOS app crashes on launch 5.1.1

### ISSUE THREAD

**Issue by jdpsah** [apache/cordova-ios#942]
# Bug Report
iOS app is crashing at launch. 
## Problem
After building iOS application with cordova iOS 5.1.1, app is crashing while launching in real device . It works fine at simulator . 
### What is expected to happen?

It should not crash and should work smoothly. 

### What does actually happen?
Crashing at launch after installation in real device . Working fine in simulator . 

### Environment, Platform, Device

Cordova : 8.1.0
Cordova-iOS : 5.1.1
Ionic 3

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Without actual version information, the crash log and a reproducible example we are unable to help.  Please adjust your issue and fill in the required information, thanks!

**Comment by jdpsah** [comment]
@timbru31, actually the issue was for Bluetooth description. I had not given Bluetooth always permission string so it was crashing on launch . Now it's resolved. Anyways thanks for the response .
