### ISSUE TITLE
TMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted

### ISSUE THREAD

**Issue by dineshrawat11** [apache/cordova-ios#943]
# Bug Report

TMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.
 
## Problem
I did two experiments:

1: Uninstall admobs from the project and submited, result: PASSED
2: Uninstaled everything except admobs and resubmitted, result: FAILED

Sharing the podfile.lock + platform details + list of plugins I'm using in my project:

```
ionic -v : 6.10.1
cordova -v : 9.0.0 (cordova-lib@9.0.1)
"cordova-ios": "^6.1.0"
"cordova-plugin-admob-free": "^0.27.0"
"cordova-admob-sdk": "^0.24.1"
 "cordova-plugin-firebasex": "^10.1.0-cli",
```

### List of plugins used : 

```
cordova-admob-sdk 0.24.1 "AdMob SDK"
cordova-plugin-admob-free 0.27.0 "Cordova AdMob Plugin"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebasex 10.1.0-cli "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
```

### What is expected to happen?
TMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability.

### What does actually happen?
ios app is not approved

### Command or Code
Ran
`grep -r UIWebView Platforms/`

```
Binary file `Platforms//ios/MyApp/Plugins/cordova-admob-sdk/GoogleMobileAds.framework/GoogleMobileAds` matches
```

It reference to cordova ios ad mobs plugin framework

POD File link:
https://www.pastiebin.com/5f0e8e3ad68a2
Google ad mobs forum (My Question):
https://groups.google.com/g/google-admob-ads-sdk/c/QuZMbjIyxn8/m/dyAxJZfOBAAJ
Google ad mobs forum (Google's answer):
https://groups.google.com/g/google-admob-ads-sdk/c/QuZMbjIyxn8/m/6lQW004KBAAJ

_MacOS Version: 10.14.5_

**Comment by breautek** [comment]
All of apache maintained codebase have moved away from uiwebview in their latest versions, which I see you are already using. 

You'll have to contact the maintainers of those admob plugins. It's up to them to update their codebases to comply with apple's standards.

**Comment by breautek** [comment]
Do note that the Cordova plugin for admob is likely not maintained by google, but a third party.

**Comment by dineshrawat11** [comment]
I understood! Thanks for the help

**Comment by piyushysoft** [comment]
> I understood! Thanks for the help

@dineshrawat11  
your issue is resolved or still have those issue in app.
I am facing same issue in ios app.
