### ISSUE TITLE
xcode don't open ios project

### ISSUE THREAD

**Issue by ihebChaaraoui** [apache/cordova-ios#948]
Hello
cordova platform add ios@6.1.0 and  ios@6.0.0 I created the platform with Windows. And send api folder send macOs pc. XCODE Running with xcode and getting errors. "The project is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts."
cordova version : 9.0.0 - lib@9.0.1

Please help me
Thank You

```

<?xml version='1.0' encoding='utf-8'?>
<widget id="com.example.v6" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>v6</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
	<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
		<allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>

```

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
