### ISSUE TITLE
Camera dismissed (cancelled or otherwise) body re-rendered, padding safe area ignored

### ISSUE THREAD

**Issue by bkervaski** [apache/cordova-ios#952]
# Bug Report

## Problem

Took me most of the weekend to track this down, thought it was my CSS, it doesn't appear to be.

When you use an INPUT of type file and select an image from the photo gallery, all is good.

However, when you take a photo, a weird phenomena happens after when you finish (either by selecting _Cancel_ or _Use Photo_, the BODY padding is removed or perhaps the body is re-rendered ignoring what appears to be the env(safe-area) resulting in everything shifting upwards.

For example, if there is a DIV with 100vh rendered, the top of the DIV afterwards would be extended to the top of the screen, behind the status bar/safe area.

### Environment, Platform, Device

Can duplicate in all iPhones, latest iOS.  However, and this is the rub, it does NOT duplicate in any of the simulators as the camera option isn't available, only on the actual hardware.

### Version information

Cordova 9.0.0, Cordova iOS 6.1.0

## Checklist
- [x] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by bkervaski** [comment]
Here's a minimalist app to demonstrate the issue:

[hello.zip](https://github.com/apache/cordova-ios/files/4989192/hello.zip)

**Comment by bkervaski** [comment]
Here's a minimalist app to demonstrate the issue, just add platform ios@6.1.0, set your certs, and run on device:

[hello.zip](https://github.com/apache/cordova-ios/files/4989197/hello.zip)

**Comment by bkervaski** [comment]
Issue appears to be cordova-plugin-statusbar related, using the latest from git (and not the npm version) resolves the problem.

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
