### ISSUE TITLE
Wrongly created exportOptions.plist file - multiple provisioning profile support

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-ios#953]
# Bug Report
When there is more than one target and you are trying to sign both it doesn't work right. 
This is partially a bug and partially a feature request.

### What is expected to happen?
I expect to be able to sign two or more targets from CI server

### What does actually happen?
I can't do it right now.

## Information
This is after reviewing the discussion here:
#820 and #538 
and #545 (which I think tried to solve this as well).

### Command or Code
I'm building an ios cordova app with a share extension.
I configured a provisioning profile for both the extension and the app
I setup everything up and the build succeeds but the export fails.
I took a look in the exportOptions.plist file and there's only one provisioning profile, somehow the bundle name and provision profile got mixed (bundle id is for the app extension and PP UUID is for the app) which I can't really explain, but in any case it doesn't support multiple PP which is what needed in order to be able to sign the app from a CI server.
Code can be seen here (although it's not straight forward)
https://github.com/IsraelHikingMap/Site/tree/bc641a1b8c6e22293678ebe8e1a214fa2782ef05/IsraelHiking.Web
Relevant build:
https://ci.appveyor.com/project/IsraelHikingHost/site/builds/34309662

### Environment, Platform, Device
iOS - Appveyor CI - macOS VM.

### Version information
cordova cli 9.0.0
cordova-ios: 6.1.0
macOS VM from appveyor and also my own: 10.15.5

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

Let me know if this is something on the road map or in implementation, otherwise I can try and see if I can do a PR for this...

**Comment by HarelM** [comment]
I'm splitting this issue into two - a bug report and a feature request.
I'll keep this thread for the feature request and submit a PR shortly.
Not sure what to do with the bug I found, currently I'm not sure how to fix it and the code I wrote is working around it.
I'll submit s PR for review and we can discuss the details there.

**Comment by erisu** [comment]
Resolved in #1251
