### ISSUE TITLE
Non ascii characters in app name 

### ISSUE THREAD

**Issue by Darkxell** [apache/cordova-ios#954]
# Bug Report

Since the release of ios 14 beta 2, app names with non ascii characters such as "é" make the app unuseable.
The app launches, but stays on a white screen until closed.

This is unrelated to similar looking splashscreen issues.

### What is expected to happen?

The index.html page should be parsed and apear, serving the app content.

### What does actually happen?

The screen stays white until the application is closed.

### Command or Code

Steps to reproduction:

```
cordova create test
```

In your new project, edit config.xml ``<name></name>`` and put a name that has non standard ascii characters, such as "é".
Also edit package.json and change ``{"diplayName":""}`` to the matching value.

```
cd test
cordova platform add ios@6.1.0
```
Then build and deploy the project on your device using Xcode.
Launch the app.

### Environment, Platform, Device

Using: 
 cordova 9.0.0 (lib 9.0.1), both on osX and Windows
 the latest version of platform-ios (6.1.0)
 no other plugin for testing purposes
 ios 14 beta 2 and ios 14 beta 3 (current build 18A5332f) on an Iphone 11

Bug does not appear on older versions of IOS, working fine in 13.x versions and 14 beta 1.

### Version information

Xcode 11.1 (11A1027)
ios 14 beta 3 (18A5332f)
platform-ios 6.1.0
cordova 9.0.0, lib 9.0.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
I would advise reporting (or linking to an existing) issue with Apple.

Chances are this is an ios bug, not a cordova bug, especially if it worked in previous iOS 14 beta versions.

**Comment by ewfian** [comment]
It seems iOS 14 Beta 4 fixed this issue

**Comment by breautek** [comment]
Thank you @ewfian for letting us know!
