### ISSUE TITLE
Getting error while updating xcode version from 10.2 to 11.8 Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by adhishgit1** [apache/cordova-ios#958]
Hi Guys ,

Still facing the problem ,not resolved yet .

I am facing the issue Cannot read property 'toLowerCase' of undefined.

Full message .,

add to body class: platform-ios  
Cannot read property 'toLowerCase' of undefined  
[ERROR] An error occurred while running subprocess cordova.  
 
cordova build ios exited with exit code 1.  
 
Re-running this command with the --verbose flag may provide more  
information.  

also when I am hitting cordova prepare ios so getting fallowing error message .

var platforms = (process.env.CORDOVA_PLATFORMS ? process.env.process.env.split(',') : []);  
^  
TypeError: Cannot read property 'env' of undefined  
at Object.<anonymous> (xxx/xxx/_add_platform_class.js:71:72)  
at Module._compile (internal/modules/cjs/loader.js:1138:30)  
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)  
at Module.load (internal/modules/cjs/loader.js:986:32)  
at Function.Module._load (internal/modules/cjs/loader.js:879:14)  
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)  

 Using Ionic - 5.4.16
codova ios - 5.0.1
angular - 6

_Originally posted by @brodybits in https://github.com/apache/cordova-ios/issues/427#issuecomment-535678681_

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
