### ISSUE TITLE
WKWebView cancelled request(NSURLErrorCancelled -999) leads to errorUrl page instead of the second request

### ISSUE THREAD

**Issue by arunn** [apache/cordova-ios#959]
# Bug Report

## Problem

A request cancelled due to another request ends up showing the error page instead of response of the second request.

### What is expected to happen?

The response of the second request should be shown.

### What does actually happen?

The errorUrl page is shown.

## Information

The error is similar to https://github.com/apache/cordova-plugin-wkwebview-engine/issues/83 . We have two requests being run one after the other. The first request is cancelled once the second request is made. Instead of waiting for the response of the second request, the didFailLoadWithError shows the errorUrl page.

### Environment, Platform, Device

cordova-ios, iPhone 8(iOS 13.6)

### Version information

cordova(9.0.0)
cordova-ios(5.1.1)
cordova-plugin-wkwebviewengine(1.2.1)

Filing it here since the code has been integrated as of cordova-ios 6.0.0 and the issue doesn't seem to be fixed in the code.

## Checklist

- [x] I searched for existing GitHub issues
- [] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by tdfeslo** [comment]
Hi. Is there any news about this problem?
The solution proposed [here](https://github.com/apache/cordova-plugin-wkwebview-engine/pull/84/commits/bcb4e90f94516737a9348092e166e0d0ffa800b4) solves the problem but may be introduce other problems (regression) ?
Thanks
