### ISSUE TITLE
Getting error while updating xcode version from 10.2 to 11.8 Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by adhishgit1** [apache/cordova-ios#960]
Hi Guys ,

Still facing the problem ,not resolved yet .

I am facing the issue Cannot read property 'toLowerCase' of undefined.

Full message .,

add to body class: platform-ios  
Cannot read property 'toLowerCase' of undefined  
[ERROR] An error occurred while running subprocess cordova.  
 
cordova build ios exited with exit code 1.  
 
Re-running this command with the --verbose flag may provide more  
information.  

also when I am hitting cordova prepare ios so getting fallowing error message .

var platforms = (process.env.CORDOVA_PLATFORMS ? process.env.process.env.split(',') : []);  
^  
TypeError: Cannot read property 'env' of undefined  
at Object.<anonymous> (xxx/xxx/_add_platform_class.js:71:72)  
at Module._compile (internal/modules/cjs/loader.js:1138:30)  
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)  
at Module.load (internal/modules/cjs/loader.js:986:32)  
at Function.Module._load (internal/modules/cjs/loader.js:879:14)  
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)  

 

Ionic:  
Ionic CLI : 5.4.16 (/usr/local/lib/node_modules/ionic)  
Ionic Framework : ionic-angular 3.9.2  
@ionic/app-scripts : 3.2.3  
Cordova:  
Cordova CLI : 9.0.0 (cordova-lib@9.0.1)  
Cordova Platforms : android 6.4.0, browser 5.0.3, ios 4.5.4, platform_ios_updated 4.5.4  
Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, (and 33 other plugins)  
Utility:  
cordova-res : not installed  
native-run : not installed  
System:  
Android SDK Tools : 26.1.1 (/Users/rogerhuser/Library/Android/sdk)  
ios-sim : 8.0.2  
NodeJS : v12.18.1 (/usr/local/bin/node)  
npm : 6.14.5  
OS : macOS Catalina  
Xcode : Xcode 11.6 Build version 11E708

_Originally posted by @brodybits in https://github.com/apache/cordova-ios/issues/427#issuecomment-535678681_

**Comment by timbru31** [comment]
And we still request a filled issues template. It's not that hard to use the template. It helps us a lot, your issue is very hard to read.
