### ISSUE TITLE
Drag Gesture bugs after upgrading

### ISSUE THREAD

**Issue by HansKrywaa** [apache/cordova-ios#963]
# Bug Report

### What does actually happen?

I just migrate a Project from `5.1.1` to `6.1.0` and found a Issue, where i thought it is resolved to Ionic.
Infos to this Bug: https://github.com/ionic-team/ionic-framework/issues/21876

So it looks like [this PR](https://github.com/apache/cordova-ios/pull/790) here caused this Bug? 

### What is expected to happen?

To have a normal Drag Behaviour like before.

## Information

I created a Repo: https://github.com/HansKrywaa/ionic-menu-bug

### Version information

```
Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.0
            serve: 4.0.0

Project Installed Platforms:

    android: 9.0.0
    ios: 6.1.0
```

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by jcesarmobile** [comment]
You are not using 6.1.0, you are using a for with 6.1.0-dev version, which is based on 6.0.0.

I can't reproduce on 6.1.0, you should update to this version since is newer than your fork and already uses latest cordova-common
