### ISSUE TITLE
Problems with iOS Wallet

### ISSUE THREAD

**Issue by marcostadeusc** [apache/cordova-ios#967]
# Bug Report
I have a project that I started to migrate to new WKWebView, but there is some plugins that I'm having some problems.

## Problem
I have problem with `cordova-plugin-passbook`.

### What is expected to happen?
Plugin works with WKWebView

### What does actually happen?
When call the plugin, since it uses UIWebView, it's not working.

### Command or Code

I have the following references code on Xcode:

```
- (BOOL)shouldOverrideLoadWithRequest:(NSURLRequest*)request navigationType:(UIWebViewNavigationType)navigationType
{
    if(PKPassLibrary.isPassLibraryAvailable && [request.URL.pathExtension isEqualToString:@"pkpass"]) {
        [self downloadPass:request.URL success:nil error:nil];
        return YES;
    }
    
    return NO;
}
```

### Environment, Platform, Device

- iPhone 5S, iOS 12.4.6
- iPhone 8 Plus, iOS 13.6

### Version information

-  9.0.0 (cordova-lib@9.0.1)
 
- cordova-ios: 6.1.0

- cordova-plugin-inappbrowser: 4.0.0

- cordova-plugin-file-transfer: 1.6.3

- angular: 1.4.14

- onsenui: 2.10.10

## Checklist

- [ x ] I searched for existing GitHub issues
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

**Comment by timbru31** [comment]
It’s a third party plugin and the developer needs to update it. Unfortunately, we can’t help with third party plugins.

**Comment by marcostadeusc** [comment]
So, is there any alternative would you recommend?

**Comment by breautek** [comment]
You can try one of its [forks](https://github.com/passslot/cordova-plugin-passbook/network/members)

https://github.com/AmTote/cordova-plugin-passbook appears to be the most recent fork, and it looks like its been refactored to use `WKWebView`.
