### ISSUE TITLE
Installing "cordova-plugin-splashscreen" for ios Plugin doesn't support this project's cordova-ios version. cordova-ios: 6.1.0, failed version requirement: <6.0.0 Skipping 'cordova-plugin-splashscreen' for ios

### ISSUE THREAD

**Issue by AlwaysLoveme** [apache/cordova-ios#969]
# Bug Report
Installing "cordova-plugin-splashscreen" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 6.1.0, failed version requirement: <6.0.0
Skipping 'cordova-plugin-splashscreen' for ios

### What is expected to happen?
installing "cordova-plugin-splashscreen" with cordova-ios 6.1.0 successful

### What does actually happen?
skip install cordova-plugin-splashscreen for cordova-ios 6.1.0 

## Information

> cordova platform ls
Installed platforms:
  ios 6.1.0
Available platforms: 
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^6.0.0

### Environment, Platform, Device

> cordova platform ls
Installed platforms:
  ios 6.1.0
Available platforms: 
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^6.0.0

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
The SplashScreen has been integrated into the core platform: https://cordova.apache.org/news/2020/07/21/splashscreen-plugin-release.html

It’s ok to be skipped if you need it for Android
