### ISSUE TITLE
Cannot use `cordova platform add ios` on windows - xcode error 66 is returned during the subsequent cordova build on macOS

### ISSUE THREAD

**Issue by stevenmldn** [apache/cordova-ios#971]
# Bug Report
Cannot use `cordova platform add ios` on windows
## Problem

Added an ios platform on a windows box results in the file containing the wrong slash type, backslashes rather than forward-slashes.

### What is expected to happen

Adding the platform on macOS includes the following line the the xcode project file
	301BF52D109A57CC0062928A /* CordovaLib/CordovaLib.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = CordovaLib.xcodeproj; path = CordovaLib/CordovaLib.xcodeproj; sourceTree = "<group>"; };

Notice the slash in the path

### What does actually happen?

Adding the platform on windows includes the following line the the xcode project file
	301BF52D109A57CC0062928A /* CordovaLib/CordovaLib.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = CordovaLib.xcodeproj; path = CordovaLib\CordovaLib.xcodeproj; sourceTree = "<group>"; };

Notice the slash in the path

The project fails to open in xcode. The following error is returned when attempting to build via corodva-cli
 stderr:
   '2020-08-20 14:22:02.768 xcodebuild[32234:997204] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 75. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.\n2020-08-20 14:22:02.768 xcodebuild[32234:997204] Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}\n2020-08-20 14:22:02.768 xcodebuild[32234:997204] [MT] IDEFileReferenceDebug: [Load] <IDEFileReference, 0x7fad238295e0: name:xxx path:group:xxx.xcodeproj> Failed to load container at path: /Mobile/platforms/ios/xxxxxx.xcodeproj, Error: Error Domain=Xcode3ProjectErrorDomain Code=2 "The project ‘xxx’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.\n\nPath: Mobile/platforms/ios/xxxxxx.xcodeproj" UserInfo={NSLocalizedDescription=The project ‘xxx’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.\n\nPath: /Mobile/platforms/ios/xxx.xcodeproj}\n--- xcodebuild: WARNING: Unable to open project file \'/Mobile/platforms/ios/xxx.xcodeproj\' in workspace \'xxx.xcworkspace\'.\n2020-08-20 14:22:02.862 xcodebuild[32234:997374]  DVTProvisioningProfileManager: Failed to load profile "///Library/MobileDevice/Provisioning Profiles/Old" (Error Domain=DVTProvisioningProfileSourceErrorDomain Code=0 "No provisioning profile provider found for profile "///Library/MobileDevice/Provisioning Profiles/Old"." UserInfo={NSLocalizedDescription=No provisioning profile provider found for profile "///Library/MobileDevice/Provisioning Profiles/Old".})\n2020-08-20 14:22:03.021 xcodebuild[32234:997377] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called\nxcodebuild: error: Scheme xxx is not currently configured for the archive action.\n\nxcodebuild: Command failed with exit code 66\n' }

### Command or Code
`cordova platform add ios` on Windows
`cordova build ios` on macOS

### Environment, Platform, Device
Adding the ios platform on Windows 10, copying to a mac and building there

### Version information
on both the windows and macOS boxes, we are using
Cordova - v10

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by AdamLak** [comment]
https://github.com/apache/cordova-ios/pull/1018

:)
