### ISSUE TITLE
Including input focus fix from cordova-plugin-wkwebview-engine

### ISSUE THREAD

**Issue by u01jmg3** [apache/cordova-ios#972]
# Bug Report

## Problem

I realise Cordova iOS `6.1.0` was released with its own copy of the WKWebView engine. I just wanted to know whether fixes previously included in [`cordova-plugin-wkwebview-engine`](https://github.com/apache/cordova-plugin-wkwebview-engine) for fixing input focus will be incorporated into this repo?

I also realise that `KeyboardDisplayRequiresUserAction` was part of the now deprecated UIWebView and in order to get similar functionality on WKWebView requires swizzling private methods. This means any fix can break if Apple decide to change their code.

### What is expected to happen?

The keyboard should show when focusing an input element.

```js
document.querySelector('input').focus()
```

### What does actually happen?

The keyboard does not show when focusing an input element.

## Information

- `cordova-plugin-wkwebview-engine`
  - Open bug report that states that this is still a problem on iOS `12.2`
    - https://github.com/apache/cordova-plugin-wkwebview-engine/issues/86
  - Open PR providing a fix for iOS `13`
    - https://github.com/apache/cordova-plugin-wkwebview-engine/pull/122
- `cordova-plugin-ionic-webview`
  - Another issue stating that the problem still exists on iOS `13`
    - https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/400

### Environment, Platform, Device

iOS `12.4.8`

### Version information

Cordova `10.0.0`
Cordova iOS `6.1.0`

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by phemets** [comment]
Is there a plugin or workaround that fixes this for Cordova iOS 6+? 
Seems like a lot of people are missing this, according to the end user feedback I get.

**Comment by breautek** [comment]
> Is there a plugin or workaround that fixes this for Cordova iOS 6+?
> Seems like a lot of people are missing this, according to the end user feedback I get.

You can try deriving from this PR https://github.com/apache/cordova-plugin-wkwebview-engine/pull/122/files

But like Darryl says, you're going against what Apple believes to be correct. Afaik, you can only accomplish this by using private APIs, which is grounds for app rejection. It can also makes your code brittle as private APIs can change with no warning.

> This seems contradictory when previously they offered the KeyboardDisplayRequiresUserAction option in UIWebView which allowed an app developer to control this very behaviour. 

`KeyboardDisplayRequiresUserAction` is also deprecated, so I think Apple indeed reconsidered what is considered good practice.

**Comment by u01jmg3** [comment]
> _so I think Apple indeed reconsidered what is considered good practice_

But as @phemets has said, user feedback suggest this feature is missed. Are Apple correct to be dictating what our users should want? Either way, there's nothing we can do.

**Comment by breautek** [comment]
>Are Apple correct to be dictating what our users should want?

This isn't really anything new for Apple. They always valued simplistic design, which often includes removing features.

The proper way to get this addressed is to get into contact with Apple and request the feature. There isn't anything that can be done from Cordova.

**Comment by u01jmg3** [comment]
For iOS 13+: https://github.com/adaptabi/cordova-plugin-wkwebview-inputfocusfix

**Comment by phemets** [comment]
Amazing! Works for me! Thank you, u01jmg3!

**Comment by u01jmg3** [comment]
Thank @onderceylan who put me onto the fork @adaptabi created

**Comment by phemets** [comment]
Thank you very much @adaptabi, @onderceylan and @u01jmg3! My users will be very happy! The app update is already done and waiting for review!
