### ISSUE TITLE
Investigate Jasmine 3.6.0 test failures

### ISSUE THREAD

**Issue by dpogue** [apache/cordova-ios#978]
# Tech Debt
Follow up from https://github.com/apache/cordova-ios/pull/976

## Problem
Unit tests fail when run with Jasmine 3.6.0.

### What is expected to happen?
Tests pass.

### What does actually happen?
A bunch of tests fail with `TypeError: target is not a constructor`.

**Comment by erisu** [comment]
Close as completed.
The main branch shows that Jasmin@^3.10.0 is being used.

https://github.com/apache/cordova-ios/blob/master/package.json#L35
