### ISSUE TITLE
iOS 11 is a minimum deployment target starting from cordova-ios 6

### ISSUE THREAD

**Issue by exxbrain** [apache/cordova-ios#981]
# Bug Report

## Problem

As from a cordova documentation iOS 11 is a minimum deployment target starting from cordova-ios 6? I think it is dramatically high. Is it possible to make it lower: 9 or maximum 10?

This is a official apple statistics for iPhone:
 81% iOS 13
 13% iOS 12
 6% Earlier (9, 10, 11)

iPad:
 73% iPadOS
 16% iOS 12
 11% Earlier (9, 10, 11)

### What is expected to happen?

Minimum deployment target should be iOS 9 or maximum 10

### What does actually happen?

Minimum deployment target is iOS 11

### Version information

cordova-ios >= 6.0.0

**Comment by breautek** [comment]
Not possible. Cordova-ios@6 utilises the scheme feature to address a lot of cross origin issues in the WKWebView, which requires iOS 11.

If you must target below iOS 11 then you're options are:

1. Stay on `cordova-iso@5.1.1` with the `WK_WEBVIEW_ONLY` flag & a wkwebview plugin installed.
2. You may be able to override the minimum deployment target on `cordova-ios@6`, but this configuration if possible may break without notice. And you obviously would have to remain on the `file://` protocol.
