### ISSUE TITLE
Getting Empty white Screen when page loaded 

### ISSUE THREAD

**Issue by perlasivakrishna** [apache/cordova-ios#983]
# Bug Report

### What is expected to happen?

Expected to load the content from the passed path. 

### What does actually happen?

An Empty white screen, WebView is was not added to view hierarchy.

## Information

my [`config.xml`](https://gist.github.com/perlasivakrishna/bbdfb43dcf04beb82ab88ca63fa623b4)

path to file "file:///Users/sivakrishna/Library/Developer/CoreSimulator/Devices/F2FE6906-6DBD-4092-89E6-9887702AB86D/data/Containers/Data/Application/FDAAB79B-4107-40A5-85B4-99FDB7AC71D2/Documents/Books/81002753033019/B366975EC40985B2889EF6FC6CCA5444/content/7984fbad-3258-43e1-aa3e-b606f8c347ee" 

### Command or Code

Installed pod, Loaded View controller by passing ww folder name as above.

### Environment, Platform, Device
Mac OS 10.15.6
iOS
iPhone 11 Simulator

### Version information

Xcode 11.5
Cordova iOS 6.1.1 (installed as pod)
cordova CLI 10.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

Im not getting any logs in Xcode console or safari debugger. 

Note: The same setup/project working fine in Cordova iOS 5.1.1 with WkWebview-Engine
I'm new to cordova, so if you need any further info please let me know where can i find that info/logs.

Do i need to add anything specific in config.xml to work for WKWebview ?

I'm passing fileUrl as www folder path, is that fine?

Thanks in advance.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by perlasivakrishna** [comment]
@timbru31 Thanks for the reply, sorry for partial information,  I have edited my issue, so please look into it, I'm new to Cordova so please let me know the procedure for further information incase if needed. 

Thanks.

**Comment by breautek** [comment]
I'll go ahead and reopen this issue.

It looks like you're using a platform-centric workflow which is a workflow I'm not very familiar with. It may help if you share some code and xcode logs.

**Comment by perlasivakrishna** [comment]
@breautek please find the Xcode logs. 
[cordovaLogs.txt](https://github.com/apache/cordova-ios/files/5174664/cordova.logs.1.txt)

I have a View Controller which is superclass of "CDVViewController", Presenting controller by specifying the www folder path.

**Comment by perlasivakrishna** [comment]
I have the found the work around. Wkwebview delegates Overrided in my class.

```
- (void)webView:(WKWebView *)webView didFinishNavigation:(WKNavigation *)navigation {
    [webView setHidden:NO];
    [self.view bringSubviewToFront:webView];
}
```
so I managed to do like this. Not sure is there any better way.  I have seen this piece of code where the webview is  getting hided. 

```
- (void)createGapView
{
    CGRect webViewBounds = self.view.bounds;
    webViewBounds.origin = self.view.bounds.origin;

    UIView* view = [self newCordovaViewWithFrame:webViewBounds];
    view.hidden = YES;
    view.autoresizingMask = (UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight);

    [self.view addSubview:view];
    [self.view sendSubviewToBack:view];
}
```
Also there is one more Empty view getting added to view hierarchy, not sure why it was getting added. 

![Screenshot 2020-09-04 at 8 00 27 PM](https://user-images.githubusercontent.com/6779941/92252413-d4045380-eeeb-11ea-822e-3aa1c41dfa6f.png)

If i need to change anything the way I'm handling webview, please suggest me.
 Thanks.

**Comment by dpogue** [comment]
The empty view is probably for the splashscreen. You might be running into https://github.com/apache/cordova-ios/issues/929

**Comment by JayzeeHuang** [comment]
Finally found somthings same as me now, my ios build got an empty page after splash screen and without any errors. I was stuck for few days, hope someone can fix this issue.

**Comment by 21pg** [comment]
@JayzeeHuang Did you find any solution on this.

**Comment by JayzeeHuang** [comment]
@21pg update all to latest version, use fresh build to compare your current project, remove and readd each plugin will solve this issue.

**Comment by bluemaschine** [comment]
@JayzeeHuang I'm using Monaca and have the same problem.

Here is a screenshot : https://ibb.co/h7FVNTZ

One week with no solution, its a bit frustring

**Comment by dpogue** [comment]
I've marked this issue as stale because it's been several years with no further comments. If this is still an issue in the latest cordova-ios version and an up-to-date iOS version, please let us know. Otherwise, this issue will be closed.

**Comment by dpogue** [comment]
Closing as stale.
