### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by Moneer-M** [apache/cordova-ios#985]
# Bug Report
UIWebView deprecated API
## Problem
I am using the latest Cordova - ios, 6.1 but I am still getting flagged for using UIWebView by Apple
### What is expected to happen?

Since I do not have any third party frameworks or plugins other than AdMob, the latest Cordova update along with the WKWebView preference should've removed any calls to UIWebView

### What does actually happen?

I am still getting flagged for Using UIWebView.

## Information

I am using Cordova and Xcode to build my app for IOS. When I search for UIWebview using the grep -r command I get no references. 

### Command or Code

Running the "grep -rnw . -e 'UIWebView'" command to look through the binary files yields these result:

Binary file ./platforms/ios/APP_Name.xcodeproj/project.xcworkspace/xcuserdata/user.xcuserdatad/UserInterfaceState.xcuserstate matches
Binary file ./platforms/ios/build/emulator/APP_Name.app.dSYM/Contents/Resources/DWARF/APP_Name matches
Binary file ./platforms/ios/build/emulator/APP_Name.app/APP_Name matches

### Environment, Platform, Device

IOS devices

### Version information

OS: Catalina
Xcode 11
Cordova - ios 6.1
Cordova version 10.0.0
Building for IOS

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
> Since I do not have any third party frameworks or plugins other than AdMob

Then logic leads to believe that your admob plugin must be using `UIWebView`. `cordova-ios@6` removed all `UIWebView` related code.
