### ISSUE TITLE
this.platform.is('ios') return false for iPad after update to cordova-ios 6.1.1

### ISSUE THREAD

**Issue by farazahmadvaival** [apache/cordova-ios#987]
# Bug Report

I am using this code to detect ios platform this.platform.is('ios') . It is working fine on iPhone but when I run the app on Ipad it always returns false. This issue happened when i updated the ios-platform to 6.1.1. In the previous version 5.1.1 it was working fine for both iPhone and iPad. 

### What is expected to happen?
this.platform.is('ios') should return true on all ios devices.

### What does actually happen?

this.platform.is('ios') return false for iPad when i update platform version to 6.1.1

### Version information

Ionic:

   Ionic CLI          : 6.11.8 (/Users/macbookx/.nvm/versions/node/v12.18.0/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.10
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 34 other plugins)

Utility:

   cordova-res                          : 0.15.1
   native-run (update available: 1.1.0) : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/macbookx/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.18.0 (/Users/macbookx/.nvm/versions/node/v12.18.0/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 11.7 Build version 11E801a

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
The code you describe is part of the `ionic-angular` package, so you'll need to seek support from Ionic, not from Apache.
