### ISSUE TITLE
SplashScreenDelay should not apply when calling splashscreen.show() / splashscreen.hide()

### ISSUE THREAD

**Issue by asgeo1** [apache/cordova-ios#991]
# Bug Report

## Problem

Calling `splashscreen.show()` or `splashscreen.hide()` do not function correctly when `SplashScreenDelay` is set to a value.

### What is expected to happen?

Manually calling `splashscreen.show()` or `splashscreen.hide()` should trigger the splash screen to show/hide immediately. The value of `SplashScreenDelay` is only meant to be taken into account when the app first loads and `AutoHideSplashScreen` is `true` - i.e. it's for controlling the initial delay when the app first boots.

(at least, this is how the documentation reads, and how it used to work on previous versions of the splash screen plugin)

One should be able to manually show/hide the splash screen immediately as required.

### What does actually happen?

Calling `splashscreen.show()` or `splashscreen.hide()`, there is a delay before the action actually happens - the delay being the value of `SplashScreenDelay`.

### Environment, Platform, Device

iOS any version

### Version information
Cordova iOS 6.1.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by svzi** [comment]
@dpogue When can we expect the version 6.1.2 to be released? I would love to give that version a try, because this bug is messing up by splashscreen behavior for iOS/Android (one of 'em is not showing a splashscreen or it shows until the configured delay has been reached)...

**Comment by timbru31** [comment]
As Cordova is maintained by volunteers, often in their free time, we can't give any ETA on release dates.

**Comment by svzi** [comment]
I fully understand and appreciate the support of all the volunteers! Keep up the good work. 👍
