### ISSUE TITLE
three finger scroll stops working (VoiceOver)

### ISSUE THREAD

**Issue by petercutting** [apache/cordova-ios#992]
Three finger scroll initially works but as soon as the user bumps into the end of the list (hollow knock sound) then scrolling no longer works and the user is stranded

**Comment by petercutting** [comment]
looks like I have found a solution

<preference name="DisallowOverscroll" value="false" />

**Comment by timbru31** [comment]
Glad if you found a working solution for you - I'm closing the issue. The next time, please fill in the issue template, otherwise we can't help.
