### ISSUE TITLE
cocos2dx support

### ISSUE THREAD

**Issue by shizu2014** [apache/cordova-ios#993]
How to integrate into the cocos2dx project?
I followed the official instructions and embedded it
But the plugin cannot be used
please help me

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
