### ISSUE TITLE
Cookies are not working after upgrading to Cordova@6.1.1 

### ISSUE THREAD

**Issue by vvsou862** [apache/cordova-ios#995]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Information

Recently i updated my app to Cordova@6.1.1 ,configured  Custom Url Schema as app://test.xxx.com  and also enabled CORS according to https://breautek.com/2020/07/14/enabling-cors/.
Issue is underlying cookie is not being sent with webapi request even though i have set Access-Control-Allow-Credentials to true from server response and withCredentials to true while sending request. 
Please help why with new update, cookies are not being sent to the request
cordova-plugin-wkwebview-inject-cookie also did not give any luck . 

### Environment, Platform, Device

Cordova@6.1.1
ipad iOS 14 

### Version information

Cordova@6.1.1
XCODE 12.0.1

## Checklist

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by NiklasMerz** [comment]
iOS 14 had some changes for blocking cookies. Please check out #922 and some other information on the internet.

This has probably nothing to do with the upgraded version of cordova-ios.
