### ISSUE TITLE
After installing cordova-plugin-wkwebview-engine still getting same Deprecated API Usage UIWEBVIEW from app store team

### ISSUE THREAD

**Issue by Mohammad-Toufiq-Pathan** [apache/cordova-ios#997]
# Bug Report

## Problem
ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability.
### What is expected to happen?
It should be removed all UIWEBVIEW form project after installing **cordova-plugin-wkwebview-engine  cordova-plugin-wkwebviewxhrfix** both pluigns

### What does actually happen?

Getting ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability, from App store team

## Information

Plugin list 
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-battery-status 2.0.2 "Battery"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 4.0.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebasex 8.0.0 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 8.4.0 "Google SignIn"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-proguard 1.0.0 "Cordova plugin ProGuard"
cordova-plugin-secure-storage 3.0.0 "SecureStorage"
cordova-plugin-softinputmode 1.0.3 "SoftInputMode"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-transport-security 0.1.2 "App Transport Security"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-websql 0.0.10 "Web SQL plugin"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
cordova-plugin-x-toast 2.7.2 "Toast"
cordova-sqlite-storage 4.0.1-dev "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
skwas-cordova-plugin-datetimepicker 1.1.3 "DateTime picker"
twitter-connect-plugin 0.6.0 "Twitter Connect"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"

### Command or Code

Whwn upload the app to app store getting this error

### Environment, Platform, Device

Platform: IOS

### Version information

cordova: 10.0.0
cordova-ios: 5.1.1
npm:6.9.0
node: 10.16.0

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
One of your plugins still uses UIWebView code. Open Xcode or your favorite editor and search the `platforms/ios` folder for string `UIWebView`, then contact the plugin authors or update the plugins to their most recent version if an update is available. Also, make sure to check out our blog how to use WKWebView only with cordova-ios@5.1.1: https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html
